package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "AMBIENT_SOUND".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class AmbientSound {
  private AmbientSound() {}

  public final static int BLACK_SMITH = 80;
  public final static int BORDELLO_MEN_AND_WOMEN = 21;
  public final static int BORDELLO_WOMEN = 20;
  public final static int CASTLE_INTERIOR_LARGE = 68;
  public final static int CASTLE_INTERIOR_MEDIUM = 67;
  public final static int CASTLE_INTERIOR_SMALL = 66;
  public final static int CAVE_EVIL_1_XP2 = 104;
  public final static int CAVE_EVIL_2_XP2 = 105;
  public final static int CAVE_EVIL_3_XP2 = 106;
  public final static int CAVE_INSECTS_1 = 42;
  public final static int CAVE_INSECTS_2 = 43;
  public final static int CAVE_LARGE = 62;
  public final static int CAVE_MEDIUM = 61;
  public final static int CAVE_SMALL = 60;
  public final static int CITY_DAY_CROWDED = 12;
  public final static int CITY_DAY_SPARSE = 13;
  public final static int CITY_MARKET = 15;
  public final static int CITY_NIGHT = 14;
  public final static int CITY_SLUMS_DAY_CROWDED = 9;
  public final static int CITY_SLUMS_DAY_SPARSE = 10;
  public final static int CITY_SLUMS_NIGHT = 11;
  public final static int CITY_TEMPLE_DISTRICT = 16;
  public final static int COMBAT_MUFFLED_1 = 26;
  public final static int COMBAT_MUFFLED_2 = 27;
  public final static int COMBAT_OUTSIDE_1 = 24;
  public final static int COMBAT_OUTSIDE_2 = 25;
  public final static int COMMONER_TAVERN_TALK = 7;
  public final static int CRYPT_MEDIUM_1 = 70;
  public final static int CRYPT_MEDIUM_2 = 71;
  public final static int CRYPT_SMALL = 69;
  public final static int DESERT_DAY_XP1 = 92;
  public final static int DESERT_NIGHT_XP1 = 93;
  public final static int DUNGEON_LAKE_LAVA = 28;
  public final static int EVIL_DRONE_XP2 = 101;
  public final static int EVIL_DUNGEON_LARGE = 59;
  public final static int EVIL_DUNGEON_MEDIUM = 58;
  public final static int EVIL_DUNGEON_SMALL = 57;
  public final static int FOREST_DAY_1 = 49;
  public final static int FOREST_DAY_2 = 50;
  public final static int FOREST_DAY_3 = 51;
  public final static int FOREST_DAY_SCARY = 52;
  public final static int FOREST_MAGICAL = 56;
  public final static int FOREST_NIGHT_1 = 53;
  public final static int FOREST_NIGHT_2 = 54;
  public final static int FOREST_NIGHT_SCARY = 55;
  public final static int FROZEN_HELL_XP2 = 103;
  public final static int GUST_CAVERN = 35;
  public final static int GUST_CHASM = 34;
  public final static int GUST_DRAFT = 37;
  public final static int GUST_GRASS = 36;
  public final static int HAUNTED_INTERIOR_1 = 77;
  public final static int HAUNTED_INTERIOR_2 = 78;
  public final static int HAUNTED_INTERIOR_3 = 79;
  public final static int HOUSE_INTERIOR_1 = 72;
  public final static int HOUSE_INTERIOR_2 = 73;
  public final static int HOUSE_INTERIOR_3 = 74;
  public final static int INTERIOR_INSECTS_1 = 44;
  public final static int INTERIOR_INSECTS_2 = 45;
  public final static int KITCHEN_INTERIOR_LARGE = 76;
  public final static int KITCHEN_INTERIOR_SMALL = 75;
  public final static int LARGE_GROUP_TALKS_INSIDE = 6;
  public final static int LIZARD_FOLK_CAVE_CRYSTALS = 46;
  public final static int MAGICAL_INTERIOR_AIRLAB = 88;
  public final static int MAGICAL_INTERIOR_EARTHLAB = 87;
  public final static int MAGICAL_INTERIOR_FIRELAB = 86;
  public final static int MAGICAL_INTERIOR_WATERLAB = 89;
  public final static int MAGIC_INTERIOR_EVIL = 85;
  public final static int MAGIC_INTERIOR_LARGE = 84;
  public final static int MAGIC_INTERIOR_MEDIUM = 83;
  public final static int MAGIC_INTERIOR_SMALL = 82;
  public final static int MEDIUM_GROUP_TALKS_INSIDE = 5;
  public final static int MEN_WHISPER_INSIDE = 1;
  public final static int MINE_LARGE = 65;
  public final static int MINE_MEDIUM = 64;
  public final static int MINE_SMALL = 63;
  public final static int MONASTERY_INTERIOR_XP1 = 94;
  public final static int NOBLE_TAVERN_TALK = 8;
  public final static int NONE = 0;
  public final static int PEOPLE_WHISPER_INSIDE = 3;
  public final static int PIT_CRIES = 81;
  public final static int PLAIN_OF_FIRE_XP2 = 102;
  public final static int RAIN_HARD = 39;
  public final static int RAIN_LIGHT = 38;
  public final static int RAIN_STORM_BIG = 41;
  public final static int RAIN_STORM_SMALL = 40;
  public final static int RIOT_MUFFLED = 23;
  public final static int RIOT_OUTSIDE = 22;
  public final static int RUIN_HAUNTED_XP1 = 98;
  public final static int RUIN_RUMBLING_XP1 = 97;
  public final static int RUIN_WET_XP1 = 96;
  public final static int SAND_STORM_EXTREME_XP1 = 100;
  public final static int SAND_STORM_LIGHT_XP1 = 99;
  public final static int SEWERS_1 = 47;
  public final static int SEWERS_2 = 48;
  public final static int SEWER_SLUDGE_LAKE = 29;
  public final static int SMALL_GROUP_TALKS_INSIDE = 4;
  public final static int TAVERN_ROWDY = 107;
  public final static int TOWN_DAY_CROWDED = 17;
  public final static int TOWN_DAY_SPARSE = 18;
  public final static int TOWN_NIGHT = 19;
  public final static int WIND_FOREST = 33;
  public final static int WIND_MEDIUM = 31;
  public final static int WIND_SOFT = 30;
  public final static int WIND_STRONG = 32;
  public final static int WINTER_DAY_WET_XP1 = 90;
  public final static int WINTER_DAY_WINDY_XP1 = 91;
  public final static int WOMEN_WHISPER_INSIDE = 2;

  public static String nameOf(int value) {
    if (value == 80) return "AmbientSound.BLACK_SMITH";
    if (value == 21) return "AmbientSound.BORDELLO_MEN_AND_WOMEN";
    if (value == 20) return "AmbientSound.BORDELLO_WOMEN";
    if (value == 68) return "AmbientSound.CASTLE_INTERIOR_LARGE";
    if (value == 67) return "AmbientSound.CASTLE_INTERIOR_MEDIUM";
    if (value == 66) return "AmbientSound.CASTLE_INTERIOR_SMALL";
    if (value == 104) return "AmbientSound.CAVE_EVIL_1_XP2";
    if (value == 105) return "AmbientSound.CAVE_EVIL_2_XP2";
    if (value == 106) return "AmbientSound.CAVE_EVIL_3_XP2";
    if (value == 42) return "AmbientSound.CAVE_INSECTS_1";
    if (value == 43) return "AmbientSound.CAVE_INSECTS_2";
    if (value == 62) return "AmbientSound.CAVE_LARGE";
    if (value == 61) return "AmbientSound.CAVE_MEDIUM";
    if (value == 60) return "AmbientSound.CAVE_SMALL";
    if (value == 12) return "AmbientSound.CITY_DAY_CROWDED";
    if (value == 13) return "AmbientSound.CITY_DAY_SPARSE";
    if (value == 15) return "AmbientSound.CITY_MARKET";
    if (value == 14) return "AmbientSound.CITY_NIGHT";
    if (value == 9) return "AmbientSound.CITY_SLUMS_DAY_CROWDED";
    if (value == 10) return "AmbientSound.CITY_SLUMS_DAY_SPARSE";
    if (value == 11) return "AmbientSound.CITY_SLUMS_NIGHT";
    if (value == 16) return "AmbientSound.CITY_TEMPLE_DISTRICT";
    if (value == 26) return "AmbientSound.COMBAT_MUFFLED_1";
    if (value == 27) return "AmbientSound.COMBAT_MUFFLED_2";
    if (value == 24) return "AmbientSound.COMBAT_OUTSIDE_1";
    if (value == 25) return "AmbientSound.COMBAT_OUTSIDE_2";
    if (value == 7) return "AmbientSound.COMMONER_TAVERN_TALK";
    if (value == 70) return "AmbientSound.CRYPT_MEDIUM_1";
    if (value == 71) return "AmbientSound.CRYPT_MEDIUM_2";
    if (value == 69) return "AmbientSound.CRYPT_SMALL";
    if (value == 92) return "AmbientSound.DESERT_DAY_XP1";
    if (value == 93) return "AmbientSound.DESERT_NIGHT_XP1";
    if (value == 28) return "AmbientSound.DUNGEON_LAKE_LAVA";
    if (value == 101) return "AmbientSound.EVIL_DRONE_XP2";
    if (value == 59) return "AmbientSound.EVIL_DUNGEON_LARGE";
    if (value == 58) return "AmbientSound.EVIL_DUNGEON_MEDIUM";
    if (value == 57) return "AmbientSound.EVIL_DUNGEON_SMALL";
    if (value == 49) return "AmbientSound.FOREST_DAY_1";
    if (value == 50) return "AmbientSound.FOREST_DAY_2";
    if (value == 51) return "AmbientSound.FOREST_DAY_3";
    if (value == 52) return "AmbientSound.FOREST_DAY_SCARY";
    if (value == 56) return "AmbientSound.FOREST_MAGICAL";
    if (value == 53) return "AmbientSound.FOREST_NIGHT_1";
    if (value == 54) return "AmbientSound.FOREST_NIGHT_2";
    if (value == 55) return "AmbientSound.FOREST_NIGHT_SCARY";
    if (value == 103) return "AmbientSound.FROZEN_HELL_XP2";
    if (value == 35) return "AmbientSound.GUST_CAVERN";
    if (value == 34) return "AmbientSound.GUST_CHASM";
    if (value == 37) return "AmbientSound.GUST_DRAFT";
    if (value == 36) return "AmbientSound.GUST_GRASS";
    if (value == 77) return "AmbientSound.HAUNTED_INTERIOR_1";
    if (value == 78) return "AmbientSound.HAUNTED_INTERIOR_2";
    if (value == 79) return "AmbientSound.HAUNTED_INTERIOR_3";
    if (value == 72) return "AmbientSound.HOUSE_INTERIOR_1";
    if (value == 73) return "AmbientSound.HOUSE_INTERIOR_2";
    if (value == 74) return "AmbientSound.HOUSE_INTERIOR_3";
    if (value == 44) return "AmbientSound.INTERIOR_INSECTS_1";
    if (value == 45) return "AmbientSound.INTERIOR_INSECTS_2";
    if (value == 76) return "AmbientSound.KITCHEN_INTERIOR_LARGE";
    if (value == 75) return "AmbientSound.KITCHEN_INTERIOR_SMALL";
    if (value == 6) return "AmbientSound.LARGE_GROUP_TALKS_INSIDE";
    if (value == 46) return "AmbientSound.LIZARD_FOLK_CAVE_CRYSTALS";
    if (value == 88) return "AmbientSound.MAGICAL_INTERIOR_AIRLAB";
    if (value == 87) return "AmbientSound.MAGICAL_INTERIOR_EARTHLAB";
    if (value == 86) return "AmbientSound.MAGICAL_INTERIOR_FIRELAB";
    if (value == 89) return "AmbientSound.MAGICAL_INTERIOR_WATERLAB";
    if (value == 85) return "AmbientSound.MAGIC_INTERIOR_EVIL";
    if (value == 84) return "AmbientSound.MAGIC_INTERIOR_LARGE";
    if (value == 83) return "AmbientSound.MAGIC_INTERIOR_MEDIUM";
    if (value == 82) return "AmbientSound.MAGIC_INTERIOR_SMALL";
    if (value == 5) return "AmbientSound.MEDIUM_GROUP_TALKS_INSIDE";
    if (value == 1) return "AmbientSound.MEN_WHISPER_INSIDE";
    if (value == 65) return "AmbientSound.MINE_LARGE";
    if (value == 64) return "AmbientSound.MINE_MEDIUM";
    if (value == 63) return "AmbientSound.MINE_SMALL";
    if (value == 94) return "AmbientSound.MONASTERY_INTERIOR_XP1";
    if (value == 8) return "AmbientSound.NOBLE_TAVERN_TALK";
    if (value == 0) return "AmbientSound.NONE";
    if (value == 3) return "AmbientSound.PEOPLE_WHISPER_INSIDE";
    if (value == 81) return "AmbientSound.PIT_CRIES";
    if (value == 102) return "AmbientSound.PLAIN_OF_FIRE_XP2";
    if (value == 39) return "AmbientSound.RAIN_HARD";
    if (value == 38) return "AmbientSound.RAIN_LIGHT";
    if (value == 41) return "AmbientSound.RAIN_STORM_BIG";
    if (value == 40) return "AmbientSound.RAIN_STORM_SMALL";
    if (value == 23) return "AmbientSound.RIOT_MUFFLED";
    if (value == 22) return "AmbientSound.RIOT_OUTSIDE";
    if (value == 98) return "AmbientSound.RUIN_HAUNTED_XP1";
    if (value == 97) return "AmbientSound.RUIN_RUMBLING_XP1";
    if (value == 96) return "AmbientSound.RUIN_WET_XP1";
    if (value == 100) return "AmbientSound.SAND_STORM_EXTREME_XP1";
    if (value == 99) return "AmbientSound.SAND_STORM_LIGHT_XP1";
    if (value == 47) return "AmbientSound.SEWERS_1";
    if (value == 48) return "AmbientSound.SEWERS_2";
    if (value == 29) return "AmbientSound.SEWER_SLUDGE_LAKE";
    if (value == 4) return "AmbientSound.SMALL_GROUP_TALKS_INSIDE";
    if (value == 107) return "AmbientSound.TAVERN_ROWDY";
    if (value == 17) return "AmbientSound.TOWN_DAY_CROWDED";
    if (value == 18) return "AmbientSound.TOWN_DAY_SPARSE";
    if (value == 19) return "AmbientSound.TOWN_NIGHT";
    if (value == 33) return "AmbientSound.WIND_FOREST";
    if (value == 31) return "AmbientSound.WIND_MEDIUM";
    if (value == 30) return "AmbientSound.WIND_SOFT";
    if (value == 32) return "AmbientSound.WIND_STRONG";
    if (value == 90) return "AmbientSound.WINTER_DAY_WET_XP1";
    if (value == 91) return "AmbientSound.WINTER_DAY_WINDY_XP1";
    if (value == 2) return "AmbientSound.WOMEN_WHISPER_INSIDE";
    return "AmbientSound.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "AmbientSound.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "AmbientSound.(not found: " + value + ")";
  }
}
