package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "AMBIENT".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class Ambient {
  private Ambient() {}

  public final static int SOUND_BLACK_SMITH = 80;
  public final static int SOUND_BORDELLO_MEN_AND_WOMEN = 21;
  public final static int SOUND_BORDELLO_WOMEN = 20;
  public final static int SOUND_CASTLE_INTERIOR_LARGE = 68;
  public final static int SOUND_CASTLE_INTERIOR_MEDIUM = 67;
  public final static int SOUND_CASTLE_INTERIOR_SMALL = 66;
  public final static int SOUND_CAVE_EVIL_1_XP2 = 104;
  public final static int SOUND_CAVE_EVIL_2_XP2 = 105;
  public final static int SOUND_CAVE_EVIL_3_XP2 = 106;
  public final static int SOUND_CAVE_INSECTS_1 = 42;
  public final static int SOUND_CAVE_INSECTS_2 = 43;
  public final static int SOUND_CAVE_LARGE = 62;
  public final static int SOUND_CAVE_MEDIUM = 61;
  public final static int SOUND_CAVE_SMALL = 60;
  public final static int SOUND_CITY_DAY_CROWDED = 12;
  public final static int SOUND_CITY_DAY_SPARSE = 13;
  public final static int SOUND_CITY_MARKET = 15;
  public final static int SOUND_CITY_NIGHT = 14;
  public final static int SOUND_CITY_SLUMS_DAY_CROWDED = 9;
  public final static int SOUND_CITY_SLUMS_DAY_SPARSE = 10;
  public final static int SOUND_CITY_SLUMS_NIGHT = 11;
  public final static int SOUND_CITY_TEMPLE_DISTRICT = 16;
  public final static int SOUND_COMBAT_MUFFLED_1 = 26;
  public final static int SOUND_COMBAT_MUFFLED_2 = 27;
  public final static int SOUND_COMBAT_OUTSIDE_1 = 24;
  public final static int SOUND_COMBAT_OUTSIDE_2 = 25;
  public final static int SOUND_COMMONER_TAVERN_TALK = 7;
  public final static int SOUND_CRYPT_MEDIUM_1 = 70;
  public final static int SOUND_CRYPT_MEDIUM_2 = 71;
  public final static int SOUND_CRYPT_SMALL = 69;
  public final static int SOUND_DESERT_DAY_XP1 = 92;
  public final static int SOUND_DESERT_NIGHT_XP1 = 93;
  public final static int SOUND_DUNGEON_LAKE_LAVA = 28;
  public final static int SOUND_EVIL_DRONE_XP2 = 101;
  public final static int SOUND_EVIL_DUNGEON_LARGE = 59;
  public final static int SOUND_EVIL_DUNGEON_MEDIUM = 58;
  public final static int SOUND_EVIL_DUNGEON_SMALL = 57;
  public final static int SOUND_FOREST_DAY_1 = 49;
  public final static int SOUND_FOREST_DAY_2 = 50;
  public final static int SOUND_FOREST_DAY_3 = 51;
  public final static int SOUND_FOREST_DAY_SCARY = 52;
  public final static int SOUND_FOREST_MAGICAL = 56;
  public final static int SOUND_FOREST_NIGHT_1 = 53;
  public final static int SOUND_FOREST_NIGHT_2 = 54;
  public final static int SOUND_FOREST_NIGHT_SCARY = 55;
  public final static int SOUND_FROZEN_HELL_XP2 = 103;
  public final static int SOUND_GUST_CAVERN = 35;
  public final static int SOUND_GUST_CHASM = 34;
  public final static int SOUND_GUST_DRAFT = 37;
  public final static int SOUND_GUST_GRASS = 36;
  public final static int SOUND_HAUNTED_INTERIOR_1 = 77;
  public final static int SOUND_HAUNTED_INTERIOR_2 = 78;
  public final static int SOUND_HAUNTED_INTERIOR_3 = 79;
  public final static int SOUND_HOUSE_INTERIOR_1 = 72;
  public final static int SOUND_HOUSE_INTERIOR_2 = 73;
  public final static int SOUND_HOUSE_INTERIOR_3 = 74;
  public final static int SOUND_INTERIOR_INSECTS_1 = 44;
  public final static int SOUND_INTERIOR_INSECTS_2 = 45;
  public final static int SOUND_KITCHEN_INTERIOR_LARGE = 76;
  public final static int SOUND_KITCHEN_INTERIOR_SMALL = 75;
  public final static int SOUND_LARGE_GROUP_TALKS_INSIDE = 6;
  public final static int SOUND_LIZARD_FOLK_CAVE_CRYSTALS = 46;
  public final static int SOUND_MAGICAL_INTERIOR_AIRLAB = 88;
  public final static int SOUND_MAGICAL_INTERIOR_EARTHLAB = 87;
  public final static int SOUND_MAGICAL_INTERIOR_FIRELAB = 86;
  public final static int SOUND_MAGICAL_INTERIOR_WATERLAB = 89;
  public final static int SOUND_MAGIC_INTERIOR_EVIL = 85;
  public final static int SOUND_MAGIC_INTERIOR_LARGE = 84;
  public final static int SOUND_MAGIC_INTERIOR_MEDIUM = 83;
  public final static int SOUND_MAGIC_INTERIOR_SMALL = 82;
  public final static int SOUND_MEDIUM_GROUP_TALKS_INSIDE = 5;
  public final static int SOUND_MEN_WHISPER_INSIDE = 1;
  public final static int SOUND_MINE_LARGE = 65;
  public final static int SOUND_MINE_MEDIUM = 64;
  public final static int SOUND_MINE_SMALL = 63;
  public final static int SOUND_MONASTERY_INTERIOR_XP1 = 94;
  public final static int SOUND_NOBLE_TAVERN_TALK = 8;
  public final static int SOUND_NONE = 0;
  public final static int SOUND_PEOPLE_WHISPER_INSIDE = 3;
  public final static int SOUND_PIT_CRIES = 81;
  public final static int SOUND_PLAIN_OF_FIRE_XP2 = 102;
  public final static int SOUND_RAIN_HARD = 39;
  public final static int SOUND_RAIN_LIGHT = 38;
  public final static int SOUND_RAIN_STORM_BIG = 41;
  public final static int SOUND_RAIN_STORM_SMALL = 40;
  public final static int SOUND_RIOT_MUFFLED = 23;
  public final static int SOUND_RIOT_OUTSIDE = 22;
  public final static int SOUND_RUIN_HAUNTED_XP1 = 98;
  public final static int SOUND_RUIN_RUMBLING_XP1 = 97;
  public final static int SOUND_RUIN_WET_XP1 = 96;
  public final static int SOUND_SAND_STORM_EXTREME_XP1 = 100;
  public final static int SOUND_SAND_STORM_LIGHT_XP1 = 99;
  public final static int SOUND_SEWERS_1 = 47;
  public final static int SOUND_SEWERS_2 = 48;
  public final static int SOUND_SEWER_SLUDGE_LAKE = 29;
  public final static int SOUND_SMALL_GROUP_TALKS_INSIDE = 4;
  public final static int SOUND_TAVERN_ROWDY = 107;
  public final static int SOUND_TOWN_DAY_CROWDED = 17;
  public final static int SOUND_TOWN_DAY_SPARSE = 18;
  public final static int SOUND_TOWN_NIGHT = 19;
  public final static int SOUND_WIND_FOREST = 33;
  public final static int SOUND_WIND_MEDIUM = 31;
  public final static int SOUND_WIND_SOFT = 30;
  public final static int SOUND_WIND_STRONG = 32;
  public final static int SOUND_WINTER_DAY_WET_XP1 = 90;
  public final static int SOUND_WINTER_DAY_WINDY_XP1 = 91;
  public final static int SOUND_WOMEN_WHISPER_INSIDE = 2;

  public static String nameOf(int value) {
    if (value == 80) return "Ambient.SOUND_BLACK_SMITH";
    if (value == 21) return "Ambient.SOUND_BORDELLO_MEN_AND_WOMEN";
    if (value == 20) return "Ambient.SOUND_BORDELLO_WOMEN";
    if (value == 68) return "Ambient.SOUND_CASTLE_INTERIOR_LARGE";
    if (value == 67) return "Ambient.SOUND_CASTLE_INTERIOR_MEDIUM";
    if (value == 66) return "Ambient.SOUND_CASTLE_INTERIOR_SMALL";
    if (value == 104) return "Ambient.SOUND_CAVE_EVIL_1_XP2";
    if (value == 105) return "Ambient.SOUND_CAVE_EVIL_2_XP2";
    if (value == 106) return "Ambient.SOUND_CAVE_EVIL_3_XP2";
    if (value == 42) return "Ambient.SOUND_CAVE_INSECTS_1";
    if (value == 43) return "Ambient.SOUND_CAVE_INSECTS_2";
    if (value == 62) return "Ambient.SOUND_CAVE_LARGE";
    if (value == 61) return "Ambient.SOUND_CAVE_MEDIUM";
    if (value == 60) return "Ambient.SOUND_CAVE_SMALL";
    if (value == 12) return "Ambient.SOUND_CITY_DAY_CROWDED";
    if (value == 13) return "Ambient.SOUND_CITY_DAY_SPARSE";
    if (value == 15) return "Ambient.SOUND_CITY_MARKET";
    if (value == 14) return "Ambient.SOUND_CITY_NIGHT";
    if (value == 9) return "Ambient.SOUND_CITY_SLUMS_DAY_CROWDED";
    if (value == 10) return "Ambient.SOUND_CITY_SLUMS_DAY_SPARSE";
    if (value == 11) return "Ambient.SOUND_CITY_SLUMS_NIGHT";
    if (value == 16) return "Ambient.SOUND_CITY_TEMPLE_DISTRICT";
    if (value == 26) return "Ambient.SOUND_COMBAT_MUFFLED_1";
    if (value == 27) return "Ambient.SOUND_COMBAT_MUFFLED_2";
    if (value == 24) return "Ambient.SOUND_COMBAT_OUTSIDE_1";
    if (value == 25) return "Ambient.SOUND_COMBAT_OUTSIDE_2";
    if (value == 7) return "Ambient.SOUND_COMMONER_TAVERN_TALK";
    if (value == 70) return "Ambient.SOUND_CRYPT_MEDIUM_1";
    if (value == 71) return "Ambient.SOUND_CRYPT_MEDIUM_2";
    if (value == 69) return "Ambient.SOUND_CRYPT_SMALL";
    if (value == 92) return "Ambient.SOUND_DESERT_DAY_XP1";
    if (value == 93) return "Ambient.SOUND_DESERT_NIGHT_XP1";
    if (value == 28) return "Ambient.SOUND_DUNGEON_LAKE_LAVA";
    if (value == 101) return "Ambient.SOUND_EVIL_DRONE_XP2";
    if (value == 59) return "Ambient.SOUND_EVIL_DUNGEON_LARGE";
    if (value == 58) return "Ambient.SOUND_EVIL_DUNGEON_MEDIUM";
    if (value == 57) return "Ambient.SOUND_EVIL_DUNGEON_SMALL";
    if (value == 49) return "Ambient.SOUND_FOREST_DAY_1";
    if (value == 50) return "Ambient.SOUND_FOREST_DAY_2";
    if (value == 51) return "Ambient.SOUND_FOREST_DAY_3";
    if (value == 52) return "Ambient.SOUND_FOREST_DAY_SCARY";
    if (value == 56) return "Ambient.SOUND_FOREST_MAGICAL";
    if (value == 53) return "Ambient.SOUND_FOREST_NIGHT_1";
    if (value == 54) return "Ambient.SOUND_FOREST_NIGHT_2";
    if (value == 55) return "Ambient.SOUND_FOREST_NIGHT_SCARY";
    if (value == 103) return "Ambient.SOUND_FROZEN_HELL_XP2";
    if (value == 35) return "Ambient.SOUND_GUST_CAVERN";
    if (value == 34) return "Ambient.SOUND_GUST_CHASM";
    if (value == 37) return "Ambient.SOUND_GUST_DRAFT";
    if (value == 36) return "Ambient.SOUND_GUST_GRASS";
    if (value == 77) return "Ambient.SOUND_HAUNTED_INTERIOR_1";
    if (value == 78) return "Ambient.SOUND_HAUNTED_INTERIOR_2";
    if (value == 79) return "Ambient.SOUND_HAUNTED_INTERIOR_3";
    if (value == 72) return "Ambient.SOUND_HOUSE_INTERIOR_1";
    if (value == 73) return "Ambient.SOUND_HOUSE_INTERIOR_2";
    if (value == 74) return "Ambient.SOUND_HOUSE_INTERIOR_3";
    if (value == 44) return "Ambient.SOUND_INTERIOR_INSECTS_1";
    if (value == 45) return "Ambient.SOUND_INTERIOR_INSECTS_2";
    if (value == 76) return "Ambient.SOUND_KITCHEN_INTERIOR_LARGE";
    if (value == 75) return "Ambient.SOUND_KITCHEN_INTERIOR_SMALL";
    if (value == 6) return "Ambient.SOUND_LARGE_GROUP_TALKS_INSIDE";
    if (value == 46) return "Ambient.SOUND_LIZARD_FOLK_CAVE_CRYSTALS";
    if (value == 88) return "Ambient.SOUND_MAGICAL_INTERIOR_AIRLAB";
    if (value == 87) return "Ambient.SOUND_MAGICAL_INTERIOR_EARTHLAB";
    if (value == 86) return "Ambient.SOUND_MAGICAL_INTERIOR_FIRELAB";
    if (value == 89) return "Ambient.SOUND_MAGICAL_INTERIOR_WATERLAB";
    if (value == 85) return "Ambient.SOUND_MAGIC_INTERIOR_EVIL";
    if (value == 84) return "Ambient.SOUND_MAGIC_INTERIOR_LARGE";
    if (value == 83) return "Ambient.SOUND_MAGIC_INTERIOR_MEDIUM";
    if (value == 82) return "Ambient.SOUND_MAGIC_INTERIOR_SMALL";
    if (value == 5) return "Ambient.SOUND_MEDIUM_GROUP_TALKS_INSIDE";
    if (value == 1) return "Ambient.SOUND_MEN_WHISPER_INSIDE";
    if (value == 65) return "Ambient.SOUND_MINE_LARGE";
    if (value == 64) return "Ambient.SOUND_MINE_MEDIUM";
    if (value == 63) return "Ambient.SOUND_MINE_SMALL";
    if (value == 94) return "Ambient.SOUND_MONASTERY_INTERIOR_XP1";
    if (value == 8) return "Ambient.SOUND_NOBLE_TAVERN_TALK";
    if (value == 0) return "Ambient.SOUND_NONE";
    if (value == 3) return "Ambient.SOUND_PEOPLE_WHISPER_INSIDE";
    if (value == 81) return "Ambient.SOUND_PIT_CRIES";
    if (value == 102) return "Ambient.SOUND_PLAIN_OF_FIRE_XP2";
    if (value == 39) return "Ambient.SOUND_RAIN_HARD";
    if (value == 38) return "Ambient.SOUND_RAIN_LIGHT";
    if (value == 41) return "Ambient.SOUND_RAIN_STORM_BIG";
    if (value == 40) return "Ambient.SOUND_RAIN_STORM_SMALL";
    if (value == 23) return "Ambient.SOUND_RIOT_MUFFLED";
    if (value == 22) return "Ambient.SOUND_RIOT_OUTSIDE";
    if (value == 98) return "Ambient.SOUND_RUIN_HAUNTED_XP1";
    if (value == 97) return "Ambient.SOUND_RUIN_RUMBLING_XP1";
    if (value == 96) return "Ambient.SOUND_RUIN_WET_XP1";
    if (value == 100) return "Ambient.SOUND_SAND_STORM_EXTREME_XP1";
    if (value == 99) return "Ambient.SOUND_SAND_STORM_LIGHT_XP1";
    if (value == 47) return "Ambient.SOUND_SEWERS_1";
    if (value == 48) return "Ambient.SOUND_SEWERS_2";
    if (value == 29) return "Ambient.SOUND_SEWER_SLUDGE_LAKE";
    if (value == 4) return "Ambient.SOUND_SMALL_GROUP_TALKS_INSIDE";
    if (value == 107) return "Ambient.SOUND_TAVERN_ROWDY";
    if (value == 17) return "Ambient.SOUND_TOWN_DAY_CROWDED";
    if (value == 18) return "Ambient.SOUND_TOWN_DAY_SPARSE";
    if (value == 19) return "Ambient.SOUND_TOWN_NIGHT";
    if (value == 33) return "Ambient.SOUND_WIND_FOREST";
    if (value == 31) return "Ambient.SOUND_WIND_MEDIUM";
    if (value == 30) return "Ambient.SOUND_WIND_SOFT";
    if (value == 32) return "Ambient.SOUND_WIND_STRONG";
    if (value == 90) return "Ambient.SOUND_WINTER_DAY_WET_XP1";
    if (value == 91) return "Ambient.SOUND_WINTER_DAY_WINDY_XP1";
    if (value == 2) return "Ambient.SOUND_WOMEN_WHISPER_INSIDE";
    return "Ambient.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "Ambient.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "Ambient.(not found: " + value + ")";
  }
}
