package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "APPEARANCE_TYPE".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class AppearanceType {
  private AppearanceType() {}

  public final static int ALLIP = 186;
  public final static int ANIMATED_CHEST = 469;
  public final static int ARANEA = 157;
  public final static int ARCH_TARGET = 200;
  public final static int ARIBETH = 190;
  public final static int ASABI_CHIEFTAIN = 353;
  public final static int ASABI_SHAMAN = 354;
  public final static int ASABI_WARRIOR = 355;
  public final static int AZER_FEMALE = 429;
  public final static int AZER_MALE = 428;
  public final static int BADGER = 8;
  public final static int BADGER_DIRE = 9;
  public final static int BALOR = 38;
  public final static int BARTENDER = 234;
  public final static int BASILISK = 369;
  public final static int BAT = 10;
  public final static int BAT_HORROR = 11;
  public final static int BEAR_BLACK = 12;
  public final static int BEAR_BROWN = 13;
  public final static int BEAR_DIRE = 15;
  public final static int BEAR_KODIAK = 204;
  public final static int BEAR_POLAR = 14;
  public final static int BEETLE_FIRE = 18;
  public final static int BEETLE_SLICER = 17;
  public final static int BEETLE_STAG = 19;
  public final static int BEETLE_STINK = 20;
  public final static int BEGGER = 220;
  public final static int BEHOLDER = 401;
  public final static int BEHOLDER_EYEBALL = 403;
  public final static int BEHOLDER_MAGE = 402;
  public final static int BEHOLDER_MOTHER = 472;
  public final static int BLOOD_SAILER = 221;
  public final static int BOAR = 21;
  public final static int BOAR_DIRE = 22;
  public final static int BODAK = 23;
  public final static int BUGBEAR_A = 29;
  public final static int BUGBEAR_B = 30;
  public final static int BUGBEAR_CHIEFTAIN_A = 25;
  public final static int BUGBEAR_CHIEFTAIN_B = 26;
  public final static int BUGBEAR_SHAMAN_A = 27;
  public final static int BUGBEAR_SHAMAN_B = 28;
  public final static int BULETTE = 481;
  public final static int CAT_CAT_DIRE = 95;
  public final static int CAT_COUGAR = 203;
  public final static int CAT_CRAG_CAT = 94;
  public final static int CAT_JAGUAR = 98;
  public final static int CAT_KRENSHAR = 96;
  public final static int CAT_LEOPARD = 93;
  public final static int CAT_LION = 97;
  public final static int CAT_MPANTHER = 306;
  public final static int CAT_PANTHER = 202;
  public final static int CHICKEN = 31;
  public final static int COCKATRICE = 368;
  public final static int COMBAT_DUMMY = 201;
  public final static int CONVICT = 238;
  public final static int COW = 34;
  public final static int CULT_MEMBER = 212;
  public final static int DEEP_ROTHE = 416;
  public final static int DEER = 35;
  public final static int DEER_STAG = 37;
  public final static int DEMI_LICH = 430;
  public final static int DEVIL = 392;
  public final static int DOG = 176;
  public final static int DOG_BLINKDOG = 174;
  public final static int DOG_DIRE_WOLF = 175;
  public final static int DOG_FENHOUND = 177;
  public final static int DOG_HELL_HOUND = 179;
  public final static int DOG_SHADOW_MASTIF = 180;
  public final static int DOG_WINTER_WOLF = 184;
  public final static int DOG_WOLF = 181;
  public final static int DOG_WORG = 185;
  public final static int DOOM_KNIGHT = 40;
  public final static int DRACOLICH = 405;
  public final static int DRAGON_BLACK = 41;
  public final static int DRAGON_BLUE = 47;
  public final static int DRAGON_BRASS = 42;
  public final static int DRAGON_BRONZE = 45;
  public final static int DRAGON_COPPER = 43;
  public final static int DRAGON_GOLD = 46;
  public final static int DRAGON_GREEN = 48;
  public final static int DRAGON_PRIS = 425;
  public final static int DRAGON_RED = 49;
  public final static int DRAGON_SHADOW = 418;
  public final static int DRAGON_SILVER = 44;
  public final static int DRAGON_WHITE = 50;
  public final static int DRIDER = 406;
  public final static int DRIDER_CHIEF = 407;
  public final static int DRIDER_FEMALE = 446;
  public final static int DROW_CLERIC = 215;
  public final static int DROW_FEMALE_1 = 478;
  public final static int DROW_FEMALE_2 = 479;
  public final static int DROW_FIGHTER = 216;
  public final static int DROW_MATRON = 410;
  public final static int DROW_SLAVE = 408;
  public final static int DROW_WARRIOR_1 = 476;
  public final static int DROW_WARRIOR_2 = 477;
  public final static int DROW_WARRIOR_3 = 480;
  public final static int DROW_WIZARD = 409;
  public final static int DRUEGAR_CLERIC = 218;
  public final static int DRUEGAR_FIGHTER = 217;
  public final static int DRYAD = 51;
  public final static int DUERGAR_CHIEF = 412;
  public final static int DUERGAR_SLAVE = 411;
  public final static int DWARF = 0;
  public final static int DWARF_GOLEM = 474;
  public final static int DWARF_HALFORC = 475;
  public final static int DWARF_NPC_FEMALE = 248;
  public final static int DWARF_NPC_MALE = 249;
  public final static int ELEMENTAL_AIR = 52;
  public final static int ELEMENTAL_AIR_ELDER = 53;
  public final static int ELEMENTAL_EARTH = 56;
  public final static int ELEMENTAL_EARTH_ELDER = 57;
  public final static int ELEMENTAL_FIRE = 60;
  public final static int ELEMENTAL_FIRE_ELDER = 61;
  public final static int ELEMENTAL_WATER = 69;
  public final static int ELEMENTAL_WATER_ELDER = 68;
  public final static int ELF = 1;
  public final static int ELF_NPC_FEMALE = 245;
  public final static int ELF_NPC_MALE_01 = 246;
  public final static int ELF_NPC_MALE_02 = 247;
  public final static int ETTERCAP = 166;
  public final static int ETTIN = 72;
  public final static int FAERIE_DRAGON = 374;
  public final static int FAIRY = 55;
  public final static int FALCON = 144;
  public final static int FEMALE_01 = 222;
  public final static int FEMALE_02 = 223;
  public final static int FEMALE_03 = 224;
  public final static int FEMALE_04 = 225;
  public final static int FORMIAN_MYRMARCH = 362;
  public final static int FORMIAN_QUEEN = 363;
  public final static int FORMIAN_WARRIOR = 361;
  public final static int FORMIAN_WORKER = 360;
  public final static int GARGOYLE = 73;
  public final static int GELATINOUS_CUBE = 470;
  public final static int GHAST = 74;
  public final static int GHOUL = 76;
  public final static int GHOUL_LORD = 77;
  public final static int GIANT_FIRE = 80;
  public final static int GIANT_FIRE_FEMALE = 351;
  public final static int GIANT_FROST = 81;
  public final static int GIANT_FROST_FEMALE = 350;
  public final static int GIANT_HILL = 78;
  public final static int GIANT_MOUNTAIN = 79;
  public final static int GNOLL_WARRIOR = 388;
  public final static int GNOLL_WIZ = 389;
  public final static int GNOME = 2;
  public final static int GNOME_NPC_FEMALE = 243;
  public final static int GNOME_NPC_MALE = 244;
  public final static int GOBLIN_A = 86;
  public final static int GOBLIN_B = 87;
  public final static int GOBLIN_CHIEF_A = 82;
  public final static int GOBLIN_CHIEF_B = 83;
  public final static int GOBLIN_SHAMAN_A = 84;
  public final static int GOBLIN_SHAMAN_B = 85;
  public final static int GOLEM_ADAMANTIUM = 421;
  public final static int GOLEM_BONE = 24;
  public final static int GOLEM_CLAY = 91;
  public final static int GOLEM_DEMONFLESH = 468;
  public final static int GOLEM_FLESH = 88;
  public final static int GOLEM_IRON = 89;
  public final static int GOLEM_MITHRAL = 420;
  public final static int GOLEM_STONE = 92;
  public final static int GORGON = 367;
  public final static int GRAY_OOZE = 393;
  public final static int GREY_RENDER = 205;
  public final static int GYNOSPHINX = 365;
  public final static int HALFLING = 3;
  public final static int HALFLING_NPC_FEMALE = 250;
  public final static int HALFLING_NPC_MALE = 251;
  public final static int HALF_ELF = 4;
  public final static int HALF_ORC = 5;
  public final static int HALF_ORC_NPC_FEMALE = 252;
  public final static int HALF_ORC_NPC_MALE_01 = 253;
  public final static int HALF_ORC_NPC_MALE_02 = 254;
  public final static int HARPY = 419;
  public final static int HELMED_HORROR = 100;
  public final static int HEURODIS_LICH = 370;
  public final static int HOBGOBLIN_WARRIOR = 390;
  public final static int HOBGOBLIN_WIZARD = 391;
  public final static int HOOK_HORROR = 102;
  public final static int HOUSE_GUARD = 219;
  public final static int HUMAN = 6;
  public final static int HUMAN_NPC_FEMALE_01 = 255;
  public final static int HUMAN_NPC_FEMALE_02 = 256;
  public final static int HUMAN_NPC_FEMALE_03 = 257;
  public final static int HUMAN_NPC_FEMALE_04 = 258;
  public final static int HUMAN_NPC_FEMALE_05 = 259;
  public final static int HUMAN_NPC_FEMALE_06 = 260;
  public final static int HUMAN_NPC_FEMALE_07 = 261;
  public final static int HUMAN_NPC_FEMALE_08 = 262;
  public final static int HUMAN_NPC_FEMALE_09 = 263;
  public final static int HUMAN_NPC_FEMALE_10 = 264;
  public final static int HUMAN_NPC_FEMALE_11 = 265;
  public final static int HUMAN_NPC_FEMALE_12 = 266;
  public final static int HUMAN_NPC_MALE_01 = 267;
  public final static int HUMAN_NPC_MALE_02 = 268;
  public final static int HUMAN_NPC_MALE_03 = 269;
  public final static int HUMAN_NPC_MALE_04 = 270;
  public final static int HUMAN_NPC_MALE_05 = 271;
  public final static int HUMAN_NPC_MALE_06 = 272;
  public final static int HUMAN_NPC_MALE_07 = 273;
  public final static int HUMAN_NPC_MALE_08 = 274;
  public final static int HUMAN_NPC_MALE_09 = 275;
  public final static int HUMAN_NPC_MALE_10 = 276;
  public final static int HUMAN_NPC_MALE_11 = 277;
  public final static int HUMAN_NPC_MALE_12 = 278;
  public final static int HUMAN_NPC_MALE_13 = 279;
  public final static int HUMAN_NPC_MALE_14 = 280;
  public final static int HUMAN_NPC_MALE_15 = 281;
  public final static int HUMAN_NPC_MALE_16 = 282;
  public final static int HUMAN_NPC_MALE_17 = 283;
  public final static int HUMAN_NPC_MALE_18 = 284;
  public final static int IMP = 105;
  public final static int INN_KEEPER = 233;
  public final static int INTELLECT_DEVOURER = 117;
  public final static int INVALID = -1;
  public final static int INVISIBLE_HUMAN_MALE = 298;
  public final static int INVISIBLE_STALKER = 64;
  public final static int KID_FEMALE = 242;
  public final static int KID_MALE = 241;
  public final static int KOBOLD_A = 302;
  public final static int KOBOLD_B = 305;
  public final static int KOBOLD_CHIEF_A = 300;
  public final static int KOBOLD_CHIEF_B = 303;
  public final static int KOBOLD_SHAMAN_A = 301;
  public final static int KOBOLD_SHAMAN_B = 304;
  public final static int LANTERN_ARCHON = 103;
  public final static int LICH = 39;
  public final static int LIZARDFOLK_A = 134;
  public final static int LIZARDFOLK_B = 135;
  public final static int LIZARDFOLK_SHAMAN_A = 132;
  public final static int LIZARDFOLK_SHAMAN_B = 133;
  public final static int LIZARDFOLK_WARRIOR_A = 130;
  public final static int LIZARDFOLK_WARRIOR_B = 131;
  public final static int LUSKAN_GUARD = 211;
  public final static int MALE_01 = 226;
  public final static int MALE_02 = 227;
  public final static int MALE_03 = 228;
  public final static int MALE_04 = 229;
  public final static int MALE_05 = 230;
  public final static int MANTICORE = 366;
  public final static int MEDUSA = 352;
  public final static int MEPHISTO_BIG = 404;
  public final static int MEPHISTO_NORM = 471;
  public final static int MEPHIT_AIR = 106;
  public final static int MEPHIT_DUST = 107;
  public final static int MEPHIT_EARTH = 108;
  public final static int MEPHIT_FIRE = 109;
  public final static int MEPHIT_ICE = 110;
  public final static int MEPHIT_MAGMA = 114;
  public final static int MEPHIT_OOZE = 112;
  public final static int MEPHIT_SALT = 111;
  public final static int MEPHIT_STEAM = 113;
  public final static int MEPHIT_WATER = 115;
  public final static int MINDFLAYER = 413;
  public final static int MINDFLAYER_2 = 414;
  public final static int MINDFLAYER_ALHOON = 415;
  public final static int MINOGON = 119;
  public final static int MINOTAUR = 120;
  public final static int MINOTAUR_CHIEFTAIN = 121;
  public final static int MINOTAUR_SHAMAN = 122;
  public final static int MOHRG = 123;
  public final static int MUMMY_COMMON = 58;
  public final static int MUMMY_FIGHTER_2 = 59;
  public final static int MUMMY_GREATER = 124;
  public final static int MUMMY_WARRIOR = 125;
  public final static int NWN_AARIN = 188;
  public final static int NWN_ARIBETH_EVIL = 189;
  public final static int NWN_HAEDRALINE = 191;
  public final static int NWN_MAUGRIM = 193;
  public final static int NWN_MORAG = 192;
  public final static int NWN_NASHER = 296;
  public final static int NWN_SEDOS = 297;
  public final static int NW_MILITIA_MEMBER = 210;
  public final static int NYMPH = 126;
  public final static int OBJECT_BLUE = 436;
  public final static int OBJECT_BOAT = 473;
  public final static int OBJECT_CANDLE = 433;
  public final static int OBJECT_CHAIR = 431;
  public final static int OBJECT_CHEST = 434;
  public final static int OBJECT_CYAN = 437;
  public final static int OBJECT_FLAME_LARGE = 445;
  public final static int OBJECT_FLAME_MEDIUM = 444;
  public final static int OBJECT_FLAME_SMALL = 443;
  public final static int OBJECT_GREEN = 438;
  public final static int OBJECT_ORANGE = 440;
  public final static int OBJECT_PURPLE = 442;
  public final static int OBJECT_RED = 441;
  public final static int OBJECT_TABLE = 432;
  public final static int OBJECT_WHITE = 435;
  public final static int OBJECT_YELLOW = 439;
  public final static int OCHRE_JELLY_LARGE = 394;
  public final static int OCHRE_JELLY_MEDIUM = 396;
  public final static int OCHRE_JELLY_SMALL = 398;
  public final static int OGRE = 127;
  public final static int OGREB = 207;
  public final static int OGRE_CHIEFTAIN = 128;
  public final static int OGRE_CHIEFTAINB = 208;
  public final static int OGRE_MAGE = 129;
  public final static int OGRE_MAGEB = 209;
  public final static int OLD_MAN = 239;
  public final static int OLD_WOMAN = 240;
  public final static int ORC_A = 140;
  public final static int ORC_B = 141;
  public final static int ORC_CHIEFTAIN_A = 136;
  public final static int ORC_CHIEFTAIN_B = 137;
  public final static int ORC_SHAMAN_A = 138;
  public final static int ORC_SHAMAN_B = 139;
  public final static int OX = 142;
  public final static int PARROT = 7;
  public final static int PENGUIN = 206;
  public final static int PLAGUE_VICTIM = 231;
  public final static int PROSTITUTE_01 = 236;
  public final static int PROSTITUTE_02 = 237;
  public final static int PSEUDODRAGON = 375;
  public final static int QUASIT = 104;
  public final static int RAKSHASA_BEAR_MALE = 294;
  public final static int RAKSHASA_TIGER_FEMALE = 290;
  public final static int RAKSHASA_TIGER_MALE = 293;
  public final static int RAKSHASA_WOLF_MALE = 295;
  public final static int RAT = 386;
  public final static int RAT_DIRE = 387;
  public final static int RAVEN = 145;
  public final static int SAHUAGIN = 65;
  public final static int SAHUAGIN_CLERIC = 67;
  public final static int SAHUAGIN_LEADER = 66;
  public final static int SEAGULL_FLYING = 291;
  public final static int SEAGULL_WALKING = 292;
  public final static int SEA_HAG = 454;
  public final static int SHADOW = 146;
  public final static int SHADOW_FIEND = 147;
  public final static int SHARK_GOBLIN = 449;
  public final static int SHARK_HAMMERHEAD = 448;
  public final static int SHARK_MAKO = 447;
  public final static int SHIELD_GUARDIAN = 90;
  public final static int SHOP_KEEPER = 232;
  public final static int SKELETAL_DEVOURER = 36;
  public final static int SKELETON_CHIEFTAIN = 182;
  public final static int SKELETON_COMMON = 63;
  public final static int SKELETON_MAGE = 148;
  public final static int SKELETON_PRIEST = 62;
  public final static int SKELETON_WARRIOR = 150;
  public final static int SKELETON_WARRIOR_1 = 70;
  public final static int SKELETON_WARRIOR_2 = 71;
  public final static int SLAAD_BLACK = 426;
  public final static int SLAAD_BLUE = 151;
  public final static int SLAAD_DEATH = 152;
  public final static int SLAAD_GRAY = 153;
  public final static int SLAAD_GREEN = 154;
  public final static int SLAAD_RED = 155;
  public final static int SLAAD_WHITE = 427;
  public final static int SPECTRE = 156;
  public final static int SPHINX = 364;
  public final static int SPIDER_DEMON = 422;
  public final static int SPIDER_DIRE = 158;
  public final static int SPIDER_GIANT = 159;
  public final static int SPIDER_PHASE = 160;
  public final static int SPIDER_SWORD = 161;
  public final static int SPIDER_WRAITH = 162;
  public final static int STINGER = 356;
  public final static int STINGER_CHIEFTAIN = 358;
  public final static int STINGER_MAGE = 359;
  public final static int STINGER_WARRIOR = 357;
  public final static int SUCCUBUS = 163;
  public final static int SVIRF_FEMALE = 424;
  public final static int SVIRF_MALE = 423;
  public final static int TROGLODYTE = 451;
  public final static int TROGLODYTE_CLERIC = 453;
  public final static int TROGLODYTE_WARRIOR = 452;
  public final static int TROLL = 167;
  public final static int TROLL_CHIEFTAIN = 164;
  public final static int TROLL_SHAMAN = 165;
  public final static int UMBERHULK = 168;
  public final static int UTHGARD_ELK_TRIBE = 213;
  public final static int UTHGARD_TIGER_TRIBE = 214;
  public final static int VAMPIRE_FEMALE = 288;
  public final static int VAMPIRE_MALE = 289;
  public final static int VROCK = 101;
  public final static int WAITRESS = 235;
  public final static int WAR_DEVOURER = 54;
  public final static int WERECAT = 99;
  public final static int WERERAT = 170;
  public final static int WEREWOLF = 171;
  public final static int WIGHT = 172;
  public final static int WILL_O_WISP = 116;
  public final static int WRAITH = 187;
  public final static int WYRMLING_BLACK = 378;
  public final static int WYRMLING_BLUE = 377;
  public final static int WYRMLING_BRASS = 381;
  public final static int WYRMLING_BRONZE = 383;
  public final static int WYRMLING_COPPER = 382;
  public final static int WYRMLING_GOLD = 385;
  public final static int WYRMLING_GREEN = 379;
  public final static int WYRMLING_RED = 376;
  public final static int WYRMLING_SILVER = 384;
  public final static int WYRMLING_WHITE = 380;
  public final static int YUAN_TI = 285;
  public final static int YUAN_TI_CHIEFTEN = 286;
  public final static int YUAN_TI_WIZARD = 287;
  public final static int ZOMBIE = 198;
  public final static int ZOMBIE_ROTTING = 195;
  public final static int ZOMBIE_TYRANT_FOG = 199;
  public final static int ZOMBIE_WARRIOR_1 = 196;
  public final static int ZOMBIE_WARRIOR_2 = 197;

  public static String nameOf(int value) {
    if (value == 186) return "AppearanceType.ALLIP";
    if (value == 469) return "AppearanceType.ANIMATED_CHEST";
    if (value == 157) return "AppearanceType.ARANEA";
    if (value == 200) return "AppearanceType.ARCH_TARGET";
    if (value == 190) return "AppearanceType.ARIBETH";
    if (value == 353) return "AppearanceType.ASABI_CHIEFTAIN";
    if (value == 354) return "AppearanceType.ASABI_SHAMAN";
    if (value == 355) return "AppearanceType.ASABI_WARRIOR";
    if (value == 429) return "AppearanceType.AZER_FEMALE";
    if (value == 428) return "AppearanceType.AZER_MALE";
    if (value == 8) return "AppearanceType.BADGER";
    if (value == 9) return "AppearanceType.BADGER_DIRE";
    if (value == 38) return "AppearanceType.BALOR";
    if (value == 234) return "AppearanceType.BARTENDER";
    if (value == 369) return "AppearanceType.BASILISK";
    if (value == 10) return "AppearanceType.BAT";
    if (value == 11) return "AppearanceType.BAT_HORROR";
    if (value == 12) return "AppearanceType.BEAR_BLACK";
    if (value == 13) return "AppearanceType.BEAR_BROWN";
    if (value == 15) return "AppearanceType.BEAR_DIRE";
    if (value == 204) return "AppearanceType.BEAR_KODIAK";
    if (value == 14) return "AppearanceType.BEAR_POLAR";
    if (value == 18) return "AppearanceType.BEETLE_FIRE";
    if (value == 17) return "AppearanceType.BEETLE_SLICER";
    if (value == 19) return "AppearanceType.BEETLE_STAG";
    if (value == 20) return "AppearanceType.BEETLE_STINK";
    if (value == 220) return "AppearanceType.BEGGER";
    if (value == 401) return "AppearanceType.BEHOLDER";
    if (value == 403) return "AppearanceType.BEHOLDER_EYEBALL";
    if (value == 402) return "AppearanceType.BEHOLDER_MAGE";
    if (value == 472) return "AppearanceType.BEHOLDER_MOTHER";
    if (value == 221) return "AppearanceType.BLOOD_SAILER";
    if (value == 21) return "AppearanceType.BOAR";
    if (value == 22) return "AppearanceType.BOAR_DIRE";
    if (value == 23) return "AppearanceType.BODAK";
    if (value == 29) return "AppearanceType.BUGBEAR_A";
    if (value == 30) return "AppearanceType.BUGBEAR_B";
    if (value == 25) return "AppearanceType.BUGBEAR_CHIEFTAIN_A";
    if (value == 26) return "AppearanceType.BUGBEAR_CHIEFTAIN_B";
    if (value == 27) return "AppearanceType.BUGBEAR_SHAMAN_A";
    if (value == 28) return "AppearanceType.BUGBEAR_SHAMAN_B";
    if (value == 481) return "AppearanceType.BULETTE";
    if (value == 95) return "AppearanceType.CAT_CAT_DIRE";
    if (value == 203) return "AppearanceType.CAT_COUGAR";
    if (value == 94) return "AppearanceType.CAT_CRAG_CAT";
    if (value == 98) return "AppearanceType.CAT_JAGUAR";
    if (value == 96) return "AppearanceType.CAT_KRENSHAR";
    if (value == 93) return "AppearanceType.CAT_LEOPARD";
    if (value == 97) return "AppearanceType.CAT_LION";
    if (value == 306) return "AppearanceType.CAT_MPANTHER";
    if (value == 202) return "AppearanceType.CAT_PANTHER";
    if (value == 31) return "AppearanceType.CHICKEN";
    if (value == 368) return "AppearanceType.COCKATRICE";
    if (value == 201) return "AppearanceType.COMBAT_DUMMY";
    if (value == 238) return "AppearanceType.CONVICT";
    if (value == 34) return "AppearanceType.COW";
    if (value == 212) return "AppearanceType.CULT_MEMBER";
    if (value == 416) return "AppearanceType.DEEP_ROTHE";
    if (value == 35) return "AppearanceType.DEER";
    if (value == 37) return "AppearanceType.DEER_STAG";
    if (value == 430) return "AppearanceType.DEMI_LICH";
    if (value == 392) return "AppearanceType.DEVIL";
    if (value == 176) return "AppearanceType.DOG";
    if (value == 174) return "AppearanceType.DOG_BLINKDOG";
    if (value == 175) return "AppearanceType.DOG_DIRE_WOLF";
    if (value == 177) return "AppearanceType.DOG_FENHOUND";
    if (value == 179) return "AppearanceType.DOG_HELL_HOUND";
    if (value == 180) return "AppearanceType.DOG_SHADOW_MASTIF";
    if (value == 184) return "AppearanceType.DOG_WINTER_WOLF";
    if (value == 181) return "AppearanceType.DOG_WOLF";
    if (value == 185) return "AppearanceType.DOG_WORG";
    if (value == 40) return "AppearanceType.DOOM_KNIGHT";
    if (value == 405) return "AppearanceType.DRACOLICH";
    if (value == 41) return "AppearanceType.DRAGON_BLACK";
    if (value == 47) return "AppearanceType.DRAGON_BLUE";
    if (value == 42) return "AppearanceType.DRAGON_BRASS";
    if (value == 45) return "AppearanceType.DRAGON_BRONZE";
    if (value == 43) return "AppearanceType.DRAGON_COPPER";
    if (value == 46) return "AppearanceType.DRAGON_GOLD";
    if (value == 48) return "AppearanceType.DRAGON_GREEN";
    if (value == 425) return "AppearanceType.DRAGON_PRIS";
    if (value == 49) return "AppearanceType.DRAGON_RED";
    if (value == 418) return "AppearanceType.DRAGON_SHADOW";
    if (value == 44) return "AppearanceType.DRAGON_SILVER";
    if (value == 50) return "AppearanceType.DRAGON_WHITE";
    if (value == 406) return "AppearanceType.DRIDER";
    if (value == 407) return "AppearanceType.DRIDER_CHIEF";
    if (value == 446) return "AppearanceType.DRIDER_FEMALE";
    if (value == 215) return "AppearanceType.DROW_CLERIC";
    if (value == 478) return "AppearanceType.DROW_FEMALE_1";
    if (value == 479) return "AppearanceType.DROW_FEMALE_2";
    if (value == 216) return "AppearanceType.DROW_FIGHTER";
    if (value == 410) return "AppearanceType.DROW_MATRON";
    if (value == 408) return "AppearanceType.DROW_SLAVE";
    if (value == 476) return "AppearanceType.DROW_WARRIOR_1";
    if (value == 477) return "AppearanceType.DROW_WARRIOR_2";
    if (value == 480) return "AppearanceType.DROW_WARRIOR_3";
    if (value == 409) return "AppearanceType.DROW_WIZARD";
    if (value == 218) return "AppearanceType.DRUEGAR_CLERIC";
    if (value == 217) return "AppearanceType.DRUEGAR_FIGHTER";
    if (value == 51) return "AppearanceType.DRYAD";
    if (value == 412) return "AppearanceType.DUERGAR_CHIEF";
    if (value == 411) return "AppearanceType.DUERGAR_SLAVE";
    if (value == 0) return "AppearanceType.DWARF";
    if (value == 474) return "AppearanceType.DWARF_GOLEM";
    if (value == 475) return "AppearanceType.DWARF_HALFORC";
    if (value == 248) return "AppearanceType.DWARF_NPC_FEMALE";
    if (value == 249) return "AppearanceType.DWARF_NPC_MALE";
    if (value == 52) return "AppearanceType.ELEMENTAL_AIR";
    if (value == 53) return "AppearanceType.ELEMENTAL_AIR_ELDER";
    if (value == 56) return "AppearanceType.ELEMENTAL_EARTH";
    if (value == 57) return "AppearanceType.ELEMENTAL_EARTH_ELDER";
    if (value == 60) return "AppearanceType.ELEMENTAL_FIRE";
    if (value == 61) return "AppearanceType.ELEMENTAL_FIRE_ELDER";
    if (value == 69) return "AppearanceType.ELEMENTAL_WATER";
    if (value == 68) return "AppearanceType.ELEMENTAL_WATER_ELDER";
    if (value == 1) return "AppearanceType.ELF";
    if (value == 245) return "AppearanceType.ELF_NPC_FEMALE";
    if (value == 246) return "AppearanceType.ELF_NPC_MALE_01";
    if (value == 247) return "AppearanceType.ELF_NPC_MALE_02";
    if (value == 166) return "AppearanceType.ETTERCAP";
    if (value == 72) return "AppearanceType.ETTIN";
    if (value == 374) return "AppearanceType.FAERIE_DRAGON";
    if (value == 55) return "AppearanceType.FAIRY";
    if (value == 144) return "AppearanceType.FALCON";
    if (value == 222) return "AppearanceType.FEMALE_01";
    if (value == 223) return "AppearanceType.FEMALE_02";
    if (value == 224) return "AppearanceType.FEMALE_03";
    if (value == 225) return "AppearanceType.FEMALE_04";
    if (value == 362) return "AppearanceType.FORMIAN_MYRMARCH";
    if (value == 363) return "AppearanceType.FORMIAN_QUEEN";
    if (value == 361) return "AppearanceType.FORMIAN_WARRIOR";
    if (value == 360) return "AppearanceType.FORMIAN_WORKER";
    if (value == 73) return "AppearanceType.GARGOYLE";
    if (value == 470) return "AppearanceType.GELATINOUS_CUBE";
    if (value == 74) return "AppearanceType.GHAST";
    if (value == 76) return "AppearanceType.GHOUL";
    if (value == 77) return "AppearanceType.GHOUL_LORD";
    if (value == 80) return "AppearanceType.GIANT_FIRE";
    if (value == 351) return "AppearanceType.GIANT_FIRE_FEMALE";
    if (value == 81) return "AppearanceType.GIANT_FROST";
    if (value == 350) return "AppearanceType.GIANT_FROST_FEMALE";
    if (value == 78) return "AppearanceType.GIANT_HILL";
    if (value == 79) return "AppearanceType.GIANT_MOUNTAIN";
    if (value == 388) return "AppearanceType.GNOLL_WARRIOR";
    if (value == 389) return "AppearanceType.GNOLL_WIZ";
    if (value == 2) return "AppearanceType.GNOME";
    if (value == 243) return "AppearanceType.GNOME_NPC_FEMALE";
    if (value == 244) return "AppearanceType.GNOME_NPC_MALE";
    if (value == 86) return "AppearanceType.GOBLIN_A";
    if (value == 87) return "AppearanceType.GOBLIN_B";
    if (value == 82) return "AppearanceType.GOBLIN_CHIEF_A";
    if (value == 83) return "AppearanceType.GOBLIN_CHIEF_B";
    if (value == 84) return "AppearanceType.GOBLIN_SHAMAN_A";
    if (value == 85) return "AppearanceType.GOBLIN_SHAMAN_B";
    if (value == 421) return "AppearanceType.GOLEM_ADAMANTIUM";
    if (value == 24) return "AppearanceType.GOLEM_BONE";
    if (value == 91) return "AppearanceType.GOLEM_CLAY";
    if (value == 468) return "AppearanceType.GOLEM_DEMONFLESH";
    if (value == 88) return "AppearanceType.GOLEM_FLESH";
    if (value == 89) return "AppearanceType.GOLEM_IRON";
    if (value == 420) return "AppearanceType.GOLEM_MITHRAL";
    if (value == 92) return "AppearanceType.GOLEM_STONE";
    if (value == 367) return "AppearanceType.GORGON";
    if (value == 393) return "AppearanceType.GRAY_OOZE";
    if (value == 205) return "AppearanceType.GREY_RENDER";
    if (value == 365) return "AppearanceType.GYNOSPHINX";
    if (value == 3) return "AppearanceType.HALFLING";
    if (value == 250) return "AppearanceType.HALFLING_NPC_FEMALE";
    if (value == 251) return "AppearanceType.HALFLING_NPC_MALE";
    if (value == 4) return "AppearanceType.HALF_ELF";
    if (value == 5) return "AppearanceType.HALF_ORC";
    if (value == 252) return "AppearanceType.HALF_ORC_NPC_FEMALE";
    if (value == 253) return "AppearanceType.HALF_ORC_NPC_MALE_01";
    if (value == 254) return "AppearanceType.HALF_ORC_NPC_MALE_02";
    if (value == 419) return "AppearanceType.HARPY";
    if (value == 100) return "AppearanceType.HELMED_HORROR";
    if (value == 370) return "AppearanceType.HEURODIS_LICH";
    if (value == 390) return "AppearanceType.HOBGOBLIN_WARRIOR";
    if (value == 391) return "AppearanceType.HOBGOBLIN_WIZARD";
    if (value == 102) return "AppearanceType.HOOK_HORROR";
    if (value == 219) return "AppearanceType.HOUSE_GUARD";
    if (value == 6) return "AppearanceType.HUMAN";
    if (value == 255) return "AppearanceType.HUMAN_NPC_FEMALE_01";
    if (value == 256) return "AppearanceType.HUMAN_NPC_FEMALE_02";
    if (value == 257) return "AppearanceType.HUMAN_NPC_FEMALE_03";
    if (value == 258) return "AppearanceType.HUMAN_NPC_FEMALE_04";
    if (value == 259) return "AppearanceType.HUMAN_NPC_FEMALE_05";
    if (value == 260) return "AppearanceType.HUMAN_NPC_FEMALE_06";
    if (value == 261) return "AppearanceType.HUMAN_NPC_FEMALE_07";
    if (value == 262) return "AppearanceType.HUMAN_NPC_FEMALE_08";
    if (value == 263) return "AppearanceType.HUMAN_NPC_FEMALE_09";
    if (value == 264) return "AppearanceType.HUMAN_NPC_FEMALE_10";
    if (value == 265) return "AppearanceType.HUMAN_NPC_FEMALE_11";
    if (value == 266) return "AppearanceType.HUMAN_NPC_FEMALE_12";
    if (value == 267) return "AppearanceType.HUMAN_NPC_MALE_01";
    if (value == 268) return "AppearanceType.HUMAN_NPC_MALE_02";
    if (value == 269) return "AppearanceType.HUMAN_NPC_MALE_03";
    if (value == 270) return "AppearanceType.HUMAN_NPC_MALE_04";
    if (value == 271) return "AppearanceType.HUMAN_NPC_MALE_05";
    if (value == 272) return "AppearanceType.HUMAN_NPC_MALE_06";
    if (value == 273) return "AppearanceType.HUMAN_NPC_MALE_07";
    if (value == 274) return "AppearanceType.HUMAN_NPC_MALE_08";
    if (value == 275) return "AppearanceType.HUMAN_NPC_MALE_09";
    if (value == 276) return "AppearanceType.HUMAN_NPC_MALE_10";
    if (value == 277) return "AppearanceType.HUMAN_NPC_MALE_11";
    if (value == 278) return "AppearanceType.HUMAN_NPC_MALE_12";
    if (value == 279) return "AppearanceType.HUMAN_NPC_MALE_13";
    if (value == 280) return "AppearanceType.HUMAN_NPC_MALE_14";
    if (value == 281) return "AppearanceType.HUMAN_NPC_MALE_15";
    if (value == 282) return "AppearanceType.HUMAN_NPC_MALE_16";
    if (value == 283) return "AppearanceType.HUMAN_NPC_MALE_17";
    if (value == 284) return "AppearanceType.HUMAN_NPC_MALE_18";
    if (value == 105) return "AppearanceType.IMP";
    if (value == 233) return "AppearanceType.INN_KEEPER";
    if (value == 117) return "AppearanceType.INTELLECT_DEVOURER";
    if (value == -1) return "AppearanceType.INVALID";
    if (value == 298) return "AppearanceType.INVISIBLE_HUMAN_MALE";
    if (value == 64) return "AppearanceType.INVISIBLE_STALKER";
    if (value == 242) return "AppearanceType.KID_FEMALE";
    if (value == 241) return "AppearanceType.KID_MALE";
    if (value == 302) return "AppearanceType.KOBOLD_A";
    if (value == 305) return "AppearanceType.KOBOLD_B";
    if (value == 300) return "AppearanceType.KOBOLD_CHIEF_A";
    if (value == 303) return "AppearanceType.KOBOLD_CHIEF_B";
    if (value == 301) return "AppearanceType.KOBOLD_SHAMAN_A";
    if (value == 304) return "AppearanceType.KOBOLD_SHAMAN_B";
    if (value == 103) return "AppearanceType.LANTERN_ARCHON";
    if (value == 39) return "AppearanceType.LICH";
    if (value == 134) return "AppearanceType.LIZARDFOLK_A";
    if (value == 135) return "AppearanceType.LIZARDFOLK_B";
    if (value == 132) return "AppearanceType.LIZARDFOLK_SHAMAN_A";
    if (value == 133) return "AppearanceType.LIZARDFOLK_SHAMAN_B";
    if (value == 130) return "AppearanceType.LIZARDFOLK_WARRIOR_A";
    if (value == 131) return "AppearanceType.LIZARDFOLK_WARRIOR_B";
    if (value == 211) return "AppearanceType.LUSKAN_GUARD";
    if (value == 226) return "AppearanceType.MALE_01";
    if (value == 227) return "AppearanceType.MALE_02";
    if (value == 228) return "AppearanceType.MALE_03";
    if (value == 229) return "AppearanceType.MALE_04";
    if (value == 230) return "AppearanceType.MALE_05";
    if (value == 366) return "AppearanceType.MANTICORE";
    if (value == 352) return "AppearanceType.MEDUSA";
    if (value == 404) return "AppearanceType.MEPHISTO_BIG";
    if (value == 471) return "AppearanceType.MEPHISTO_NORM";
    if (value == 106) return "AppearanceType.MEPHIT_AIR";
    if (value == 107) return "AppearanceType.MEPHIT_DUST";
    if (value == 108) return "AppearanceType.MEPHIT_EARTH";
    if (value == 109) return "AppearanceType.MEPHIT_FIRE";
    if (value == 110) return "AppearanceType.MEPHIT_ICE";
    if (value == 114) return "AppearanceType.MEPHIT_MAGMA";
    if (value == 112) return "AppearanceType.MEPHIT_OOZE";
    if (value == 111) return "AppearanceType.MEPHIT_SALT";
    if (value == 113) return "AppearanceType.MEPHIT_STEAM";
    if (value == 115) return "AppearanceType.MEPHIT_WATER";
    if (value == 413) return "AppearanceType.MINDFLAYER";
    if (value == 414) return "AppearanceType.MINDFLAYER_2";
    if (value == 415) return "AppearanceType.MINDFLAYER_ALHOON";
    if (value == 119) return "AppearanceType.MINOGON";
    if (value == 120) return "AppearanceType.MINOTAUR";
    if (value == 121) return "AppearanceType.MINOTAUR_CHIEFTAIN";
    if (value == 122) return "AppearanceType.MINOTAUR_SHAMAN";
    if (value == 123) return "AppearanceType.MOHRG";
    if (value == 58) return "AppearanceType.MUMMY_COMMON";
    if (value == 59) return "AppearanceType.MUMMY_FIGHTER_2";
    if (value == 124) return "AppearanceType.MUMMY_GREATER";
    if (value == 125) return "AppearanceType.MUMMY_WARRIOR";
    if (value == 188) return "AppearanceType.NWN_AARIN";
    if (value == 189) return "AppearanceType.NWN_ARIBETH_EVIL";
    if (value == 191) return "AppearanceType.NWN_HAEDRALINE";
    if (value == 193) return "AppearanceType.NWN_MAUGRIM";
    if (value == 192) return "AppearanceType.NWN_MORAG";
    if (value == 296) return "AppearanceType.NWN_NASHER";
    if (value == 297) return "AppearanceType.NWN_SEDOS";
    if (value == 210) return "AppearanceType.NW_MILITIA_MEMBER";
    if (value == 126) return "AppearanceType.NYMPH";
    if (value == 436) return "AppearanceType.OBJECT_BLUE";
    if (value == 473) return "AppearanceType.OBJECT_BOAT";
    if (value == 433) return "AppearanceType.OBJECT_CANDLE";
    if (value == 431) return "AppearanceType.OBJECT_CHAIR";
    if (value == 434) return "AppearanceType.OBJECT_CHEST";
    if (value == 437) return "AppearanceType.OBJECT_CYAN";
    if (value == 445) return "AppearanceType.OBJECT_FLAME_LARGE";
    if (value == 444) return "AppearanceType.OBJECT_FLAME_MEDIUM";
    if (value == 443) return "AppearanceType.OBJECT_FLAME_SMALL";
    if (value == 438) return "AppearanceType.OBJECT_GREEN";
    if (value == 440) return "AppearanceType.OBJECT_ORANGE";
    if (value == 442) return "AppearanceType.OBJECT_PURPLE";
    if (value == 441) return "AppearanceType.OBJECT_RED";
    if (value == 432) return "AppearanceType.OBJECT_TABLE";
    if (value == 435) return "AppearanceType.OBJECT_WHITE";
    if (value == 439) return "AppearanceType.OBJECT_YELLOW";
    if (value == 394) return "AppearanceType.OCHRE_JELLY_LARGE";
    if (value == 396) return "AppearanceType.OCHRE_JELLY_MEDIUM";
    if (value == 398) return "AppearanceType.OCHRE_JELLY_SMALL";
    if (value == 127) return "AppearanceType.OGRE";
    if (value == 207) return "AppearanceType.OGREB";
    if (value == 128) return "AppearanceType.OGRE_CHIEFTAIN";
    if (value == 208) return "AppearanceType.OGRE_CHIEFTAINB";
    if (value == 129) return "AppearanceType.OGRE_MAGE";
    if (value == 209) return "AppearanceType.OGRE_MAGEB";
    if (value == 239) return "AppearanceType.OLD_MAN";
    if (value == 240) return "AppearanceType.OLD_WOMAN";
    if (value == 140) return "AppearanceType.ORC_A";
    if (value == 141) return "AppearanceType.ORC_B";
    if (value == 136) return "AppearanceType.ORC_CHIEFTAIN_A";
    if (value == 137) return "AppearanceType.ORC_CHIEFTAIN_B";
    if (value == 138) return "AppearanceType.ORC_SHAMAN_A";
    if (value == 139) return "AppearanceType.ORC_SHAMAN_B";
    if (value == 142) return "AppearanceType.OX";
    if (value == 7) return "AppearanceType.PARROT";
    if (value == 206) return "AppearanceType.PENGUIN";
    if (value == 231) return "AppearanceType.PLAGUE_VICTIM";
    if (value == 236) return "AppearanceType.PROSTITUTE_01";
    if (value == 237) return "AppearanceType.PROSTITUTE_02";
    if (value == 375) return "AppearanceType.PSEUDODRAGON";
    if (value == 104) return "AppearanceType.QUASIT";
    if (value == 294) return "AppearanceType.RAKSHASA_BEAR_MALE";
    if (value == 290) return "AppearanceType.RAKSHASA_TIGER_FEMALE";
    if (value == 293) return "AppearanceType.RAKSHASA_TIGER_MALE";
    if (value == 295) return "AppearanceType.RAKSHASA_WOLF_MALE";
    if (value == 386) return "AppearanceType.RAT";
    if (value == 387) return "AppearanceType.RAT_DIRE";
    if (value == 145) return "AppearanceType.RAVEN";
    if (value == 65) return "AppearanceType.SAHUAGIN";
    if (value == 67) return "AppearanceType.SAHUAGIN_CLERIC";
    if (value == 66) return "AppearanceType.SAHUAGIN_LEADER";
    if (value == 291) return "AppearanceType.SEAGULL_FLYING";
    if (value == 292) return "AppearanceType.SEAGULL_WALKING";
    if (value == 454) return "AppearanceType.SEA_HAG";
    if (value == 146) return "AppearanceType.SHADOW";
    if (value == 147) return "AppearanceType.SHADOW_FIEND";
    if (value == 449) return "AppearanceType.SHARK_GOBLIN";
    if (value == 448) return "AppearanceType.SHARK_HAMMERHEAD";
    if (value == 447) return "AppearanceType.SHARK_MAKO";
    if (value == 90) return "AppearanceType.SHIELD_GUARDIAN";
    if (value == 232) return "AppearanceType.SHOP_KEEPER";
    if (value == 36) return "AppearanceType.SKELETAL_DEVOURER";
    if (value == 182) return "AppearanceType.SKELETON_CHIEFTAIN";
    if (value == 63) return "AppearanceType.SKELETON_COMMON";
    if (value == 148) return "AppearanceType.SKELETON_MAGE";
    if (value == 62) return "AppearanceType.SKELETON_PRIEST";
    if (value == 150) return "AppearanceType.SKELETON_WARRIOR";
    if (value == 70) return "AppearanceType.SKELETON_WARRIOR_1";
    if (value == 71) return "AppearanceType.SKELETON_WARRIOR_2";
    if (value == 426) return "AppearanceType.SLAAD_BLACK";
    if (value == 151) return "AppearanceType.SLAAD_BLUE";
    if (value == 152) return "AppearanceType.SLAAD_DEATH";
    if (value == 153) return "AppearanceType.SLAAD_GRAY";
    if (value == 154) return "AppearanceType.SLAAD_GREEN";
    if (value == 155) return "AppearanceType.SLAAD_RED";
    if (value == 427) return "AppearanceType.SLAAD_WHITE";
    if (value == 156) return "AppearanceType.SPECTRE";
    if (value == 364) return "AppearanceType.SPHINX";
    if (value == 422) return "AppearanceType.SPIDER_DEMON";
    if (value == 158) return "AppearanceType.SPIDER_DIRE";
    if (value == 159) return "AppearanceType.SPIDER_GIANT";
    if (value == 160) return "AppearanceType.SPIDER_PHASE";
    if (value == 161) return "AppearanceType.SPIDER_SWORD";
    if (value == 162) return "AppearanceType.SPIDER_WRAITH";
    if (value == 356) return "AppearanceType.STINGER";
    if (value == 358) return "AppearanceType.STINGER_CHIEFTAIN";
    if (value == 359) return "AppearanceType.STINGER_MAGE";
    if (value == 357) return "AppearanceType.STINGER_WARRIOR";
    if (value == 163) return "AppearanceType.SUCCUBUS";
    if (value == 424) return "AppearanceType.SVIRF_FEMALE";
    if (value == 423) return "AppearanceType.SVIRF_MALE";
    if (value == 451) return "AppearanceType.TROGLODYTE";
    if (value == 453) return "AppearanceType.TROGLODYTE_CLERIC";
    if (value == 452) return "AppearanceType.TROGLODYTE_WARRIOR";
    if (value == 167) return "AppearanceType.TROLL";
    if (value == 164) return "AppearanceType.TROLL_CHIEFTAIN";
    if (value == 165) return "AppearanceType.TROLL_SHAMAN";
    if (value == 168) return "AppearanceType.UMBERHULK";
    if (value == 213) return "AppearanceType.UTHGARD_ELK_TRIBE";
    if (value == 214) return "AppearanceType.UTHGARD_TIGER_TRIBE";
    if (value == 288) return "AppearanceType.VAMPIRE_FEMALE";
    if (value == 289) return "AppearanceType.VAMPIRE_MALE";
    if (value == 101) return "AppearanceType.VROCK";
    if (value == 235) return "AppearanceType.WAITRESS";
    if (value == 54) return "AppearanceType.WAR_DEVOURER";
    if (value == 99) return "AppearanceType.WERECAT";
    if (value == 170) return "AppearanceType.WERERAT";
    if (value == 171) return "AppearanceType.WEREWOLF";
    if (value == 172) return "AppearanceType.WIGHT";
    if (value == 116) return "AppearanceType.WILL_O_WISP";
    if (value == 187) return "AppearanceType.WRAITH";
    if (value == 378) return "AppearanceType.WYRMLING_BLACK";
    if (value == 377) return "AppearanceType.WYRMLING_BLUE";
    if (value == 381) return "AppearanceType.WYRMLING_BRASS";
    if (value == 383) return "AppearanceType.WYRMLING_BRONZE";
    if (value == 382) return "AppearanceType.WYRMLING_COPPER";
    if (value == 385) return "AppearanceType.WYRMLING_GOLD";
    if (value == 379) return "AppearanceType.WYRMLING_GREEN";
    if (value == 376) return "AppearanceType.WYRMLING_RED";
    if (value == 384) return "AppearanceType.WYRMLING_SILVER";
    if (value == 380) return "AppearanceType.WYRMLING_WHITE";
    if (value == 285) return "AppearanceType.YUAN_TI";
    if (value == 286) return "AppearanceType.YUAN_TI_CHIEFTEN";
    if (value == 287) return "AppearanceType.YUAN_TI_WIZARD";
    if (value == 198) return "AppearanceType.ZOMBIE";
    if (value == 195) return "AppearanceType.ZOMBIE_ROTTING";
    if (value == 199) return "AppearanceType.ZOMBIE_TYRANT_FOG";
    if (value == 196) return "AppearanceType.ZOMBIE_WARRIOR_1";
    if (value == 197) return "AppearanceType.ZOMBIE_WARRIOR_2";
    return "AppearanceType.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "AppearanceType.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "AppearanceType.(not found: " + value + ")";
  }
}
