package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "APPEARANCE".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class Appearance {
  private Appearance() {}

  public final static int TYPE_ALLIP = 186;
  public final static int TYPE_ANIMATED_CHEST = 469;
  public final static int TYPE_ARANEA = 157;
  public final static int TYPE_ARCH_TARGET = 200;
  public final static int TYPE_ARIBETH = 190;
  public final static int TYPE_ASABI_CHIEFTAIN = 353;
  public final static int TYPE_ASABI_SHAMAN = 354;
  public final static int TYPE_ASABI_WARRIOR = 355;
  public final static int TYPE_AZER_FEMALE = 429;
  public final static int TYPE_AZER_MALE = 428;
  public final static int TYPE_BADGER = 8;
  public final static int TYPE_BADGER_DIRE = 9;
  public final static int TYPE_BALOR = 38;
  public final static int TYPE_BARTENDER = 234;
  public final static int TYPE_BASILISK = 369;
  public final static int TYPE_BAT = 10;
  public final static int TYPE_BAT_HORROR = 11;
  public final static int TYPE_BEAR_BLACK = 12;
  public final static int TYPE_BEAR_BROWN = 13;
  public final static int TYPE_BEAR_DIRE = 15;
  public final static int TYPE_BEAR_KODIAK = 204;
  public final static int TYPE_BEAR_POLAR = 14;
  public final static int TYPE_BEETLE_FIRE = 18;
  public final static int TYPE_BEETLE_SLICER = 17;
  public final static int TYPE_BEETLE_STAG = 19;
  public final static int TYPE_BEETLE_STINK = 20;
  public final static int TYPE_BEGGER = 220;
  public final static int TYPE_BEHOLDER = 401;
  public final static int TYPE_BEHOLDER_EYEBALL = 403;
  public final static int TYPE_BEHOLDER_MAGE = 402;
  public final static int TYPE_BEHOLDER_MOTHER = 472;
  public final static int TYPE_BLOOD_SAILER = 221;
  public final static int TYPE_BOAR = 21;
  public final static int TYPE_BOAR_DIRE = 22;
  public final static int TYPE_BODAK = 23;
  public final static int TYPE_BUGBEAR_A = 29;
  public final static int TYPE_BUGBEAR_B = 30;
  public final static int TYPE_BUGBEAR_CHIEFTAIN_A = 25;
  public final static int TYPE_BUGBEAR_CHIEFTAIN_B = 26;
  public final static int TYPE_BUGBEAR_SHAMAN_A = 27;
  public final static int TYPE_BUGBEAR_SHAMAN_B = 28;
  public final static int TYPE_BULETTE = 481;
  public final static int TYPE_CAT_CAT_DIRE = 95;
  public final static int TYPE_CAT_COUGAR = 203;
  public final static int TYPE_CAT_CRAG_CAT = 94;
  public final static int TYPE_CAT_JAGUAR = 98;
  public final static int TYPE_CAT_KRENSHAR = 96;
  public final static int TYPE_CAT_LEOPARD = 93;
  public final static int TYPE_CAT_LION = 97;
  public final static int TYPE_CAT_MPANTHER = 306;
  public final static int TYPE_CAT_PANTHER = 202;
  public final static int TYPE_CHICKEN = 31;
  public final static int TYPE_COCKATRICE = 368;
  public final static int TYPE_COMBAT_DUMMY = 201;
  public final static int TYPE_CONVICT = 238;
  public final static int TYPE_COW = 34;
  public final static int TYPE_CULT_MEMBER = 212;
  public final static int TYPE_DEEP_ROTHE = 416;
  public final static int TYPE_DEER = 35;
  public final static int TYPE_DEER_STAG = 37;
  public final static int TYPE_DEMI_LICH = 430;
  public final static int TYPE_DEVIL = 392;
  public final static int TYPE_DOG = 176;
  public final static int TYPE_DOG_BLINKDOG = 174;
  public final static int TYPE_DOG_DIRE_WOLF = 175;
  public final static int TYPE_DOG_FENHOUND = 177;
  public final static int TYPE_DOG_HELL_HOUND = 179;
  public final static int TYPE_DOG_SHADOW_MASTIF = 180;
  public final static int TYPE_DOG_WINTER_WOLF = 184;
  public final static int TYPE_DOG_WOLF = 181;
  public final static int TYPE_DOG_WORG = 185;
  public final static int TYPE_DOOM_KNIGHT = 40;
  public final static int TYPE_DRACOLICH = 405;
  public final static int TYPE_DRAGON_BLACK = 41;
  public final static int TYPE_DRAGON_BLUE = 47;
  public final static int TYPE_DRAGON_BRASS = 42;
  public final static int TYPE_DRAGON_BRONZE = 45;
  public final static int TYPE_DRAGON_COPPER = 43;
  public final static int TYPE_DRAGON_GOLD = 46;
  public final static int TYPE_DRAGON_GREEN = 48;
  public final static int TYPE_DRAGON_PRIS = 425;
  public final static int TYPE_DRAGON_RED = 49;
  public final static int TYPE_DRAGON_SHADOW = 418;
  public final static int TYPE_DRAGON_SILVER = 44;
  public final static int TYPE_DRAGON_WHITE = 50;
  public final static int TYPE_DRIDER = 406;
  public final static int TYPE_DRIDER_CHIEF = 407;
  public final static int TYPE_DRIDER_FEMALE = 446;
  public final static int TYPE_DROW_CLERIC = 215;
  public final static int TYPE_DROW_FEMALE_1 = 478;
  public final static int TYPE_DROW_FEMALE_2 = 479;
  public final static int TYPE_DROW_FIGHTER = 216;
  public final static int TYPE_DROW_MATRON = 410;
  public final static int TYPE_DROW_SLAVE = 408;
  public final static int TYPE_DROW_WARRIOR_1 = 476;
  public final static int TYPE_DROW_WARRIOR_2 = 477;
  public final static int TYPE_DROW_WARRIOR_3 = 480;
  public final static int TYPE_DROW_WIZARD = 409;
  public final static int TYPE_DRUEGAR_CLERIC = 218;
  public final static int TYPE_DRUEGAR_FIGHTER = 217;
  public final static int TYPE_DRYAD = 51;
  public final static int TYPE_DUERGAR_CHIEF = 412;
  public final static int TYPE_DUERGAR_SLAVE = 411;
  public final static int TYPE_DWARF = 0;
  public final static int TYPE_DWARF_GOLEM = 474;
  public final static int TYPE_DWARF_HALFORC = 475;
  public final static int TYPE_DWARF_NPC_FEMALE = 248;
  public final static int TYPE_DWARF_NPC_MALE = 249;
  public final static int TYPE_ELEMENTAL_AIR = 52;
  public final static int TYPE_ELEMENTAL_AIR_ELDER = 53;
  public final static int TYPE_ELEMENTAL_EARTH = 56;
  public final static int TYPE_ELEMENTAL_EARTH_ELDER = 57;
  public final static int TYPE_ELEMENTAL_FIRE = 60;
  public final static int TYPE_ELEMENTAL_FIRE_ELDER = 61;
  public final static int TYPE_ELEMENTAL_WATER = 69;
  public final static int TYPE_ELEMENTAL_WATER_ELDER = 68;
  public final static int TYPE_ELF = 1;
  public final static int TYPE_ELF_NPC_FEMALE = 245;
  public final static int TYPE_ELF_NPC_MALE_01 = 246;
  public final static int TYPE_ELF_NPC_MALE_02 = 247;
  public final static int TYPE_ETTERCAP = 166;
  public final static int TYPE_ETTIN = 72;
  public final static int TYPE_FAERIE_DRAGON = 374;
  public final static int TYPE_FAIRY = 55;
  public final static int TYPE_FALCON = 144;
  public final static int TYPE_FEMALE_01 = 222;
  public final static int TYPE_FEMALE_02 = 223;
  public final static int TYPE_FEMALE_03 = 224;
  public final static int TYPE_FEMALE_04 = 225;
  public final static int TYPE_FORMIAN_MYRMARCH = 362;
  public final static int TYPE_FORMIAN_QUEEN = 363;
  public final static int TYPE_FORMIAN_WARRIOR = 361;
  public final static int TYPE_FORMIAN_WORKER = 360;
  public final static int TYPE_GARGOYLE = 73;
  public final static int TYPE_GELATINOUS_CUBE = 470;
  public final static int TYPE_GHAST = 74;
  public final static int TYPE_GHOUL = 76;
  public final static int TYPE_GHOUL_LORD = 77;
  public final static int TYPE_GIANT_FIRE = 80;
  public final static int TYPE_GIANT_FIRE_FEMALE = 351;
  public final static int TYPE_GIANT_FROST = 81;
  public final static int TYPE_GIANT_FROST_FEMALE = 350;
  public final static int TYPE_GIANT_HILL = 78;
  public final static int TYPE_GIANT_MOUNTAIN = 79;
  public final static int TYPE_GNOLL_WARRIOR = 388;
  public final static int TYPE_GNOLL_WIZ = 389;
  public final static int TYPE_GNOME = 2;
  public final static int TYPE_GNOME_NPC_FEMALE = 243;
  public final static int TYPE_GNOME_NPC_MALE = 244;
  public final static int TYPE_GOBLIN_A = 86;
  public final static int TYPE_GOBLIN_B = 87;
  public final static int TYPE_GOBLIN_CHIEF_A = 82;
  public final static int TYPE_GOBLIN_CHIEF_B = 83;
  public final static int TYPE_GOBLIN_SHAMAN_A = 84;
  public final static int TYPE_GOBLIN_SHAMAN_B = 85;
  public final static int TYPE_GOLEM_ADAMANTIUM = 421;
  public final static int TYPE_GOLEM_BONE = 24;
  public final static int TYPE_GOLEM_CLAY = 91;
  public final static int TYPE_GOLEM_DEMONFLESH = 468;
  public final static int TYPE_GOLEM_FLESH = 88;
  public final static int TYPE_GOLEM_IRON = 89;
  public final static int TYPE_GOLEM_MITHRAL = 420;
  public final static int TYPE_GOLEM_STONE = 92;
  public final static int TYPE_GORGON = 367;
  public final static int TYPE_GRAY_OOZE = 393;
  public final static int TYPE_GREY_RENDER = 205;
  public final static int TYPE_GYNOSPHINX = 365;
  public final static int TYPE_HALFLING = 3;
  public final static int TYPE_HALFLING_NPC_FEMALE = 250;
  public final static int TYPE_HALFLING_NPC_MALE = 251;
  public final static int TYPE_HALF_ELF = 4;
  public final static int TYPE_HALF_ORC = 5;
  public final static int TYPE_HALF_ORC_NPC_FEMALE = 252;
  public final static int TYPE_HALF_ORC_NPC_MALE_01 = 253;
  public final static int TYPE_HALF_ORC_NPC_MALE_02 = 254;
  public final static int TYPE_HARPY = 419;
  public final static int TYPE_HELMED_HORROR = 100;
  public final static int TYPE_HEURODIS_LICH = 370;
  public final static int TYPE_HOBGOBLIN_WARRIOR = 390;
  public final static int TYPE_HOBGOBLIN_WIZARD = 391;
  public final static int TYPE_HOOK_HORROR = 102;
  public final static int TYPE_HOUSE_GUARD = 219;
  public final static int TYPE_HUMAN = 6;
  public final static int TYPE_HUMAN_NPC_FEMALE_01 = 255;
  public final static int TYPE_HUMAN_NPC_FEMALE_02 = 256;
  public final static int TYPE_HUMAN_NPC_FEMALE_03 = 257;
  public final static int TYPE_HUMAN_NPC_FEMALE_04 = 258;
  public final static int TYPE_HUMAN_NPC_FEMALE_05 = 259;
  public final static int TYPE_HUMAN_NPC_FEMALE_06 = 260;
  public final static int TYPE_HUMAN_NPC_FEMALE_07 = 261;
  public final static int TYPE_HUMAN_NPC_FEMALE_08 = 262;
  public final static int TYPE_HUMAN_NPC_FEMALE_09 = 263;
  public final static int TYPE_HUMAN_NPC_FEMALE_10 = 264;
  public final static int TYPE_HUMAN_NPC_FEMALE_11 = 265;
  public final static int TYPE_HUMAN_NPC_FEMALE_12 = 266;
  public final static int TYPE_HUMAN_NPC_MALE_01 = 267;
  public final static int TYPE_HUMAN_NPC_MALE_02 = 268;
  public final static int TYPE_HUMAN_NPC_MALE_03 = 269;
  public final static int TYPE_HUMAN_NPC_MALE_04 = 270;
  public final static int TYPE_HUMAN_NPC_MALE_05 = 271;
  public final static int TYPE_HUMAN_NPC_MALE_06 = 272;
  public final static int TYPE_HUMAN_NPC_MALE_07 = 273;
  public final static int TYPE_HUMAN_NPC_MALE_08 = 274;
  public final static int TYPE_HUMAN_NPC_MALE_09 = 275;
  public final static int TYPE_HUMAN_NPC_MALE_10 = 276;
  public final static int TYPE_HUMAN_NPC_MALE_11 = 277;
  public final static int TYPE_HUMAN_NPC_MALE_12 = 278;
  public final static int TYPE_HUMAN_NPC_MALE_13 = 279;
  public final static int TYPE_HUMAN_NPC_MALE_14 = 280;
  public final static int TYPE_HUMAN_NPC_MALE_15 = 281;
  public final static int TYPE_HUMAN_NPC_MALE_16 = 282;
  public final static int TYPE_HUMAN_NPC_MALE_17 = 283;
  public final static int TYPE_HUMAN_NPC_MALE_18 = 284;
  public final static int TYPE_IMP = 105;
  public final static int TYPE_INN_KEEPER = 233;
  public final static int TYPE_INTELLECT_DEVOURER = 117;
  public final static int TYPE_INVALID = -1;
  public final static int TYPE_INVISIBLE_HUMAN_MALE = 298;
  public final static int TYPE_INVISIBLE_STALKER = 64;
  public final static int TYPE_KID_FEMALE = 242;
  public final static int TYPE_KID_MALE = 241;
  public final static int TYPE_KOBOLD_A = 302;
  public final static int TYPE_KOBOLD_B = 305;
  public final static int TYPE_KOBOLD_CHIEF_A = 300;
  public final static int TYPE_KOBOLD_CHIEF_B = 303;
  public final static int TYPE_KOBOLD_SHAMAN_A = 301;
  public final static int TYPE_KOBOLD_SHAMAN_B = 304;
  public final static int TYPE_LANTERN_ARCHON = 103;
  public final static int TYPE_LICH = 39;
  public final static int TYPE_LIZARDFOLK_A = 134;
  public final static int TYPE_LIZARDFOLK_B = 135;
  public final static int TYPE_LIZARDFOLK_SHAMAN_A = 132;
  public final static int TYPE_LIZARDFOLK_SHAMAN_B = 133;
  public final static int TYPE_LIZARDFOLK_WARRIOR_A = 130;
  public final static int TYPE_LIZARDFOLK_WARRIOR_B = 131;
  public final static int TYPE_LUSKAN_GUARD = 211;
  public final static int TYPE_MALE_01 = 226;
  public final static int TYPE_MALE_02 = 227;
  public final static int TYPE_MALE_03 = 228;
  public final static int TYPE_MALE_04 = 229;
  public final static int TYPE_MALE_05 = 230;
  public final static int TYPE_MANTICORE = 366;
  public final static int TYPE_MEDUSA = 352;
  public final static int TYPE_MEPHISTO_BIG = 404;
  public final static int TYPE_MEPHISTO_NORM = 471;
  public final static int TYPE_MEPHIT_AIR = 106;
  public final static int TYPE_MEPHIT_DUST = 107;
  public final static int TYPE_MEPHIT_EARTH = 108;
  public final static int TYPE_MEPHIT_FIRE = 109;
  public final static int TYPE_MEPHIT_ICE = 110;
  public final static int TYPE_MEPHIT_MAGMA = 114;
  public final static int TYPE_MEPHIT_OOZE = 112;
  public final static int TYPE_MEPHIT_SALT = 111;
  public final static int TYPE_MEPHIT_STEAM = 113;
  public final static int TYPE_MEPHIT_WATER = 115;
  public final static int TYPE_MINDFLAYER = 413;
  public final static int TYPE_MINDFLAYER_2 = 414;
  public final static int TYPE_MINDFLAYER_ALHOON = 415;
  public final static int TYPE_MINOGON = 119;
  public final static int TYPE_MINOTAUR = 120;
  public final static int TYPE_MINOTAUR_CHIEFTAIN = 121;
  public final static int TYPE_MINOTAUR_SHAMAN = 122;
  public final static int TYPE_MOHRG = 123;
  public final static int TYPE_MUMMY_COMMON = 58;
  public final static int TYPE_MUMMY_FIGHTER_2 = 59;
  public final static int TYPE_MUMMY_GREATER = 124;
  public final static int TYPE_MUMMY_WARRIOR = 125;
  public final static int TYPE_NWN_AARIN = 188;
  public final static int TYPE_NWN_ARIBETH_EVIL = 189;
  public final static int TYPE_NWN_HAEDRALINE = 191;
  public final static int TYPE_NWN_MAUGRIM = 193;
  public final static int TYPE_NWN_MORAG = 192;
  public final static int TYPE_NWN_NASHER = 296;
  public final static int TYPE_NWN_SEDOS = 297;
  public final static int TYPE_NW_MILITIA_MEMBER = 210;
  public final static int TYPE_NYMPH = 126;
  public final static int TYPE_OBJECT_BLUE = 436;
  public final static int TYPE_OBJECT_BOAT = 473;
  public final static int TYPE_OBJECT_CANDLE = 433;
  public final static int TYPE_OBJECT_CHAIR = 431;
  public final static int TYPE_OBJECT_CHEST = 434;
  public final static int TYPE_OBJECT_CYAN = 437;
  public final static int TYPE_OBJECT_FLAME_LARGE = 445;
  public final static int TYPE_OBJECT_FLAME_MEDIUM = 444;
  public final static int TYPE_OBJECT_FLAME_SMALL = 443;
  public final static int TYPE_OBJECT_GREEN = 438;
  public final static int TYPE_OBJECT_ORANGE = 440;
  public final static int TYPE_OBJECT_PURPLE = 442;
  public final static int TYPE_OBJECT_RED = 441;
  public final static int TYPE_OBJECT_TABLE = 432;
  public final static int TYPE_OBJECT_WHITE = 435;
  public final static int TYPE_OBJECT_YELLOW = 439;
  public final static int TYPE_OCHRE_JELLY_LARGE = 394;
  public final static int TYPE_OCHRE_JELLY_MEDIUM = 396;
  public final static int TYPE_OCHRE_JELLY_SMALL = 398;
  public final static int TYPE_OGRE = 127;
  public final static int TYPE_OGREB = 207;
  public final static int TYPE_OGRE_CHIEFTAIN = 128;
  public final static int TYPE_OGRE_CHIEFTAINB = 208;
  public final static int TYPE_OGRE_MAGE = 129;
  public final static int TYPE_OGRE_MAGEB = 209;
  public final static int TYPE_OLD_MAN = 239;
  public final static int TYPE_OLD_WOMAN = 240;
  public final static int TYPE_ORC_A = 140;
  public final static int TYPE_ORC_B = 141;
  public final static int TYPE_ORC_CHIEFTAIN_A = 136;
  public final static int TYPE_ORC_CHIEFTAIN_B = 137;
  public final static int TYPE_ORC_SHAMAN_A = 138;
  public final static int TYPE_ORC_SHAMAN_B = 139;
  public final static int TYPE_OX = 142;
  public final static int TYPE_PARROT = 7;
  public final static int TYPE_PENGUIN = 206;
  public final static int TYPE_PLAGUE_VICTIM = 231;
  public final static int TYPE_PROSTITUTE_01 = 236;
  public final static int TYPE_PROSTITUTE_02 = 237;
  public final static int TYPE_PSEUDODRAGON = 375;
  public final static int TYPE_QUASIT = 104;
  public final static int TYPE_RAKSHASA_BEAR_MALE = 294;
  public final static int TYPE_RAKSHASA_TIGER_FEMALE = 290;
  public final static int TYPE_RAKSHASA_TIGER_MALE = 293;
  public final static int TYPE_RAKSHASA_WOLF_MALE = 295;
  public final static int TYPE_RAT = 386;
  public final static int TYPE_RAT_DIRE = 387;
  public final static int TYPE_RAVEN = 145;
  public final static int TYPE_SAHUAGIN = 65;
  public final static int TYPE_SAHUAGIN_CLERIC = 67;
  public final static int TYPE_SAHUAGIN_LEADER = 66;
  public final static int TYPE_SEAGULL_FLYING = 291;
  public final static int TYPE_SEAGULL_WALKING = 292;
  public final static int TYPE_SEA_HAG = 454;
  public final static int TYPE_SHADOW = 146;
  public final static int TYPE_SHADOW_FIEND = 147;
  public final static int TYPE_SHARK_GOBLIN = 449;
  public final static int TYPE_SHARK_HAMMERHEAD = 448;
  public final static int TYPE_SHARK_MAKO = 447;
  public final static int TYPE_SHIELD_GUARDIAN = 90;
  public final static int TYPE_SHOP_KEEPER = 232;
  public final static int TYPE_SKELETAL_DEVOURER = 36;
  public final static int TYPE_SKELETON_CHIEFTAIN = 182;
  public final static int TYPE_SKELETON_COMMON = 63;
  public final static int TYPE_SKELETON_MAGE = 148;
  public final static int TYPE_SKELETON_PRIEST = 62;
  public final static int TYPE_SKELETON_WARRIOR = 150;
  public final static int TYPE_SKELETON_WARRIOR_1 = 70;
  public final static int TYPE_SKELETON_WARRIOR_2 = 71;
  public final static int TYPE_SLAAD_BLACK = 426;
  public final static int TYPE_SLAAD_BLUE = 151;
  public final static int TYPE_SLAAD_DEATH = 152;
  public final static int TYPE_SLAAD_GRAY = 153;
  public final static int TYPE_SLAAD_GREEN = 154;
  public final static int TYPE_SLAAD_RED = 155;
  public final static int TYPE_SLAAD_WHITE = 427;
  public final static int TYPE_SPECTRE = 156;
  public final static int TYPE_SPHINX = 364;
  public final static int TYPE_SPIDER_DEMON = 422;
  public final static int TYPE_SPIDER_DIRE = 158;
  public final static int TYPE_SPIDER_GIANT = 159;
  public final static int TYPE_SPIDER_PHASE = 160;
  public final static int TYPE_SPIDER_SWORD = 161;
  public final static int TYPE_SPIDER_WRAITH = 162;
  public final static int TYPE_STINGER = 356;
  public final static int TYPE_STINGER_CHIEFTAIN = 358;
  public final static int TYPE_STINGER_MAGE = 359;
  public final static int TYPE_STINGER_WARRIOR = 357;
  public final static int TYPE_SUCCUBUS = 163;
  public final static int TYPE_SVIRF_FEMALE = 424;
  public final static int TYPE_SVIRF_MALE = 423;
  public final static int TYPE_TROGLODYTE = 451;
  public final static int TYPE_TROGLODYTE_CLERIC = 453;
  public final static int TYPE_TROGLODYTE_WARRIOR = 452;
  public final static int TYPE_TROLL = 167;
  public final static int TYPE_TROLL_CHIEFTAIN = 164;
  public final static int TYPE_TROLL_SHAMAN = 165;
  public final static int TYPE_UMBERHULK = 168;
  public final static int TYPE_UTHGARD_ELK_TRIBE = 213;
  public final static int TYPE_UTHGARD_TIGER_TRIBE = 214;
  public final static int TYPE_VAMPIRE_FEMALE = 288;
  public final static int TYPE_VAMPIRE_MALE = 289;
  public final static int TYPE_VROCK = 101;
  public final static int TYPE_WAITRESS = 235;
  public final static int TYPE_WAR_DEVOURER = 54;
  public final static int TYPE_WERECAT = 99;
  public final static int TYPE_WERERAT = 170;
  public final static int TYPE_WEREWOLF = 171;
  public final static int TYPE_WIGHT = 172;
  public final static int TYPE_WILL_O_WISP = 116;
  public final static int TYPE_WRAITH = 187;
  public final static int TYPE_WYRMLING_BLACK = 378;
  public final static int TYPE_WYRMLING_BLUE = 377;
  public final static int TYPE_WYRMLING_BRASS = 381;
  public final static int TYPE_WYRMLING_BRONZE = 383;
  public final static int TYPE_WYRMLING_COPPER = 382;
  public final static int TYPE_WYRMLING_GOLD = 385;
  public final static int TYPE_WYRMLING_GREEN = 379;
  public final static int TYPE_WYRMLING_RED = 376;
  public final static int TYPE_WYRMLING_SILVER = 384;
  public final static int TYPE_WYRMLING_WHITE = 380;
  public final static int TYPE_YUAN_TI = 285;
  public final static int TYPE_YUAN_TI_CHIEFTEN = 286;
  public final static int TYPE_YUAN_TI_WIZARD = 287;
  public final static int TYPE_ZOMBIE = 198;
  public final static int TYPE_ZOMBIE_ROTTING = 195;
  public final static int TYPE_ZOMBIE_TYRANT_FOG = 199;
  public final static int TYPE_ZOMBIE_WARRIOR_1 = 196;
  public final static int TYPE_ZOMBIE_WARRIOR_2 = 197;

  public static String nameOf(int value) {
    if (value == 186) return "Appearance.TYPE_ALLIP";
    if (value == 469) return "Appearance.TYPE_ANIMATED_CHEST";
    if (value == 157) return "Appearance.TYPE_ARANEA";
    if (value == 200) return "Appearance.TYPE_ARCH_TARGET";
    if (value == 190) return "Appearance.TYPE_ARIBETH";
    if (value == 353) return "Appearance.TYPE_ASABI_CHIEFTAIN";
    if (value == 354) return "Appearance.TYPE_ASABI_SHAMAN";
    if (value == 355) return "Appearance.TYPE_ASABI_WARRIOR";
    if (value == 429) return "Appearance.TYPE_AZER_FEMALE";
    if (value == 428) return "Appearance.TYPE_AZER_MALE";
    if (value == 8) return "Appearance.TYPE_BADGER";
    if (value == 9) return "Appearance.TYPE_BADGER_DIRE";
    if (value == 38) return "Appearance.TYPE_BALOR";
    if (value == 234) return "Appearance.TYPE_BARTENDER";
    if (value == 369) return "Appearance.TYPE_BASILISK";
    if (value == 10) return "Appearance.TYPE_BAT";
    if (value == 11) return "Appearance.TYPE_BAT_HORROR";
    if (value == 12) return "Appearance.TYPE_BEAR_BLACK";
    if (value == 13) return "Appearance.TYPE_BEAR_BROWN";
    if (value == 15) return "Appearance.TYPE_BEAR_DIRE";
    if (value == 204) return "Appearance.TYPE_BEAR_KODIAK";
    if (value == 14) return "Appearance.TYPE_BEAR_POLAR";
    if (value == 18) return "Appearance.TYPE_BEETLE_FIRE";
    if (value == 17) return "Appearance.TYPE_BEETLE_SLICER";
    if (value == 19) return "Appearance.TYPE_BEETLE_STAG";
    if (value == 20) return "Appearance.TYPE_BEETLE_STINK";
    if (value == 220) return "Appearance.TYPE_BEGGER";
    if (value == 401) return "Appearance.TYPE_BEHOLDER";
    if (value == 403) return "Appearance.TYPE_BEHOLDER_EYEBALL";
    if (value == 402) return "Appearance.TYPE_BEHOLDER_MAGE";
    if (value == 472) return "Appearance.TYPE_BEHOLDER_MOTHER";
    if (value == 221) return "Appearance.TYPE_BLOOD_SAILER";
    if (value == 21) return "Appearance.TYPE_BOAR";
    if (value == 22) return "Appearance.TYPE_BOAR_DIRE";
    if (value == 23) return "Appearance.TYPE_BODAK";
    if (value == 29) return "Appearance.TYPE_BUGBEAR_A";
    if (value == 30) return "Appearance.TYPE_BUGBEAR_B";
    if (value == 25) return "Appearance.TYPE_BUGBEAR_CHIEFTAIN_A";
    if (value == 26) return "Appearance.TYPE_BUGBEAR_CHIEFTAIN_B";
    if (value == 27) return "Appearance.TYPE_BUGBEAR_SHAMAN_A";
    if (value == 28) return "Appearance.TYPE_BUGBEAR_SHAMAN_B";
    if (value == 481) return "Appearance.TYPE_BULETTE";
    if (value == 95) return "Appearance.TYPE_CAT_CAT_DIRE";
    if (value == 203) return "Appearance.TYPE_CAT_COUGAR";
    if (value == 94) return "Appearance.TYPE_CAT_CRAG_CAT";
    if (value == 98) return "Appearance.TYPE_CAT_JAGUAR";
    if (value == 96) return "Appearance.TYPE_CAT_KRENSHAR";
    if (value == 93) return "Appearance.TYPE_CAT_LEOPARD";
    if (value == 97) return "Appearance.TYPE_CAT_LION";
    if (value == 306) return "Appearance.TYPE_CAT_MPANTHER";
    if (value == 202) return "Appearance.TYPE_CAT_PANTHER";
    if (value == 31) return "Appearance.TYPE_CHICKEN";
    if (value == 368) return "Appearance.TYPE_COCKATRICE";
    if (value == 201) return "Appearance.TYPE_COMBAT_DUMMY";
    if (value == 238) return "Appearance.TYPE_CONVICT";
    if (value == 34) return "Appearance.TYPE_COW";
    if (value == 212) return "Appearance.TYPE_CULT_MEMBER";
    if (value == 416) return "Appearance.TYPE_DEEP_ROTHE";
    if (value == 35) return "Appearance.TYPE_DEER";
    if (value == 37) return "Appearance.TYPE_DEER_STAG";
    if (value == 430) return "Appearance.TYPE_DEMI_LICH";
    if (value == 392) return "Appearance.TYPE_DEVIL";
    if (value == 176) return "Appearance.TYPE_DOG";
    if (value == 174) return "Appearance.TYPE_DOG_BLINKDOG";
    if (value == 175) return "Appearance.TYPE_DOG_DIRE_WOLF";
    if (value == 177) return "Appearance.TYPE_DOG_FENHOUND";
    if (value == 179) return "Appearance.TYPE_DOG_HELL_HOUND";
    if (value == 180) return "Appearance.TYPE_DOG_SHADOW_MASTIF";
    if (value == 184) return "Appearance.TYPE_DOG_WINTER_WOLF";
    if (value == 181) return "Appearance.TYPE_DOG_WOLF";
    if (value == 185) return "Appearance.TYPE_DOG_WORG";
    if (value == 40) return "Appearance.TYPE_DOOM_KNIGHT";
    if (value == 405) return "Appearance.TYPE_DRACOLICH";
    if (value == 41) return "Appearance.TYPE_DRAGON_BLACK";
    if (value == 47) return "Appearance.TYPE_DRAGON_BLUE";
    if (value == 42) return "Appearance.TYPE_DRAGON_BRASS";
    if (value == 45) return "Appearance.TYPE_DRAGON_BRONZE";
    if (value == 43) return "Appearance.TYPE_DRAGON_COPPER";
    if (value == 46) return "Appearance.TYPE_DRAGON_GOLD";
    if (value == 48) return "Appearance.TYPE_DRAGON_GREEN";
    if (value == 425) return "Appearance.TYPE_DRAGON_PRIS";
    if (value == 49) return "Appearance.TYPE_DRAGON_RED";
    if (value == 418) return "Appearance.TYPE_DRAGON_SHADOW";
    if (value == 44) return "Appearance.TYPE_DRAGON_SILVER";
    if (value == 50) return "Appearance.TYPE_DRAGON_WHITE";
    if (value == 406) return "Appearance.TYPE_DRIDER";
    if (value == 407) return "Appearance.TYPE_DRIDER_CHIEF";
    if (value == 446) return "Appearance.TYPE_DRIDER_FEMALE";
    if (value == 215) return "Appearance.TYPE_DROW_CLERIC";
    if (value == 478) return "Appearance.TYPE_DROW_FEMALE_1";
    if (value == 479) return "Appearance.TYPE_DROW_FEMALE_2";
    if (value == 216) return "Appearance.TYPE_DROW_FIGHTER";
    if (value == 410) return "Appearance.TYPE_DROW_MATRON";
    if (value == 408) return "Appearance.TYPE_DROW_SLAVE";
    if (value == 476) return "Appearance.TYPE_DROW_WARRIOR_1";
    if (value == 477) return "Appearance.TYPE_DROW_WARRIOR_2";
    if (value == 480) return "Appearance.TYPE_DROW_WARRIOR_3";
    if (value == 409) return "Appearance.TYPE_DROW_WIZARD";
    if (value == 218) return "Appearance.TYPE_DRUEGAR_CLERIC";
    if (value == 217) return "Appearance.TYPE_DRUEGAR_FIGHTER";
    if (value == 51) return "Appearance.TYPE_DRYAD";
    if (value == 412) return "Appearance.TYPE_DUERGAR_CHIEF";
    if (value == 411) return "Appearance.TYPE_DUERGAR_SLAVE";
    if (value == 0) return "Appearance.TYPE_DWARF";
    if (value == 474) return "Appearance.TYPE_DWARF_GOLEM";
    if (value == 475) return "Appearance.TYPE_DWARF_HALFORC";
    if (value == 248) return "Appearance.TYPE_DWARF_NPC_FEMALE";
    if (value == 249) return "Appearance.TYPE_DWARF_NPC_MALE";
    if (value == 52) return "Appearance.TYPE_ELEMENTAL_AIR";
    if (value == 53) return "Appearance.TYPE_ELEMENTAL_AIR_ELDER";
    if (value == 56) return "Appearance.TYPE_ELEMENTAL_EARTH";
    if (value == 57) return "Appearance.TYPE_ELEMENTAL_EARTH_ELDER";
    if (value == 60) return "Appearance.TYPE_ELEMENTAL_FIRE";
    if (value == 61) return "Appearance.TYPE_ELEMENTAL_FIRE_ELDER";
    if (value == 69) return "Appearance.TYPE_ELEMENTAL_WATER";
    if (value == 68) return "Appearance.TYPE_ELEMENTAL_WATER_ELDER";
    if (value == 1) return "Appearance.TYPE_ELF";
    if (value == 245) return "Appearance.TYPE_ELF_NPC_FEMALE";
    if (value == 246) return "Appearance.TYPE_ELF_NPC_MALE_01";
    if (value == 247) return "Appearance.TYPE_ELF_NPC_MALE_02";
    if (value == 166) return "Appearance.TYPE_ETTERCAP";
    if (value == 72) return "Appearance.TYPE_ETTIN";
    if (value == 374) return "Appearance.TYPE_FAERIE_DRAGON";
    if (value == 55) return "Appearance.TYPE_FAIRY";
    if (value == 144) return "Appearance.TYPE_FALCON";
    if (value == 222) return "Appearance.TYPE_FEMALE_01";
    if (value == 223) return "Appearance.TYPE_FEMALE_02";
    if (value == 224) return "Appearance.TYPE_FEMALE_03";
    if (value == 225) return "Appearance.TYPE_FEMALE_04";
    if (value == 362) return "Appearance.TYPE_FORMIAN_MYRMARCH";
    if (value == 363) return "Appearance.TYPE_FORMIAN_QUEEN";
    if (value == 361) return "Appearance.TYPE_FORMIAN_WARRIOR";
    if (value == 360) return "Appearance.TYPE_FORMIAN_WORKER";
    if (value == 73) return "Appearance.TYPE_GARGOYLE";
    if (value == 470) return "Appearance.TYPE_GELATINOUS_CUBE";
    if (value == 74) return "Appearance.TYPE_GHAST";
    if (value == 76) return "Appearance.TYPE_GHOUL";
    if (value == 77) return "Appearance.TYPE_GHOUL_LORD";
    if (value == 80) return "Appearance.TYPE_GIANT_FIRE";
    if (value == 351) return "Appearance.TYPE_GIANT_FIRE_FEMALE";
    if (value == 81) return "Appearance.TYPE_GIANT_FROST";
    if (value == 350) return "Appearance.TYPE_GIANT_FROST_FEMALE";
    if (value == 78) return "Appearance.TYPE_GIANT_HILL";
    if (value == 79) return "Appearance.TYPE_GIANT_MOUNTAIN";
    if (value == 388) return "Appearance.TYPE_GNOLL_WARRIOR";
    if (value == 389) return "Appearance.TYPE_GNOLL_WIZ";
    if (value == 2) return "Appearance.TYPE_GNOME";
    if (value == 243) return "Appearance.TYPE_GNOME_NPC_FEMALE";
    if (value == 244) return "Appearance.TYPE_GNOME_NPC_MALE";
    if (value == 86) return "Appearance.TYPE_GOBLIN_A";
    if (value == 87) return "Appearance.TYPE_GOBLIN_B";
    if (value == 82) return "Appearance.TYPE_GOBLIN_CHIEF_A";
    if (value == 83) return "Appearance.TYPE_GOBLIN_CHIEF_B";
    if (value == 84) return "Appearance.TYPE_GOBLIN_SHAMAN_A";
    if (value == 85) return "Appearance.TYPE_GOBLIN_SHAMAN_B";
    if (value == 421) return "Appearance.TYPE_GOLEM_ADAMANTIUM";
    if (value == 24) return "Appearance.TYPE_GOLEM_BONE";
    if (value == 91) return "Appearance.TYPE_GOLEM_CLAY";
    if (value == 468) return "Appearance.TYPE_GOLEM_DEMONFLESH";
    if (value == 88) return "Appearance.TYPE_GOLEM_FLESH";
    if (value == 89) return "Appearance.TYPE_GOLEM_IRON";
    if (value == 420) return "Appearance.TYPE_GOLEM_MITHRAL";
    if (value == 92) return "Appearance.TYPE_GOLEM_STONE";
    if (value == 367) return "Appearance.TYPE_GORGON";
    if (value == 393) return "Appearance.TYPE_GRAY_OOZE";
    if (value == 205) return "Appearance.TYPE_GREY_RENDER";
    if (value == 365) return "Appearance.TYPE_GYNOSPHINX";
    if (value == 3) return "Appearance.TYPE_HALFLING";
    if (value == 250) return "Appearance.TYPE_HALFLING_NPC_FEMALE";
    if (value == 251) return "Appearance.TYPE_HALFLING_NPC_MALE";
    if (value == 4) return "Appearance.TYPE_HALF_ELF";
    if (value == 5) return "Appearance.TYPE_HALF_ORC";
    if (value == 252) return "Appearance.TYPE_HALF_ORC_NPC_FEMALE";
    if (value == 253) return "Appearance.TYPE_HALF_ORC_NPC_MALE_01";
    if (value == 254) return "Appearance.TYPE_HALF_ORC_NPC_MALE_02";
    if (value == 419) return "Appearance.TYPE_HARPY";
    if (value == 100) return "Appearance.TYPE_HELMED_HORROR";
    if (value == 370) return "Appearance.TYPE_HEURODIS_LICH";
    if (value == 390) return "Appearance.TYPE_HOBGOBLIN_WARRIOR";
    if (value == 391) return "Appearance.TYPE_HOBGOBLIN_WIZARD";
    if (value == 102) return "Appearance.TYPE_HOOK_HORROR";
    if (value == 219) return "Appearance.TYPE_HOUSE_GUARD";
    if (value == 6) return "Appearance.TYPE_HUMAN";
    if (value == 255) return "Appearance.TYPE_HUMAN_NPC_FEMALE_01";
    if (value == 256) return "Appearance.TYPE_HUMAN_NPC_FEMALE_02";
    if (value == 257) return "Appearance.TYPE_HUMAN_NPC_FEMALE_03";
    if (value == 258) return "Appearance.TYPE_HUMAN_NPC_FEMALE_04";
    if (value == 259) return "Appearance.TYPE_HUMAN_NPC_FEMALE_05";
    if (value == 260) return "Appearance.TYPE_HUMAN_NPC_FEMALE_06";
    if (value == 261) return "Appearance.TYPE_HUMAN_NPC_FEMALE_07";
    if (value == 262) return "Appearance.TYPE_HUMAN_NPC_FEMALE_08";
    if (value == 263) return "Appearance.TYPE_HUMAN_NPC_FEMALE_09";
    if (value == 264) return "Appearance.TYPE_HUMAN_NPC_FEMALE_10";
    if (value == 265) return "Appearance.TYPE_HUMAN_NPC_FEMALE_11";
    if (value == 266) return "Appearance.TYPE_HUMAN_NPC_FEMALE_12";
    if (value == 267) return "Appearance.TYPE_HUMAN_NPC_MALE_01";
    if (value == 268) return "Appearance.TYPE_HUMAN_NPC_MALE_02";
    if (value == 269) return "Appearance.TYPE_HUMAN_NPC_MALE_03";
    if (value == 270) return "Appearance.TYPE_HUMAN_NPC_MALE_04";
    if (value == 271) return "Appearance.TYPE_HUMAN_NPC_MALE_05";
    if (value == 272) return "Appearance.TYPE_HUMAN_NPC_MALE_06";
    if (value == 273) return "Appearance.TYPE_HUMAN_NPC_MALE_07";
    if (value == 274) return "Appearance.TYPE_HUMAN_NPC_MALE_08";
    if (value == 275) return "Appearance.TYPE_HUMAN_NPC_MALE_09";
    if (value == 276) return "Appearance.TYPE_HUMAN_NPC_MALE_10";
    if (value == 277) return "Appearance.TYPE_HUMAN_NPC_MALE_11";
    if (value == 278) return "Appearance.TYPE_HUMAN_NPC_MALE_12";
    if (value == 279) return "Appearance.TYPE_HUMAN_NPC_MALE_13";
    if (value == 280) return "Appearance.TYPE_HUMAN_NPC_MALE_14";
    if (value == 281) return "Appearance.TYPE_HUMAN_NPC_MALE_15";
    if (value == 282) return "Appearance.TYPE_HUMAN_NPC_MALE_16";
    if (value == 283) return "Appearance.TYPE_HUMAN_NPC_MALE_17";
    if (value == 284) return "Appearance.TYPE_HUMAN_NPC_MALE_18";
    if (value == 105) return "Appearance.TYPE_IMP";
    if (value == 233) return "Appearance.TYPE_INN_KEEPER";
    if (value == 117) return "Appearance.TYPE_INTELLECT_DEVOURER";
    if (value == -1) return "Appearance.TYPE_INVALID";
    if (value == 298) return "Appearance.TYPE_INVISIBLE_HUMAN_MALE";
    if (value == 64) return "Appearance.TYPE_INVISIBLE_STALKER";
    if (value == 242) return "Appearance.TYPE_KID_FEMALE";
    if (value == 241) return "Appearance.TYPE_KID_MALE";
    if (value == 302) return "Appearance.TYPE_KOBOLD_A";
    if (value == 305) return "Appearance.TYPE_KOBOLD_B";
    if (value == 300) return "Appearance.TYPE_KOBOLD_CHIEF_A";
    if (value == 303) return "Appearance.TYPE_KOBOLD_CHIEF_B";
    if (value == 301) return "Appearance.TYPE_KOBOLD_SHAMAN_A";
    if (value == 304) return "Appearance.TYPE_KOBOLD_SHAMAN_B";
    if (value == 103) return "Appearance.TYPE_LANTERN_ARCHON";
    if (value == 39) return "Appearance.TYPE_LICH";
    if (value == 134) return "Appearance.TYPE_LIZARDFOLK_A";
    if (value == 135) return "Appearance.TYPE_LIZARDFOLK_B";
    if (value == 132) return "Appearance.TYPE_LIZARDFOLK_SHAMAN_A";
    if (value == 133) return "Appearance.TYPE_LIZARDFOLK_SHAMAN_B";
    if (value == 130) return "Appearance.TYPE_LIZARDFOLK_WARRIOR_A";
    if (value == 131) return "Appearance.TYPE_LIZARDFOLK_WARRIOR_B";
    if (value == 211) return "Appearance.TYPE_LUSKAN_GUARD";
    if (value == 226) return "Appearance.TYPE_MALE_01";
    if (value == 227) return "Appearance.TYPE_MALE_02";
    if (value == 228) return "Appearance.TYPE_MALE_03";
    if (value == 229) return "Appearance.TYPE_MALE_04";
    if (value == 230) return "Appearance.TYPE_MALE_05";
    if (value == 366) return "Appearance.TYPE_MANTICORE";
    if (value == 352) return "Appearance.TYPE_MEDUSA";
    if (value == 404) return "Appearance.TYPE_MEPHISTO_BIG";
    if (value == 471) return "Appearance.TYPE_MEPHISTO_NORM";
    if (value == 106) return "Appearance.TYPE_MEPHIT_AIR";
    if (value == 107) return "Appearance.TYPE_MEPHIT_DUST";
    if (value == 108) return "Appearance.TYPE_MEPHIT_EARTH";
    if (value == 109) return "Appearance.TYPE_MEPHIT_FIRE";
    if (value == 110) return "Appearance.TYPE_MEPHIT_ICE";
    if (value == 114) return "Appearance.TYPE_MEPHIT_MAGMA";
    if (value == 112) return "Appearance.TYPE_MEPHIT_OOZE";
    if (value == 111) return "Appearance.TYPE_MEPHIT_SALT";
    if (value == 113) return "Appearance.TYPE_MEPHIT_STEAM";
    if (value == 115) return "Appearance.TYPE_MEPHIT_WATER";
    if (value == 413) return "Appearance.TYPE_MINDFLAYER";
    if (value == 414) return "Appearance.TYPE_MINDFLAYER_2";
    if (value == 415) return "Appearance.TYPE_MINDFLAYER_ALHOON";
    if (value == 119) return "Appearance.TYPE_MINOGON";
    if (value == 120) return "Appearance.TYPE_MINOTAUR";
    if (value == 121) return "Appearance.TYPE_MINOTAUR_CHIEFTAIN";
    if (value == 122) return "Appearance.TYPE_MINOTAUR_SHAMAN";
    if (value == 123) return "Appearance.TYPE_MOHRG";
    if (value == 58) return "Appearance.TYPE_MUMMY_COMMON";
    if (value == 59) return "Appearance.TYPE_MUMMY_FIGHTER_2";
    if (value == 124) return "Appearance.TYPE_MUMMY_GREATER";
    if (value == 125) return "Appearance.TYPE_MUMMY_WARRIOR";
    if (value == 188) return "Appearance.TYPE_NWN_AARIN";
    if (value == 189) return "Appearance.TYPE_NWN_ARIBETH_EVIL";
    if (value == 191) return "Appearance.TYPE_NWN_HAEDRALINE";
    if (value == 193) return "Appearance.TYPE_NWN_MAUGRIM";
    if (value == 192) return "Appearance.TYPE_NWN_MORAG";
    if (value == 296) return "Appearance.TYPE_NWN_NASHER";
    if (value == 297) return "Appearance.TYPE_NWN_SEDOS";
    if (value == 210) return "Appearance.TYPE_NW_MILITIA_MEMBER";
    if (value == 126) return "Appearance.TYPE_NYMPH";
    if (value == 436) return "Appearance.TYPE_OBJECT_BLUE";
    if (value == 473) return "Appearance.TYPE_OBJECT_BOAT";
    if (value == 433) return "Appearance.TYPE_OBJECT_CANDLE";
    if (value == 431) return "Appearance.TYPE_OBJECT_CHAIR";
    if (value == 434) return "Appearance.TYPE_OBJECT_CHEST";
    if (value == 437) return "Appearance.TYPE_OBJECT_CYAN";
    if (value == 445) return "Appearance.TYPE_OBJECT_FLAME_LARGE";
    if (value == 444) return "Appearance.TYPE_OBJECT_FLAME_MEDIUM";
    if (value == 443) return "Appearance.TYPE_OBJECT_FLAME_SMALL";
    if (value == 438) return "Appearance.TYPE_OBJECT_GREEN";
    if (value == 440) return "Appearance.TYPE_OBJECT_ORANGE";
    if (value == 442) return "Appearance.TYPE_OBJECT_PURPLE";
    if (value == 441) return "Appearance.TYPE_OBJECT_RED";
    if (value == 432) return "Appearance.TYPE_OBJECT_TABLE";
    if (value == 435) return "Appearance.TYPE_OBJECT_WHITE";
    if (value == 439) return "Appearance.TYPE_OBJECT_YELLOW";
    if (value == 394) return "Appearance.TYPE_OCHRE_JELLY_LARGE";
    if (value == 396) return "Appearance.TYPE_OCHRE_JELLY_MEDIUM";
    if (value == 398) return "Appearance.TYPE_OCHRE_JELLY_SMALL";
    if (value == 127) return "Appearance.TYPE_OGRE";
    if (value == 207) return "Appearance.TYPE_OGREB";
    if (value == 128) return "Appearance.TYPE_OGRE_CHIEFTAIN";
    if (value == 208) return "Appearance.TYPE_OGRE_CHIEFTAINB";
    if (value == 129) return "Appearance.TYPE_OGRE_MAGE";
    if (value == 209) return "Appearance.TYPE_OGRE_MAGEB";
    if (value == 239) return "Appearance.TYPE_OLD_MAN";
    if (value == 240) return "Appearance.TYPE_OLD_WOMAN";
    if (value == 140) return "Appearance.TYPE_ORC_A";
    if (value == 141) return "Appearance.TYPE_ORC_B";
    if (value == 136) return "Appearance.TYPE_ORC_CHIEFTAIN_A";
    if (value == 137) return "Appearance.TYPE_ORC_CHIEFTAIN_B";
    if (value == 138) return "Appearance.TYPE_ORC_SHAMAN_A";
    if (value == 139) return "Appearance.TYPE_ORC_SHAMAN_B";
    if (value == 142) return "Appearance.TYPE_OX";
    if (value == 7) return "Appearance.TYPE_PARROT";
    if (value == 206) return "Appearance.TYPE_PENGUIN";
    if (value == 231) return "Appearance.TYPE_PLAGUE_VICTIM";
    if (value == 236) return "Appearance.TYPE_PROSTITUTE_01";
    if (value == 237) return "Appearance.TYPE_PROSTITUTE_02";
    if (value == 375) return "Appearance.TYPE_PSEUDODRAGON";
    if (value == 104) return "Appearance.TYPE_QUASIT";
    if (value == 294) return "Appearance.TYPE_RAKSHASA_BEAR_MALE";
    if (value == 290) return "Appearance.TYPE_RAKSHASA_TIGER_FEMALE";
    if (value == 293) return "Appearance.TYPE_RAKSHASA_TIGER_MALE";
    if (value == 295) return "Appearance.TYPE_RAKSHASA_WOLF_MALE";
    if (value == 386) return "Appearance.TYPE_RAT";
    if (value == 387) return "Appearance.TYPE_RAT_DIRE";
    if (value == 145) return "Appearance.TYPE_RAVEN";
    if (value == 65) return "Appearance.TYPE_SAHUAGIN";
    if (value == 67) return "Appearance.TYPE_SAHUAGIN_CLERIC";
    if (value == 66) return "Appearance.TYPE_SAHUAGIN_LEADER";
    if (value == 291) return "Appearance.TYPE_SEAGULL_FLYING";
    if (value == 292) return "Appearance.TYPE_SEAGULL_WALKING";
    if (value == 454) return "Appearance.TYPE_SEA_HAG";
    if (value == 146) return "Appearance.TYPE_SHADOW";
    if (value == 147) return "Appearance.TYPE_SHADOW_FIEND";
    if (value == 449) return "Appearance.TYPE_SHARK_GOBLIN";
    if (value == 448) return "Appearance.TYPE_SHARK_HAMMERHEAD";
    if (value == 447) return "Appearance.TYPE_SHARK_MAKO";
    if (value == 90) return "Appearance.TYPE_SHIELD_GUARDIAN";
    if (value == 232) return "Appearance.TYPE_SHOP_KEEPER";
    if (value == 36) return "Appearance.TYPE_SKELETAL_DEVOURER";
    if (value == 182) return "Appearance.TYPE_SKELETON_CHIEFTAIN";
    if (value == 63) return "Appearance.TYPE_SKELETON_COMMON";
    if (value == 148) return "Appearance.TYPE_SKELETON_MAGE";
    if (value == 62) return "Appearance.TYPE_SKELETON_PRIEST";
    if (value == 150) return "Appearance.TYPE_SKELETON_WARRIOR";
    if (value == 70) return "Appearance.TYPE_SKELETON_WARRIOR_1";
    if (value == 71) return "Appearance.TYPE_SKELETON_WARRIOR_2";
    if (value == 426) return "Appearance.TYPE_SLAAD_BLACK";
    if (value == 151) return "Appearance.TYPE_SLAAD_BLUE";
    if (value == 152) return "Appearance.TYPE_SLAAD_DEATH";
    if (value == 153) return "Appearance.TYPE_SLAAD_GRAY";
    if (value == 154) return "Appearance.TYPE_SLAAD_GREEN";
    if (value == 155) return "Appearance.TYPE_SLAAD_RED";
    if (value == 427) return "Appearance.TYPE_SLAAD_WHITE";
    if (value == 156) return "Appearance.TYPE_SPECTRE";
    if (value == 364) return "Appearance.TYPE_SPHINX";
    if (value == 422) return "Appearance.TYPE_SPIDER_DEMON";
    if (value == 158) return "Appearance.TYPE_SPIDER_DIRE";
    if (value == 159) return "Appearance.TYPE_SPIDER_GIANT";
    if (value == 160) return "Appearance.TYPE_SPIDER_PHASE";
    if (value == 161) return "Appearance.TYPE_SPIDER_SWORD";
    if (value == 162) return "Appearance.TYPE_SPIDER_WRAITH";
    if (value == 356) return "Appearance.TYPE_STINGER";
    if (value == 358) return "Appearance.TYPE_STINGER_CHIEFTAIN";
    if (value == 359) return "Appearance.TYPE_STINGER_MAGE";
    if (value == 357) return "Appearance.TYPE_STINGER_WARRIOR";
    if (value == 163) return "Appearance.TYPE_SUCCUBUS";
    if (value == 424) return "Appearance.TYPE_SVIRF_FEMALE";
    if (value == 423) return "Appearance.TYPE_SVIRF_MALE";
    if (value == 451) return "Appearance.TYPE_TROGLODYTE";
    if (value == 453) return "Appearance.TYPE_TROGLODYTE_CLERIC";
    if (value == 452) return "Appearance.TYPE_TROGLODYTE_WARRIOR";
    if (value == 167) return "Appearance.TYPE_TROLL";
    if (value == 164) return "Appearance.TYPE_TROLL_CHIEFTAIN";
    if (value == 165) return "Appearance.TYPE_TROLL_SHAMAN";
    if (value == 168) return "Appearance.TYPE_UMBERHULK";
    if (value == 213) return "Appearance.TYPE_UTHGARD_ELK_TRIBE";
    if (value == 214) return "Appearance.TYPE_UTHGARD_TIGER_TRIBE";
    if (value == 288) return "Appearance.TYPE_VAMPIRE_FEMALE";
    if (value == 289) return "Appearance.TYPE_VAMPIRE_MALE";
    if (value == 101) return "Appearance.TYPE_VROCK";
    if (value == 235) return "Appearance.TYPE_WAITRESS";
    if (value == 54) return "Appearance.TYPE_WAR_DEVOURER";
    if (value == 99) return "Appearance.TYPE_WERECAT";
    if (value == 170) return "Appearance.TYPE_WERERAT";
    if (value == 171) return "Appearance.TYPE_WEREWOLF";
    if (value == 172) return "Appearance.TYPE_WIGHT";
    if (value == 116) return "Appearance.TYPE_WILL_O_WISP";
    if (value == 187) return "Appearance.TYPE_WRAITH";
    if (value == 378) return "Appearance.TYPE_WYRMLING_BLACK";
    if (value == 377) return "Appearance.TYPE_WYRMLING_BLUE";
    if (value == 381) return "Appearance.TYPE_WYRMLING_BRASS";
    if (value == 383) return "Appearance.TYPE_WYRMLING_BRONZE";
    if (value == 382) return "Appearance.TYPE_WYRMLING_COPPER";
    if (value == 385) return "Appearance.TYPE_WYRMLING_GOLD";
    if (value == 379) return "Appearance.TYPE_WYRMLING_GREEN";
    if (value == 376) return "Appearance.TYPE_WYRMLING_RED";
    if (value == 384) return "Appearance.TYPE_WYRMLING_SILVER";
    if (value == 380) return "Appearance.TYPE_WYRMLING_WHITE";
    if (value == 285) return "Appearance.TYPE_YUAN_TI";
    if (value == 286) return "Appearance.TYPE_YUAN_TI_CHIEFTEN";
    if (value == 287) return "Appearance.TYPE_YUAN_TI_WIZARD";
    if (value == 198) return "Appearance.TYPE_ZOMBIE";
    if (value == 195) return "Appearance.TYPE_ZOMBIE_ROTTING";
    if (value == 199) return "Appearance.TYPE_ZOMBIE_TYRANT_FOG";
    if (value == 196) return "Appearance.TYPE_ZOMBIE_WARRIOR_1";
    if (value == 197) return "Appearance.TYPE_ZOMBIE_WARRIOR_2";
    return "Appearance.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "Appearance.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "Appearance.(not found: " + value + ")";
  }
}
