package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "AREA".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class Area {
  private Area() {}

  public final static int ABOVEGROUND = 1;
  public final static int ARTIFICIAL = 0;
  public final static int HEIGHT = 0;
  public final static int INVALID = -1;
  public final static int NATURAL = 1;
  public final static int TRANSITION_BEHOLDER_01 = 95;
  public final static int TRANSITION_BEHOLDER_02 = 96;
  public final static int TRANSITION_CARAVAN_DESERT = 84;
  public final static int TRANSITION_CARAVAN_RURAL = 85;
  public final static int TRANSITION_CARAVAN_WINTER = 83;
  public final static int TRANSITION_CASTLE_01 = 34;
  public final static int TRANSITION_CASTLE_02 = 35;
  public final static int TRANSITION_CASTLE_03 = 36;
  public final static int TRANSITION_CASTLE_04 = 37;
  public final static int TRANSITION_CASTLE_05 = 38;
  public final static int TRANSITION_CASTLE_06 = 39;
  public final static int TRANSITION_CASTLE_07 = 40;
  public final static int TRANSITION_CASTLE_08 = 41;
  public final static int TRANSITION_CITY = 2;
  public final static int TRANSITION_CITY_01 = 2;
  public final static int TRANSITION_CITY_02 = 3;
  public final static int TRANSITION_CITY_03 = 4;
  public final static int TRANSITION_CITY_04 = 5;
  public final static int TRANSITION_CITY_05 = 6;
  public final static int TRANSITION_CRYPT = 7;
  public final static int TRANSITION_CRYPT_01 = 7;
  public final static int TRANSITION_CRYPT_02 = 8;
  public final static int TRANSITION_CRYPT_03 = 9;
  public final static int TRANSITION_CRYPT_04 = 10;
  public final static int TRANSITION_CRYPT_05 = 11;
  public final static int TRANSITION_DESERT_01 = 73;
  public final static int TRANSITION_DESERT_02 = 74;
  public final static int TRANSITION_DESERT_03 = 75;
  public final static int TRANSITION_DESERT_04 = 76;
  public final static int TRANSITION_DESERT_05 = 77;
  public final static int TRANSITION_DROW_01 = 97;
  public final static int TRANSITION_DROW_02 = 98;
  public final static int TRANSITION_DROW_03 = 104;
  public final static int TRANSITION_DROW_04 = 105;
  public final static int TRANSITION_DUNGEON_01 = 12;
  public final static int TRANSITION_DUNGEON_02 = 13;
  public final static int TRANSITION_DUNGEON_03 = 14;
  public final static int TRANSITION_DUNGEON_04 = 15;
  public final static int TRANSITION_DUNGEON_05 = 16;
  public final static int TRANSITION_DUNGEON_06 = 17;
  public final static int TRANSITION_DUNGEON_07 = 18;
  public final static int TRANSITION_DUNGEON_08 = 19;
  public final static int TRANSITION_FOREST = 58;
  public final static int TRANSITION_FOREST_01 = 58;
  public final static int TRANSITION_FOREST_02 = 59;
  public final static int TRANSITION_FOREST_03 = 60;
  public final static int TRANSITION_FOREST_04 = 61;
  public final static int TRANSITION_FOREST_05 = 62;
  public final static int TRANSITION_ILLITHID_01 = 99;
  public final static int TRANSITION_ILLITHID_02 = 100;
  public final static int TRANSITION_INTERIOR_01 = 42;
  public final static int TRANSITION_INTERIOR_02 = 43;
  public final static int TRANSITION_INTERIOR_03 = 44;
  public final static int TRANSITION_INTERIOR_04 = 45;
  public final static int TRANSITION_INTERIOR_05 = 46;
  public final static int TRANSITION_INTERIOR_06 = 47;
  public final static int TRANSITION_INTERIOR_07 = 48;
  public final static int TRANSITION_INTERIOR_08 = 49;
  public final static int TRANSITION_INTERIOR_09 = 50;
  public final static int TRANSITION_INTERIOR_10 = 51;
  public final static int TRANSITION_INTERIOR_11 = 52;
  public final static int TRANSITION_INTERIOR_12 = 53;
  public final static int TRANSITION_INTERIOR_13 = 54;
  public final static int TRANSITION_INTERIOR_14 = 55;
  public final static int TRANSITION_INTERIOR_15 = 56;
  public final static int TRANSITION_INTERIOR_16 = 57;
  public final static int TRANSITION_MAGICAL_01 = 86;
  public final static int TRANSITION_MAGICAL_02 = 87;
  public final static int TRANSITION_MINES_01 = 20;
  public final static int TRANSITION_MINES_02 = 21;
  public final static int TRANSITION_MINES_03 = 22;
  public final static int TRANSITION_MINES_04 = 23;
  public final static int TRANSITION_MINES_05 = 24;
  public final static int TRANSITION_MINES_06 = 25;
  public final static int TRANSITION_MINES_07 = 26;
  public final static int TRANSITION_MINES_08 = 27;
  public final static int TRANSITION_MINES_09 = 28;
  public final static int TRANSITION_RANDOM = 0;
  public final static int TRANSITION_RUINS_01 = 78;
  public final static int TRANSITION_RUINS_02 = 79;
  public final static int TRANSITION_RUINS_03 = 80;
  public final static int TRANSITION_RUINS_04 = 81;
  public final static int TRANSITION_RUINS_05 = 82;
  public final static int TRANSITION_RURAL = 63;
  public final static int TRANSITION_RURAL_01 = 63;
  public final static int TRANSITION_RURAL_02 = 64;
  public final static int TRANSITION_RURAL_03 = 65;
  public final static int TRANSITION_RURAL_04 = 66;
  public final static int TRANSITION_RURAL_05 = 67;
  public final static int TRANSITION_SEWER_01 = 29;
  public final static int TRANSITION_SEWER_02 = 30;
  public final static int TRANSITION_SEWER_03 = 31;
  public final static int TRANSITION_SEWER_04 = 32;
  public final static int TRANSITION_SEWER_05 = 33;
  public final static int TRANSITION_UNDERDARK_01 = 88;
  public final static int TRANSITION_UNDERDARK_02 = 89;
  public final static int TRANSITION_UNDERDARK_03 = 90;
  public final static int TRANSITION_UNDERDARK_04 = 91;
  public final static int TRANSITION_UNDERDARK_05 = 92;
  public final static int TRANSITION_UNDERDARK_06 = 93;
  public final static int TRANSITION_UNDERDARK_07 = 94;
  public final static int TRANSITION_USER_DEFINED = 1;
  public final static int TRANSITION_WASTELAND_01 = 101;
  public final static int TRANSITION_WASTELAND_02 = 102;
  public final static int TRANSITION_WASTELAND_03 = 103;
  public final static int TRANSITION_WRURAL_01 = 68;
  public final static int TRANSITION_WRURAL_02 = 69;
  public final static int TRANSITION_WRURAL_03 = 70;
  public final static int TRANSITION_WRURAL_04 = 71;
  public final static int TRANSITION_WRURAL_05 = 72;
  public final static int UNDERGROUND = 0;
  public final static int WIDTH = 1;

  public static String nameOf(int value) {
    if (value == 1) return "Area.ABOVEGROUND";
    if (value == 0) return "Area.ARTIFICIAL";
    if (value == 0) return "Area.HEIGHT";
    if (value == -1) return "Area.INVALID";
    if (value == 1) return "Area.NATURAL";
    if (value == 95) return "Area.TRANSITION_BEHOLDER_01";
    if (value == 96) return "Area.TRANSITION_BEHOLDER_02";
    if (value == 84) return "Area.TRANSITION_CARAVAN_DESERT";
    if (value == 85) return "Area.TRANSITION_CARAVAN_RURAL";
    if (value == 83) return "Area.TRANSITION_CARAVAN_WINTER";
    if (value == 34) return "Area.TRANSITION_CASTLE_01";
    if (value == 35) return "Area.TRANSITION_CASTLE_02";
    if (value == 36) return "Area.TRANSITION_CASTLE_03";
    if (value == 37) return "Area.TRANSITION_CASTLE_04";
    if (value == 38) return "Area.TRANSITION_CASTLE_05";
    if (value == 39) return "Area.TRANSITION_CASTLE_06";
    if (value == 40) return "Area.TRANSITION_CASTLE_07";
    if (value == 41) return "Area.TRANSITION_CASTLE_08";
    if (value == 2) return "Area.TRANSITION_CITY";
    if (value == 2) return "Area.TRANSITION_CITY_01";
    if (value == 3) return "Area.TRANSITION_CITY_02";
    if (value == 4) return "Area.TRANSITION_CITY_03";
    if (value == 5) return "Area.TRANSITION_CITY_04";
    if (value == 6) return "Area.TRANSITION_CITY_05";
    if (value == 7) return "Area.TRANSITION_CRYPT";
    if (value == 7) return "Area.TRANSITION_CRYPT_01";
    if (value == 8) return "Area.TRANSITION_CRYPT_02";
    if (value == 9) return "Area.TRANSITION_CRYPT_03";
    if (value == 10) return "Area.TRANSITION_CRYPT_04";
    if (value == 11) return "Area.TRANSITION_CRYPT_05";
    if (value == 73) return "Area.TRANSITION_DESERT_01";
    if (value == 74) return "Area.TRANSITION_DESERT_02";
    if (value == 75) return "Area.TRANSITION_DESERT_03";
    if (value == 76) return "Area.TRANSITION_DESERT_04";
    if (value == 77) return "Area.TRANSITION_DESERT_05";
    if (value == 97) return "Area.TRANSITION_DROW_01";
    if (value == 98) return "Area.TRANSITION_DROW_02";
    if (value == 104) return "Area.TRANSITION_DROW_03";
    if (value == 105) return "Area.TRANSITION_DROW_04";
    if (value == 12) return "Area.TRANSITION_DUNGEON_01";
    if (value == 13) return "Area.TRANSITION_DUNGEON_02";
    if (value == 14) return "Area.TRANSITION_DUNGEON_03";
    if (value == 15) return "Area.TRANSITION_DUNGEON_04";
    if (value == 16) return "Area.TRANSITION_DUNGEON_05";
    if (value == 17) return "Area.TRANSITION_DUNGEON_06";
    if (value == 18) return "Area.TRANSITION_DUNGEON_07";
    if (value == 19) return "Area.TRANSITION_DUNGEON_08";
    if (value == 58) return "Area.TRANSITION_FOREST";
    if (value == 58) return "Area.TRANSITION_FOREST_01";
    if (value == 59) return "Area.TRANSITION_FOREST_02";
    if (value == 60) return "Area.TRANSITION_FOREST_03";
    if (value == 61) return "Area.TRANSITION_FOREST_04";
    if (value == 62) return "Area.TRANSITION_FOREST_05";
    if (value == 99) return "Area.TRANSITION_ILLITHID_01";
    if (value == 100) return "Area.TRANSITION_ILLITHID_02";
    if (value == 42) return "Area.TRANSITION_INTERIOR_01";
    if (value == 43) return "Area.TRANSITION_INTERIOR_02";
    if (value == 44) return "Area.TRANSITION_INTERIOR_03";
    if (value == 45) return "Area.TRANSITION_INTERIOR_04";
    if (value == 46) return "Area.TRANSITION_INTERIOR_05";
    if (value == 47) return "Area.TRANSITION_INTERIOR_06";
    if (value == 48) return "Area.TRANSITION_INTERIOR_07";
    if (value == 49) return "Area.TRANSITION_INTERIOR_08";
    if (value == 50) return "Area.TRANSITION_INTERIOR_09";
    if (value == 51) return "Area.TRANSITION_INTERIOR_10";
    if (value == 52) return "Area.TRANSITION_INTERIOR_11";
    if (value == 53) return "Area.TRANSITION_INTERIOR_12";
    if (value == 54) return "Area.TRANSITION_INTERIOR_13";
    if (value == 55) return "Area.TRANSITION_INTERIOR_14";
    if (value == 56) return "Area.TRANSITION_INTERIOR_15";
    if (value == 57) return "Area.TRANSITION_INTERIOR_16";
    if (value == 86) return "Area.TRANSITION_MAGICAL_01";
    if (value == 87) return "Area.TRANSITION_MAGICAL_02";
    if (value == 20) return "Area.TRANSITION_MINES_01";
    if (value == 21) return "Area.TRANSITION_MINES_02";
    if (value == 22) return "Area.TRANSITION_MINES_03";
    if (value == 23) return "Area.TRANSITION_MINES_04";
    if (value == 24) return "Area.TRANSITION_MINES_05";
    if (value == 25) return "Area.TRANSITION_MINES_06";
    if (value == 26) return "Area.TRANSITION_MINES_07";
    if (value == 27) return "Area.TRANSITION_MINES_08";
    if (value == 28) return "Area.TRANSITION_MINES_09";
    if (value == 0) return "Area.TRANSITION_RANDOM";
    if (value == 78) return "Area.TRANSITION_RUINS_01";
    if (value == 79) return "Area.TRANSITION_RUINS_02";
    if (value == 80) return "Area.TRANSITION_RUINS_03";
    if (value == 81) return "Area.TRANSITION_RUINS_04";
    if (value == 82) return "Area.TRANSITION_RUINS_05";
    if (value == 63) return "Area.TRANSITION_RURAL";
    if (value == 63) return "Area.TRANSITION_RURAL_01";
    if (value == 64) return "Area.TRANSITION_RURAL_02";
    if (value == 65) return "Area.TRANSITION_RURAL_03";
    if (value == 66) return "Area.TRANSITION_RURAL_04";
    if (value == 67) return "Area.TRANSITION_RURAL_05";
    if (value == 29) return "Area.TRANSITION_SEWER_01";
    if (value == 30) return "Area.TRANSITION_SEWER_02";
    if (value == 31) return "Area.TRANSITION_SEWER_03";
    if (value == 32) return "Area.TRANSITION_SEWER_04";
    if (value == 33) return "Area.TRANSITION_SEWER_05";
    if (value == 88) return "Area.TRANSITION_UNDERDARK_01";
    if (value == 89) return "Area.TRANSITION_UNDERDARK_02";
    if (value == 90) return "Area.TRANSITION_UNDERDARK_03";
    if (value == 91) return "Area.TRANSITION_UNDERDARK_04";
    if (value == 92) return "Area.TRANSITION_UNDERDARK_05";
    if (value == 93) return "Area.TRANSITION_UNDERDARK_06";
    if (value == 94) return "Area.TRANSITION_UNDERDARK_07";
    if (value == 1) return "Area.TRANSITION_USER_DEFINED";
    if (value == 101) return "Area.TRANSITION_WASTELAND_01";
    if (value == 102) return "Area.TRANSITION_WASTELAND_02";
    if (value == 103) return "Area.TRANSITION_WASTELAND_03";
    if (value == 68) return "Area.TRANSITION_WRURAL_01";
    if (value == 69) return "Area.TRANSITION_WRURAL_02";
    if (value == 70) return "Area.TRANSITION_WRURAL_03";
    if (value == 71) return "Area.TRANSITION_WRURAL_04";
    if (value == 72) return "Area.TRANSITION_WRURAL_05";
    if (value == 0) return "Area.UNDERGROUND";
    if (value == 1) return "Area.WIDTH";
    return "Area.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "Area.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "Area.(not found: " + value + ")";
  }
}
