package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "AREA_TRANSITION".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class AreaTransition {
  private AreaTransition() {}

  public final static int BEHOLDER_01 = 95;
  public final static int BEHOLDER_02 = 96;
  public final static int CARAVAN_DESERT = 84;
  public final static int CARAVAN_RURAL = 85;
  public final static int CARAVAN_WINTER = 83;
  public final static int CASTLE_01 = 34;
  public final static int CASTLE_02 = 35;
  public final static int CASTLE_03 = 36;
  public final static int CASTLE_04 = 37;
  public final static int CASTLE_05 = 38;
  public final static int CASTLE_06 = 39;
  public final static int CASTLE_07 = 40;
  public final static int CASTLE_08 = 41;
  public final static int CITY = 2;
  public final static int CITY_01 = 2;
  public final static int CITY_02 = 3;
  public final static int CITY_03 = 4;
  public final static int CITY_04 = 5;
  public final static int CITY_05 = 6;
  public final static int CRYPT = 7;
  public final static int CRYPT_01 = 7;
  public final static int CRYPT_02 = 8;
  public final static int CRYPT_03 = 9;
  public final static int CRYPT_04 = 10;
  public final static int CRYPT_05 = 11;
  public final static int DESERT_01 = 73;
  public final static int DESERT_02 = 74;
  public final static int DESERT_03 = 75;
  public final static int DESERT_04 = 76;
  public final static int DESERT_05 = 77;
  public final static int DROW_01 = 97;
  public final static int DROW_02 = 98;
  public final static int DROW_03 = 104;
  public final static int DROW_04 = 105;
  public final static int DUNGEON_01 = 12;
  public final static int DUNGEON_02 = 13;
  public final static int DUNGEON_03 = 14;
  public final static int DUNGEON_04 = 15;
  public final static int DUNGEON_05 = 16;
  public final static int DUNGEON_06 = 17;
  public final static int DUNGEON_07 = 18;
  public final static int DUNGEON_08 = 19;
  public final static int FOREST = 58;
  public final static int FOREST_01 = 58;
  public final static int FOREST_02 = 59;
  public final static int FOREST_03 = 60;
  public final static int FOREST_04 = 61;
  public final static int FOREST_05 = 62;
  public final static int ILLITHID_01 = 99;
  public final static int ILLITHID_02 = 100;
  public final static int INTERIOR_01 = 42;
  public final static int INTERIOR_02 = 43;
  public final static int INTERIOR_03 = 44;
  public final static int INTERIOR_04 = 45;
  public final static int INTERIOR_05 = 46;
  public final static int INTERIOR_06 = 47;
  public final static int INTERIOR_07 = 48;
  public final static int INTERIOR_08 = 49;
  public final static int INTERIOR_09 = 50;
  public final static int INTERIOR_10 = 51;
  public final static int INTERIOR_11 = 52;
  public final static int INTERIOR_12 = 53;
  public final static int INTERIOR_13 = 54;
  public final static int INTERIOR_14 = 55;
  public final static int INTERIOR_15 = 56;
  public final static int INTERIOR_16 = 57;
  public final static int MAGICAL_01 = 86;
  public final static int MAGICAL_02 = 87;
  public final static int MINES_01 = 20;
  public final static int MINES_02 = 21;
  public final static int MINES_03 = 22;
  public final static int MINES_04 = 23;
  public final static int MINES_05 = 24;
  public final static int MINES_06 = 25;
  public final static int MINES_07 = 26;
  public final static int MINES_08 = 27;
  public final static int MINES_09 = 28;
  public final static int RANDOM = 0;
  public final static int RUINS_01 = 78;
  public final static int RUINS_02 = 79;
  public final static int RUINS_03 = 80;
  public final static int RUINS_04 = 81;
  public final static int RUINS_05 = 82;
  public final static int RURAL = 63;
  public final static int RURAL_01 = 63;
  public final static int RURAL_02 = 64;
  public final static int RURAL_03 = 65;
  public final static int RURAL_04 = 66;
  public final static int RURAL_05 = 67;
  public final static int SEWER_01 = 29;
  public final static int SEWER_02 = 30;
  public final static int SEWER_03 = 31;
  public final static int SEWER_04 = 32;
  public final static int SEWER_05 = 33;
  public final static int UNDERDARK_01 = 88;
  public final static int UNDERDARK_02 = 89;
  public final static int UNDERDARK_03 = 90;
  public final static int UNDERDARK_04 = 91;
  public final static int UNDERDARK_05 = 92;
  public final static int UNDERDARK_06 = 93;
  public final static int UNDERDARK_07 = 94;
  public final static int USER_DEFINED = 1;
  public final static int WASTELAND_01 = 101;
  public final static int WASTELAND_02 = 102;
  public final static int WASTELAND_03 = 103;
  public final static int WRURAL_01 = 68;
  public final static int WRURAL_02 = 69;
  public final static int WRURAL_03 = 70;
  public final static int WRURAL_04 = 71;
  public final static int WRURAL_05 = 72;

  public static String nameOf(int value) {
    if (value == 95) return "AreaTransition.BEHOLDER_01";
    if (value == 96) return "AreaTransition.BEHOLDER_02";
    if (value == 84) return "AreaTransition.CARAVAN_DESERT";
    if (value == 85) return "AreaTransition.CARAVAN_RURAL";
    if (value == 83) return "AreaTransition.CARAVAN_WINTER";
    if (value == 34) return "AreaTransition.CASTLE_01";
    if (value == 35) return "AreaTransition.CASTLE_02";
    if (value == 36) return "AreaTransition.CASTLE_03";
    if (value == 37) return "AreaTransition.CASTLE_04";
    if (value == 38) return "AreaTransition.CASTLE_05";
    if (value == 39) return "AreaTransition.CASTLE_06";
    if (value == 40) return "AreaTransition.CASTLE_07";
    if (value == 41) return "AreaTransition.CASTLE_08";
    if (value == 2) return "AreaTransition.CITY";
    if (value == 2) return "AreaTransition.CITY_01";
    if (value == 3) return "AreaTransition.CITY_02";
    if (value == 4) return "AreaTransition.CITY_03";
    if (value == 5) return "AreaTransition.CITY_04";
    if (value == 6) return "AreaTransition.CITY_05";
    if (value == 7) return "AreaTransition.CRYPT";
    if (value == 7) return "AreaTransition.CRYPT_01";
    if (value == 8) return "AreaTransition.CRYPT_02";
    if (value == 9) return "AreaTransition.CRYPT_03";
    if (value == 10) return "AreaTransition.CRYPT_04";
    if (value == 11) return "AreaTransition.CRYPT_05";
    if (value == 73) return "AreaTransition.DESERT_01";
    if (value == 74) return "AreaTransition.DESERT_02";
    if (value == 75) return "AreaTransition.DESERT_03";
    if (value == 76) return "AreaTransition.DESERT_04";
    if (value == 77) return "AreaTransition.DESERT_05";
    if (value == 97) return "AreaTransition.DROW_01";
    if (value == 98) return "AreaTransition.DROW_02";
    if (value == 104) return "AreaTransition.DROW_03";
    if (value == 105) return "AreaTransition.DROW_04";
    if (value == 12) return "AreaTransition.DUNGEON_01";
    if (value == 13) return "AreaTransition.DUNGEON_02";
    if (value == 14) return "AreaTransition.DUNGEON_03";
    if (value == 15) return "AreaTransition.DUNGEON_04";
    if (value == 16) return "AreaTransition.DUNGEON_05";
    if (value == 17) return "AreaTransition.DUNGEON_06";
    if (value == 18) return "AreaTransition.DUNGEON_07";
    if (value == 19) return "AreaTransition.DUNGEON_08";
    if (value == 58) return "AreaTransition.FOREST";
    if (value == 58) return "AreaTransition.FOREST_01";
    if (value == 59) return "AreaTransition.FOREST_02";
    if (value == 60) return "AreaTransition.FOREST_03";
    if (value == 61) return "AreaTransition.FOREST_04";
    if (value == 62) return "AreaTransition.FOREST_05";
    if (value == 99) return "AreaTransition.ILLITHID_01";
    if (value == 100) return "AreaTransition.ILLITHID_02";
    if (value == 42) return "AreaTransition.INTERIOR_01";
    if (value == 43) return "AreaTransition.INTERIOR_02";
    if (value == 44) return "AreaTransition.INTERIOR_03";
    if (value == 45) return "AreaTransition.INTERIOR_04";
    if (value == 46) return "AreaTransition.INTERIOR_05";
    if (value == 47) return "AreaTransition.INTERIOR_06";
    if (value == 48) return "AreaTransition.INTERIOR_07";
    if (value == 49) return "AreaTransition.INTERIOR_08";
    if (value == 50) return "AreaTransition.INTERIOR_09";
    if (value == 51) return "AreaTransition.INTERIOR_10";
    if (value == 52) return "AreaTransition.INTERIOR_11";
    if (value == 53) return "AreaTransition.INTERIOR_12";
    if (value == 54) return "AreaTransition.INTERIOR_13";
    if (value == 55) return "AreaTransition.INTERIOR_14";
    if (value == 56) return "AreaTransition.INTERIOR_15";
    if (value == 57) return "AreaTransition.INTERIOR_16";
    if (value == 86) return "AreaTransition.MAGICAL_01";
    if (value == 87) return "AreaTransition.MAGICAL_02";
    if (value == 20) return "AreaTransition.MINES_01";
    if (value == 21) return "AreaTransition.MINES_02";
    if (value == 22) return "AreaTransition.MINES_03";
    if (value == 23) return "AreaTransition.MINES_04";
    if (value == 24) return "AreaTransition.MINES_05";
    if (value == 25) return "AreaTransition.MINES_06";
    if (value == 26) return "AreaTransition.MINES_07";
    if (value == 27) return "AreaTransition.MINES_08";
    if (value == 28) return "AreaTransition.MINES_09";
    if (value == 0) return "AreaTransition.RANDOM";
    if (value == 78) return "AreaTransition.RUINS_01";
    if (value == 79) return "AreaTransition.RUINS_02";
    if (value == 80) return "AreaTransition.RUINS_03";
    if (value == 81) return "AreaTransition.RUINS_04";
    if (value == 82) return "AreaTransition.RUINS_05";
    if (value == 63) return "AreaTransition.RURAL";
    if (value == 63) return "AreaTransition.RURAL_01";
    if (value == 64) return "AreaTransition.RURAL_02";
    if (value == 65) return "AreaTransition.RURAL_03";
    if (value == 66) return "AreaTransition.RURAL_04";
    if (value == 67) return "AreaTransition.RURAL_05";
    if (value == 29) return "AreaTransition.SEWER_01";
    if (value == 30) return "AreaTransition.SEWER_02";
    if (value == 31) return "AreaTransition.SEWER_03";
    if (value == 32) return "AreaTransition.SEWER_04";
    if (value == 33) return "AreaTransition.SEWER_05";
    if (value == 88) return "AreaTransition.UNDERDARK_01";
    if (value == 89) return "AreaTransition.UNDERDARK_02";
    if (value == 90) return "AreaTransition.UNDERDARK_03";
    if (value == 91) return "AreaTransition.UNDERDARK_04";
    if (value == 92) return "AreaTransition.UNDERDARK_05";
    if (value == 93) return "AreaTransition.UNDERDARK_06";
    if (value == 94) return "AreaTransition.UNDERDARK_07";
    if (value == 1) return "AreaTransition.USER_DEFINED";
    if (value == 101) return "AreaTransition.WASTELAND_01";
    if (value == 102) return "AreaTransition.WASTELAND_02";
    if (value == 103) return "AreaTransition.WASTELAND_03";
    if (value == 68) return "AreaTransition.WRURAL_01";
    if (value == 69) return "AreaTransition.WRURAL_02";
    if (value == 70) return "AreaTransition.WRURAL_03";
    if (value == 71) return "AreaTransition.WRURAL_04";
    if (value == 72) return "AreaTransition.WRURAL_05";
    return "AreaTransition.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "AreaTransition.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "AreaTransition.(not found: " + value + ")";
  }
}
