package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "FEAT_EPIC".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class FeatEpic {
  private FeatEpic() {}

  public final static int ARCANE_ARCHER = 977;
  public final static int ARMOR_SKIN = 490;
  public final static int ASSASSIN = 978;
  public final static int AUTOMATIC_QUICKEN_1 = 857;
  public final static int AUTOMATIC_QUICKEN_2 = 858;
  public final static int AUTOMATIC_QUICKEN_3 = 859;
  public final static int AUTOMATIC_SILENT_SPELL_1 = 860;
  public final static int AUTOMATIC_SILENT_SPELL_2 = 861;
  public final static int AUTOMATIC_SILENT_SPELL_3 = 862;
  public final static int AUTOMATIC_STILL_SPELL_1 = 863;
  public final static int AUTOMATIC_STILL_SPELL_2 = 864;
  public final static int AUTOMATIC_STILL_SPELL_3 = 865;
  public final static int BANE_OF_ENEMIES = 855;
  public final static int BARBARIAN = 967;
  public final static int BARBARIAN_DAMAGE_REDUCTION = 1067;
  public final static int BARD = 968;
  public final static int BLACKGUARD = 979;
  public final static int BLINDING_SPEED = 491;
  public final static int CHARACTER = 1001;
  public final static int CLERIC = 969;
  public final static int CONSTRUCT_SHAPE = 1061;
  public final static int DAMAGE_REDUCTION_3 = 492;
  public final static int DAMAGE_REDUCTION_6 = 493;
  public final static int DAMAGE_REDUCTION_9 = 494;
  public final static int DEVASTATING_CRITICAL_BASTARDSWORD = 528;
  public final static int DEVASTATING_CRITICAL_BATTLEAXE = 516;
  public final static int DEVASTATING_CRITICAL_CLUB = 495;
  public final static int DEVASTATING_CRITICAL_CREATURE = 532;
  public final static int DEVASTATING_CRITICAL_DAGGER = 496;
  public final static int DEVASTATING_CRITICAL_DART = 497;
  public final static int DEVASTATING_CRITICAL_DIREMACE = 529;
  public final static int DEVASTATING_CRITICAL_DOUBLEAXE = 530;
  public final static int DEVASTATING_CRITICAL_DWAXE = 955;
  public final static int DEVASTATING_CRITICAL_GREATAXE = 517;
  public final static int DEVASTATING_CRITICAL_GREATSWORD = 513;
  public final static int DEVASTATING_CRITICAL_HALBERD = 518;
  public final static int DEVASTATING_CRITICAL_HANDAXE = 514;
  public final static int DEVASTATING_CRITICAL_HEAVYCROSSBOW = 498;
  public final static int DEVASTATING_CRITICAL_HEAVYFLAIL = 522;
  public final static int DEVASTATING_CRITICAL_KAMA = 523;
  public final static int DEVASTATING_CRITICAL_KATANA = 527;
  public final static int DEVASTATING_CRITICAL_KUKRI = 524;
  public final static int DEVASTATING_CRITICAL_LIGHTCROSSBOW = 499;
  public final static int DEVASTATING_CRITICAL_LIGHTFLAIL = 520;
  public final static int DEVASTATING_CRITICAL_LIGHTHAMMER = 519;
  public final static int DEVASTATING_CRITICAL_LIGHTMACE = 500;
  public final static int DEVASTATING_CRITICAL_LONGBOW = 507;
  public final static int DEVASTATING_CRITICAL_LONGSWORD = 512;
  public final static int DEVASTATING_CRITICAL_MORNINGSTAR = 501;
  public final static int DEVASTATING_CRITICAL_QUARTERSTAFF = 502;
  public final static int DEVASTATING_CRITICAL_RAPIER = 510;
  public final static int DEVASTATING_CRITICAL_SCIMITAR = 511;
  public final static int DEVASTATING_CRITICAL_SCYTHE = 526;
  public final static int DEVASTATING_CRITICAL_SHORTBOW = 508;
  public final static int DEVASTATING_CRITICAL_SHORTSPEAR = 503;
  public final static int DEVASTATING_CRITICAL_SHORTSWORD = 509;
  public final static int DEVASTATING_CRITICAL_SHURIKEN = 525;
  public final static int DEVASTATING_CRITICAL_SICKLE = 504;
  public final static int DEVASTATING_CRITICAL_SLING = 505;
  public final static int DEVASTATING_CRITICAL_THROWINGAXE = 515;
  public final static int DEVASTATING_CRITICAL_TRIDENT = 1075;
  public final static int DEVASTATING_CRITICAL_TWOBLADEDSWORD = 531;
  public final static int DEVASTATING_CRITICAL_UNARMED = 506;
  public final static int DEVASTATING_CRITICAL_WARHAMMER = 521;
  public final static int DEVASTATING_CRITICAL_WHIP = 996;
  public final static int DIVINE_CHAMPION = 982;
  public final static int DODGE = 856;
  public final static int DRUID = 970;
  public final static int DRUID_INFINITE_ELEMENTAL_SHAPE = 1069;
  public final static int DRUID_INFINITE_WILDSHAPE = 1068;
  public final static int DWARVEN_DEFENDER = 985;
  public final static int ENERGY_RESISTANCE_ACID_1 = 543;
  public final static int ENERGY_RESISTANCE_ACID_10 = 552;
  public final static int ENERGY_RESISTANCE_ACID_2 = 544;
  public final static int ENERGY_RESISTANCE_ACID_3 = 545;
  public final static int ENERGY_RESISTANCE_ACID_4 = 546;
  public final static int ENERGY_RESISTANCE_ACID_5 = 547;
  public final static int ENERGY_RESISTANCE_ACID_6 = 548;
  public final static int ENERGY_RESISTANCE_ACID_7 = 549;
  public final static int ENERGY_RESISTANCE_ACID_8 = 550;
  public final static int ENERGY_RESISTANCE_ACID_9 = 551;
  public final static int ENERGY_RESISTANCE_COLD_1 = 533;
  public final static int ENERGY_RESISTANCE_COLD_10 = 542;
  public final static int ENERGY_RESISTANCE_COLD_2 = 534;
  public final static int ENERGY_RESISTANCE_COLD_3 = 535;
  public final static int ENERGY_RESISTANCE_COLD_4 = 536;
  public final static int ENERGY_RESISTANCE_COLD_5 = 537;
  public final static int ENERGY_RESISTANCE_COLD_6 = 538;
  public final static int ENERGY_RESISTANCE_COLD_7 = 539;
  public final static int ENERGY_RESISTANCE_COLD_8 = 540;
  public final static int ENERGY_RESISTANCE_COLD_9 = 541;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_1 = 563;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_10 = 572;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_2 = 564;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_3 = 565;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_4 = 566;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_5 = 567;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_6 = 568;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_7 = 569;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_8 = 570;
  public final static int ENERGY_RESISTANCE_ELECTRICAL_9 = 571;
  public final static int ENERGY_RESISTANCE_FIRE_1 = 553;
  public final static int ENERGY_RESISTANCE_FIRE_10 = 562;
  public final static int ENERGY_RESISTANCE_FIRE_2 = 554;
  public final static int ENERGY_RESISTANCE_FIRE_3 = 555;
  public final static int ENERGY_RESISTANCE_FIRE_4 = 556;
  public final static int ENERGY_RESISTANCE_FIRE_5 = 557;
  public final static int ENERGY_RESISTANCE_FIRE_6 = 558;
  public final static int ENERGY_RESISTANCE_FIRE_7 = 559;
  public final static int ENERGY_RESISTANCE_FIRE_8 = 560;
  public final static int ENERGY_RESISTANCE_FIRE_9 = 561;
  public final static int ENERGY_RESISTANCE_SONIC_1 = 573;
  public final static int ENERGY_RESISTANCE_SONIC_10 = 582;
  public final static int ENERGY_RESISTANCE_SONIC_2 = 574;
  public final static int ENERGY_RESISTANCE_SONIC_3 = 575;
  public final static int ENERGY_RESISTANCE_SONIC_4 = 576;
  public final static int ENERGY_RESISTANCE_SONIC_5 = 577;
  public final static int ENERGY_RESISTANCE_SONIC_6 = 578;
  public final static int ENERGY_RESISTANCE_SONIC_7 = 579;
  public final static int ENERGY_RESISTANCE_SONIC_8 = 580;
  public final static int ENERGY_RESISTANCE_SONIC_9 = 581;
  public final static int EPIC_FIEND = 1003;
  public final static int EPIC_SHADOWLORD = 1002;
  public final static int FIGHTER = 966;
  public final static int FORTITUDE = 583;
  public final static int GREAT_CHARISMA_1 = 764;
  public final static int GREAT_CHARISMA_10 = 773;
  public final static int GREAT_CHARISMA_2 = 765;
  public final static int GREAT_CHARISMA_3 = 766;
  public final static int GREAT_CHARISMA_4 = 767;
  public final static int GREAT_CHARISMA_5 = 768;
  public final static int GREAT_CHARISMA_6 = 769;
  public final static int GREAT_CHARISMA_7 = 770;
  public final static int GREAT_CHARISMA_8 = 771;
  public final static int GREAT_CHARISMA_9 = 772;
  public final static int GREAT_CONSTITUTION_1 = 774;
  public final static int GREAT_CONSTITUTION_10 = 783;
  public final static int GREAT_CONSTITUTION_2 = 775;
  public final static int GREAT_CONSTITUTION_3 = 776;
  public final static int GREAT_CONSTITUTION_4 = 777;
  public final static int GREAT_CONSTITUTION_5 = 778;
  public final static int GREAT_CONSTITUTION_6 = 779;
  public final static int GREAT_CONSTITUTION_7 = 780;
  public final static int GREAT_CONSTITUTION_8 = 781;
  public final static int GREAT_CONSTITUTION_9 = 782;
  public final static int GREAT_DEXTERITY_1 = 784;
  public final static int GREAT_DEXTERITY_10 = 793;
  public final static int GREAT_DEXTERITY_2 = 785;
  public final static int GREAT_DEXTERITY_3 = 786;
  public final static int GREAT_DEXTERITY_4 = 787;
  public final static int GREAT_DEXTERITY_5 = 788;
  public final static int GREAT_DEXTERITY_6 = 789;
  public final static int GREAT_DEXTERITY_7 = 790;
  public final static int GREAT_DEXTERITY_8 = 791;
  public final static int GREAT_DEXTERITY_9 = 792;
  public final static int GREAT_INTELLIGENCE_1 = 794;
  public final static int GREAT_INTELLIGENCE_10 = 803;
  public final static int GREAT_INTELLIGENCE_2 = 795;
  public final static int GREAT_INTELLIGENCE_3 = 796;
  public final static int GREAT_INTELLIGENCE_4 = 797;
  public final static int GREAT_INTELLIGENCE_5 = 798;
  public final static int GREAT_INTELLIGENCE_6 = 799;
  public final static int GREAT_INTELLIGENCE_7 = 800;
  public final static int GREAT_INTELLIGENCE_8 = 801;
  public final static int GREAT_INTELLIGENCE_9 = 802;
  public final static int GREAT_SMITING_1 = 824;
  public final static int GREAT_SMITING_10 = 833;
  public final static int GREAT_SMITING_2 = 825;
  public final static int GREAT_SMITING_3 = 826;
  public final static int GREAT_SMITING_4 = 827;
  public final static int GREAT_SMITING_5 = 828;
  public final static int GREAT_SMITING_6 = 829;
  public final static int GREAT_SMITING_7 = 830;
  public final static int GREAT_SMITING_8 = 831;
  public final static int GREAT_SMITING_9 = 832;
  public final static int GREAT_STRENGTH_1 = 814;
  public final static int GREAT_STRENGTH_10 = 823;
  public final static int GREAT_STRENGTH_2 = 815;
  public final static int GREAT_STRENGTH_3 = 816;
  public final static int GREAT_STRENGTH_4 = 817;
  public final static int GREAT_STRENGTH_5 = 818;
  public final static int GREAT_STRENGTH_6 = 819;
  public final static int GREAT_STRENGTH_7 = 820;
  public final static int GREAT_STRENGTH_8 = 821;
  public final static int GREAT_STRENGTH_9 = 822;
  public final static int GREAT_WISDOM_1 = 804;
  public final static int GREAT_WISDOM_10 = 813;
  public final static int GREAT_WISDOM_2 = 805;
  public final static int GREAT_WISDOM_3 = 806;
  public final static int GREAT_WISDOM_4 = 807;
  public final static int GREAT_WISDOM_5 = 808;
  public final static int GREAT_WISDOM_6 = 809;
  public final static int GREAT_WISDOM_7 = 810;
  public final static int GREAT_WISDOM_8 = 811;
  public final static int GREAT_WISDOM_9 = 812;
  public final static int HARPER_SCOUT = 981;
  public final static int IMPROVED_COMBAT_CASTING = 696;
  public final static int IMPROVED_KI_STRIKE_4 = 697;
  public final static int IMPROVED_KI_STRIKE_5 = 698;
  public final static int IMPROVED_SNEAK_ATTACK_1 = 834;
  public final static int IMPROVED_SNEAK_ATTACK_10 = 843;
  public final static int IMPROVED_SNEAK_ATTACK_2 = 835;
  public final static int IMPROVED_SNEAK_ATTACK_3 = 836;
  public final static int IMPROVED_SNEAK_ATTACK_4 = 837;
  public final static int IMPROVED_SNEAK_ATTACK_5 = 838;
  public final static int IMPROVED_SNEAK_ATTACK_6 = 839;
  public final static int IMPROVED_SNEAK_ATTACK_7 = 840;
  public final static int IMPROVED_SNEAK_ATTACK_8 = 841;
  public final static int IMPROVED_SNEAK_ATTACK_9 = 842;
  public final static int IMPROVED_SPELL_RESISTANCE_1 = 699;
  public final static int IMPROVED_SPELL_RESISTANCE_10 = 708;
  public final static int IMPROVED_SPELL_RESISTANCE_2 = 700;
  public final static int IMPROVED_SPELL_RESISTANCE_3 = 701;
  public final static int IMPROVED_SPELL_RESISTANCE_4 = 702;
  public final static int IMPROVED_SPELL_RESISTANCE_5 = 703;
  public final static int IMPROVED_SPELL_RESISTANCE_6 = 704;
  public final static int IMPROVED_SPELL_RESISTANCE_7 = 705;
  public final static int IMPROVED_SPELL_RESISTANCE_8 = 706;
  public final static int IMPROVED_SPELL_RESISTANCE_9 = 707;
  public final static int IMPROVED_STUNNING_FIST_1 = 844;
  public final static int IMPROVED_STUNNING_FIST_10 = 853;
  public final static int IMPROVED_STUNNING_FIST_2 = 845;
  public final static int IMPROVED_STUNNING_FIST_3 = 846;
  public final static int IMPROVED_STUNNING_FIST_4 = 847;
  public final static int IMPROVED_STUNNING_FIST_5 = 848;
  public final static int IMPROVED_STUNNING_FIST_6 = 849;
  public final static int IMPROVED_STUNNING_FIST_7 = 850;
  public final static int IMPROVED_STUNNING_FIST_8 = 851;
  public final static int IMPROVED_STUNNING_FIST_9 = 852;
  public final static int LASTING_INSPIRATION = 870;
  public final static int MONK = 971;
  public final static int OUTSIDER_SHAPE = 1060;
  public final static int OVERWHELMING_CRITICAL_BASTARDSWORD = 742;
  public final static int OVERWHELMING_CRITICAL_BATTLEAXE = 730;
  public final static int OVERWHELMING_CRITICAL_CLUB = 709;
  public final static int OVERWHELMING_CRITICAL_CREATURE = 746;
  public final static int OVERWHELMING_CRITICAL_DAGGER = 710;
  public final static int OVERWHELMING_CRITICAL_DART = 711;
  public final static int OVERWHELMING_CRITICAL_DIREMACE = 743;
  public final static int OVERWHELMING_CRITICAL_DOUBLEAXE = 744;
  public final static int OVERWHELMING_CRITICAL_DWAXE = 958;
  public final static int OVERWHELMING_CRITICAL_GREATAXE = 731;
  public final static int OVERWHELMING_CRITICAL_GREATSWORD = 727;
  public final static int OVERWHELMING_CRITICAL_HALBERD = 732;
  public final static int OVERWHELMING_CRITICAL_HANDAXE = 728;
  public final static int OVERWHELMING_CRITICAL_HEAVYCROSSBOW = 712;
  public final static int OVERWHELMING_CRITICAL_HEAVYFLAIL = 736;
  public final static int OVERWHELMING_CRITICAL_KAMA = 737;
  public final static int OVERWHELMING_CRITICAL_KATANA = 741;
  public final static int OVERWHELMING_CRITICAL_KUKRI = 738;
  public final static int OVERWHELMING_CRITICAL_LIGHTCROSSBOW = 713;
  public final static int OVERWHELMING_CRITICAL_LIGHTFLAIL = 734;
  public final static int OVERWHELMING_CRITICAL_LIGHTHAMMER = 733;
  public final static int OVERWHELMING_CRITICAL_LIGHTMACE = 714;
  public final static int OVERWHELMING_CRITICAL_LONGBOW = 721;
  public final static int OVERWHELMING_CRITICAL_LONGSWORD = 726;
  public final static int OVERWHELMING_CRITICAL_MORNINGSTAR = 715;
  public final static int OVERWHELMING_CRITICAL_QUARTERSTAFF = 716;
  public final static int OVERWHELMING_CRITICAL_RAPIER = 724;
  public final static int OVERWHELMING_CRITICAL_SCIMITAR = 725;
  public final static int OVERWHELMING_CRITICAL_SCYTHE = 740;
  public final static int OVERWHELMING_CRITICAL_SHORTBOW = 722;
  public final static int OVERWHELMING_CRITICAL_SHORTSPEAR = 717;
  public final static int OVERWHELMING_CRITICAL_SHORTSWORD = 723;
  public final static int OVERWHELMING_CRITICAL_SHURIKEN = 739;
  public final static int OVERWHELMING_CRITICAL_SICKLE = 718;
  public final static int OVERWHELMING_CRITICAL_SLING = 719;
  public final static int OVERWHELMING_CRITICAL_THROWINGAXE = 729;
  public final static int OVERWHELMING_CRITICAL_TRIDENT = 1078;
  public final static int OVERWHELMING_CRITICAL_TWOBLADEDSWORD = 745;
  public final static int OVERWHELMING_CRITICAL_UNARMED = 720;
  public final static int OVERWHELMING_CRITICAL_WARHAMMER = 735;
  public final static int OVERWHELMING_CRITICAL_WHIP = 999;
  public final static int PALADIN = 972;
  public final static int PALE_MASTER = 984;
  public final static int PERFECT_HEALTH = 747;
  public final static int PROWESS = 584;
  public final static int RANGER = 973;
  public final static int RED_DRAGON_DISC = 987;
  public final static int REFLEXES = 585;
  public final static int REPUTATION = 586;
  public final static int ROGUE = 974;
  public final static int SELF_CONCEALMENT_10 = 748;
  public final static int SELF_CONCEALMENT_20 = 749;
  public final static int SELF_CONCEALMENT_30 = 750;
  public final static int SELF_CONCEALMENT_40 = 751;
  public final static int SELF_CONCEALMENT_50 = 752;
  public final static int SHADOWDANCER = 980;
  public final static int SHIFTER = 986;
  public final static int SHIFTER_INFINITE_HUMANOID_SHAPE = 1066;
  public final static int SHIFTER_INFINITE_WILDSHAPE_1 = 1062;
  public final static int SHIFTER_INFINITE_WILDSHAPE_2 = 1063;
  public final static int SHIFTER_INFINITE_WILDSHAPE_3 = 1064;
  public final static int SHIFTER_INFINITE_WILDSHAPE_4 = 1065;
  public final static int SKILL_FOCUS_ANIMAL_EMPATHY = 587;
  public final static int SKILL_FOCUS_APPRAISE = 588;
  public final static int SKILL_FOCUS_BLUFF = 917;
  public final static int SKILL_FOCUS_CONCENTRATION = 589;
  public final static int SKILL_FOCUS_CRAFT_ARMOR = 913;
  public final static int SKILL_FOCUS_CRAFT_TRAP = 590;
  public final static int SKILL_FOCUS_CRAFT_WEAPON = 914;
  public final static int SKILL_FOCUS_DISABLETRAP = 591;
  public final static int SKILL_FOCUS_DISCIPLINE = 592;
  public final static int SKILL_FOCUS_HEAL = 593;
  public final static int SKILL_FOCUS_HIDE = 594;
  public final static int SKILL_FOCUS_INTIMIDATE = 918;
  public final static int SKILL_FOCUS_LISTEN = 595;
  public final static int SKILL_FOCUS_LORE = 596;
  public final static int SKILL_FOCUS_MOVESILENTLY = 597;
  public final static int SKILL_FOCUS_OPENLOCK = 598;
  public final static int SKILL_FOCUS_PARRY = 599;
  public final static int SKILL_FOCUS_PERFORM = 600;
  public final static int SKILL_FOCUS_PERSUADE = 601;
  public final static int SKILL_FOCUS_PICKPOCKET = 602;
  public final static int SKILL_FOCUS_SEARCH = 603;
  public final static int SKILL_FOCUS_SETTRAP = 604;
  public final static int SKILL_FOCUS_SPELLCRAFT = 605;
  public final static int SKILL_FOCUS_SPOT = 606;
  public final static int SKILL_FOCUS_TAUNT = 607;
  public final static int SKILL_FOCUS_TUMBLE = 608;
  public final static int SKILL_FOCUS_USEMAGICDEVICE = 609;
  public final static int SORCERER = 975;
  public final static int SPELL_DRAGON_KNIGHT = 875;
  public final static int SPELL_EPIC_WARDING = 990;
  public final static int SPELL_FOCUS_ABJURATION = 610;
  public final static int SPELL_FOCUS_CONJURATION = 611;
  public final static int SPELL_FOCUS_DIVINATION = 612;
  public final static int SPELL_FOCUS_ENCHANTMENT = 613;
  public final static int SPELL_FOCUS_EVOCATION = 614;
  public final static int SPELL_FOCUS_ILLUSION = 615;
  public final static int SPELL_FOCUS_NECROMANCY = 616;
  public final static int SPELL_FOCUS_TRANSMUTATION = 617;
  public final static int SPELL_HELLBALL = 876;
  public final static int SPELL_MAGE_ARMOUR = 877;
  public final static int SPELL_MUMMY_DUST = 874;
  public final static int SPELL_PENETRATION = 618;
  public final static int SPELL_RUIN = 878;
  public final static int SUPERIOR_INITIATIVE = 753;
  public final static int SUPERIOR_WEAPON_FOCUS = 1071;
  public final static int TERRIFYING_RAGE = 989;
  public final static int THUNDERING_RAGE = 988;
  public final static int TOUGHNESS_1 = 754;
  public final static int TOUGHNESS_10 = 763;
  public final static int TOUGHNESS_2 = 755;
  public final static int TOUGHNESS_3 = 756;
  public final static int TOUGHNESS_4 = 757;
  public final static int TOUGHNESS_5 = 758;
  public final static int TOUGHNESS_6 = 759;
  public final static int TOUGHNESS_7 = 760;
  public final static int TOUGHNESS_8 = 761;
  public final static int TOUGHNESS_9 = 762;
  public final static int WEAPON_FOCUS_BASTARDSWORD = 652;
  public final static int WEAPON_FOCUS_BATTLEAXE = 640;
  public final static int WEAPON_FOCUS_CLUB = 619;
  public final static int WEAPON_FOCUS_CREATURE = 656;
  public final static int WEAPON_FOCUS_DAGGER = 620;
  public final static int WEAPON_FOCUS_DART = 621;
  public final static int WEAPON_FOCUS_DIREMACE = 653;
  public final static int WEAPON_FOCUS_DOUBLEAXE = 654;
  public final static int WEAPON_FOCUS_DWAXE = 956;
  public final static int WEAPON_FOCUS_GREATAXE = 641;
  public final static int WEAPON_FOCUS_GREATSWORD = 637;
  public final static int WEAPON_FOCUS_HALBERD = 642;
  public final static int WEAPON_FOCUS_HANDAXE = 638;
  public final static int WEAPON_FOCUS_HEAVYCROSSBOW = 622;
  public final static int WEAPON_FOCUS_HEAVYFLAIL = 646;
  public final static int WEAPON_FOCUS_KAMA = 647;
  public final static int WEAPON_FOCUS_KATANA = 651;
  public final static int WEAPON_FOCUS_KUKRI = 648;
  public final static int WEAPON_FOCUS_LIGHTCROSSBOW = 623;
  public final static int WEAPON_FOCUS_LIGHTFLAIL = 644;
  public final static int WEAPON_FOCUS_LIGHTHAMMER = 643;
  public final static int WEAPON_FOCUS_LIGHTMACE = 624;
  public final static int WEAPON_FOCUS_LONGBOW = 631;
  public final static int WEAPON_FOCUS_LONGSWORD = 636;
  public final static int WEAPON_FOCUS_MORNINGSTAR = 625;
  public final static int WEAPON_FOCUS_QUARTERSTAFF = 626;
  public final static int WEAPON_FOCUS_RAPIER = 634;
  public final static int WEAPON_FOCUS_SCIMITAR = 635;
  public final static int WEAPON_FOCUS_SCYTHE = 650;
  public final static int WEAPON_FOCUS_SHORTBOW = 632;
  public final static int WEAPON_FOCUS_SHORTSPEAR = 627;
  public final static int WEAPON_FOCUS_SHORTSWORD = 633;
  public final static int WEAPON_FOCUS_SHURIKEN = 649;
  public final static int WEAPON_FOCUS_SICKLE = 628;
  public final static int WEAPON_FOCUS_SLING = 629;
  public final static int WEAPON_FOCUS_THROWINGAXE = 639;
  public final static int WEAPON_FOCUS_TRIDENT = 1076;
  public final static int WEAPON_FOCUS_TWOBLADEDSWORD = 655;
  public final static int WEAPON_FOCUS_UNARMED = 630;
  public final static int WEAPON_FOCUS_WARHAMMER = 645;
  public final static int WEAPON_FOCUS_WHIP = 997;
  public final static int WEAPON_MASTER = 983;
  public final static int WEAPON_SPECIALIZATION_BASTARDSWORD = 690;
  public final static int WEAPON_SPECIALIZATION_BATTLEAXE = 678;
  public final static int WEAPON_SPECIALIZATION_CLUB = 657;
  public final static int WEAPON_SPECIALIZATION_CREATURE = 694;
  public final static int WEAPON_SPECIALIZATION_DAGGER = 658;
  public final static int WEAPON_SPECIALIZATION_DART = 659;
  public final static int WEAPON_SPECIALIZATION_DIREMACE = 691;
  public final static int WEAPON_SPECIALIZATION_DOUBLEAXE = 692;
  public final static int WEAPON_SPECIALIZATION_DWAXE = 957;
  public final static int WEAPON_SPECIALIZATION_GREATAXE = 679;
  public final static int WEAPON_SPECIALIZATION_GREATSWORD = 675;
  public final static int WEAPON_SPECIALIZATION_HALBERD = 680;
  public final static int WEAPON_SPECIALIZATION_HANDAXE = 676;
  public final static int WEAPON_SPECIALIZATION_HEAVYCROSSBOW = 660;
  public final static int WEAPON_SPECIALIZATION_HEAVYFLAIL = 684;
  public final static int WEAPON_SPECIALIZATION_KAMA = 685;
  public final static int WEAPON_SPECIALIZATION_KATANA = 689;
  public final static int WEAPON_SPECIALIZATION_KUKRI = 686;
  public final static int WEAPON_SPECIALIZATION_LIGHTCROSSBOW = 661;
  public final static int WEAPON_SPECIALIZATION_LIGHTFLAIL = 682;
  public final static int WEAPON_SPECIALIZATION_LIGHTHAMMER = 681;
  public final static int WEAPON_SPECIALIZATION_LIGHTMACE = 662;
  public final static int WEAPON_SPECIALIZATION_LONGBOW = 669;
  public final static int WEAPON_SPECIALIZATION_LONGSWORD = 674;
  public final static int WEAPON_SPECIALIZATION_MORNINGSTAR = 663;
  public final static int WEAPON_SPECIALIZATION_QUARTERSTAFF = 664;
  public final static int WEAPON_SPECIALIZATION_RAPIER = 672;
  public final static int WEAPON_SPECIALIZATION_SCIMITAR = 673;
  public final static int WEAPON_SPECIALIZATION_SCYTHE = 688;
  public final static int WEAPON_SPECIALIZATION_SHORTBOW = 670;
  public final static int WEAPON_SPECIALIZATION_SHORTSPEAR = 665;
  public final static int WEAPON_SPECIALIZATION_SHORTSWORD = 671;
  public final static int WEAPON_SPECIALIZATION_SHURIKEN = 687;
  public final static int WEAPON_SPECIALIZATION_SICKLE = 666;
  public final static int WEAPON_SPECIALIZATION_SLING = 667;
  public final static int WEAPON_SPECIALIZATION_THROWINGAXE = 677;
  public final static int WEAPON_SPECIALIZATION_TRIDENT = 1077;
  public final static int WEAPON_SPECIALIZATION_TWOBLADEDSWORD = 693;
  public final static int WEAPON_SPECIALIZATION_UNARMED = 668;
  public final static int WEAPON_SPECIALIZATION_WARHAMMER = 683;
  public final static int WEAPON_SPECIALIZATION_WHIP = 998;
  public final static int WILD_SHAPE_DRAGON = 873;
  public final static int WILD_SHAPE_UNDEAD = 872;
  public final static int WILL = 695;
  public final static int WIZARD = 976;

  public static String nameOf(int value) {
    if (value == 977) return "FeatEpic.ARCANE_ARCHER";
    if (value == 490) return "FeatEpic.ARMOR_SKIN";
    if (value == 978) return "FeatEpic.ASSASSIN";
    if (value == 857) return "FeatEpic.AUTOMATIC_QUICKEN_1";
    if (value == 858) return "FeatEpic.AUTOMATIC_QUICKEN_2";
    if (value == 859) return "FeatEpic.AUTOMATIC_QUICKEN_3";
    if (value == 860) return "FeatEpic.AUTOMATIC_SILENT_SPELL_1";
    if (value == 861) return "FeatEpic.AUTOMATIC_SILENT_SPELL_2";
    if (value == 862) return "FeatEpic.AUTOMATIC_SILENT_SPELL_3";
    if (value == 863) return "FeatEpic.AUTOMATIC_STILL_SPELL_1";
    if (value == 864) return "FeatEpic.AUTOMATIC_STILL_SPELL_2";
    if (value == 865) return "FeatEpic.AUTOMATIC_STILL_SPELL_3";
    if (value == 855) return "FeatEpic.BANE_OF_ENEMIES";
    if (value == 967) return "FeatEpic.BARBARIAN";
    if (value == 1067) return "FeatEpic.BARBARIAN_DAMAGE_REDUCTION";
    if (value == 968) return "FeatEpic.BARD";
    if (value == 979) return "FeatEpic.BLACKGUARD";
    if (value == 491) return "FeatEpic.BLINDING_SPEED";
    if (value == 1001) return "FeatEpic.CHARACTER";
    if (value == 969) return "FeatEpic.CLERIC";
    if (value == 1061) return "FeatEpic.CONSTRUCT_SHAPE";
    if (value == 492) return "FeatEpic.DAMAGE_REDUCTION_3";
    if (value == 493) return "FeatEpic.DAMAGE_REDUCTION_6";
    if (value == 494) return "FeatEpic.DAMAGE_REDUCTION_9";
    if (value == 528) return "FeatEpic.DEVASTATING_CRITICAL_BASTARDSWORD";
    if (value == 516) return "FeatEpic.DEVASTATING_CRITICAL_BATTLEAXE";
    if (value == 495) return "FeatEpic.DEVASTATING_CRITICAL_CLUB";
    if (value == 532) return "FeatEpic.DEVASTATING_CRITICAL_CREATURE";
    if (value == 496) return "FeatEpic.DEVASTATING_CRITICAL_DAGGER";
    if (value == 497) return "FeatEpic.DEVASTATING_CRITICAL_DART";
    if (value == 529) return "FeatEpic.DEVASTATING_CRITICAL_DIREMACE";
    if (value == 530) return "FeatEpic.DEVASTATING_CRITICAL_DOUBLEAXE";
    if (value == 955) return "FeatEpic.DEVASTATING_CRITICAL_DWAXE";
    if (value == 517) return "FeatEpic.DEVASTATING_CRITICAL_GREATAXE";
    if (value == 513) return "FeatEpic.DEVASTATING_CRITICAL_GREATSWORD";
    if (value == 518) return "FeatEpic.DEVASTATING_CRITICAL_HALBERD";
    if (value == 514) return "FeatEpic.DEVASTATING_CRITICAL_HANDAXE";
    if (value == 498) return "FeatEpic.DEVASTATING_CRITICAL_HEAVYCROSSBOW";
    if (value == 522) return "FeatEpic.DEVASTATING_CRITICAL_HEAVYFLAIL";
    if (value == 523) return "FeatEpic.DEVASTATING_CRITICAL_KAMA";
    if (value == 527) return "FeatEpic.DEVASTATING_CRITICAL_KATANA";
    if (value == 524) return "FeatEpic.DEVASTATING_CRITICAL_KUKRI";
    if (value == 499) return "FeatEpic.DEVASTATING_CRITICAL_LIGHTCROSSBOW";
    if (value == 520) return "FeatEpic.DEVASTATING_CRITICAL_LIGHTFLAIL";
    if (value == 519) return "FeatEpic.DEVASTATING_CRITICAL_LIGHTHAMMER";
    if (value == 500) return "FeatEpic.DEVASTATING_CRITICAL_LIGHTMACE";
    if (value == 507) return "FeatEpic.DEVASTATING_CRITICAL_LONGBOW";
    if (value == 512) return "FeatEpic.DEVASTATING_CRITICAL_LONGSWORD";
    if (value == 501) return "FeatEpic.DEVASTATING_CRITICAL_MORNINGSTAR";
    if (value == 502) return "FeatEpic.DEVASTATING_CRITICAL_QUARTERSTAFF";
    if (value == 510) return "FeatEpic.DEVASTATING_CRITICAL_RAPIER";
    if (value == 511) return "FeatEpic.DEVASTATING_CRITICAL_SCIMITAR";
    if (value == 526) return "FeatEpic.DEVASTATING_CRITICAL_SCYTHE";
    if (value == 508) return "FeatEpic.DEVASTATING_CRITICAL_SHORTBOW";
    if (value == 503) return "FeatEpic.DEVASTATING_CRITICAL_SHORTSPEAR";
    if (value == 509) return "FeatEpic.DEVASTATING_CRITICAL_SHORTSWORD";
    if (value == 525) return "FeatEpic.DEVASTATING_CRITICAL_SHURIKEN";
    if (value == 504) return "FeatEpic.DEVASTATING_CRITICAL_SICKLE";
    if (value == 505) return "FeatEpic.DEVASTATING_CRITICAL_SLING";
    if (value == 515) return "FeatEpic.DEVASTATING_CRITICAL_THROWINGAXE";
    if (value == 1075) return "FeatEpic.DEVASTATING_CRITICAL_TRIDENT";
    if (value == 531) return "FeatEpic.DEVASTATING_CRITICAL_TWOBLADEDSWORD";
    if (value == 506) return "FeatEpic.DEVASTATING_CRITICAL_UNARMED";
    if (value == 521) return "FeatEpic.DEVASTATING_CRITICAL_WARHAMMER";
    if (value == 996) return "FeatEpic.DEVASTATING_CRITICAL_WHIP";
    if (value == 982) return "FeatEpic.DIVINE_CHAMPION";
    if (value == 856) return "FeatEpic.DODGE";
    if (value == 970) return "FeatEpic.DRUID";
    if (value == 1069) return "FeatEpic.DRUID_INFINITE_ELEMENTAL_SHAPE";
    if (value == 1068) return "FeatEpic.DRUID_INFINITE_WILDSHAPE";
    if (value == 985) return "FeatEpic.DWARVEN_DEFENDER";
    if (value == 543) return "FeatEpic.ENERGY_RESISTANCE_ACID_1";
    if (value == 552) return "FeatEpic.ENERGY_RESISTANCE_ACID_10";
    if (value == 544) return "FeatEpic.ENERGY_RESISTANCE_ACID_2";
    if (value == 545) return "FeatEpic.ENERGY_RESISTANCE_ACID_3";
    if (value == 546) return "FeatEpic.ENERGY_RESISTANCE_ACID_4";
    if (value == 547) return "FeatEpic.ENERGY_RESISTANCE_ACID_5";
    if (value == 548) return "FeatEpic.ENERGY_RESISTANCE_ACID_6";
    if (value == 549) return "FeatEpic.ENERGY_RESISTANCE_ACID_7";
    if (value == 550) return "FeatEpic.ENERGY_RESISTANCE_ACID_8";
    if (value == 551) return "FeatEpic.ENERGY_RESISTANCE_ACID_9";
    if (value == 533) return "FeatEpic.ENERGY_RESISTANCE_COLD_1";
    if (value == 542) return "FeatEpic.ENERGY_RESISTANCE_COLD_10";
    if (value == 534) return "FeatEpic.ENERGY_RESISTANCE_COLD_2";
    if (value == 535) return "FeatEpic.ENERGY_RESISTANCE_COLD_3";
    if (value == 536) return "FeatEpic.ENERGY_RESISTANCE_COLD_4";
    if (value == 537) return "FeatEpic.ENERGY_RESISTANCE_COLD_5";
    if (value == 538) return "FeatEpic.ENERGY_RESISTANCE_COLD_6";
    if (value == 539) return "FeatEpic.ENERGY_RESISTANCE_COLD_7";
    if (value == 540) return "FeatEpic.ENERGY_RESISTANCE_COLD_8";
    if (value == 541) return "FeatEpic.ENERGY_RESISTANCE_COLD_9";
    if (value == 563) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_1";
    if (value == 572) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_10";
    if (value == 564) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_2";
    if (value == 565) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_3";
    if (value == 566) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_4";
    if (value == 567) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_5";
    if (value == 568) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_6";
    if (value == 569) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_7";
    if (value == 570) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_8";
    if (value == 571) return "FeatEpic.ENERGY_RESISTANCE_ELECTRICAL_9";
    if (value == 553) return "FeatEpic.ENERGY_RESISTANCE_FIRE_1";
    if (value == 562) return "FeatEpic.ENERGY_RESISTANCE_FIRE_10";
    if (value == 554) return "FeatEpic.ENERGY_RESISTANCE_FIRE_2";
    if (value == 555) return "FeatEpic.ENERGY_RESISTANCE_FIRE_3";
    if (value == 556) return "FeatEpic.ENERGY_RESISTANCE_FIRE_4";
    if (value == 557) return "FeatEpic.ENERGY_RESISTANCE_FIRE_5";
    if (value == 558) return "FeatEpic.ENERGY_RESISTANCE_FIRE_6";
    if (value == 559) return "FeatEpic.ENERGY_RESISTANCE_FIRE_7";
    if (value == 560) return "FeatEpic.ENERGY_RESISTANCE_FIRE_8";
    if (value == 561) return "FeatEpic.ENERGY_RESISTANCE_FIRE_9";
    if (value == 573) return "FeatEpic.ENERGY_RESISTANCE_SONIC_1";
    if (value == 582) return "FeatEpic.ENERGY_RESISTANCE_SONIC_10";
    if (value == 574) return "FeatEpic.ENERGY_RESISTANCE_SONIC_2";
    if (value == 575) return "FeatEpic.ENERGY_RESISTANCE_SONIC_3";
    if (value == 576) return "FeatEpic.ENERGY_RESISTANCE_SONIC_4";
    if (value == 577) return "FeatEpic.ENERGY_RESISTANCE_SONIC_5";
    if (value == 578) return "FeatEpic.ENERGY_RESISTANCE_SONIC_6";
    if (value == 579) return "FeatEpic.ENERGY_RESISTANCE_SONIC_7";
    if (value == 580) return "FeatEpic.ENERGY_RESISTANCE_SONIC_8";
    if (value == 581) return "FeatEpic.ENERGY_RESISTANCE_SONIC_9";
    if (value == 1003) return "FeatEpic.EPIC_FIEND";
    if (value == 1002) return "FeatEpic.EPIC_SHADOWLORD";
    if (value == 966) return "FeatEpic.FIGHTER";
    if (value == 583) return "FeatEpic.FORTITUDE";
    if (value == 764) return "FeatEpic.GREAT_CHARISMA_1";
    if (value == 773) return "FeatEpic.GREAT_CHARISMA_10";
    if (value == 765) return "FeatEpic.GREAT_CHARISMA_2";
    if (value == 766) return "FeatEpic.GREAT_CHARISMA_3";
    if (value == 767) return "FeatEpic.GREAT_CHARISMA_4";
    if (value == 768) return "FeatEpic.GREAT_CHARISMA_5";
    if (value == 769) return "FeatEpic.GREAT_CHARISMA_6";
    if (value == 770) return "FeatEpic.GREAT_CHARISMA_7";
    if (value == 771) return "FeatEpic.GREAT_CHARISMA_8";
    if (value == 772) return "FeatEpic.GREAT_CHARISMA_9";
    if (value == 774) return "FeatEpic.GREAT_CONSTITUTION_1";
    if (value == 783) return "FeatEpic.GREAT_CONSTITUTION_10";
    if (value == 775) return "FeatEpic.GREAT_CONSTITUTION_2";
    if (value == 776) return "FeatEpic.GREAT_CONSTITUTION_3";
    if (value == 777) return "FeatEpic.GREAT_CONSTITUTION_4";
    if (value == 778) return "FeatEpic.GREAT_CONSTITUTION_5";
    if (value == 779) return "FeatEpic.GREAT_CONSTITUTION_6";
    if (value == 780) return "FeatEpic.GREAT_CONSTITUTION_7";
    if (value == 781) return "FeatEpic.GREAT_CONSTITUTION_8";
    if (value == 782) return "FeatEpic.GREAT_CONSTITUTION_9";
    if (value == 784) return "FeatEpic.GREAT_DEXTERITY_1";
    if (value == 793) return "FeatEpic.GREAT_DEXTERITY_10";
    if (value == 785) return "FeatEpic.GREAT_DEXTERITY_2";
    if (value == 786) return "FeatEpic.GREAT_DEXTERITY_3";
    if (value == 787) return "FeatEpic.GREAT_DEXTERITY_4";
    if (value == 788) return "FeatEpic.GREAT_DEXTERITY_5";
    if (value == 789) return "FeatEpic.GREAT_DEXTERITY_6";
    if (value == 790) return "FeatEpic.GREAT_DEXTERITY_7";
    if (value == 791) return "FeatEpic.GREAT_DEXTERITY_8";
    if (value == 792) return "FeatEpic.GREAT_DEXTERITY_9";
    if (value == 794) return "FeatEpic.GREAT_INTELLIGENCE_1";
    if (value == 803) return "FeatEpic.GREAT_INTELLIGENCE_10";
    if (value == 795) return "FeatEpic.GREAT_INTELLIGENCE_2";
    if (value == 796) return "FeatEpic.GREAT_INTELLIGENCE_3";
    if (value == 797) return "FeatEpic.GREAT_INTELLIGENCE_4";
    if (value == 798) return "FeatEpic.GREAT_INTELLIGENCE_5";
    if (value == 799) return "FeatEpic.GREAT_INTELLIGENCE_6";
    if (value == 800) return "FeatEpic.GREAT_INTELLIGENCE_7";
    if (value == 801) return "FeatEpic.GREAT_INTELLIGENCE_8";
    if (value == 802) return "FeatEpic.GREAT_INTELLIGENCE_9";
    if (value == 824) return "FeatEpic.GREAT_SMITING_1";
    if (value == 833) return "FeatEpic.GREAT_SMITING_10";
    if (value == 825) return "FeatEpic.GREAT_SMITING_2";
    if (value == 826) return "FeatEpic.GREAT_SMITING_3";
    if (value == 827) return "FeatEpic.GREAT_SMITING_4";
    if (value == 828) return "FeatEpic.GREAT_SMITING_5";
    if (value == 829) return "FeatEpic.GREAT_SMITING_6";
    if (value == 830) return "FeatEpic.GREAT_SMITING_7";
    if (value == 831) return "FeatEpic.GREAT_SMITING_8";
    if (value == 832) return "FeatEpic.GREAT_SMITING_9";
    if (value == 814) return "FeatEpic.GREAT_STRENGTH_1";
    if (value == 823) return "FeatEpic.GREAT_STRENGTH_10";
    if (value == 815) return "FeatEpic.GREAT_STRENGTH_2";
    if (value == 816) return "FeatEpic.GREAT_STRENGTH_3";
    if (value == 817) return "FeatEpic.GREAT_STRENGTH_4";
    if (value == 818) return "FeatEpic.GREAT_STRENGTH_5";
    if (value == 819) return "FeatEpic.GREAT_STRENGTH_6";
    if (value == 820) return "FeatEpic.GREAT_STRENGTH_7";
    if (value == 821) return "FeatEpic.GREAT_STRENGTH_8";
    if (value == 822) return "FeatEpic.GREAT_STRENGTH_9";
    if (value == 804) return "FeatEpic.GREAT_WISDOM_1";
    if (value == 813) return "FeatEpic.GREAT_WISDOM_10";
    if (value == 805) return "FeatEpic.GREAT_WISDOM_2";
    if (value == 806) return "FeatEpic.GREAT_WISDOM_3";
    if (value == 807) return "FeatEpic.GREAT_WISDOM_4";
    if (value == 808) return "FeatEpic.GREAT_WISDOM_5";
    if (value == 809) return "FeatEpic.GREAT_WISDOM_6";
    if (value == 810) return "FeatEpic.GREAT_WISDOM_7";
    if (value == 811) return "FeatEpic.GREAT_WISDOM_8";
    if (value == 812) return "FeatEpic.GREAT_WISDOM_9";
    if (value == 981) return "FeatEpic.HARPER_SCOUT";
    if (value == 696) return "FeatEpic.IMPROVED_COMBAT_CASTING";
    if (value == 697) return "FeatEpic.IMPROVED_KI_STRIKE_4";
    if (value == 698) return "FeatEpic.IMPROVED_KI_STRIKE_5";
    if (value == 834) return "FeatEpic.IMPROVED_SNEAK_ATTACK_1";
    if (value == 843) return "FeatEpic.IMPROVED_SNEAK_ATTACK_10";
    if (value == 835) return "FeatEpic.IMPROVED_SNEAK_ATTACK_2";
    if (value == 836) return "FeatEpic.IMPROVED_SNEAK_ATTACK_3";
    if (value == 837) return "FeatEpic.IMPROVED_SNEAK_ATTACK_4";
    if (value == 838) return "FeatEpic.IMPROVED_SNEAK_ATTACK_5";
    if (value == 839) return "FeatEpic.IMPROVED_SNEAK_ATTACK_6";
    if (value == 840) return "FeatEpic.IMPROVED_SNEAK_ATTACK_7";
    if (value == 841) return "FeatEpic.IMPROVED_SNEAK_ATTACK_8";
    if (value == 842) return "FeatEpic.IMPROVED_SNEAK_ATTACK_9";
    if (value == 699) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_1";
    if (value == 708) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_10";
    if (value == 700) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_2";
    if (value == 701) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_3";
    if (value == 702) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_4";
    if (value == 703) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_5";
    if (value == 704) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_6";
    if (value == 705) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_7";
    if (value == 706) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_8";
    if (value == 707) return "FeatEpic.IMPROVED_SPELL_RESISTANCE_9";
    if (value == 844) return "FeatEpic.IMPROVED_STUNNING_FIST_1";
    if (value == 853) return "FeatEpic.IMPROVED_STUNNING_FIST_10";
    if (value == 845) return "FeatEpic.IMPROVED_STUNNING_FIST_2";
    if (value == 846) return "FeatEpic.IMPROVED_STUNNING_FIST_3";
    if (value == 847) return "FeatEpic.IMPROVED_STUNNING_FIST_4";
    if (value == 848) return "FeatEpic.IMPROVED_STUNNING_FIST_5";
    if (value == 849) return "FeatEpic.IMPROVED_STUNNING_FIST_6";
    if (value == 850) return "FeatEpic.IMPROVED_STUNNING_FIST_7";
    if (value == 851) return "FeatEpic.IMPROVED_STUNNING_FIST_8";
    if (value == 852) return "FeatEpic.IMPROVED_STUNNING_FIST_9";
    if (value == 870) return "FeatEpic.LASTING_INSPIRATION";
    if (value == 971) return "FeatEpic.MONK";
    if (value == 1060) return "FeatEpic.OUTSIDER_SHAPE";
    if (value == 742) return "FeatEpic.OVERWHELMING_CRITICAL_BASTARDSWORD";
    if (value == 730) return "FeatEpic.OVERWHELMING_CRITICAL_BATTLEAXE";
    if (value == 709) return "FeatEpic.OVERWHELMING_CRITICAL_CLUB";
    if (value == 746) return "FeatEpic.OVERWHELMING_CRITICAL_CREATURE";
    if (value == 710) return "FeatEpic.OVERWHELMING_CRITICAL_DAGGER";
    if (value == 711) return "FeatEpic.OVERWHELMING_CRITICAL_DART";
    if (value == 743) return "FeatEpic.OVERWHELMING_CRITICAL_DIREMACE";
    if (value == 744) return "FeatEpic.OVERWHELMING_CRITICAL_DOUBLEAXE";
    if (value == 958) return "FeatEpic.OVERWHELMING_CRITICAL_DWAXE";
    if (value == 731) return "FeatEpic.OVERWHELMING_CRITICAL_GREATAXE";
    if (value == 727) return "FeatEpic.OVERWHELMING_CRITICAL_GREATSWORD";
    if (value == 732) return "FeatEpic.OVERWHELMING_CRITICAL_HALBERD";
    if (value == 728) return "FeatEpic.OVERWHELMING_CRITICAL_HANDAXE";
    if (value == 712) return "FeatEpic.OVERWHELMING_CRITICAL_HEAVYCROSSBOW";
    if (value == 736) return "FeatEpic.OVERWHELMING_CRITICAL_HEAVYFLAIL";
    if (value == 737) return "FeatEpic.OVERWHELMING_CRITICAL_KAMA";
    if (value == 741) return "FeatEpic.OVERWHELMING_CRITICAL_KATANA";
    if (value == 738) return "FeatEpic.OVERWHELMING_CRITICAL_KUKRI";
    if (value == 713) return "FeatEpic.OVERWHELMING_CRITICAL_LIGHTCROSSBOW";
    if (value == 734) return "FeatEpic.OVERWHELMING_CRITICAL_LIGHTFLAIL";
    if (value == 733) return "FeatEpic.OVERWHELMING_CRITICAL_LIGHTHAMMER";
    if (value == 714) return "FeatEpic.OVERWHELMING_CRITICAL_LIGHTMACE";
    if (value == 721) return "FeatEpic.OVERWHELMING_CRITICAL_LONGBOW";
    if (value == 726) return "FeatEpic.OVERWHELMING_CRITICAL_LONGSWORD";
    if (value == 715) return "FeatEpic.OVERWHELMING_CRITICAL_MORNINGSTAR";
    if (value == 716) return "FeatEpic.OVERWHELMING_CRITICAL_QUARTERSTAFF";
    if (value == 724) return "FeatEpic.OVERWHELMING_CRITICAL_RAPIER";
    if (value == 725) return "FeatEpic.OVERWHELMING_CRITICAL_SCIMITAR";
    if (value == 740) return "FeatEpic.OVERWHELMING_CRITICAL_SCYTHE";
    if (value == 722) return "FeatEpic.OVERWHELMING_CRITICAL_SHORTBOW";
    if (value == 717) return "FeatEpic.OVERWHELMING_CRITICAL_SHORTSPEAR";
    if (value == 723) return "FeatEpic.OVERWHELMING_CRITICAL_SHORTSWORD";
    if (value == 739) return "FeatEpic.OVERWHELMING_CRITICAL_SHURIKEN";
    if (value == 718) return "FeatEpic.OVERWHELMING_CRITICAL_SICKLE";
    if (value == 719) return "FeatEpic.OVERWHELMING_CRITICAL_SLING";
    if (value == 729) return "FeatEpic.OVERWHELMING_CRITICAL_THROWINGAXE";
    if (value == 1078) return "FeatEpic.OVERWHELMING_CRITICAL_TRIDENT";
    if (value == 745) return "FeatEpic.OVERWHELMING_CRITICAL_TWOBLADEDSWORD";
    if (value == 720) return "FeatEpic.OVERWHELMING_CRITICAL_UNARMED";
    if (value == 735) return "FeatEpic.OVERWHELMING_CRITICAL_WARHAMMER";
    if (value == 999) return "FeatEpic.OVERWHELMING_CRITICAL_WHIP";
    if (value == 972) return "FeatEpic.PALADIN";
    if (value == 984) return "FeatEpic.PALE_MASTER";
    if (value == 747) return "FeatEpic.PERFECT_HEALTH";
    if (value == 584) return "FeatEpic.PROWESS";
    if (value == 973) return "FeatEpic.RANGER";
    if (value == 987) return "FeatEpic.RED_DRAGON_DISC";
    if (value == 585) return "FeatEpic.REFLEXES";
    if (value == 586) return "FeatEpic.REPUTATION";
    if (value == 974) return "FeatEpic.ROGUE";
    if (value == 748) return "FeatEpic.SELF_CONCEALMENT_10";
    if (value == 749) return "FeatEpic.SELF_CONCEALMENT_20";
    if (value == 750) return "FeatEpic.SELF_CONCEALMENT_30";
    if (value == 751) return "FeatEpic.SELF_CONCEALMENT_40";
    if (value == 752) return "FeatEpic.SELF_CONCEALMENT_50";
    if (value == 980) return "FeatEpic.SHADOWDANCER";
    if (value == 986) return "FeatEpic.SHIFTER";
    if (value == 1066) return "FeatEpic.SHIFTER_INFINITE_HUMANOID_SHAPE";
    if (value == 1062) return "FeatEpic.SHIFTER_INFINITE_WILDSHAPE_1";
    if (value == 1063) return "FeatEpic.SHIFTER_INFINITE_WILDSHAPE_2";
    if (value == 1064) return "FeatEpic.SHIFTER_INFINITE_WILDSHAPE_3";
    if (value == 1065) return "FeatEpic.SHIFTER_INFINITE_WILDSHAPE_4";
    if (value == 587) return "FeatEpic.SKILL_FOCUS_ANIMAL_EMPATHY";
    if (value == 588) return "FeatEpic.SKILL_FOCUS_APPRAISE";
    if (value == 917) return "FeatEpic.SKILL_FOCUS_BLUFF";
    if (value == 589) return "FeatEpic.SKILL_FOCUS_CONCENTRATION";
    if (value == 913) return "FeatEpic.SKILL_FOCUS_CRAFT_ARMOR";
    if (value == 590) return "FeatEpic.SKILL_FOCUS_CRAFT_TRAP";
    if (value == 914) return "FeatEpic.SKILL_FOCUS_CRAFT_WEAPON";
    if (value == 591) return "FeatEpic.SKILL_FOCUS_DISABLETRAP";
    if (value == 592) return "FeatEpic.SKILL_FOCUS_DISCIPLINE";
    if (value == 593) return "FeatEpic.SKILL_FOCUS_HEAL";
    if (value == 594) return "FeatEpic.SKILL_FOCUS_HIDE";
    if (value == 918) return "FeatEpic.SKILL_FOCUS_INTIMIDATE";
    if (value == 595) return "FeatEpic.SKILL_FOCUS_LISTEN";
    if (value == 596) return "FeatEpic.SKILL_FOCUS_LORE";
    if (value == 597) return "FeatEpic.SKILL_FOCUS_MOVESILENTLY";
    if (value == 598) return "FeatEpic.SKILL_FOCUS_OPENLOCK";
    if (value == 599) return "FeatEpic.SKILL_FOCUS_PARRY";
    if (value == 600) return "FeatEpic.SKILL_FOCUS_PERFORM";
    if (value == 601) return "FeatEpic.SKILL_FOCUS_PERSUADE";
    if (value == 602) return "FeatEpic.SKILL_FOCUS_PICKPOCKET";
    if (value == 603) return "FeatEpic.SKILL_FOCUS_SEARCH";
    if (value == 604) return "FeatEpic.SKILL_FOCUS_SETTRAP";
    if (value == 605) return "FeatEpic.SKILL_FOCUS_SPELLCRAFT";
    if (value == 606) return "FeatEpic.SKILL_FOCUS_SPOT";
    if (value == 607) return "FeatEpic.SKILL_FOCUS_TAUNT";
    if (value == 608) return "FeatEpic.SKILL_FOCUS_TUMBLE";
    if (value == 609) return "FeatEpic.SKILL_FOCUS_USEMAGICDEVICE";
    if (value == 975) return "FeatEpic.SORCERER";
    if (value == 875) return "FeatEpic.SPELL_DRAGON_KNIGHT";
    if (value == 990) return "FeatEpic.SPELL_EPIC_WARDING";
    if (value == 610) return "FeatEpic.SPELL_FOCUS_ABJURATION";
    if (value == 611) return "FeatEpic.SPELL_FOCUS_CONJURATION";
    if (value == 612) return "FeatEpic.SPELL_FOCUS_DIVINATION";
    if (value == 613) return "FeatEpic.SPELL_FOCUS_ENCHANTMENT";
    if (value == 614) return "FeatEpic.SPELL_FOCUS_EVOCATION";
    if (value == 615) return "FeatEpic.SPELL_FOCUS_ILLUSION";
    if (value == 616) return "FeatEpic.SPELL_FOCUS_NECROMANCY";
    if (value == 617) return "FeatEpic.SPELL_FOCUS_TRANSMUTATION";
    if (value == 876) return "FeatEpic.SPELL_HELLBALL";
    if (value == 877) return "FeatEpic.SPELL_MAGE_ARMOUR";
    if (value == 874) return "FeatEpic.SPELL_MUMMY_DUST";
    if (value == 618) return "FeatEpic.SPELL_PENETRATION";
    if (value == 878) return "FeatEpic.SPELL_RUIN";
    if (value == 753) return "FeatEpic.SUPERIOR_INITIATIVE";
    if (value == 1071) return "FeatEpic.SUPERIOR_WEAPON_FOCUS";
    if (value == 989) return "FeatEpic.TERRIFYING_RAGE";
    if (value == 988) return "FeatEpic.THUNDERING_RAGE";
    if (value == 754) return "FeatEpic.TOUGHNESS_1";
    if (value == 763) return "FeatEpic.TOUGHNESS_10";
    if (value == 755) return "FeatEpic.TOUGHNESS_2";
    if (value == 756) return "FeatEpic.TOUGHNESS_3";
    if (value == 757) return "FeatEpic.TOUGHNESS_4";
    if (value == 758) return "FeatEpic.TOUGHNESS_5";
    if (value == 759) return "FeatEpic.TOUGHNESS_6";
    if (value == 760) return "FeatEpic.TOUGHNESS_7";
    if (value == 761) return "FeatEpic.TOUGHNESS_8";
    if (value == 762) return "FeatEpic.TOUGHNESS_9";
    if (value == 652) return "FeatEpic.WEAPON_FOCUS_BASTARDSWORD";
    if (value == 640) return "FeatEpic.WEAPON_FOCUS_BATTLEAXE";
    if (value == 619) return "FeatEpic.WEAPON_FOCUS_CLUB";
    if (value == 656) return "FeatEpic.WEAPON_FOCUS_CREATURE";
    if (value == 620) return "FeatEpic.WEAPON_FOCUS_DAGGER";
    if (value == 621) return "FeatEpic.WEAPON_FOCUS_DART";
    if (value == 653) return "FeatEpic.WEAPON_FOCUS_DIREMACE";
    if (value == 654) return "FeatEpic.WEAPON_FOCUS_DOUBLEAXE";
    if (value == 956) return "FeatEpic.WEAPON_FOCUS_DWAXE";
    if (value == 641) return "FeatEpic.WEAPON_FOCUS_GREATAXE";
    if (value == 637) return "FeatEpic.WEAPON_FOCUS_GREATSWORD";
    if (value == 642) return "FeatEpic.WEAPON_FOCUS_HALBERD";
    if (value == 638) return "FeatEpic.WEAPON_FOCUS_HANDAXE";
    if (value == 622) return "FeatEpic.WEAPON_FOCUS_HEAVYCROSSBOW";
    if (value == 646) return "FeatEpic.WEAPON_FOCUS_HEAVYFLAIL";
    if (value == 647) return "FeatEpic.WEAPON_FOCUS_KAMA";
    if (value == 651) return "FeatEpic.WEAPON_FOCUS_KATANA";
    if (value == 648) return "FeatEpic.WEAPON_FOCUS_KUKRI";
    if (value == 623) return "FeatEpic.WEAPON_FOCUS_LIGHTCROSSBOW";
    if (value == 644) return "FeatEpic.WEAPON_FOCUS_LIGHTFLAIL";
    if (value == 643) return "FeatEpic.WEAPON_FOCUS_LIGHTHAMMER";
    if (value == 624) return "FeatEpic.WEAPON_FOCUS_LIGHTMACE";
    if (value == 631) return "FeatEpic.WEAPON_FOCUS_LONGBOW";
    if (value == 636) return "FeatEpic.WEAPON_FOCUS_LONGSWORD";
    if (value == 625) return "FeatEpic.WEAPON_FOCUS_MORNINGSTAR";
    if (value == 626) return "FeatEpic.WEAPON_FOCUS_QUARTERSTAFF";
    if (value == 634) return "FeatEpic.WEAPON_FOCUS_RAPIER";
    if (value == 635) return "FeatEpic.WEAPON_FOCUS_SCIMITAR";
    if (value == 650) return "FeatEpic.WEAPON_FOCUS_SCYTHE";
    if (value == 632) return "FeatEpic.WEAPON_FOCUS_SHORTBOW";
    if (value == 627) return "FeatEpic.WEAPON_FOCUS_SHORTSPEAR";
    if (value == 633) return "FeatEpic.WEAPON_FOCUS_SHORTSWORD";
    if (value == 649) return "FeatEpic.WEAPON_FOCUS_SHURIKEN";
    if (value == 628) return "FeatEpic.WEAPON_FOCUS_SICKLE";
    if (value == 629) return "FeatEpic.WEAPON_FOCUS_SLING";
    if (value == 639) return "FeatEpic.WEAPON_FOCUS_THROWINGAXE";
    if (value == 1076) return "FeatEpic.WEAPON_FOCUS_TRIDENT";
    if (value == 655) return "FeatEpic.WEAPON_FOCUS_TWOBLADEDSWORD";
    if (value == 630) return "FeatEpic.WEAPON_FOCUS_UNARMED";
    if (value == 645) return "FeatEpic.WEAPON_FOCUS_WARHAMMER";
    if (value == 997) return "FeatEpic.WEAPON_FOCUS_WHIP";
    if (value == 983) return "FeatEpic.WEAPON_MASTER";
    if (value == 690) return "FeatEpic.WEAPON_SPECIALIZATION_BASTARDSWORD";
    if (value == 678) return "FeatEpic.WEAPON_SPECIALIZATION_BATTLEAXE";
    if (value == 657) return "FeatEpic.WEAPON_SPECIALIZATION_CLUB";
    if (value == 694) return "FeatEpic.WEAPON_SPECIALIZATION_CREATURE";
    if (value == 658) return "FeatEpic.WEAPON_SPECIALIZATION_DAGGER";
    if (value == 659) return "FeatEpic.WEAPON_SPECIALIZATION_DART";
    if (value == 691) return "FeatEpic.WEAPON_SPECIALIZATION_DIREMACE";
    if (value == 692) return "FeatEpic.WEAPON_SPECIALIZATION_DOUBLEAXE";
    if (value == 957) return "FeatEpic.WEAPON_SPECIALIZATION_DWAXE";
    if (value == 679) return "FeatEpic.WEAPON_SPECIALIZATION_GREATAXE";
    if (value == 675) return "FeatEpic.WEAPON_SPECIALIZATION_GREATSWORD";
    if (value == 680) return "FeatEpic.WEAPON_SPECIALIZATION_HALBERD";
    if (value == 676) return "FeatEpic.WEAPON_SPECIALIZATION_HANDAXE";
    if (value == 660) return "FeatEpic.WEAPON_SPECIALIZATION_HEAVYCROSSBOW";
    if (value == 684) return "FeatEpic.WEAPON_SPECIALIZATION_HEAVYFLAIL";
    if (value == 685) return "FeatEpic.WEAPON_SPECIALIZATION_KAMA";
    if (value == 689) return "FeatEpic.WEAPON_SPECIALIZATION_KATANA";
    if (value == 686) return "FeatEpic.WEAPON_SPECIALIZATION_KUKRI";
    if (value == 661) return "FeatEpic.WEAPON_SPECIALIZATION_LIGHTCROSSBOW";
    if (value == 682) return "FeatEpic.WEAPON_SPECIALIZATION_LIGHTFLAIL";
    if (value == 681) return "FeatEpic.WEAPON_SPECIALIZATION_LIGHTHAMMER";
    if (value == 662) return "FeatEpic.WEAPON_SPECIALIZATION_LIGHTMACE";
    if (value == 669) return "FeatEpic.WEAPON_SPECIALIZATION_LONGBOW";
    if (value == 674) return "FeatEpic.WEAPON_SPECIALIZATION_LONGSWORD";
    if (value == 663) return "FeatEpic.WEAPON_SPECIALIZATION_MORNINGSTAR";
    if (value == 664) return "FeatEpic.WEAPON_SPECIALIZATION_QUARTERSTAFF";
    if (value == 672) return "FeatEpic.WEAPON_SPECIALIZATION_RAPIER";
    if (value == 673) return "FeatEpic.WEAPON_SPECIALIZATION_SCIMITAR";
    if (value == 688) return "FeatEpic.WEAPON_SPECIALIZATION_SCYTHE";
    if (value == 670) return "FeatEpic.WEAPON_SPECIALIZATION_SHORTBOW";
    if (value == 665) return "FeatEpic.WEAPON_SPECIALIZATION_SHORTSPEAR";
    if (value == 671) return "FeatEpic.WEAPON_SPECIALIZATION_SHORTSWORD";
    if (value == 687) return "FeatEpic.WEAPON_SPECIALIZATION_SHURIKEN";
    if (value == 666) return "FeatEpic.WEAPON_SPECIALIZATION_SICKLE";
    if (value == 667) return "FeatEpic.WEAPON_SPECIALIZATION_SLING";
    if (value == 677) return "FeatEpic.WEAPON_SPECIALIZATION_THROWINGAXE";
    if (value == 1077) return "FeatEpic.WEAPON_SPECIALIZATION_TRIDENT";
    if (value == 693) return "FeatEpic.WEAPON_SPECIALIZATION_TWOBLADEDSWORD";
    if (value == 668) return "FeatEpic.WEAPON_SPECIALIZATION_UNARMED";
    if (value == 683) return "FeatEpic.WEAPON_SPECIALIZATION_WARHAMMER";
    if (value == 998) return "FeatEpic.WEAPON_SPECIALIZATION_WHIP";
    if (value == 873) return "FeatEpic.WILD_SHAPE_DRAGON";
    if (value == 872) return "FeatEpic.WILD_SHAPE_UNDEAD";
    if (value == 695) return "FeatEpic.WILL";
    if (value == 976) return "FeatEpic.WIZARD";
    return "FeatEpic.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "FeatEpic.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "FeatEpic.(not found: " + value + ")";
  }
}
