package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "FEAT_WEAPON".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class FeatWeapon {
  private FeatWeapon() {}

  public final static int FINESSE = 42;
  public final static int FOCUS_BASTARD_SWORD = 123;
  public final static int FOCUS_BATTLE_AXE = 110;
  public final static int FOCUS_CLUB = 43;
  public final static int FOCUS_CREATURE = 291;
  public final static int FOCUS_DAGGER = 90;
  public final static int FOCUS_DART = 91;
  public final static int FOCUS_DIRE_MACE = 125;
  public final static int FOCUS_DOUBLE_AXE = 126;
  public final static int FOCUS_DWAXE = 952;
  public final static int FOCUS_GREAT_AXE = 111;
  public final static int FOCUS_GREAT_SWORD = 107;
  public final static int FOCUS_HALBERD = 112;
  public final static int FOCUS_HAND_AXE = 108;
  public final static int FOCUS_HEAVY_CROSSBOW = 92;
  public final static int FOCUS_HEAVY_FLAIL = 116;
  public final static int FOCUS_KAMA = 117;
  public final static int FOCUS_KATANA = 122;
  public final static int FOCUS_KUKRI = 118;
  public final static int FOCUS_LIGHT_CROSSBOW = 93;
  public final static int FOCUS_LIGHT_FLAIL = 114;
  public final static int FOCUS_LIGHT_HAMMER = 113;
  public final static int FOCUS_LIGHT_MACE = 94;
  public final static int FOCUS_LONGBOW = 101;
  public final static int FOCUS_LONG_SWORD = 106;
  public final static int FOCUS_MORNING_STAR = 95;
  public final static int FOCUS_RAPIER = 104;
  public final static int FOCUS_SCIMITAR = 105;
  public final static int FOCUS_SCYTHE = 121;
  public final static int FOCUS_SHORTBOW = 102;
  public final static int FOCUS_SHORT_SWORD = 103;
  public final static int FOCUS_SHURIKEN = 120;
  public final static int FOCUS_SICKLE = 98;
  public final static int FOCUS_SLING = 99;
  public final static int FOCUS_SPEAR = 97;
  public final static int FOCUS_STAFF = 96;
  public final static int FOCUS_THROWING_AXE = 109;
  public final static int FOCUS_TRIDENT = 1072;
  public final static int FOCUS_TWO_BLADED_SWORD = 127;
  public final static int FOCUS_UNARMED_STRIKE = 100;
  public final static int FOCUS_WAR_HAMMER = 115;
  public final static int FOCUS_WHIP = 993;
  public final static int OF_CHOICE_BASTARDSWORD = 940;
  public final static int OF_CHOICE_BATTLEAXE = 931;
  public final static int OF_CHOICE_CLUB = 919;
  public final static int OF_CHOICE_DAGGER = 920;
  public final static int OF_CHOICE_DIREMACE = 941;
  public final static int OF_CHOICE_DOUBLEAXE = 942;
  public final static int OF_CHOICE_DWAXE = 959;
  public final static int OF_CHOICE_GREATAXE = 932;
  public final static int OF_CHOICE_GREATSWORD = 929;
  public final static int OF_CHOICE_HALBERD = 933;
  public final static int OF_CHOICE_HANDAXE = 930;
  public final static int OF_CHOICE_HEAVYFLAIL = 937;
  public final static int OF_CHOICE_KAMA = 880;
  public final static int OF_CHOICE_KATANA = 939;
  public final static int OF_CHOICE_KUKRI = 881;
  public final static int OF_CHOICE_LIGHTFLAIL = 935;
  public final static int OF_CHOICE_LIGHTHAMMER = 934;
  public final static int OF_CHOICE_LIGHTMACE = 921;
  public final static int OF_CHOICE_LONGSWORD = 928;
  public final static int OF_CHOICE_MORNINGSTAR = 922;
  public final static int OF_CHOICE_QUARTERSTAFF = 923;
  public final static int OF_CHOICE_RAPIER = 926;
  public final static int OF_CHOICE_SCIMITAR = 927;
  public final static int OF_CHOICE_SCYTHE = 938;
  public final static int OF_CHOICE_SHORTSPEAR = 924;
  public final static int OF_CHOICE_SHORTSWORD = 925;
  public final static int OF_CHOICE_SICKLE = 879;
  public final static int OF_CHOICE_TRIDENT = 1079;
  public final static int OF_CHOICE_TWOBLADEDSWORD = 943;
  public final static int OF_CHOICE_WARHAMMER = 936;
  public final static int OF_CHOICE_WHIP = 1000;
  public final static int PROFICIENCY_CREATURE = 289;
  public final static int PROFICIENCY_DRUID = 48;
  public final static int PROFICIENCY_ELF = 256;
  public final static int PROFICIENCY_EXOTIC = 44;
  public final static int PROFICIENCY_MARTIAL = 45;
  public final static int PROFICIENCY_MONK = 49;
  public final static int PROFICIENCY_ROGUE = 50;
  public final static int PROFICIENCY_SIMPLE = 46;
  public final static int PROFICIENCY_WIZARD = 51;
  public final static int SPECIALIZATION_BASTARD_SWORD = 161;
  public final static int SPECIALIZATION_BATTLE_AXE = 148;
  public final static int SPECIALIZATION_CLUB = 47;
  public final static int SPECIALIZATION_CREATURE = 290;
  public final static int SPECIALIZATION_DAGGER = 128;
  public final static int SPECIALIZATION_DART = 129;
  public final static int SPECIALIZATION_DIRE_MACE = 163;
  public final static int SPECIALIZATION_DOUBLE_AXE = 164;
  public final static int SPECIALIZATION_DWAXE = 953;
  public final static int SPECIALIZATION_GREAT_AXE = 149;
  public final static int SPECIALIZATION_GREAT_SWORD = 145;
  public final static int SPECIALIZATION_HALBERD = 150;
  public final static int SPECIALIZATION_HAND_AXE = 146;
  public final static int SPECIALIZATION_HEAVY_CROSSBOW = 130;
  public final static int SPECIALIZATION_HEAVY_FLAIL = 154;
  public final static int SPECIALIZATION_KAMA = 155;
  public final static int SPECIALIZATION_KATANA = 160;
  public final static int SPECIALIZATION_KUKRI = 156;
  public final static int SPECIALIZATION_LIGHT_CROSSBOW = 131;
  public final static int SPECIALIZATION_LIGHT_FLAIL = 152;
  public final static int SPECIALIZATION_LIGHT_HAMMER = 151;
  public final static int SPECIALIZATION_LIGHT_MACE = 132;
  public final static int SPECIALIZATION_LONGBOW = 139;
  public final static int SPECIALIZATION_LONG_SWORD = 144;
  public final static int SPECIALIZATION_MORNING_STAR = 133;
  public final static int SPECIALIZATION_RAPIER = 142;
  public final static int SPECIALIZATION_SCIMITAR = 143;
  public final static int SPECIALIZATION_SCYTHE = 159;
  public final static int SPECIALIZATION_SHORTBOW = 140;
  public final static int SPECIALIZATION_SHORT_SWORD = 141;
  public final static int SPECIALIZATION_SHURIKEN = 158;
  public final static int SPECIALIZATION_SICKLE = 136;
  public final static int SPECIALIZATION_SLING = 137;
  public final static int SPECIALIZATION_SPEAR = 135;
  public final static int SPECIALIZATION_STAFF = 134;
  public final static int SPECIALIZATION_THROWING_AXE = 147;
  public final static int SPECIALIZATION_TRIDENT = 1073;
  public final static int SPECIALIZATION_TWO_BLADED_SWORD = 165;
  public final static int SPECIALIZATION_UNARMED_STRIKE = 138;
  public final static int SPECIALIZATION_WAR_HAMMER = 153;
  public final static int SPECIALIZATION_WHIP = 994;

  public static String nameOf(int value) {
    if (value == 42) return "FeatWeapon.FINESSE";
    if (value == 123) return "FeatWeapon.FOCUS_BASTARD_SWORD";
    if (value == 110) return "FeatWeapon.FOCUS_BATTLE_AXE";
    if (value == 43) return "FeatWeapon.FOCUS_CLUB";
    if (value == 291) return "FeatWeapon.FOCUS_CREATURE";
    if (value == 90) return "FeatWeapon.FOCUS_DAGGER";
    if (value == 91) return "FeatWeapon.FOCUS_DART";
    if (value == 125) return "FeatWeapon.FOCUS_DIRE_MACE";
    if (value == 126) return "FeatWeapon.FOCUS_DOUBLE_AXE";
    if (value == 952) return "FeatWeapon.FOCUS_DWAXE";
    if (value == 111) return "FeatWeapon.FOCUS_GREAT_AXE";
    if (value == 107) return "FeatWeapon.FOCUS_GREAT_SWORD";
    if (value == 112) return "FeatWeapon.FOCUS_HALBERD";
    if (value == 108) return "FeatWeapon.FOCUS_HAND_AXE";
    if (value == 92) return "FeatWeapon.FOCUS_HEAVY_CROSSBOW";
    if (value == 116) return "FeatWeapon.FOCUS_HEAVY_FLAIL";
    if (value == 117) return "FeatWeapon.FOCUS_KAMA";
    if (value == 122) return "FeatWeapon.FOCUS_KATANA";
    if (value == 118) return "FeatWeapon.FOCUS_KUKRI";
    if (value == 93) return "FeatWeapon.FOCUS_LIGHT_CROSSBOW";
    if (value == 114) return "FeatWeapon.FOCUS_LIGHT_FLAIL";
    if (value == 113) return "FeatWeapon.FOCUS_LIGHT_HAMMER";
    if (value == 94) return "FeatWeapon.FOCUS_LIGHT_MACE";
    if (value == 101) return "FeatWeapon.FOCUS_LONGBOW";
    if (value == 106) return "FeatWeapon.FOCUS_LONG_SWORD";
    if (value == 95) return "FeatWeapon.FOCUS_MORNING_STAR";
    if (value == 104) return "FeatWeapon.FOCUS_RAPIER";
    if (value == 105) return "FeatWeapon.FOCUS_SCIMITAR";
    if (value == 121) return "FeatWeapon.FOCUS_SCYTHE";
    if (value == 102) return "FeatWeapon.FOCUS_SHORTBOW";
    if (value == 103) return "FeatWeapon.FOCUS_SHORT_SWORD";
    if (value == 120) return "FeatWeapon.FOCUS_SHURIKEN";
    if (value == 98) return "FeatWeapon.FOCUS_SICKLE";
    if (value == 99) return "FeatWeapon.FOCUS_SLING";
    if (value == 97) return "FeatWeapon.FOCUS_SPEAR";
    if (value == 96) return "FeatWeapon.FOCUS_STAFF";
    if (value == 109) return "FeatWeapon.FOCUS_THROWING_AXE";
    if (value == 1072) return "FeatWeapon.FOCUS_TRIDENT";
    if (value == 127) return "FeatWeapon.FOCUS_TWO_BLADED_SWORD";
    if (value == 100) return "FeatWeapon.FOCUS_UNARMED_STRIKE";
    if (value == 115) return "FeatWeapon.FOCUS_WAR_HAMMER";
    if (value == 993) return "FeatWeapon.FOCUS_WHIP";
    if (value == 940) return "FeatWeapon.OF_CHOICE_BASTARDSWORD";
    if (value == 931) return "FeatWeapon.OF_CHOICE_BATTLEAXE";
    if (value == 919) return "FeatWeapon.OF_CHOICE_CLUB";
    if (value == 920) return "FeatWeapon.OF_CHOICE_DAGGER";
    if (value == 941) return "FeatWeapon.OF_CHOICE_DIREMACE";
    if (value == 942) return "FeatWeapon.OF_CHOICE_DOUBLEAXE";
    if (value == 959) return "FeatWeapon.OF_CHOICE_DWAXE";
    if (value == 932) return "FeatWeapon.OF_CHOICE_GREATAXE";
    if (value == 929) return "FeatWeapon.OF_CHOICE_GREATSWORD";
    if (value == 933) return "FeatWeapon.OF_CHOICE_HALBERD";
    if (value == 930) return "FeatWeapon.OF_CHOICE_HANDAXE";
    if (value == 937) return "FeatWeapon.OF_CHOICE_HEAVYFLAIL";
    if (value == 880) return "FeatWeapon.OF_CHOICE_KAMA";
    if (value == 939) return "FeatWeapon.OF_CHOICE_KATANA";
    if (value == 881) return "FeatWeapon.OF_CHOICE_KUKRI";
    if (value == 935) return "FeatWeapon.OF_CHOICE_LIGHTFLAIL";
    if (value == 934) return "FeatWeapon.OF_CHOICE_LIGHTHAMMER";
    if (value == 921) return "FeatWeapon.OF_CHOICE_LIGHTMACE";
    if (value == 928) return "FeatWeapon.OF_CHOICE_LONGSWORD";
    if (value == 922) return "FeatWeapon.OF_CHOICE_MORNINGSTAR";
    if (value == 923) return "FeatWeapon.OF_CHOICE_QUARTERSTAFF";
    if (value == 926) return "FeatWeapon.OF_CHOICE_RAPIER";
    if (value == 927) return "FeatWeapon.OF_CHOICE_SCIMITAR";
    if (value == 938) return "FeatWeapon.OF_CHOICE_SCYTHE";
    if (value == 924) return "FeatWeapon.OF_CHOICE_SHORTSPEAR";
    if (value == 925) return "FeatWeapon.OF_CHOICE_SHORTSWORD";
    if (value == 879) return "FeatWeapon.OF_CHOICE_SICKLE";
    if (value == 1079) return "FeatWeapon.OF_CHOICE_TRIDENT";
    if (value == 943) return "FeatWeapon.OF_CHOICE_TWOBLADEDSWORD";
    if (value == 936) return "FeatWeapon.OF_CHOICE_WARHAMMER";
    if (value == 1000) return "FeatWeapon.OF_CHOICE_WHIP";
    if (value == 289) return "FeatWeapon.PROFICIENCY_CREATURE";
    if (value == 48) return "FeatWeapon.PROFICIENCY_DRUID";
    if (value == 256) return "FeatWeapon.PROFICIENCY_ELF";
    if (value == 44) return "FeatWeapon.PROFICIENCY_EXOTIC";
    if (value == 45) return "FeatWeapon.PROFICIENCY_MARTIAL";
    if (value == 49) return "FeatWeapon.PROFICIENCY_MONK";
    if (value == 50) return "FeatWeapon.PROFICIENCY_ROGUE";
    if (value == 46) return "FeatWeapon.PROFICIENCY_SIMPLE";
    if (value == 51) return "FeatWeapon.PROFICIENCY_WIZARD";
    if (value == 161) return "FeatWeapon.SPECIALIZATION_BASTARD_SWORD";
    if (value == 148) return "FeatWeapon.SPECIALIZATION_BATTLE_AXE";
    if (value == 47) return "FeatWeapon.SPECIALIZATION_CLUB";
    if (value == 290) return "FeatWeapon.SPECIALIZATION_CREATURE";
    if (value == 128) return "FeatWeapon.SPECIALIZATION_DAGGER";
    if (value == 129) return "FeatWeapon.SPECIALIZATION_DART";
    if (value == 163) return "FeatWeapon.SPECIALIZATION_DIRE_MACE";
    if (value == 164) return "FeatWeapon.SPECIALIZATION_DOUBLE_AXE";
    if (value == 953) return "FeatWeapon.SPECIALIZATION_DWAXE";
    if (value == 149) return "FeatWeapon.SPECIALIZATION_GREAT_AXE";
    if (value == 145) return "FeatWeapon.SPECIALIZATION_GREAT_SWORD";
    if (value == 150) return "FeatWeapon.SPECIALIZATION_HALBERD";
    if (value == 146) return "FeatWeapon.SPECIALIZATION_HAND_AXE";
    if (value == 130) return "FeatWeapon.SPECIALIZATION_HEAVY_CROSSBOW";
    if (value == 154) return "FeatWeapon.SPECIALIZATION_HEAVY_FLAIL";
    if (value == 155) return "FeatWeapon.SPECIALIZATION_KAMA";
    if (value == 160) return "FeatWeapon.SPECIALIZATION_KATANA";
    if (value == 156) return "FeatWeapon.SPECIALIZATION_KUKRI";
    if (value == 131) return "FeatWeapon.SPECIALIZATION_LIGHT_CROSSBOW";
    if (value == 152) return "FeatWeapon.SPECIALIZATION_LIGHT_FLAIL";
    if (value == 151) return "FeatWeapon.SPECIALIZATION_LIGHT_HAMMER";
    if (value == 132) return "FeatWeapon.SPECIALIZATION_LIGHT_MACE";
    if (value == 139) return "FeatWeapon.SPECIALIZATION_LONGBOW";
    if (value == 144) return "FeatWeapon.SPECIALIZATION_LONG_SWORD";
    if (value == 133) return "FeatWeapon.SPECIALIZATION_MORNING_STAR";
    if (value == 142) return "FeatWeapon.SPECIALIZATION_RAPIER";
    if (value == 143) return "FeatWeapon.SPECIALIZATION_SCIMITAR";
    if (value == 159) return "FeatWeapon.SPECIALIZATION_SCYTHE";
    if (value == 140) return "FeatWeapon.SPECIALIZATION_SHORTBOW";
    if (value == 141) return "FeatWeapon.SPECIALIZATION_SHORT_SWORD";
    if (value == 158) return "FeatWeapon.SPECIALIZATION_SHURIKEN";
    if (value == 136) return "FeatWeapon.SPECIALIZATION_SICKLE";
    if (value == 137) return "FeatWeapon.SPECIALIZATION_SLING";
    if (value == 135) return "FeatWeapon.SPECIALIZATION_SPEAR";
    if (value == 134) return "FeatWeapon.SPECIALIZATION_STAFF";
    if (value == 147) return "FeatWeapon.SPECIALIZATION_THROWING_AXE";
    if (value == 1073) return "FeatWeapon.SPECIALIZATION_TRIDENT";
    if (value == 165) return "FeatWeapon.SPECIALIZATION_TWO_BLADED_SWORD";
    if (value == 138) return "FeatWeapon.SPECIALIZATION_UNARMED_STRIKE";
    if (value == 153) return "FeatWeapon.SPECIALIZATION_WAR_HAMMER";
    if (value == 994) return "FeatWeapon.SPECIALIZATION_WHIP";
    return "FeatWeapon.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "FeatWeapon.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "FeatWeapon.(not found: " + value + ")";
  }
}
