package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "IP_CONST_IMMUNITYSPELL".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class IpConstImmunityspell {
  private IpConstImmunityspell() {}

  public final static int ACID_FOG = 0;
  public final static int AID = 1;
  public final static int AURA_OF_VITALITY = 182;
  public final static int BARKSKIN = 2;
  public final static int BESTOW_CURSE = 3;
  public final static int BLINDNESS_AND_DEAFNESS = 6;
  public final static int BURNING_HANDS = 8;
  public final static int CALL_LIGHTNING = 9;
  public final static int CHAIN_LIGHTNING = 12;
  public final static int CHARM_MONSTER = 13;
  public final static int CHARM_PERSON = 14;
  public final static int CHARM_PERSON_OR_ANIMAL = 15;
  public final static int CIRCLE_OF_DEATH = 16;
  public final static int CIRCLE_OF_DOOM = 17;
  public final static int CLOUDKILL = 21;
  public final static int COLOR_SPRAY = 22;
  public final static int CONE_OF_COLD = 23;
  public final static int CONFUSION = 24;
  public final static int CONTAGION = 25;
  public final static int CONTROL_UNDEAD = 26;
  public final static int CURE_CRITICAL_WOUNDS = 27;
  public final static int CURE_LIGHT_WOUNDS = 28;
  public final static int CURE_MINOR_WOUNDS = 29;
  public final static int CURE_MODERATE_WOUNDS = 30;
  public final static int CURE_SERIOUS_WOUNDS = 31;
  public final static int DARKNESS = 32;
  public final static int DAZE = 33;
  public final static int DEATH_WARD = 34;
  public final static int DELAYED_BLAST_FIREBALL = 35;
  public final static int DISMISSAL = 36;
  public final static int DISPEL_MAGIC = 37;
  public final static int DOMINATE_ANIMAL = 39;
  public final static int DOMINATE_MONSTER = 40;
  public final static int DOMINATE_PERSON = 41;
  public final static int DOOM = 42;
  public final static int EAGLE_SPLEDOR = 173;
  public final static int ENERGY_DRAIN = 46;
  public final static int ENERVATION = 47;
  public final static int ENTANGLE = 48;
  public final static int EVARDS_BLACK_TENTACLES = 185;
  public final static int FEAR = 49;
  public final static int FEEBLEMIND = 50;
  public final static int FIND_TRAPS = 187;
  public final static int FINGER_OF_DEATH = 51;
  public final static int FIREBALL = 53;
  public final static int FIRE_STORM = 52;
  public final static int FLAME_ARROW = 54;
  public final static int FLAME_LASH = 55;
  public final static int FLAME_STRIKE = 56;
  public final static int FOXS_CUNNING = 175;
  public final static int FREEDOM_OF_MOVEMENT = 57;
  public final static int GREASE = 59;
  public final static int GREATER_BULLS_STRENGTH = 179;
  public final static int GREATER_CATS_GRACE = 180;
  public final static int GREATER_DISPELLING = 60;
  public final static int GREATER_EAGLES_SPLENDOR = 176;
  public final static int GREATER_ENDURANCE = 181;
  public final static int GREATER_FOXS_CUNNING = 178;
  public final static int GREATER_OWLS_WISDOM = 177;
  public final static int GREATER_PLANAR_BINDING = 62;
  public final static int GREATER_SHADOW_CONJURATION = 64;
  public final static int GREATER_SPELL_BREACH = 65;
  public final static int HAMMER_OF_THE_GODS = 68;
  public final static int HARM = 69;
  public final static int HEAL = 71;
  public final static int HEALING_CIRCLE = 72;
  public final static int HOLD_ANIMAL = 73;
  public final static int HOLD_MONSTER = 74;
  public final static int HOLD_PERSON = 75;
  public final static int IMPLOSION = 78;
  public final static int IMPROVED_INVISIBILITY = 79;
  public final static int INCENDIARY_CLOUD = 80;
  public final static int INVISIBILITY_PURGE = 82;
  public final static int LEGEND_LORE = 186;
  public final static int LESSER_DISPEL = 84;
  public final static int LESSER_PLANAR_BINDING = 86;
  public final static int LESSER_SPELL_BREACH = 88;
  public final static int LIGHTNING_BOLT = 91;
  public final static int MAGIC_CIRCLE_AGAINST_ALIGNMENT = 171;
  public final static int MAGIC_MISSILE = 97;
  public final static int MASS_BLINDNESS_AND_DEAFNESS = 100;
  public final static int MASS_CHARM = 101;
  public final static int MASS_HEAL = 104;
  public final static int MELFS_ACID_ARROW = 105;
  public final static int METEOR_SWARM = 106;
  public final static int MIND_FOG = 108;
  public final static int MORDENKAINENS_DISJUNCTION = 112;
  public final static int OWLS_WISDOM = 174;
  public final static int PHANTASMAL_KILLER = 116;
  public final static int PLANAR_BINDING = 117;
  public final static int POISON = 118;
  public final static int POWER_WORD_KILL = 120;
  public final static int POWER_WORD_STUN = 121;
  public final static int PRISMATIC_SPRAY = 124;
  public final static int RAY_OF_ENFEEBLEMENT = 131;
  public final static int RAY_OF_FROST = 132;
  public final static int REGENERATE = 184;
  public final static int SCARE = 142;
  public final static int SEARING_LIGHT = 143;
  public final static int SHADES = 145;
  public final static int SHADOW_CONJURATION = 146;
  public final static int SILENCE = 150;
  public final static int SLAY_LIVING = 151;
  public final static int SLEEP = 152;
  public final static int SLOW = 153;
  public final static int SOUND_BURST = 154;
  public final static int STINKING_CLOUD = 158;
  public final static int STONESKIN = 159;
  public final static int STORM_OF_VENGEANCE = 160;
  public final static int SUNBEAM = 161;
  public final static int VIRTUE = 165;
  public final static int WAIL_OF_THE_BANSHEE = 166;
  public final static int WAR_CRY = 183;
  public final static int WEB = 167;
  public final static int WEIRD = 168;
  public final static int WORD_OF_FAITH = 169;

  public static String nameOf(int value) {
    if (value == 0) return "IpConstImmunityspell.ACID_FOG";
    if (value == 1) return "IpConstImmunityspell.AID";
    if (value == 182) return "IpConstImmunityspell.AURA_OF_VITALITY";
    if (value == 2) return "IpConstImmunityspell.BARKSKIN";
    if (value == 3) return "IpConstImmunityspell.BESTOW_CURSE";
    if (value == 6) return "IpConstImmunityspell.BLINDNESS_AND_DEAFNESS";
    if (value == 8) return "IpConstImmunityspell.BURNING_HANDS";
    if (value == 9) return "IpConstImmunityspell.CALL_LIGHTNING";
    if (value == 12) return "IpConstImmunityspell.CHAIN_LIGHTNING";
    if (value == 13) return "IpConstImmunityspell.CHARM_MONSTER";
    if (value == 14) return "IpConstImmunityspell.CHARM_PERSON";
    if (value == 15) return "IpConstImmunityspell.CHARM_PERSON_OR_ANIMAL";
    if (value == 16) return "IpConstImmunityspell.CIRCLE_OF_DEATH";
    if (value == 17) return "IpConstImmunityspell.CIRCLE_OF_DOOM";
    if (value == 21) return "IpConstImmunityspell.CLOUDKILL";
    if (value == 22) return "IpConstImmunityspell.COLOR_SPRAY";
    if (value == 23) return "IpConstImmunityspell.CONE_OF_COLD";
    if (value == 24) return "IpConstImmunityspell.CONFUSION";
    if (value == 25) return "IpConstImmunityspell.CONTAGION";
    if (value == 26) return "IpConstImmunityspell.CONTROL_UNDEAD";
    if (value == 27) return "IpConstImmunityspell.CURE_CRITICAL_WOUNDS";
    if (value == 28) return "IpConstImmunityspell.CURE_LIGHT_WOUNDS";
    if (value == 29) return "IpConstImmunityspell.CURE_MINOR_WOUNDS";
    if (value == 30) return "IpConstImmunityspell.CURE_MODERATE_WOUNDS";
    if (value == 31) return "IpConstImmunityspell.CURE_SERIOUS_WOUNDS";
    if (value == 32) return "IpConstImmunityspell.DARKNESS";
    if (value == 33) return "IpConstImmunityspell.DAZE";
    if (value == 34) return "IpConstImmunityspell.DEATH_WARD";
    if (value == 35) return "IpConstImmunityspell.DELAYED_BLAST_FIREBALL";
    if (value == 36) return "IpConstImmunityspell.DISMISSAL";
    if (value == 37) return "IpConstImmunityspell.DISPEL_MAGIC";
    if (value == 39) return "IpConstImmunityspell.DOMINATE_ANIMAL";
    if (value == 40) return "IpConstImmunityspell.DOMINATE_MONSTER";
    if (value == 41) return "IpConstImmunityspell.DOMINATE_PERSON";
    if (value == 42) return "IpConstImmunityspell.DOOM";
    if (value == 173) return "IpConstImmunityspell.EAGLE_SPLEDOR";
    if (value == 46) return "IpConstImmunityspell.ENERGY_DRAIN";
    if (value == 47) return "IpConstImmunityspell.ENERVATION";
    if (value == 48) return "IpConstImmunityspell.ENTANGLE";
    if (value == 185) return "IpConstImmunityspell.EVARDS_BLACK_TENTACLES";
    if (value == 49) return "IpConstImmunityspell.FEAR";
    if (value == 50) return "IpConstImmunityspell.FEEBLEMIND";
    if (value == 187) return "IpConstImmunityspell.FIND_TRAPS";
    if (value == 51) return "IpConstImmunityspell.FINGER_OF_DEATH";
    if (value == 53) return "IpConstImmunityspell.FIREBALL";
    if (value == 52) return "IpConstImmunityspell.FIRE_STORM";
    if (value == 54) return "IpConstImmunityspell.FLAME_ARROW";
    if (value == 55) return "IpConstImmunityspell.FLAME_LASH";
    if (value == 56) return "IpConstImmunityspell.FLAME_STRIKE";
    if (value == 175) return "IpConstImmunityspell.FOXS_CUNNING";
    if (value == 57) return "IpConstImmunityspell.FREEDOM_OF_MOVEMENT";
    if (value == 59) return "IpConstImmunityspell.GREASE";
    if (value == 179) return "IpConstImmunityspell.GREATER_BULLS_STRENGTH";
    if (value == 180) return "IpConstImmunityspell.GREATER_CATS_GRACE";
    if (value == 60) return "IpConstImmunityspell.GREATER_DISPELLING";
    if (value == 176) return "IpConstImmunityspell.GREATER_EAGLES_SPLENDOR";
    if (value == 181) return "IpConstImmunityspell.GREATER_ENDURANCE";
    if (value == 178) return "IpConstImmunityspell.GREATER_FOXS_CUNNING";
    if (value == 177) return "IpConstImmunityspell.GREATER_OWLS_WISDOM";
    if (value == 62) return "IpConstImmunityspell.GREATER_PLANAR_BINDING";
    if (value == 64) return "IpConstImmunityspell.GREATER_SHADOW_CONJURATION";
    if (value == 65) return "IpConstImmunityspell.GREATER_SPELL_BREACH";
    if (value == 68) return "IpConstImmunityspell.HAMMER_OF_THE_GODS";
    if (value == 69) return "IpConstImmunityspell.HARM";
    if (value == 71) return "IpConstImmunityspell.HEAL";
    if (value == 72) return "IpConstImmunityspell.HEALING_CIRCLE";
    if (value == 73) return "IpConstImmunityspell.HOLD_ANIMAL";
    if (value == 74) return "IpConstImmunityspell.HOLD_MONSTER";
    if (value == 75) return "IpConstImmunityspell.HOLD_PERSON";
    if (value == 78) return "IpConstImmunityspell.IMPLOSION";
    if (value == 79) return "IpConstImmunityspell.IMPROVED_INVISIBILITY";
    if (value == 80) return "IpConstImmunityspell.INCENDIARY_CLOUD";
    if (value == 82) return "IpConstImmunityspell.INVISIBILITY_PURGE";
    if (value == 186) return "IpConstImmunityspell.LEGEND_LORE";
    if (value == 84) return "IpConstImmunityspell.LESSER_DISPEL";
    if (value == 86) return "IpConstImmunityspell.LESSER_PLANAR_BINDING";
    if (value == 88) return "IpConstImmunityspell.LESSER_SPELL_BREACH";
    if (value == 91) return "IpConstImmunityspell.LIGHTNING_BOLT";
    if (value == 171) return "IpConstImmunityspell.MAGIC_CIRCLE_AGAINST_ALIGNMENT";
    if (value == 97) return "IpConstImmunityspell.MAGIC_MISSILE";
    if (value == 100) return "IpConstImmunityspell.MASS_BLINDNESS_AND_DEAFNESS";
    if (value == 101) return "IpConstImmunityspell.MASS_CHARM";
    if (value == 104) return "IpConstImmunityspell.MASS_HEAL";
    if (value == 105) return "IpConstImmunityspell.MELFS_ACID_ARROW";
    if (value == 106) return "IpConstImmunityspell.METEOR_SWARM";
    if (value == 108) return "IpConstImmunityspell.MIND_FOG";
    if (value == 112) return "IpConstImmunityspell.MORDENKAINENS_DISJUNCTION";
    if (value == 174) return "IpConstImmunityspell.OWLS_WISDOM";
    if (value == 116) return "IpConstImmunityspell.PHANTASMAL_KILLER";
    if (value == 117) return "IpConstImmunityspell.PLANAR_BINDING";
    if (value == 118) return "IpConstImmunityspell.POISON";
    if (value == 120) return "IpConstImmunityspell.POWER_WORD_KILL";
    if (value == 121) return "IpConstImmunityspell.POWER_WORD_STUN";
    if (value == 124) return "IpConstImmunityspell.PRISMATIC_SPRAY";
    if (value == 131) return "IpConstImmunityspell.RAY_OF_ENFEEBLEMENT";
    if (value == 132) return "IpConstImmunityspell.RAY_OF_FROST";
    if (value == 184) return "IpConstImmunityspell.REGENERATE";
    if (value == 142) return "IpConstImmunityspell.SCARE";
    if (value == 143) return "IpConstImmunityspell.SEARING_LIGHT";
    if (value == 145) return "IpConstImmunityspell.SHADES";
    if (value == 146) return "IpConstImmunityspell.SHADOW_CONJURATION";
    if (value == 150) return "IpConstImmunityspell.SILENCE";
    if (value == 151) return "IpConstImmunityspell.SLAY_LIVING";
    if (value == 152) return "IpConstImmunityspell.SLEEP";
    if (value == 153) return "IpConstImmunityspell.SLOW";
    if (value == 154) return "IpConstImmunityspell.SOUND_BURST";
    if (value == 158) return "IpConstImmunityspell.STINKING_CLOUD";
    if (value == 159) return "IpConstImmunityspell.STONESKIN";
    if (value == 160) return "IpConstImmunityspell.STORM_OF_VENGEANCE";
    if (value == 161) return "IpConstImmunityspell.SUNBEAM";
    if (value == 165) return "IpConstImmunityspell.VIRTUE";
    if (value == 166) return "IpConstImmunityspell.WAIL_OF_THE_BANSHEE";
    if (value == 183) return "IpConstImmunityspell.WAR_CRY";
    if (value == 167) return "IpConstImmunityspell.WEB";
    if (value == 168) return "IpConstImmunityspell.WEIRD";
    if (value == 169) return "IpConstImmunityspell.WORD_OF_FAITH";
    return "IpConstImmunityspell.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "IpConstImmunityspell.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "IpConstImmunityspell.(not found: " + value + ")";
  }
}
