package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "IP_CONST_ONHIT_CASTSPELL".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class IpConstOnhitCastspell {
  private IpConstOnhitCastspell() {}

  public final static int ACID_FOG = 0;
  public final static int ACID_SPLASH = 81;
  public final static int ACTIVATE_ITEM = 78;
  public final static int BALAGARNSIRONHORN = 91;
  public final static int BALL_LIGHTNING = 113;
  public final static int BANE = 100;
  public final static int BANISHMENT = 85;
  public final static int BESTOW_CURSE = 1;
  public final static int BIGBYS_CLENCHED_FIST = 106;
  public final static int BIGBYS_CRUSHING_HAND = 107;
  public final static int BIGBYS_FORCEFUL_HAND = 104;
  public final static int BIGBYS_GRASPING_HAND = 105;
  public final static int BIGBYS_INTERPOSING_HAND = 103;
  public final static int BLADE_BARRIER = 2;
  public final static int BLINDNESS_AND_DEAFNESS = 3;
  public final static int BOMBARDMENT = 80;
  public final static int CALL_LIGHTNING = 4;
  public final static int CHAIN_LIGHTNING = 5;
  public final static int CLOUDKILL = 6;
  public final static int COMBUST = 140;
  public final static int CONFUSION = 7;
  public final static int CONTAGION = 8;
  public final static int CREEPING_DOOM = 72;
  public final static int CRUMBLE = 110;
  public final static int DARKNESS = 9;
  public final static int DAZE = 10;
  public final static int DEAFENING_CLNG = 137;
  public final static int DELAYED_BLAST_FIREBALL = 11;
  public final static int DESTRUCTION = 73;
  public final static int DISMISSAL = 12;
  public final static int DISPEL_MAGIC = 13;
  public final static int DOOM = 14;
  public final static int DROWN = 92;
  public final static int EARTHQUAKE = 83;
  public final static int ELECTRIC_JOLT = 93;
  public final static int ENERGY_DRAIN = 15;
  public final static int ENERVATION = 16;
  public final static int ENTANGLE = 17;
  public final static int EVARDS_BLACK_TENTACLES = 77;
  public final static int EVIL_BLIGHT = 121;
  public final static int FEAR = 18;
  public final static int FEEBLEMIND = 19;
  public final static int FIREBALL = 21;
  public final static int FIREBRAND = 94;
  public final static int FIRE_STORM = 20;
  public final static int FLAME_LASH = 22;
  public final static int FLAME_STRIKE = 23;
  public final static int FLARE = 79;
  public final static int FLESH_TO_STONE = 108;
  public final static int FREEZE = 139;
  public final static int GEDLEES_ELECTRIC_LOOP = 114;
  public final static int GHOUL_TOUCH = 24;
  public final static int GREASE = 25;
  public final static int GREATER_DISPELLING = 26;
  public final static int GREATER_SPELL_BREACH = 27;
  public final static int GREAT_THUNDERCLAP = 112;
  public final static int GUST_OF_WIND = 28;
  public final static int HAMMER_OF_THE_GODS = 29;
  public final static int HARM = 30;
  public final static int HOLD_ANIMAL = 31;
  public final static int HOLD_MONSTER = 32;
  public final static int HOLD_PERSON = 33;
  public final static int HORIZIKAULS_BOOM = 115;
  public final static int HORRID_WILTING = 74;
  public final static int ICE_STORM = 75;
  public final static int IMPLOSION = 34;
  public final static int INCENDIARY_CLOUD = 35;
  public final static int INFERNO = 97;
  public final static int INFESTATION_OF_MAGGOTS = 111;
  public final static int INFLICT_CRITICAL_WOUNDS = 90;
  public final static int INFLICT_LIGHT_WOUNDS = 87;
  public final static int INFLICT_MINOR_WOUNDS = 86;
  public final static int INFLICT_MODERATE_WOUNDS = 88;
  public final static int INFLICT_SERIOUS_WOUNDS = 89;
  public final static int INTELLIGENT_WEAPON_ONHIT = 135;
  public final static int ISAACS_GREATER_MISSILE_STORM = 99;
  public final static int ISAACS_LESSER_MISSILE_STORM = 98;
  public final static int KNOCKDOWN = 138;
  public final static int LESSER_DISPEL = 36;
  public final static int LESSER_SPELL_BREACH = 38;
  public final static int LIGHT = 40;
  public final static int LIGHTNING_BOLT = 41;
  public final static int MAGIC_MISSILE = 42;
  public final static int MASS_BLINDNESS_AND_DEAFNESS = 43;
  public final static int MASS_CHARM = 44;
  public final static int MELFS_ACID_ARROW = 45;
  public final static int MESTILS_ACID_BREATH = 116;
  public final static int METEOR_SWARM = 46;
  public final static int MIND_FOG = 47;
  public final static int NEGATIVE_ENERGY_BURST = 76;
  public final static int ONHITDEMILICHTOUCH = 133;
  public final static int ONHITDRACOLICHTOUCH = 134;
  public final static int ONHITFLAMINGSKIN = 129;
  public final static int ONHITRUINARMORBEBILITH = 132;
  public final static int ONHIT_CHAOSSHIELD = 130;
  public final static int ONHIT_CONSTRICTWEAPON = 131;
  public final static int ONHIT_DARKFIRE = 127;
  public final static int ONHIT_EXTRACTBRAIN = 128;
  public final static int ONHIT_FIREDAMAGE = 124;
  public final static int ONHIT_PLANARRIFT = 126;
  public final static int ONHIT_SLAYRAKSHASA = 123;
  public final static int ONHIT_TELEPORT = 122;
  public final static int ONHIT_UNIQUEPOWER = 125;
  public final static int PARALYZE_2 = 136;
  public final static int PHANTASMAL_KILLER = 49;
  public final static int POISON = 50;
  public final static int POWER_WORD_KILL = 51;
  public final static int POWER_WORD_STUN = 52;
  public final static int QUILLFIRE = 82;
  public final static int SCARE = 54;
  public final static int SCINTILLATING_SPHERE = 117;
  public final static int SEARING_LIGHT = 55;
  public final static int SILENCE = 56;
  public final static int SLAY_LIVING = 57;
  public final static int SLEEP = 58;
  public final static int SLOW = 59;
  public final static int SOUND_BURST = 60;
  public final static int SPIKE_GROWTH = 101;
  public final static int STINKING_CLOUD = 61;
  public final static int STONEHOLD = 119;
  public final static int STONE_TO_FLESH = 109;
  public final static int STORM_OF_VENGEANCE = 63;
  public final static int SUNBEAM = 64;
  public final static int SUNBURST = 84;
  public final static int TASHAS_HIDEOUS_LAUGHTER = 102;
  public final static int UNDEATHS_ETERNAL_FOE = 96;
  public final static int UNDEATH_TO_DEATH = 118;
  public final static int VAMPIRIC_TOUCH = 65;
  public final static int WAIL_OF_THE_BANSHEE = 66;
  public final static int WALL_OF_FIRE = 67;
  public final static int WEB = 68;
  public final static int WEIRD = 69;
  public final static int WORD_OF_FAITH = 70;
  public final static int WOUNDING_WHISPERS = 95;

  public static String nameOf(int value) {
    if (value == 0) return "IpConstOnhitCastspell.ACID_FOG";
    if (value == 81) return "IpConstOnhitCastspell.ACID_SPLASH";
    if (value == 78) return "IpConstOnhitCastspell.ACTIVATE_ITEM";
    if (value == 91) return "IpConstOnhitCastspell.BALAGARNSIRONHORN";
    if (value == 113) return "IpConstOnhitCastspell.BALL_LIGHTNING";
    if (value == 100) return "IpConstOnhitCastspell.BANE";
    if (value == 85) return "IpConstOnhitCastspell.BANISHMENT";
    if (value == 1) return "IpConstOnhitCastspell.BESTOW_CURSE";
    if (value == 106) return "IpConstOnhitCastspell.BIGBYS_CLENCHED_FIST";
    if (value == 107) return "IpConstOnhitCastspell.BIGBYS_CRUSHING_HAND";
    if (value == 104) return "IpConstOnhitCastspell.BIGBYS_FORCEFUL_HAND";
    if (value == 105) return "IpConstOnhitCastspell.BIGBYS_GRASPING_HAND";
    if (value == 103) return "IpConstOnhitCastspell.BIGBYS_INTERPOSING_HAND";
    if (value == 2) return "IpConstOnhitCastspell.BLADE_BARRIER";
    if (value == 3) return "IpConstOnhitCastspell.BLINDNESS_AND_DEAFNESS";
    if (value == 80) return "IpConstOnhitCastspell.BOMBARDMENT";
    if (value == 4) return "IpConstOnhitCastspell.CALL_LIGHTNING";
    if (value == 5) return "IpConstOnhitCastspell.CHAIN_LIGHTNING";
    if (value == 6) return "IpConstOnhitCastspell.CLOUDKILL";
    if (value == 140) return "IpConstOnhitCastspell.COMBUST";
    if (value == 7) return "IpConstOnhitCastspell.CONFUSION";
    if (value == 8) return "IpConstOnhitCastspell.CONTAGION";
    if (value == 72) return "IpConstOnhitCastspell.CREEPING_DOOM";
    if (value == 110) return "IpConstOnhitCastspell.CRUMBLE";
    if (value == 9) return "IpConstOnhitCastspell.DARKNESS";
    if (value == 10) return "IpConstOnhitCastspell.DAZE";
    if (value == 137) return "IpConstOnhitCastspell.DEAFENING_CLNG";
    if (value == 11) return "IpConstOnhitCastspell.DELAYED_BLAST_FIREBALL";
    if (value == 73) return "IpConstOnhitCastspell.DESTRUCTION";
    if (value == 12) return "IpConstOnhitCastspell.DISMISSAL";
    if (value == 13) return "IpConstOnhitCastspell.DISPEL_MAGIC";
    if (value == 14) return "IpConstOnhitCastspell.DOOM";
    if (value == 92) return "IpConstOnhitCastspell.DROWN";
    if (value == 83) return "IpConstOnhitCastspell.EARTHQUAKE";
    if (value == 93) return "IpConstOnhitCastspell.ELECTRIC_JOLT";
    if (value == 15) return "IpConstOnhitCastspell.ENERGY_DRAIN";
    if (value == 16) return "IpConstOnhitCastspell.ENERVATION";
    if (value == 17) return "IpConstOnhitCastspell.ENTANGLE";
    if (value == 77) return "IpConstOnhitCastspell.EVARDS_BLACK_TENTACLES";
    if (value == 121) return "IpConstOnhitCastspell.EVIL_BLIGHT";
    if (value == 18) return "IpConstOnhitCastspell.FEAR";
    if (value == 19) return "IpConstOnhitCastspell.FEEBLEMIND";
    if (value == 21) return "IpConstOnhitCastspell.FIREBALL";
    if (value == 94) return "IpConstOnhitCastspell.FIREBRAND";
    if (value == 20) return "IpConstOnhitCastspell.FIRE_STORM";
    if (value == 22) return "IpConstOnhitCastspell.FLAME_LASH";
    if (value == 23) return "IpConstOnhitCastspell.FLAME_STRIKE";
    if (value == 79) return "IpConstOnhitCastspell.FLARE";
    if (value == 108) return "IpConstOnhitCastspell.FLESH_TO_STONE";
    if (value == 139) return "IpConstOnhitCastspell.FREEZE";
    if (value == 114) return "IpConstOnhitCastspell.GEDLEES_ELECTRIC_LOOP";
    if (value == 24) return "IpConstOnhitCastspell.GHOUL_TOUCH";
    if (value == 25) return "IpConstOnhitCastspell.GREASE";
    if (value == 26) return "IpConstOnhitCastspell.GREATER_DISPELLING";
    if (value == 27) return "IpConstOnhitCastspell.GREATER_SPELL_BREACH";
    if (value == 112) return "IpConstOnhitCastspell.GREAT_THUNDERCLAP";
    if (value == 28) return "IpConstOnhitCastspell.GUST_OF_WIND";
    if (value == 29) return "IpConstOnhitCastspell.HAMMER_OF_THE_GODS";
    if (value == 30) return "IpConstOnhitCastspell.HARM";
    if (value == 31) return "IpConstOnhitCastspell.HOLD_ANIMAL";
    if (value == 32) return "IpConstOnhitCastspell.HOLD_MONSTER";
    if (value == 33) return "IpConstOnhitCastspell.HOLD_PERSON";
    if (value == 115) return "IpConstOnhitCastspell.HORIZIKAULS_BOOM";
    if (value == 74) return "IpConstOnhitCastspell.HORRID_WILTING";
    if (value == 75) return "IpConstOnhitCastspell.ICE_STORM";
    if (value == 34) return "IpConstOnhitCastspell.IMPLOSION";
    if (value == 35) return "IpConstOnhitCastspell.INCENDIARY_CLOUD";
    if (value == 97) return "IpConstOnhitCastspell.INFERNO";
    if (value == 111) return "IpConstOnhitCastspell.INFESTATION_OF_MAGGOTS";
    if (value == 90) return "IpConstOnhitCastspell.INFLICT_CRITICAL_WOUNDS";
    if (value == 87) return "IpConstOnhitCastspell.INFLICT_LIGHT_WOUNDS";
    if (value == 86) return "IpConstOnhitCastspell.INFLICT_MINOR_WOUNDS";
    if (value == 88) return "IpConstOnhitCastspell.INFLICT_MODERATE_WOUNDS";
    if (value == 89) return "IpConstOnhitCastspell.INFLICT_SERIOUS_WOUNDS";
    if (value == 135) return "IpConstOnhitCastspell.INTELLIGENT_WEAPON_ONHIT";
    if (value == 99) return "IpConstOnhitCastspell.ISAACS_GREATER_MISSILE_STORM";
    if (value == 98) return "IpConstOnhitCastspell.ISAACS_LESSER_MISSILE_STORM";
    if (value == 138) return "IpConstOnhitCastspell.KNOCKDOWN";
    if (value == 36) return "IpConstOnhitCastspell.LESSER_DISPEL";
    if (value == 38) return "IpConstOnhitCastspell.LESSER_SPELL_BREACH";
    if (value == 40) return "IpConstOnhitCastspell.LIGHT";
    if (value == 41) return "IpConstOnhitCastspell.LIGHTNING_BOLT";
    if (value == 42) return "IpConstOnhitCastspell.MAGIC_MISSILE";
    if (value == 43) return "IpConstOnhitCastspell.MASS_BLINDNESS_AND_DEAFNESS";
    if (value == 44) return "IpConstOnhitCastspell.MASS_CHARM";
    if (value == 45) return "IpConstOnhitCastspell.MELFS_ACID_ARROW";
    if (value == 116) return "IpConstOnhitCastspell.MESTILS_ACID_BREATH";
    if (value == 46) return "IpConstOnhitCastspell.METEOR_SWARM";
    if (value == 47) return "IpConstOnhitCastspell.MIND_FOG";
    if (value == 76) return "IpConstOnhitCastspell.NEGATIVE_ENERGY_BURST";
    if (value == 133) return "IpConstOnhitCastspell.ONHITDEMILICHTOUCH";
    if (value == 134) return "IpConstOnhitCastspell.ONHITDRACOLICHTOUCH";
    if (value == 129) return "IpConstOnhitCastspell.ONHITFLAMINGSKIN";
    if (value == 132) return "IpConstOnhitCastspell.ONHITRUINARMORBEBILITH";
    if (value == 130) return "IpConstOnhitCastspell.ONHIT_CHAOSSHIELD";
    if (value == 131) return "IpConstOnhitCastspell.ONHIT_CONSTRICTWEAPON";
    if (value == 127) return "IpConstOnhitCastspell.ONHIT_DARKFIRE";
    if (value == 128) return "IpConstOnhitCastspell.ONHIT_EXTRACTBRAIN";
    if (value == 124) return "IpConstOnhitCastspell.ONHIT_FIREDAMAGE";
    if (value == 126) return "IpConstOnhitCastspell.ONHIT_PLANARRIFT";
    if (value == 123) return "IpConstOnhitCastspell.ONHIT_SLAYRAKSHASA";
    if (value == 122) return "IpConstOnhitCastspell.ONHIT_TELEPORT";
    if (value == 125) return "IpConstOnhitCastspell.ONHIT_UNIQUEPOWER";
    if (value == 136) return "IpConstOnhitCastspell.PARALYZE_2";
    if (value == 49) return "IpConstOnhitCastspell.PHANTASMAL_KILLER";
    if (value == 50) return "IpConstOnhitCastspell.POISON";
    if (value == 51) return "IpConstOnhitCastspell.POWER_WORD_KILL";
    if (value == 52) return "IpConstOnhitCastspell.POWER_WORD_STUN";
    if (value == 82) return "IpConstOnhitCastspell.QUILLFIRE";
    if (value == 54) return "IpConstOnhitCastspell.SCARE";
    if (value == 117) return "IpConstOnhitCastspell.SCINTILLATING_SPHERE";
    if (value == 55) return "IpConstOnhitCastspell.SEARING_LIGHT";
    if (value == 56) return "IpConstOnhitCastspell.SILENCE";
    if (value == 57) return "IpConstOnhitCastspell.SLAY_LIVING";
    if (value == 58) return "IpConstOnhitCastspell.SLEEP";
    if (value == 59) return "IpConstOnhitCastspell.SLOW";
    if (value == 60) return "IpConstOnhitCastspell.SOUND_BURST";
    if (value == 101) return "IpConstOnhitCastspell.SPIKE_GROWTH";
    if (value == 61) return "IpConstOnhitCastspell.STINKING_CLOUD";
    if (value == 119) return "IpConstOnhitCastspell.STONEHOLD";
    if (value == 109) return "IpConstOnhitCastspell.STONE_TO_FLESH";
    if (value == 63) return "IpConstOnhitCastspell.STORM_OF_VENGEANCE";
    if (value == 64) return "IpConstOnhitCastspell.SUNBEAM";
    if (value == 84) return "IpConstOnhitCastspell.SUNBURST";
    if (value == 102) return "IpConstOnhitCastspell.TASHAS_HIDEOUS_LAUGHTER";
    if (value == 96) return "IpConstOnhitCastspell.UNDEATHS_ETERNAL_FOE";
    if (value == 118) return "IpConstOnhitCastspell.UNDEATH_TO_DEATH";
    if (value == 65) return "IpConstOnhitCastspell.VAMPIRIC_TOUCH";
    if (value == 66) return "IpConstOnhitCastspell.WAIL_OF_THE_BANSHEE";
    if (value == 67) return "IpConstOnhitCastspell.WALL_OF_FIRE";
    if (value == 68) return "IpConstOnhitCastspell.WEB";
    if (value == 69) return "IpConstOnhitCastspell.WEIRD";
    if (value == 70) return "IpConstOnhitCastspell.WORD_OF_FAITH";
    if (value == 95) return "IpConstOnhitCastspell.WOUNDING_WHISPERS";
    return "IpConstOnhitCastspell.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "IpConstOnhitCastspell.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "IpConstOnhitCastspell.(not found: " + value + ")";
  }
}
