package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "IP_CONST_ONHIT".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class IpConstOnhit {
  private IpConstOnhit() {}

  public final static int ABILITYDRAIN = 18;
  public final static int BLINDNESS = 16;
  public final static int CASTSPELL_ACID_FOG = 0;
  public final static int CASTSPELL_ACID_SPLASH = 81;
  public final static int CASTSPELL_ACTIVATE_ITEM = 78;
  public final static int CASTSPELL_BALAGARNSIRONHORN = 91;
  public final static int CASTSPELL_BALL_LIGHTNING = 113;
  public final static int CASTSPELL_BANE = 100;
  public final static int CASTSPELL_BANISHMENT = 85;
  public final static int CASTSPELL_BESTOW_CURSE = 1;
  public final static int CASTSPELL_BIGBYS_CLENCHED_FIST = 106;
  public final static int CASTSPELL_BIGBYS_CRUSHING_HAND = 107;
  public final static int CASTSPELL_BIGBYS_FORCEFUL_HAND = 104;
  public final static int CASTSPELL_BIGBYS_GRASPING_HAND = 105;
  public final static int CASTSPELL_BIGBYS_INTERPOSING_HAND = 103;
  public final static int CASTSPELL_BLADE_BARRIER = 2;
  public final static int CASTSPELL_BLINDNESS_AND_DEAFNESS = 3;
  public final static int CASTSPELL_BOMBARDMENT = 80;
  public final static int CASTSPELL_CALL_LIGHTNING = 4;
  public final static int CASTSPELL_CHAIN_LIGHTNING = 5;
  public final static int CASTSPELL_CLOUDKILL = 6;
  public final static int CASTSPELL_COMBUST = 140;
  public final static int CASTSPELL_CONFUSION = 7;
  public final static int CASTSPELL_CONTAGION = 8;
  public final static int CASTSPELL_CREEPING_DOOM = 72;
  public final static int CASTSPELL_CRUMBLE = 110;
  public final static int CASTSPELL_DARKNESS = 9;
  public final static int CASTSPELL_DAZE = 10;
  public final static int CASTSPELL_DEAFENING_CLNG = 137;
  public final static int CASTSPELL_DELAYED_BLAST_FIREBALL = 11;
  public final static int CASTSPELL_DESTRUCTION = 73;
  public final static int CASTSPELL_DISMISSAL = 12;
  public final static int CASTSPELL_DISPEL_MAGIC = 13;
  public final static int CASTSPELL_DOOM = 14;
  public final static int CASTSPELL_DROWN = 92;
  public final static int CASTSPELL_EARTHQUAKE = 83;
  public final static int CASTSPELL_ELECTRIC_JOLT = 93;
  public final static int CASTSPELL_ENERGY_DRAIN = 15;
  public final static int CASTSPELL_ENERVATION = 16;
  public final static int CASTSPELL_ENTANGLE = 17;
  public final static int CASTSPELL_EVARDS_BLACK_TENTACLES = 77;
  public final static int CASTSPELL_EVIL_BLIGHT = 121;
  public final static int CASTSPELL_FEAR = 18;
  public final static int CASTSPELL_FEEBLEMIND = 19;
  public final static int CASTSPELL_FIREBALL = 21;
  public final static int CASTSPELL_FIREBRAND = 94;
  public final static int CASTSPELL_FIRE_STORM = 20;
  public final static int CASTSPELL_FLAME_LASH = 22;
  public final static int CASTSPELL_FLAME_STRIKE = 23;
  public final static int CASTSPELL_FLARE = 79;
  public final static int CASTSPELL_FLESH_TO_STONE = 108;
  public final static int CASTSPELL_FREEZE = 139;
  public final static int CASTSPELL_GEDLEES_ELECTRIC_LOOP = 114;
  public final static int CASTSPELL_GHOUL_TOUCH = 24;
  public final static int CASTSPELL_GREASE = 25;
  public final static int CASTSPELL_GREATER_DISPELLING = 26;
  public final static int CASTSPELL_GREATER_SPELL_BREACH = 27;
  public final static int CASTSPELL_GREAT_THUNDERCLAP = 112;
  public final static int CASTSPELL_GUST_OF_WIND = 28;
  public final static int CASTSPELL_HAMMER_OF_THE_GODS = 29;
  public final static int CASTSPELL_HARM = 30;
  public final static int CASTSPELL_HOLD_ANIMAL = 31;
  public final static int CASTSPELL_HOLD_MONSTER = 32;
  public final static int CASTSPELL_HOLD_PERSON = 33;
  public final static int CASTSPELL_HORIZIKAULS_BOOM = 115;
  public final static int CASTSPELL_HORRID_WILTING = 74;
  public final static int CASTSPELL_ICE_STORM = 75;
  public final static int CASTSPELL_IMPLOSION = 34;
  public final static int CASTSPELL_INCENDIARY_CLOUD = 35;
  public final static int CASTSPELL_INFERNO = 97;
  public final static int CASTSPELL_INFESTATION_OF_MAGGOTS = 111;
  public final static int CASTSPELL_INFLICT_CRITICAL_WOUNDS = 90;
  public final static int CASTSPELL_INFLICT_LIGHT_WOUNDS = 87;
  public final static int CASTSPELL_INFLICT_MINOR_WOUNDS = 86;
  public final static int CASTSPELL_INFLICT_MODERATE_WOUNDS = 88;
  public final static int CASTSPELL_INFLICT_SERIOUS_WOUNDS = 89;
  public final static int CASTSPELL_INTELLIGENT_WEAPON_ONHIT = 135;
  public final static int CASTSPELL_ISAACS_GREATER_MISSILE_STORM = 99;
  public final static int CASTSPELL_ISAACS_LESSER_MISSILE_STORM = 98;
  public final static int CASTSPELL_KNOCKDOWN = 138;
  public final static int CASTSPELL_LESSER_DISPEL = 36;
  public final static int CASTSPELL_LESSER_SPELL_BREACH = 38;
  public final static int CASTSPELL_LIGHT = 40;
  public final static int CASTSPELL_LIGHTNING_BOLT = 41;
  public final static int CASTSPELL_MAGIC_MISSILE = 42;
  public final static int CASTSPELL_MASS_BLINDNESS_AND_DEAFNESS = 43;
  public final static int CASTSPELL_MASS_CHARM = 44;
  public final static int CASTSPELL_MELFS_ACID_ARROW = 45;
  public final static int CASTSPELL_MESTILS_ACID_BREATH = 116;
  public final static int CASTSPELL_METEOR_SWARM = 46;
  public final static int CASTSPELL_MIND_FOG = 47;
  public final static int CASTSPELL_NEGATIVE_ENERGY_BURST = 76;
  public final static int CASTSPELL_ONHITDEMILICHTOUCH = 133;
  public final static int CASTSPELL_ONHITDRACOLICHTOUCH = 134;
  public final static int CASTSPELL_ONHITFLAMINGSKIN = 129;
  public final static int CASTSPELL_ONHITRUINARMORBEBILITH = 132;
  public final static int CASTSPELL_ONHIT_CHAOSSHIELD = 130;
  public final static int CASTSPELL_ONHIT_CONSTRICTWEAPON = 131;
  public final static int CASTSPELL_ONHIT_DARKFIRE = 127;
  public final static int CASTSPELL_ONHIT_EXTRACTBRAIN = 128;
  public final static int CASTSPELL_ONHIT_FIREDAMAGE = 124;
  public final static int CASTSPELL_ONHIT_PLANARRIFT = 126;
  public final static int CASTSPELL_ONHIT_SLAYRAKSHASA = 123;
  public final static int CASTSPELL_ONHIT_TELEPORT = 122;
  public final static int CASTSPELL_ONHIT_UNIQUEPOWER = 125;
  public final static int CASTSPELL_PARALYZE_2 = 136;
  public final static int CASTSPELL_PHANTASMAL_KILLER = 49;
  public final static int CASTSPELL_POISON = 50;
  public final static int CASTSPELL_POWER_WORD_KILL = 51;
  public final static int CASTSPELL_POWER_WORD_STUN = 52;
  public final static int CASTSPELL_QUILLFIRE = 82;
  public final static int CASTSPELL_SCARE = 54;
  public final static int CASTSPELL_SCINTILLATING_SPHERE = 117;
  public final static int CASTSPELL_SEARING_LIGHT = 55;
  public final static int CASTSPELL_SILENCE = 56;
  public final static int CASTSPELL_SLAY_LIVING = 57;
  public final static int CASTSPELL_SLEEP = 58;
  public final static int CASTSPELL_SLOW = 59;
  public final static int CASTSPELL_SOUND_BURST = 60;
  public final static int CASTSPELL_SPIKE_GROWTH = 101;
  public final static int CASTSPELL_STINKING_CLOUD = 61;
  public final static int CASTSPELL_STONEHOLD = 119;
  public final static int CASTSPELL_STONE_TO_FLESH = 109;
  public final static int CASTSPELL_STORM_OF_VENGEANCE = 63;
  public final static int CASTSPELL_SUNBEAM = 64;
  public final static int CASTSPELL_SUNBURST = 84;
  public final static int CASTSPELL_TASHAS_HIDEOUS_LAUGHTER = 102;
  public final static int CASTSPELL_UNDEATHS_ETERNAL_FOE = 96;
  public final static int CASTSPELL_UNDEATH_TO_DEATH = 118;
  public final static int CASTSPELL_VAMPIRIC_TOUCH = 65;
  public final static int CASTSPELL_WAIL_OF_THE_BANSHEE = 66;
  public final static int CASTSPELL_WALL_OF_FIRE = 67;
  public final static int CASTSPELL_WEB = 68;
  public final static int CASTSPELL_WEIRD = 69;
  public final static int CASTSPELL_WORD_OF_FAITH = 70;
  public final static int CASTSPELL_WOUNDING_WHISPERS = 95;
  public final static int CONFUSION = 3;
  public final static int DAZE = 5;
  public final static int DEAFNESS = 15;
  public final static int DISEASE = 20;
  public final static int DISPELMAGIC = 11;
  public final static int DOOM = 6;
  public final static int DURATION_10_PERCENT_4_ROUNDS = 1;
  public final static int DURATION_25_PERCENT_3_ROUNDS = 2;
  public final static int DURATION_50_PERCENT_2_ROUNDS = 3;
  public final static int DURATION_5_PERCENT_5_ROUNDS = 0;
  public final static int DURATION_75_PERCENT_1_ROUND = 4;
  public final static int FEAR = 7;
  public final static int GREATERDISPEL = 12;
  public final static int HOLD = 2;
  public final static int ITEMPOISON = 19;
  public final static int KNOCK = 8;
  public final static int LESSERDISPEL = 10;
  public final static int LEVELDRAIN = 17;
  public final static int MORDSDISJUNCTION = 13;
  public final static int SAVEDC_14 = 0;
  public final static int SAVEDC_16 = 1;
  public final static int SAVEDC_18 = 2;
  public final static int SAVEDC_20 = 3;
  public final static int SAVEDC_22 = 4;
  public final static int SAVEDC_24 = 5;
  public final static int SAVEDC_26 = 6;
  public final static int SILENCE = 14;
  public final static int SLAYALIGNMENT = 23;
  public final static int SLAYALIGNMENTGROUP = 22;
  public final static int SLAYRACE = 21;
  public final static int SLEEP = 0;
  public final static int SLOW = 9;
  public final static int STUN = 1;
  public final static int VORPAL = 24;
  public final static int WOUNDING = 25;

  public static String nameOf(int value) {
    if (value == 18) return "IpConstOnhit.ABILITYDRAIN";
    if (value == 16) return "IpConstOnhit.BLINDNESS";
    if (value == 0) return "IpConstOnhit.CASTSPELL_ACID_FOG";
    if (value == 81) return "IpConstOnhit.CASTSPELL_ACID_SPLASH";
    if (value == 78) return "IpConstOnhit.CASTSPELL_ACTIVATE_ITEM";
    if (value == 91) return "IpConstOnhit.CASTSPELL_BALAGARNSIRONHORN";
    if (value == 113) return "IpConstOnhit.CASTSPELL_BALL_LIGHTNING";
    if (value == 100) return "IpConstOnhit.CASTSPELL_BANE";
    if (value == 85) return "IpConstOnhit.CASTSPELL_BANISHMENT";
    if (value == 1) return "IpConstOnhit.CASTSPELL_BESTOW_CURSE";
    if (value == 106) return "IpConstOnhit.CASTSPELL_BIGBYS_CLENCHED_FIST";
    if (value == 107) return "IpConstOnhit.CASTSPELL_BIGBYS_CRUSHING_HAND";
    if (value == 104) return "IpConstOnhit.CASTSPELL_BIGBYS_FORCEFUL_HAND";
    if (value == 105) return "IpConstOnhit.CASTSPELL_BIGBYS_GRASPING_HAND";
    if (value == 103) return "IpConstOnhit.CASTSPELL_BIGBYS_INTERPOSING_HAND";
    if (value == 2) return "IpConstOnhit.CASTSPELL_BLADE_BARRIER";
    if (value == 3) return "IpConstOnhit.CASTSPELL_BLINDNESS_AND_DEAFNESS";
    if (value == 80) return "IpConstOnhit.CASTSPELL_BOMBARDMENT";
    if (value == 4) return "IpConstOnhit.CASTSPELL_CALL_LIGHTNING";
    if (value == 5) return "IpConstOnhit.CASTSPELL_CHAIN_LIGHTNING";
    if (value == 6) return "IpConstOnhit.CASTSPELL_CLOUDKILL";
    if (value == 140) return "IpConstOnhit.CASTSPELL_COMBUST";
    if (value == 7) return "IpConstOnhit.CASTSPELL_CONFUSION";
    if (value == 8) return "IpConstOnhit.CASTSPELL_CONTAGION";
    if (value == 72) return "IpConstOnhit.CASTSPELL_CREEPING_DOOM";
    if (value == 110) return "IpConstOnhit.CASTSPELL_CRUMBLE";
    if (value == 9) return "IpConstOnhit.CASTSPELL_DARKNESS";
    if (value == 10) return "IpConstOnhit.CASTSPELL_DAZE";
    if (value == 137) return "IpConstOnhit.CASTSPELL_DEAFENING_CLNG";
    if (value == 11) return "IpConstOnhit.CASTSPELL_DELAYED_BLAST_FIREBALL";
    if (value == 73) return "IpConstOnhit.CASTSPELL_DESTRUCTION";
    if (value == 12) return "IpConstOnhit.CASTSPELL_DISMISSAL";
    if (value == 13) return "IpConstOnhit.CASTSPELL_DISPEL_MAGIC";
    if (value == 14) return "IpConstOnhit.CASTSPELL_DOOM";
    if (value == 92) return "IpConstOnhit.CASTSPELL_DROWN";
    if (value == 83) return "IpConstOnhit.CASTSPELL_EARTHQUAKE";
    if (value == 93) return "IpConstOnhit.CASTSPELL_ELECTRIC_JOLT";
    if (value == 15) return "IpConstOnhit.CASTSPELL_ENERGY_DRAIN";
    if (value == 16) return "IpConstOnhit.CASTSPELL_ENERVATION";
    if (value == 17) return "IpConstOnhit.CASTSPELL_ENTANGLE";
    if (value == 77) return "IpConstOnhit.CASTSPELL_EVARDS_BLACK_TENTACLES";
    if (value == 121) return "IpConstOnhit.CASTSPELL_EVIL_BLIGHT";
    if (value == 18) return "IpConstOnhit.CASTSPELL_FEAR";
    if (value == 19) return "IpConstOnhit.CASTSPELL_FEEBLEMIND";
    if (value == 21) return "IpConstOnhit.CASTSPELL_FIREBALL";
    if (value == 94) return "IpConstOnhit.CASTSPELL_FIREBRAND";
    if (value == 20) return "IpConstOnhit.CASTSPELL_FIRE_STORM";
    if (value == 22) return "IpConstOnhit.CASTSPELL_FLAME_LASH";
    if (value == 23) return "IpConstOnhit.CASTSPELL_FLAME_STRIKE";
    if (value == 79) return "IpConstOnhit.CASTSPELL_FLARE";
    if (value == 108) return "IpConstOnhit.CASTSPELL_FLESH_TO_STONE";
    if (value == 139) return "IpConstOnhit.CASTSPELL_FREEZE";
    if (value == 114) return "IpConstOnhit.CASTSPELL_GEDLEES_ELECTRIC_LOOP";
    if (value == 24) return "IpConstOnhit.CASTSPELL_GHOUL_TOUCH";
    if (value == 25) return "IpConstOnhit.CASTSPELL_GREASE";
    if (value == 26) return "IpConstOnhit.CASTSPELL_GREATER_DISPELLING";
    if (value == 27) return "IpConstOnhit.CASTSPELL_GREATER_SPELL_BREACH";
    if (value == 112) return "IpConstOnhit.CASTSPELL_GREAT_THUNDERCLAP";
    if (value == 28) return "IpConstOnhit.CASTSPELL_GUST_OF_WIND";
    if (value == 29) return "IpConstOnhit.CASTSPELL_HAMMER_OF_THE_GODS";
    if (value == 30) return "IpConstOnhit.CASTSPELL_HARM";
    if (value == 31) return "IpConstOnhit.CASTSPELL_HOLD_ANIMAL";
    if (value == 32) return "IpConstOnhit.CASTSPELL_HOLD_MONSTER";
    if (value == 33) return "IpConstOnhit.CASTSPELL_HOLD_PERSON";
    if (value == 115) return "IpConstOnhit.CASTSPELL_HORIZIKAULS_BOOM";
    if (value == 74) return "IpConstOnhit.CASTSPELL_HORRID_WILTING";
    if (value == 75) return "IpConstOnhit.CASTSPELL_ICE_STORM";
    if (value == 34) return "IpConstOnhit.CASTSPELL_IMPLOSION";
    if (value == 35) return "IpConstOnhit.CASTSPELL_INCENDIARY_CLOUD";
    if (value == 97) return "IpConstOnhit.CASTSPELL_INFERNO";
    if (value == 111) return "IpConstOnhit.CASTSPELL_INFESTATION_OF_MAGGOTS";
    if (value == 90) return "IpConstOnhit.CASTSPELL_INFLICT_CRITICAL_WOUNDS";
    if (value == 87) return "IpConstOnhit.CASTSPELL_INFLICT_LIGHT_WOUNDS";
    if (value == 86) return "IpConstOnhit.CASTSPELL_INFLICT_MINOR_WOUNDS";
    if (value == 88) return "IpConstOnhit.CASTSPELL_INFLICT_MODERATE_WOUNDS";
    if (value == 89) return "IpConstOnhit.CASTSPELL_INFLICT_SERIOUS_WOUNDS";
    if (value == 135) return "IpConstOnhit.CASTSPELL_INTELLIGENT_WEAPON_ONHIT";
    if (value == 99) return "IpConstOnhit.CASTSPELL_ISAACS_GREATER_MISSILE_STORM";
    if (value == 98) return "IpConstOnhit.CASTSPELL_ISAACS_LESSER_MISSILE_STORM";
    if (value == 138) return "IpConstOnhit.CASTSPELL_KNOCKDOWN";
    if (value == 36) return "IpConstOnhit.CASTSPELL_LESSER_DISPEL";
    if (value == 38) return "IpConstOnhit.CASTSPELL_LESSER_SPELL_BREACH";
    if (value == 40) return "IpConstOnhit.CASTSPELL_LIGHT";
    if (value == 41) return "IpConstOnhit.CASTSPELL_LIGHTNING_BOLT";
    if (value == 42) return "IpConstOnhit.CASTSPELL_MAGIC_MISSILE";
    if (value == 43) return "IpConstOnhit.CASTSPELL_MASS_BLINDNESS_AND_DEAFNESS";
    if (value == 44) return "IpConstOnhit.CASTSPELL_MASS_CHARM";
    if (value == 45) return "IpConstOnhit.CASTSPELL_MELFS_ACID_ARROW";
    if (value == 116) return "IpConstOnhit.CASTSPELL_MESTILS_ACID_BREATH";
    if (value == 46) return "IpConstOnhit.CASTSPELL_METEOR_SWARM";
    if (value == 47) return "IpConstOnhit.CASTSPELL_MIND_FOG";
    if (value == 76) return "IpConstOnhit.CASTSPELL_NEGATIVE_ENERGY_BURST";
    if (value == 133) return "IpConstOnhit.CASTSPELL_ONHITDEMILICHTOUCH";
    if (value == 134) return "IpConstOnhit.CASTSPELL_ONHITDRACOLICHTOUCH";
    if (value == 129) return "IpConstOnhit.CASTSPELL_ONHITFLAMINGSKIN";
    if (value == 132) return "IpConstOnhit.CASTSPELL_ONHITRUINARMORBEBILITH";
    if (value == 130) return "IpConstOnhit.CASTSPELL_ONHIT_CHAOSSHIELD";
    if (value == 131) return "IpConstOnhit.CASTSPELL_ONHIT_CONSTRICTWEAPON";
    if (value == 127) return "IpConstOnhit.CASTSPELL_ONHIT_DARKFIRE";
    if (value == 128) return "IpConstOnhit.CASTSPELL_ONHIT_EXTRACTBRAIN";
    if (value == 124) return "IpConstOnhit.CASTSPELL_ONHIT_FIREDAMAGE";
    if (value == 126) return "IpConstOnhit.CASTSPELL_ONHIT_PLANARRIFT";
    if (value == 123) return "IpConstOnhit.CASTSPELL_ONHIT_SLAYRAKSHASA";
    if (value == 122) return "IpConstOnhit.CASTSPELL_ONHIT_TELEPORT";
    if (value == 125) return "IpConstOnhit.CASTSPELL_ONHIT_UNIQUEPOWER";
    if (value == 136) return "IpConstOnhit.CASTSPELL_PARALYZE_2";
    if (value == 49) return "IpConstOnhit.CASTSPELL_PHANTASMAL_KILLER";
    if (value == 50) return "IpConstOnhit.CASTSPELL_POISON";
    if (value == 51) return "IpConstOnhit.CASTSPELL_POWER_WORD_KILL";
    if (value == 52) return "IpConstOnhit.CASTSPELL_POWER_WORD_STUN";
    if (value == 82) return "IpConstOnhit.CASTSPELL_QUILLFIRE";
    if (value == 54) return "IpConstOnhit.CASTSPELL_SCARE";
    if (value == 117) return "IpConstOnhit.CASTSPELL_SCINTILLATING_SPHERE";
    if (value == 55) return "IpConstOnhit.CASTSPELL_SEARING_LIGHT";
    if (value == 56) return "IpConstOnhit.CASTSPELL_SILENCE";
    if (value == 57) return "IpConstOnhit.CASTSPELL_SLAY_LIVING";
    if (value == 58) return "IpConstOnhit.CASTSPELL_SLEEP";
    if (value == 59) return "IpConstOnhit.CASTSPELL_SLOW";
    if (value == 60) return "IpConstOnhit.CASTSPELL_SOUND_BURST";
    if (value == 101) return "IpConstOnhit.CASTSPELL_SPIKE_GROWTH";
    if (value == 61) return "IpConstOnhit.CASTSPELL_STINKING_CLOUD";
    if (value == 119) return "IpConstOnhit.CASTSPELL_STONEHOLD";
    if (value == 109) return "IpConstOnhit.CASTSPELL_STONE_TO_FLESH";
    if (value == 63) return "IpConstOnhit.CASTSPELL_STORM_OF_VENGEANCE";
    if (value == 64) return "IpConstOnhit.CASTSPELL_SUNBEAM";
    if (value == 84) return "IpConstOnhit.CASTSPELL_SUNBURST";
    if (value == 102) return "IpConstOnhit.CASTSPELL_TASHAS_HIDEOUS_LAUGHTER";
    if (value == 96) return "IpConstOnhit.CASTSPELL_UNDEATHS_ETERNAL_FOE";
    if (value == 118) return "IpConstOnhit.CASTSPELL_UNDEATH_TO_DEATH";
    if (value == 65) return "IpConstOnhit.CASTSPELL_VAMPIRIC_TOUCH";
    if (value == 66) return "IpConstOnhit.CASTSPELL_WAIL_OF_THE_BANSHEE";
    if (value == 67) return "IpConstOnhit.CASTSPELL_WALL_OF_FIRE";
    if (value == 68) return "IpConstOnhit.CASTSPELL_WEB";
    if (value == 69) return "IpConstOnhit.CASTSPELL_WEIRD";
    if (value == 70) return "IpConstOnhit.CASTSPELL_WORD_OF_FAITH";
    if (value == 95) return "IpConstOnhit.CASTSPELL_WOUNDING_WHISPERS";
    if (value == 3) return "IpConstOnhit.CONFUSION";
    if (value == 5) return "IpConstOnhit.DAZE";
    if (value == 15) return "IpConstOnhit.DEAFNESS";
    if (value == 20) return "IpConstOnhit.DISEASE";
    if (value == 11) return "IpConstOnhit.DISPELMAGIC";
    if (value == 6) return "IpConstOnhit.DOOM";
    if (value == 1) return "IpConstOnhit.DURATION_10_PERCENT_4_ROUNDS";
    if (value == 2) return "IpConstOnhit.DURATION_25_PERCENT_3_ROUNDS";
    if (value == 3) return "IpConstOnhit.DURATION_50_PERCENT_2_ROUNDS";
    if (value == 0) return "IpConstOnhit.DURATION_5_PERCENT_5_ROUNDS";
    if (value == 4) return "IpConstOnhit.DURATION_75_PERCENT_1_ROUND";
    if (value == 7) return "IpConstOnhit.FEAR";
    if (value == 12) return "IpConstOnhit.GREATERDISPEL";
    if (value == 2) return "IpConstOnhit.HOLD";
    if (value == 19) return "IpConstOnhit.ITEMPOISON";
    if (value == 8) return "IpConstOnhit.KNOCK";
    if (value == 10) return "IpConstOnhit.LESSERDISPEL";
    if (value == 17) return "IpConstOnhit.LEVELDRAIN";
    if (value == 13) return "IpConstOnhit.MORDSDISJUNCTION";
    if (value == 0) return "IpConstOnhit.SAVEDC_14";
    if (value == 1) return "IpConstOnhit.SAVEDC_16";
    if (value == 2) return "IpConstOnhit.SAVEDC_18";
    if (value == 3) return "IpConstOnhit.SAVEDC_20";
    if (value == 4) return "IpConstOnhit.SAVEDC_22";
    if (value == 5) return "IpConstOnhit.SAVEDC_24";
    if (value == 6) return "IpConstOnhit.SAVEDC_26";
    if (value == 14) return "IpConstOnhit.SILENCE";
    if (value == 23) return "IpConstOnhit.SLAYALIGNMENT";
    if (value == 22) return "IpConstOnhit.SLAYALIGNMENTGROUP";
    if (value == 21) return "IpConstOnhit.SLAYRACE";
    if (value == 0) return "IpConstOnhit.SLEEP";
    if (value == 9) return "IpConstOnhit.SLOW";
    if (value == 1) return "IpConstOnhit.STUN";
    if (value == 24) return "IpConstOnhit.VORPAL";
    if (value == 25) return "IpConstOnhit.WOUNDING";
    return "IpConstOnhit.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "IpConstOnhit.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "IpConstOnhit.(not found: " + value + ")";
  }
}
