package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "IP_CONST_CASTSPELL".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class IpConstCastspell {
  private IpConstCastspell() {}

  public final static int ACID_FOG_11 = 0;
  public final static int ACID_SPLASH_1 = 355;
  public final static int ACTIVATE_ITEM = 359;
  public final static int AID_3 = 1;
  public final static int AMPLIFY_5 = 373;
  public final static int ANIMATE_DEAD_10 = 3;
  public final static int ANIMATE_DEAD_15 = 4;
  public final static int ANIMATE_DEAD_5 = 2;
  public final static int AURAOFGLORY_7 = 360;
  public final static int AURA_OF_VITALITY_13 = 321;
  public final static int AURA_VERSUS_ALIGNMENT_15 = 287;
  public final static int AWAKEN_9 = 303;
  public final static int BALAGARNSIRONHORN_7 = 367;
  public final static int BANE_5 = 380;
  public final static int BANISHMENT_15 = 361;
  public final static int BARKSKIN_12 = 7;
  public final static int BARKSKIN_3 = 5;
  public final static int BARKSKIN_6 = 6;
  public final static int BESTOW_CURSE_5 = 8;
  public final static int BIGBYS_CLENCHED_FIST_20 = 393;
  public final static int BIGBYS_CRUSHING_HAND_20 = 394;
  public final static int BIGBYS_FORCEFUL_HAND_15 = 391;
  public final static int BIGBYS_GRASPING_HAND_17 = 392;
  public final static int BIGBYS_INTERPOSING_HAND_15 = 390;
  public final static int BLADE_BARRIER_11 = 9;
  public final static int BLADE_BARRIER_15 = 10;
  public final static int BLESS_2 = 11;
  public final static int BLINDNESS_DEAFNESS_3 = 14;
  public final static int BLOOD_FRENZY_7 = 353;
  public final static int BOMBARDMENT_20 = 354;
  public final static int BULLS_STRENGTH_10 = 16;
  public final static int BULLS_STRENGTH_15 = 17;
  public final static int BULLS_STRENGTH_3 = 15;
  public final static int BURNING_HANDS_2 = 18;
  public final static int BURNING_HANDS_5 = 19;
  public final static int CALL_LIGHTNING_10 = 21;
  public final static int CALL_LIGHTNING_5 = 20;
  public final static int CAMOFLAGE_5 = 352;
  public final static int CATS_GRACE_10 = 26;
  public final static int CATS_GRACE_15 = 27;
  public final static int CATS_GRACE_3 = 25;
  public final static int CHAIN_LIGHTNING_11 = 28;
  public final static int CHAIN_LIGHTNING_15 = 29;
  public final static int CHAIN_LIGHTNING_20 = 30;
  public final static int CHARM_MONSTER_10 = 32;
  public final static int CHARM_MONSTER_5 = 31;
  public final static int CHARM_PERSON_10 = 34;
  public final static int CHARM_PERSON_2 = 33;
  public final static int CHARM_PERSON_OR_ANIMAL_10 = 36;
  public final static int CHARM_PERSON_OR_ANIMAL_3 = 35;
  public final static int CIRCLE_OF_DEATH_11 = 37;
  public final static int CIRCLE_OF_DEATH_15 = 38;
  public final static int CIRCLE_OF_DEATH_20 = 39;
  public final static int CIRCLE_OF_DOOM_15 = 41;
  public final static int CIRCLE_OF_DOOM_20 = 42;
  public final static int CIRCLE_OF_DOOM_9 = 40;
  public final static int CLAIRAUDIENCE_CLAIRVOYANCE_10 = 44;
  public final static int CLAIRAUDIENCE_CLAIRVOYANCE_15 = 45;
  public final static int CLAIRAUDIENCE_CLAIRVOYANCE_5 = 43;
  public final static int CLARITY_3 = 46;
  public final static int CLOUDKILL_9 = 48;
  public final static int COLOR_SPRAY_2 = 49;
  public final static int CONE_OF_COLD_15 = 51;
  public final static int CONE_OF_COLD_9 = 50;
  public final static int CONFUSION_10 = 53;
  public final static int CONFUSION_5 = 52;
  public final static int CONTAGION_5 = 54;
  public final static int CONTINUAL_FLAME_7 = 350;
  public final static int CONTROL_UNDEAD_13 = 55;
  public final static int CONTROL_UNDEAD_20 = 56;
  public final static int CREATE_GREATER_UNDEAD_15 = 57;
  public final static int CREATE_GREATER_UNDEAD_16 = 58;
  public final static int CREATE_GREATER_UNDEAD_18 = 59;
  public final static int CREATE_UNDEAD_11 = 60;
  public final static int CREATE_UNDEAD_14 = 61;
  public final static int CREATE_UNDEAD_16 = 62;
  public final static int CREEPING_DOOM_13 = 304;
  public final static int CURE_CRITICAL_WOUNDS_12 = 64;
  public final static int CURE_CRITICAL_WOUNDS_15 = 65;
  public final static int CURE_CRITICAL_WOUNDS_7 = 63;
  public final static int CURE_LIGHT_WOUNDS_2 = 66;
  public final static int CURE_LIGHT_WOUNDS_5 = 67;
  public final static int CURE_MINOR_WOUNDS_1 = 68;
  public final static int CURE_MODERATE_WOUNDS_10 = 71;
  public final static int CURE_MODERATE_WOUNDS_3 = 69;
  public final static int CURE_MODERATE_WOUNDS_6 = 70;
  public final static int CURE_SERIOUS_WOUNDS_10 = 73;
  public final static int CURE_SERIOUS_WOUNDS_5 = 72;
  public final static int DARKNESS_3 = 75;
  public final static int DARKVISION_3 = 305;
  public final static int DARKVISION_6 = 306;
  public final static int DAZE_1 = 76;
  public final static int DEATH_WARD_7 = 77;
  public final static int DELAYED_BLAST_FIREBALL_13 = 78;
  public final static int DELAYED_BLAST_FIREBALL_15 = 79;
  public final static int DELAYED_BLAST_FIREBALL_20 = 80;
  public final static int DESTRUCTION_13 = 307;
  public final static int DIRGE_15 = 376;
  public final static int DISMISSAL_12 = 82;
  public final static int DISMISSAL_18 = 83;
  public final static int DISMISSAL_7 = 81;
  public final static int DISPEL_MAGIC_10 = 85;
  public final static int DISPEL_MAGIC_5 = 84;
  public final static int DISPLACEMENT_9 = 389;
  public final static int DIVINE_FAVOR_5 = 345;
  public final static int DIVINE_MIGHT_5 = 395;
  public final static int DIVINE_POWER_7 = 86;
  public final static int DIVINE_SHIELD_5 = 396;
  public final static int DOMINATE_ANIMAL_5 = 87;
  public final static int DOMINATE_MONSTER_17 = 88;
  public final static int DOMINATE_PERSON_7 = 89;
  public final static int DOOM_2 = 90;
  public final static int DOOM_5 = 91;
  public final static int DRAGON_BREATH_ACID_10 = 400;
  public final static int DRAGON_BREATH_COLD_10 = 401;
  public final static int DRAGON_BREATH_FEAR_10 = 402;
  public final static int DRAGON_BREATH_FIRE_10 = 403;
  public final static int DRAGON_BREATH_GAS_10 = 404;
  public final static int DRAGON_BREATH_LIGHTNING_10 = 405;
  public final static int DRAGON_BREATH_PARALYZE_10 = 406;
  public final static int DRAGON_BREATH_SLEEP_10 = 407;
  public final static int DRAGON_BREATH_SLOW_10 = 408;
  public final static int DRAGON_BREATH_WEAKEN_10 = 409;
  public final static int DROWN_15 = 368;
  public final static int EAGLE_SPLEDOR_10 = 289;
  public final static int EAGLE_SPLEDOR_15 = 290;
  public final static int EAGLE_SPLEDOR_3 = 288;
  public final static int EARTHQUAKE_20 = 357;
  public final static int ELECTRIC_JOLT_1 = 370;
  public final static int ELEMENTAL_SHIELD_12 = 93;
  public final static int ELEMENTAL_SHIELD_7 = 92;
  public final static int ELEMENTAL_SWARM_17 = 94;
  public final static int ENDURANCE_10 = 96;
  public final static int ENDURANCE_15 = 97;
  public final static int ENDURANCE_3 = 95;
  public final static int ENDURE_ELEMENTS_2 = 98;
  public final static int ENERGY_BUFFER_11 = 311;
  public final static int ENERGY_BUFFER_15 = 312;
  public final static int ENERGY_BUFFER_20 = 313;
  public final static int ENERGY_DRAIN_17 = 99;
  public final static int ENERVATION_7 = 100;
  public final static int ENTANGLE_2 = 101;
  public final static int ENTANGLE_5 = 102;
  public final static int ENTROPIC_SHIELD_5 = 349;
  public final static int ETHEREALNESS_18 = 374;
  public final static int ETHEREAL_VISAGE_15 = 196;
  public final static int ETHEREAL_VISAGE_9 = 195;
  public final static int EVARDS_BLACK_TENTACLES_15 = 325;
  public final static int EVARDS_BLACK_TENTACLES_7 = 324;
  public final static int EXPEDITIOUS_RETREAT_5 = 387;
  public final static int FEAR_5 = 103;
  public final static int FEEBLEMIND_9 = 104;
  public final static int FIND_TRAPS_3 = 327;
  public final static int FINGER_OF_DEATH_13 = 105;
  public final static int FIREBALL_10 = 109;
  public final static int FIREBALL_5 = 108;
  public final static int FIREBRAND_15 = 371;
  public final static int FIRE_STORM_13 = 106;
  public final static int FIRE_STORM_18 = 107;
  public final static int FLAME_ARROW_12 = 111;
  public final static int FLAME_ARROW_18 = 112;
  public final static int FLAME_ARROW_5 = 110;
  public final static int FLAME_LASH_10 = 114;
  public final static int FLAME_LASH_3 = 113;
  public final static int FLAME_STRIKE_12 = 116;
  public final static int FLAME_STRIKE_18 = 117;
  public final static int FLAME_STRIKE_7 = 115;
  public final static int FLARE_1 = 347;
  public final static int FLESH_TO_STONE_5 = 398;
  public final static int FOXS_CUNNING_10 = 295;
  public final static int FOXS_CUNNING_15 = 296;
  public final static int FOXS_CUNNING_3 = 294;
  public final static int FREEDOM_OF_MOVEMENT_7 = 118;
  public final static int GATE_17 = 119;
  public final static int GHOSTLY_VISAGE_15 = 194;
  public final static int GHOSTLY_VISAGE_3 = 192;
  public final static int GHOSTLY_VISAGE_9 = 193;
  public final static int GHOUL_TOUCH_3 = 120;
  public final static int GLOBE_OF_INVULNERABILITY_11 = 121;
  public final static int GREASE_2 = 122;
  public final static int GREATER_BULLS_STRENGTH_11 = 300;
  public final static int GREATER_CATS_GRACE_11 = 301;
  public final static int GREATER_DISPELLING_15 = 124;
  public final static int GREATER_DISPELLING_7 = 123;
  public final static int GREATER_EAGLES_SPLENDOR_11 = 297;
  public final static int GREATER_ENDURANCE_11 = 302;
  public final static int GREATER_FOXS_CUNNING_11 = 299;
  public final static int GREATER_MAGIC_FANG_9 = 384;
  public final static int GREATER_OWLS_WISDOM_11 = 298;
  public final static int GREATER_PLANAR_BINDING_15 = 126;
  public final static int GREATER_RESTORATION_13 = 127;
  public final static int GREATER_SHADOW_CONJURATION_9 = 128;
  public final static int GREATER_SPELL_BREACH_11 = 129;
  public final static int GREATER_SPELL_MANTLE_17 = 130;
  public final static int GREATER_STONESKIN_11 = 131;
  public final static int GRENADE_ACID_1 = 341;
  public final static int GRENADE_CALTROPS_1 = 343;
  public final static int GRENADE_CHICKEN_1 = 342;
  public final static int GRENADE_CHOKING_1 = 339;
  public final static int GRENADE_FIRE_1 = 336;
  public final static int GRENADE_HOLY_1 = 338;
  public final static int GRENADE_TANGLE_1 = 337;
  public final static int GRENADE_THUNDERSTONE_1 = 340;
  public final static int GUST_OF_WIND_10 = 410;
  public final static int HAMMER_OF_THE_GODS_12 = 134;
  public final static int HAMMER_OF_THE_GODS_7 = 133;
  public final static int HARM_11 = 136;
  public final static int HASTE_10 = 138;
  public final static int HASTE_5 = 137;
  public final static int HEALING_CIRCLE_16 = 141;
  public final static int HEALING_CIRCLE_9 = 140;
  public final static int HEAL_11 = 139;
  public final static int HOLD_ANIMAL_3 = 142;
  public final static int HOLD_MONSTER_7 = 143;
  public final static int HOLD_PERSON_3 = 144;
  public final static int HORRID_WILTING_15 = 308;
  public final static int HORRID_WILTING_20 = 309;
  public final static int ICE_STORM_9 = 310;
  public final static int IDENTIFY_3 = 147;
  public final static int IMPLOSION_17 = 148;
  public final static int IMPROVED_INVISIBILITY_7 = 149;
  public final static int INCENDIARY_CLOUD_15 = 150;
  public final static int INFERNO_15 = 377;
  public final static int INFLICT_CRITICAL_WOUNDS_12 = 366;
  public final static int INFLICT_LIGHT_WOUNDS_5 = 363;
  public final static int INFLICT_MINOR_WOUNDS_1 = 362;
  public final static int INFLICT_MODERATE_WOUNDS_7 = 364;
  public final static int INFLICT_SERIOUS_WOUNDS_9 = 365;
  public final static int INVISIBILITY_3 = 151;
  public final static int INVISIBILITY_PURGE_5 = 152;
  public final static int INVISIBILITY_SPHERE_5 = 153;
  public final static int ISAACS_GREATER_MISSILE_STORM_15 = 379;
  public final static int ISAACS_LESSER_MISSILE_STORM_13 = 378;
  public final static int KNOCK_3 = 154;
  public final static int LEGEND_LORE_5 = 326;
  public final static int LESSER_DISPEL_3 = 155;
  public final static int LESSER_DISPEL_5 = 156;
  public final static int LESSER_MIND_BLANK_9 = 157;
  public final static int LESSER_PLANAR_BINDING_9 = 158;
  public final static int LESSER_RESTORATION_3 = 159;
  public final static int LESSER_SPELL_BREACH_7 = 160;
  public final static int LESSER_SPELL_MANTLE_9 = 161;
  public final static int LIGHTNING_BOLT_10 = 165;
  public final static int LIGHTNING_BOLT_5 = 164;
  public final static int LIGHT_1 = 162;
  public final static int LIGHT_5 = 163;
  public final static int MAGE_ARMOR_2 = 167;
  public final static int MAGIC_CIRCLE_AGAINST_ALIGNMENT_5 = 286;
  public final static int MAGIC_FANG_5 = 383;
  public final static int MAGIC_MISSILE_3 = 172;
  public final static int MAGIC_MISSILE_5 = 173;
  public final static int MAGIC_MISSILE_9 = 174;
  public final static int MANIPULATE_PORTAL_STONE = 344;
  public final static int MASS_BLINDNESS_DEAFNESS_15 = 179;
  public final static int MASS_CAMOFLAGE_13 = 386;
  public final static int MASS_CHARM_15 = 180;
  public final static int MASS_HASTE_11 = 182;
  public final static int MASS_HEAL_15 = 183;
  public final static int MELFS_ACID_ARROW_3 = 184;
  public final static int MELFS_ACID_ARROW_6 = 185;
  public final static int MELFS_ACID_ARROW_9 = 186;
  public final static int METEOR_SWARM_17 = 187;
  public final static int MIND_BLANK_15 = 188;
  public final static int MIND_FOG_9 = 189;
  public final static int MINOR_GLOBE_OF_INVULNERABILITY_15 = 191;
  public final static int MINOR_GLOBE_OF_INVULNERABILITY_7 = 190;
  public final static int MORDENKAINENS_DISJUNCTION_17 = 197;
  public final static int MORDENKAINENS_SWORD_13 = 198;
  public final static int MORDENKAINENS_SWORD_18 = 199;
  public final static int NATURES_BALANCE_15 = 200;
  public final static int NEGATIVE_ENERGY_BURST_10 = 315;
  public final static int NEGATIVE_ENERGY_BURST_5 = 314;
  public final static int NEGATIVE_ENERGY_PROTECTION_10 = 202;
  public final static int NEGATIVE_ENERGY_PROTECTION_15 = 203;
  public final static int NEGATIVE_ENERGY_PROTECTION_5 = 201;
  public final static int NEGATIVE_ENERGY_RAY_1 = 316;
  public final static int NEGATIVE_ENERGY_RAY_3 = 317;
  public final static int NEGATIVE_ENERGY_RAY_5 = 318;
  public final static int NEGATIVE_ENERGY_RAY_7 = 319;
  public final static int NEGATIVE_ENERGY_RAY_9 = 320;
  public final static int NEUTRALIZE_POISON_5 = 204;
  public final static int NUMUSES_0_CHARGES_PER_USE = 7;
  public final static int NUMUSES_1_CHARGE_PER_USE = 6;
  public final static int NUMUSES_1_USE_PER_DAY = 8;
  public final static int NUMUSES_2_CHARGES_PER_USE = 5;
  public final static int NUMUSES_2_USES_PER_DAY = 9;
  public final static int NUMUSES_3_CHARGES_PER_USE = 4;
  public final static int NUMUSES_3_USES_PER_DAY = 10;
  public final static int NUMUSES_4_CHARGES_PER_USE = 3;
  public final static int NUMUSES_4_USES_PER_DAY = 11;
  public final static int NUMUSES_5_CHARGES_PER_USE = 2;
  public final static int NUMUSES_5_USES_PER_DAY = 12;
  public final static int NUMUSES_SINGLE_USE = 1;
  public final static int NUMUSES_UNLIMITED_USE = 13;
  public final static int ONE_WITH_THE_LAND_7 = 351;
  public final static int OWLS_INSIGHT_15 = 369;
  public final static int OWLS_WISDOM_10 = 292;
  public final static int OWLS_WISDOM_15 = 293;
  public final static int OWLS_WISDOM_3 = 291;
  public final static int PHANTASMAL_KILLER_7 = 205;
  public final static int PLANAR_ALLY_15 = 382;
  public final static int PLANAR_BINDING_11 = 206;
  public final static int POISON_5 = 207;
  public final static int POLYMORPH_SELF_7 = 208;
  public final static int POWER_WORD_KILL_17 = 209;
  public final static int POWER_WORD_STUN_13 = 210;
  public final static int PRAYER_5 = 211;
  public final static int PREMONITION_15 = 212;
  public final static int PRISMATIC_SPRAY_13 = 213;
  public final static int PROTECTION_FROM_ALIGNMENT_2 = 284;
  public final static int PROTECTION_FROM_ALIGNMENT_5 = 285;
  public final static int PROTECTION_FROM_ELEMENTS_10 = 217;
  public final static int PROTECTION_FROM_ELEMENTS_3 = 216;
  public final static int PROTECTION_FROM_SPELLS_13 = 224;
  public final static int PROTECTION_FROM_SPELLS_20 = 225;
  public final static int QUILLFIRE_8 = 356;
  public final static int RAISE_DEAD_9 = 226;
  public final static int RAY_OF_ENFEEBLEMENT_2 = 227;
  public final static int RAY_OF_FROST_1 = 228;
  public final static int REGENERATE_13 = 323;
  public final static int REMOVE_BLINDNESS_DEAFNESS_5 = 229;
  public final static int REMOVE_CURSE_5 = 230;
  public final static int REMOVE_DISEASE_5 = 231;
  public final static int REMOVE_FEAR_2 = 232;
  public final static int REMOVE_PARALYSIS_3 = 233;
  public final static int RESISTANCE_2 = 236;
  public final static int RESISTANCE_5 = 237;
  public final static int RESIST_ELEMENTS_10 = 235;
  public final static int RESIST_ELEMENTS_3 = 234;
  public final static int RESTORATION_7 = 238;
  public final static int RESURRECTION_13 = 239;
  public final static int ROGUES_CUNNING_3 = 328;
  public final static int SANCTUARY_2 = 240;
  public final static int SCARE_2 = 241;
  public final static int SEARING_LIGHT_5 = 242;
  public final static int SEE_INVISIBILITY_3 = 243;
  public final static int SHADES_11 = 244;
  public final static int SHADOW_CONJURATION_7 = 245;
  public final static int SHADOW_SHIELD_13 = 246;
  public final static int SHAPECHANGE_17 = 247;
  public final static int SHIELD_5 = 348;
  public final static int SHIELD_OF_FAITH_5 = 381;
  public final static int SILENCE_3 = 249;
  public final static int SLAY_LIVING_9 = 250;
  public final static int SLEEP_2 = 251;
  public final static int SLEEP_5 = 252;
  public final static int SLOW_5 = 253;
  public final static int SOUND_BURST_3 = 254;
  public final static int SPECIAL_ALCOHOL_BEER = 330;
  public final static int SPECIAL_ALCOHOL_SPIRITS = 332;
  public final static int SPECIAL_ALCOHOL_WINE = 331;
  public final static int SPECIAL_HERB_BELLADONNA = 333;
  public final static int SPECIAL_HERB_GARLIC = 334;
  public final static int SPELL_MANTLE_13 = 257;
  public final static int SPELL_RESISTANCE_15 = 256;
  public final static int SPELL_RESISTANCE_9 = 255;
  public final static int SPIKE_GROWTH_9 = 385;
  public final static int STINKING_CLOUD_5 = 259;
  public final static int STONESKIN_7 = 260;
  public final static int STONE_TO_FLESH_5 = 399;
  public final static int STORM_OF_VENGEANCE_17 = 261;
  public final static int SUMMON_CREATURE_III_5 = 265;
  public final static int SUMMON_CREATURE_II_3 = 264;
  public final static int SUMMON_CREATURE_IV_7 = 266;
  public final static int SUMMON_CREATURE_IX_17 = 267;
  public final static int SUMMON_CREATURE_I_2 = 262;
  public final static int SUMMON_CREATURE_I_5 = 263;
  public final static int SUMMON_CREATURE_VIII_15 = 271;
  public final static int SUMMON_CREATURE_VII_13 = 270;
  public final static int SUMMON_CREATURE_VI_11 = 269;
  public final static int SUMMON_CREATURE_V_9 = 268;
  public final static int SUNBEAM_13 = 272;
  public final static int SUNBURST_20 = 358;
  public final static int TASHAS_HIDEOUS_LAUGHTER_7 = 388;
  public final static int TENSERS_TRANSFORMATION_11 = 273;
  public final static int TIME_STOP_17 = 274;
  public final static int TRUE_SEEING_9 = 275;
  public final static int TRUE_STRIKE_5 = 346;
  public final static int UNDEATHS_ETERNAL_FOE_20 = 375;
  public final static int UNIQUE_POWER = 329;
  public final static int UNIQUE_POWER_SELF_ONLY = 335;
  public final static int VAMPIRIC_TOUCH_5 = 277;
  public final static int VIRTUE_1 = 278;
  public final static int WAIL_OF_THE_BANSHEE_17 = 279;
  public final static int WALL_OF_FIRE_9 = 280;
  public final static int WAR_CRY_7 = 322;
  public final static int WEB_3 = 281;
  public final static int WEIRD_17 = 282;
  public final static int WORD_OF_FAITH_13 = 283;
  public final static int WOUNDING_WHISPERS_9 = 372;

  public static String nameOf(int value) {
    if (value == 0) return "IpConstCastspell.ACID_FOG_11";
    if (value == 355) return "IpConstCastspell.ACID_SPLASH_1";
    if (value == 359) return "IpConstCastspell.ACTIVATE_ITEM";
    if (value == 1) return "IpConstCastspell.AID_3";
    if (value == 373) return "IpConstCastspell.AMPLIFY_5";
    if (value == 3) return "IpConstCastspell.ANIMATE_DEAD_10";
    if (value == 4) return "IpConstCastspell.ANIMATE_DEAD_15";
    if (value == 2) return "IpConstCastspell.ANIMATE_DEAD_5";
    if (value == 360) return "IpConstCastspell.AURAOFGLORY_7";
    if (value == 321) return "IpConstCastspell.AURA_OF_VITALITY_13";
    if (value == 287) return "IpConstCastspell.AURA_VERSUS_ALIGNMENT_15";
    if (value == 303) return "IpConstCastspell.AWAKEN_9";
    if (value == 367) return "IpConstCastspell.BALAGARNSIRONHORN_7";
    if (value == 380) return "IpConstCastspell.BANE_5";
    if (value == 361) return "IpConstCastspell.BANISHMENT_15";
    if (value == 7) return "IpConstCastspell.BARKSKIN_12";
    if (value == 5) return "IpConstCastspell.BARKSKIN_3";
    if (value == 6) return "IpConstCastspell.BARKSKIN_6";
    if (value == 8) return "IpConstCastspell.BESTOW_CURSE_5";
    if (value == 393) return "IpConstCastspell.BIGBYS_CLENCHED_FIST_20";
    if (value == 394) return "IpConstCastspell.BIGBYS_CRUSHING_HAND_20";
    if (value == 391) return "IpConstCastspell.BIGBYS_FORCEFUL_HAND_15";
    if (value == 392) return "IpConstCastspell.BIGBYS_GRASPING_HAND_17";
    if (value == 390) return "IpConstCastspell.BIGBYS_INTERPOSING_HAND_15";
    if (value == 9) return "IpConstCastspell.BLADE_BARRIER_11";
    if (value == 10) return "IpConstCastspell.BLADE_BARRIER_15";
    if (value == 11) return "IpConstCastspell.BLESS_2";
    if (value == 14) return "IpConstCastspell.BLINDNESS_DEAFNESS_3";
    if (value == 353) return "IpConstCastspell.BLOOD_FRENZY_7";
    if (value == 354) return "IpConstCastspell.BOMBARDMENT_20";
    if (value == 16) return "IpConstCastspell.BULLS_STRENGTH_10";
    if (value == 17) return "IpConstCastspell.BULLS_STRENGTH_15";
    if (value == 15) return "IpConstCastspell.BULLS_STRENGTH_3";
    if (value == 18) return "IpConstCastspell.BURNING_HANDS_2";
    if (value == 19) return "IpConstCastspell.BURNING_HANDS_5";
    if (value == 21) return "IpConstCastspell.CALL_LIGHTNING_10";
    if (value == 20) return "IpConstCastspell.CALL_LIGHTNING_5";
    if (value == 352) return "IpConstCastspell.CAMOFLAGE_5";
    if (value == 26) return "IpConstCastspell.CATS_GRACE_10";
    if (value == 27) return "IpConstCastspell.CATS_GRACE_15";
    if (value == 25) return "IpConstCastspell.CATS_GRACE_3";
    if (value == 28) return "IpConstCastspell.CHAIN_LIGHTNING_11";
    if (value == 29) return "IpConstCastspell.CHAIN_LIGHTNING_15";
    if (value == 30) return "IpConstCastspell.CHAIN_LIGHTNING_20";
    if (value == 32) return "IpConstCastspell.CHARM_MONSTER_10";
    if (value == 31) return "IpConstCastspell.CHARM_MONSTER_5";
    if (value == 34) return "IpConstCastspell.CHARM_PERSON_10";
    if (value == 33) return "IpConstCastspell.CHARM_PERSON_2";
    if (value == 36) return "IpConstCastspell.CHARM_PERSON_OR_ANIMAL_10";
    if (value == 35) return "IpConstCastspell.CHARM_PERSON_OR_ANIMAL_3";
    if (value == 37) return "IpConstCastspell.CIRCLE_OF_DEATH_11";
    if (value == 38) return "IpConstCastspell.CIRCLE_OF_DEATH_15";
    if (value == 39) return "IpConstCastspell.CIRCLE_OF_DEATH_20";
    if (value == 41) return "IpConstCastspell.CIRCLE_OF_DOOM_15";
    if (value == 42) return "IpConstCastspell.CIRCLE_OF_DOOM_20";
    if (value == 40) return "IpConstCastspell.CIRCLE_OF_DOOM_9";
    if (value == 44) return "IpConstCastspell.CLAIRAUDIENCE_CLAIRVOYANCE_10";
    if (value == 45) return "IpConstCastspell.CLAIRAUDIENCE_CLAIRVOYANCE_15";
    if (value == 43) return "IpConstCastspell.CLAIRAUDIENCE_CLAIRVOYANCE_5";
    if (value == 46) return "IpConstCastspell.CLARITY_3";
    if (value == 48) return "IpConstCastspell.CLOUDKILL_9";
    if (value == 49) return "IpConstCastspell.COLOR_SPRAY_2";
    if (value == 51) return "IpConstCastspell.CONE_OF_COLD_15";
    if (value == 50) return "IpConstCastspell.CONE_OF_COLD_9";
    if (value == 53) return "IpConstCastspell.CONFUSION_10";
    if (value == 52) return "IpConstCastspell.CONFUSION_5";
    if (value == 54) return "IpConstCastspell.CONTAGION_5";
    if (value == 350) return "IpConstCastspell.CONTINUAL_FLAME_7";
    if (value == 55) return "IpConstCastspell.CONTROL_UNDEAD_13";
    if (value == 56) return "IpConstCastspell.CONTROL_UNDEAD_20";
    if (value == 57) return "IpConstCastspell.CREATE_GREATER_UNDEAD_15";
    if (value == 58) return "IpConstCastspell.CREATE_GREATER_UNDEAD_16";
    if (value == 59) return "IpConstCastspell.CREATE_GREATER_UNDEAD_18";
    if (value == 60) return "IpConstCastspell.CREATE_UNDEAD_11";
    if (value == 61) return "IpConstCastspell.CREATE_UNDEAD_14";
    if (value == 62) return "IpConstCastspell.CREATE_UNDEAD_16";
    if (value == 304) return "IpConstCastspell.CREEPING_DOOM_13";
    if (value == 64) return "IpConstCastspell.CURE_CRITICAL_WOUNDS_12";
    if (value == 65) return "IpConstCastspell.CURE_CRITICAL_WOUNDS_15";
    if (value == 63) return "IpConstCastspell.CURE_CRITICAL_WOUNDS_7";
    if (value == 66) return "IpConstCastspell.CURE_LIGHT_WOUNDS_2";
    if (value == 67) return "IpConstCastspell.CURE_LIGHT_WOUNDS_5";
    if (value == 68) return "IpConstCastspell.CURE_MINOR_WOUNDS_1";
    if (value == 71) return "IpConstCastspell.CURE_MODERATE_WOUNDS_10";
    if (value == 69) return "IpConstCastspell.CURE_MODERATE_WOUNDS_3";
    if (value == 70) return "IpConstCastspell.CURE_MODERATE_WOUNDS_6";
    if (value == 73) return "IpConstCastspell.CURE_SERIOUS_WOUNDS_10";
    if (value == 72) return "IpConstCastspell.CURE_SERIOUS_WOUNDS_5";
    if (value == 75) return "IpConstCastspell.DARKNESS_3";
    if (value == 305) return "IpConstCastspell.DARKVISION_3";
    if (value == 306) return "IpConstCastspell.DARKVISION_6";
    if (value == 76) return "IpConstCastspell.DAZE_1";
    if (value == 77) return "IpConstCastspell.DEATH_WARD_7";
    if (value == 78) return "IpConstCastspell.DELAYED_BLAST_FIREBALL_13";
    if (value == 79) return "IpConstCastspell.DELAYED_BLAST_FIREBALL_15";
    if (value == 80) return "IpConstCastspell.DELAYED_BLAST_FIREBALL_20";
    if (value == 307) return "IpConstCastspell.DESTRUCTION_13";
    if (value == 376) return "IpConstCastspell.DIRGE_15";
    if (value == 82) return "IpConstCastspell.DISMISSAL_12";
    if (value == 83) return "IpConstCastspell.DISMISSAL_18";
    if (value == 81) return "IpConstCastspell.DISMISSAL_7";
    if (value == 85) return "IpConstCastspell.DISPEL_MAGIC_10";
    if (value == 84) return "IpConstCastspell.DISPEL_MAGIC_5";
    if (value == 389) return "IpConstCastspell.DISPLACEMENT_9";
    if (value == 345) return "IpConstCastspell.DIVINE_FAVOR_5";
    if (value == 395) return "IpConstCastspell.DIVINE_MIGHT_5";
    if (value == 86) return "IpConstCastspell.DIVINE_POWER_7";
    if (value == 396) return "IpConstCastspell.DIVINE_SHIELD_5";
    if (value == 87) return "IpConstCastspell.DOMINATE_ANIMAL_5";
    if (value == 88) return "IpConstCastspell.DOMINATE_MONSTER_17";
    if (value == 89) return "IpConstCastspell.DOMINATE_PERSON_7";
    if (value == 90) return "IpConstCastspell.DOOM_2";
    if (value == 91) return "IpConstCastspell.DOOM_5";
    if (value == 400) return "IpConstCastspell.DRAGON_BREATH_ACID_10";
    if (value == 401) return "IpConstCastspell.DRAGON_BREATH_COLD_10";
    if (value == 402) return "IpConstCastspell.DRAGON_BREATH_FEAR_10";
    if (value == 403) return "IpConstCastspell.DRAGON_BREATH_FIRE_10";
    if (value == 404) return "IpConstCastspell.DRAGON_BREATH_GAS_10";
    if (value == 405) return "IpConstCastspell.DRAGON_BREATH_LIGHTNING_10";
    if (value == 406) return "IpConstCastspell.DRAGON_BREATH_PARALYZE_10";
    if (value == 407) return "IpConstCastspell.DRAGON_BREATH_SLEEP_10";
    if (value == 408) return "IpConstCastspell.DRAGON_BREATH_SLOW_10";
    if (value == 409) return "IpConstCastspell.DRAGON_BREATH_WEAKEN_10";
    if (value == 368) return "IpConstCastspell.DROWN_15";
    if (value == 289) return "IpConstCastspell.EAGLE_SPLEDOR_10";
    if (value == 290) return "IpConstCastspell.EAGLE_SPLEDOR_15";
    if (value == 288) return "IpConstCastspell.EAGLE_SPLEDOR_3";
    if (value == 357) return "IpConstCastspell.EARTHQUAKE_20";
    if (value == 370) return "IpConstCastspell.ELECTRIC_JOLT_1";
    if (value == 93) return "IpConstCastspell.ELEMENTAL_SHIELD_12";
    if (value == 92) return "IpConstCastspell.ELEMENTAL_SHIELD_7";
    if (value == 94) return "IpConstCastspell.ELEMENTAL_SWARM_17";
    if (value == 96) return "IpConstCastspell.ENDURANCE_10";
    if (value == 97) return "IpConstCastspell.ENDURANCE_15";
    if (value == 95) return "IpConstCastspell.ENDURANCE_3";
    if (value == 98) return "IpConstCastspell.ENDURE_ELEMENTS_2";
    if (value == 311) return "IpConstCastspell.ENERGY_BUFFER_11";
    if (value == 312) return "IpConstCastspell.ENERGY_BUFFER_15";
    if (value == 313) return "IpConstCastspell.ENERGY_BUFFER_20";
    if (value == 99) return "IpConstCastspell.ENERGY_DRAIN_17";
    if (value == 100) return "IpConstCastspell.ENERVATION_7";
    if (value == 101) return "IpConstCastspell.ENTANGLE_2";
    if (value == 102) return "IpConstCastspell.ENTANGLE_5";
    if (value == 349) return "IpConstCastspell.ENTROPIC_SHIELD_5";
    if (value == 374) return "IpConstCastspell.ETHEREALNESS_18";
    if (value == 196) return "IpConstCastspell.ETHEREAL_VISAGE_15";
    if (value == 195) return "IpConstCastspell.ETHEREAL_VISAGE_9";
    if (value == 325) return "IpConstCastspell.EVARDS_BLACK_TENTACLES_15";
    if (value == 324) return "IpConstCastspell.EVARDS_BLACK_TENTACLES_7";
    if (value == 387) return "IpConstCastspell.EXPEDITIOUS_RETREAT_5";
    if (value == 103) return "IpConstCastspell.FEAR_5";
    if (value == 104) return "IpConstCastspell.FEEBLEMIND_9";
    if (value == 327) return "IpConstCastspell.FIND_TRAPS_3";
    if (value == 105) return "IpConstCastspell.FINGER_OF_DEATH_13";
    if (value == 109) return "IpConstCastspell.FIREBALL_10";
    if (value == 108) return "IpConstCastspell.FIREBALL_5";
    if (value == 371) return "IpConstCastspell.FIREBRAND_15";
    if (value == 106) return "IpConstCastspell.FIRE_STORM_13";
    if (value == 107) return "IpConstCastspell.FIRE_STORM_18";
    if (value == 111) return "IpConstCastspell.FLAME_ARROW_12";
    if (value == 112) return "IpConstCastspell.FLAME_ARROW_18";
    if (value == 110) return "IpConstCastspell.FLAME_ARROW_5";
    if (value == 114) return "IpConstCastspell.FLAME_LASH_10";
    if (value == 113) return "IpConstCastspell.FLAME_LASH_3";
    if (value == 116) return "IpConstCastspell.FLAME_STRIKE_12";
    if (value == 117) return "IpConstCastspell.FLAME_STRIKE_18";
    if (value == 115) return "IpConstCastspell.FLAME_STRIKE_7";
    if (value == 347) return "IpConstCastspell.FLARE_1";
    if (value == 398) return "IpConstCastspell.FLESH_TO_STONE_5";
    if (value == 295) return "IpConstCastspell.FOXS_CUNNING_10";
    if (value == 296) return "IpConstCastspell.FOXS_CUNNING_15";
    if (value == 294) return "IpConstCastspell.FOXS_CUNNING_3";
    if (value == 118) return "IpConstCastspell.FREEDOM_OF_MOVEMENT_7";
    if (value == 119) return "IpConstCastspell.GATE_17";
    if (value == 194) return "IpConstCastspell.GHOSTLY_VISAGE_15";
    if (value == 192) return "IpConstCastspell.GHOSTLY_VISAGE_3";
    if (value == 193) return "IpConstCastspell.GHOSTLY_VISAGE_9";
    if (value == 120) return "IpConstCastspell.GHOUL_TOUCH_3";
    if (value == 121) return "IpConstCastspell.GLOBE_OF_INVULNERABILITY_11";
    if (value == 122) return "IpConstCastspell.GREASE_2";
    if (value == 300) return "IpConstCastspell.GREATER_BULLS_STRENGTH_11";
    if (value == 301) return "IpConstCastspell.GREATER_CATS_GRACE_11";
    if (value == 124) return "IpConstCastspell.GREATER_DISPELLING_15";
    if (value == 123) return "IpConstCastspell.GREATER_DISPELLING_7";
    if (value == 297) return "IpConstCastspell.GREATER_EAGLES_SPLENDOR_11";
    if (value == 302) return "IpConstCastspell.GREATER_ENDURANCE_11";
    if (value == 299) return "IpConstCastspell.GREATER_FOXS_CUNNING_11";
    if (value == 384) return "IpConstCastspell.GREATER_MAGIC_FANG_9";
    if (value == 298) return "IpConstCastspell.GREATER_OWLS_WISDOM_11";
    if (value == 126) return "IpConstCastspell.GREATER_PLANAR_BINDING_15";
    if (value == 127) return "IpConstCastspell.GREATER_RESTORATION_13";
    if (value == 128) return "IpConstCastspell.GREATER_SHADOW_CONJURATION_9";
    if (value == 129) return "IpConstCastspell.GREATER_SPELL_BREACH_11";
    if (value == 130) return "IpConstCastspell.GREATER_SPELL_MANTLE_17";
    if (value == 131) return "IpConstCastspell.GREATER_STONESKIN_11";
    if (value == 341) return "IpConstCastspell.GRENADE_ACID_1";
    if (value == 343) return "IpConstCastspell.GRENADE_CALTROPS_1";
    if (value == 342) return "IpConstCastspell.GRENADE_CHICKEN_1";
    if (value == 339) return "IpConstCastspell.GRENADE_CHOKING_1";
    if (value == 336) return "IpConstCastspell.GRENADE_FIRE_1";
    if (value == 338) return "IpConstCastspell.GRENADE_HOLY_1";
    if (value == 337) return "IpConstCastspell.GRENADE_TANGLE_1";
    if (value == 340) return "IpConstCastspell.GRENADE_THUNDERSTONE_1";
    if (value == 410) return "IpConstCastspell.GUST_OF_WIND_10";
    if (value == 134) return "IpConstCastspell.HAMMER_OF_THE_GODS_12";
    if (value == 133) return "IpConstCastspell.HAMMER_OF_THE_GODS_7";
    if (value == 136) return "IpConstCastspell.HARM_11";
    if (value == 138) return "IpConstCastspell.HASTE_10";
    if (value == 137) return "IpConstCastspell.HASTE_5";
    if (value == 141) return "IpConstCastspell.HEALING_CIRCLE_16";
    if (value == 140) return "IpConstCastspell.HEALING_CIRCLE_9";
    if (value == 139) return "IpConstCastspell.HEAL_11";
    if (value == 142) return "IpConstCastspell.HOLD_ANIMAL_3";
    if (value == 143) return "IpConstCastspell.HOLD_MONSTER_7";
    if (value == 144) return "IpConstCastspell.HOLD_PERSON_3";
    if (value == 308) return "IpConstCastspell.HORRID_WILTING_15";
    if (value == 309) return "IpConstCastspell.HORRID_WILTING_20";
    if (value == 310) return "IpConstCastspell.ICE_STORM_9";
    if (value == 147) return "IpConstCastspell.IDENTIFY_3";
    if (value == 148) return "IpConstCastspell.IMPLOSION_17";
    if (value == 149) return "IpConstCastspell.IMPROVED_INVISIBILITY_7";
    if (value == 150) return "IpConstCastspell.INCENDIARY_CLOUD_15";
    if (value == 377) return "IpConstCastspell.INFERNO_15";
    if (value == 366) return "IpConstCastspell.INFLICT_CRITICAL_WOUNDS_12";
    if (value == 363) return "IpConstCastspell.INFLICT_LIGHT_WOUNDS_5";
    if (value == 362) return "IpConstCastspell.INFLICT_MINOR_WOUNDS_1";
    if (value == 364) return "IpConstCastspell.INFLICT_MODERATE_WOUNDS_7";
    if (value == 365) return "IpConstCastspell.INFLICT_SERIOUS_WOUNDS_9";
    if (value == 151) return "IpConstCastspell.INVISIBILITY_3";
    if (value == 152) return "IpConstCastspell.INVISIBILITY_PURGE_5";
    if (value == 153) return "IpConstCastspell.INVISIBILITY_SPHERE_5";
    if (value == 379) return "IpConstCastspell.ISAACS_GREATER_MISSILE_STORM_15";
    if (value == 378) return "IpConstCastspell.ISAACS_LESSER_MISSILE_STORM_13";
    if (value == 154) return "IpConstCastspell.KNOCK_3";
    if (value == 326) return "IpConstCastspell.LEGEND_LORE_5";
    if (value == 155) return "IpConstCastspell.LESSER_DISPEL_3";
    if (value == 156) return "IpConstCastspell.LESSER_DISPEL_5";
    if (value == 157) return "IpConstCastspell.LESSER_MIND_BLANK_9";
    if (value == 158) return "IpConstCastspell.LESSER_PLANAR_BINDING_9";
    if (value == 159) return "IpConstCastspell.LESSER_RESTORATION_3";
    if (value == 160) return "IpConstCastspell.LESSER_SPELL_BREACH_7";
    if (value == 161) return "IpConstCastspell.LESSER_SPELL_MANTLE_9";
    if (value == 165) return "IpConstCastspell.LIGHTNING_BOLT_10";
    if (value == 164) return "IpConstCastspell.LIGHTNING_BOLT_5";
    if (value == 162) return "IpConstCastspell.LIGHT_1";
    if (value == 163) return "IpConstCastspell.LIGHT_5";
    if (value == 167) return "IpConstCastspell.MAGE_ARMOR_2";
    if (value == 286) return "IpConstCastspell.MAGIC_CIRCLE_AGAINST_ALIGNMENT_5";
    if (value == 383) return "IpConstCastspell.MAGIC_FANG_5";
    if (value == 172) return "IpConstCastspell.MAGIC_MISSILE_3";
    if (value == 173) return "IpConstCastspell.MAGIC_MISSILE_5";
    if (value == 174) return "IpConstCastspell.MAGIC_MISSILE_9";
    if (value == 344) return "IpConstCastspell.MANIPULATE_PORTAL_STONE";
    if (value == 179) return "IpConstCastspell.MASS_BLINDNESS_DEAFNESS_15";
    if (value == 386) return "IpConstCastspell.MASS_CAMOFLAGE_13";
    if (value == 180) return "IpConstCastspell.MASS_CHARM_15";
    if (value == 182) return "IpConstCastspell.MASS_HASTE_11";
    if (value == 183) return "IpConstCastspell.MASS_HEAL_15";
    if (value == 184) return "IpConstCastspell.MELFS_ACID_ARROW_3";
    if (value == 185) return "IpConstCastspell.MELFS_ACID_ARROW_6";
    if (value == 186) return "IpConstCastspell.MELFS_ACID_ARROW_9";
    if (value == 187) return "IpConstCastspell.METEOR_SWARM_17";
    if (value == 188) return "IpConstCastspell.MIND_BLANK_15";
    if (value == 189) return "IpConstCastspell.MIND_FOG_9";
    if (value == 191) return "IpConstCastspell.MINOR_GLOBE_OF_INVULNERABILITY_15";
    if (value == 190) return "IpConstCastspell.MINOR_GLOBE_OF_INVULNERABILITY_7";
    if (value == 197) return "IpConstCastspell.MORDENKAINENS_DISJUNCTION_17";
    if (value == 198) return "IpConstCastspell.MORDENKAINENS_SWORD_13";
    if (value == 199) return "IpConstCastspell.MORDENKAINENS_SWORD_18";
    if (value == 200) return "IpConstCastspell.NATURES_BALANCE_15";
    if (value == 315) return "IpConstCastspell.NEGATIVE_ENERGY_BURST_10";
    if (value == 314) return "IpConstCastspell.NEGATIVE_ENERGY_BURST_5";
    if (value == 202) return "IpConstCastspell.NEGATIVE_ENERGY_PROTECTION_10";
    if (value == 203) return "IpConstCastspell.NEGATIVE_ENERGY_PROTECTION_15";
    if (value == 201) return "IpConstCastspell.NEGATIVE_ENERGY_PROTECTION_5";
    if (value == 316) return "IpConstCastspell.NEGATIVE_ENERGY_RAY_1";
    if (value == 317) return "IpConstCastspell.NEGATIVE_ENERGY_RAY_3";
    if (value == 318) return "IpConstCastspell.NEGATIVE_ENERGY_RAY_5";
    if (value == 319) return "IpConstCastspell.NEGATIVE_ENERGY_RAY_7";
    if (value == 320) return "IpConstCastspell.NEGATIVE_ENERGY_RAY_9";
    if (value == 204) return "IpConstCastspell.NEUTRALIZE_POISON_5";
    if (value == 7) return "IpConstCastspell.NUMUSES_0_CHARGES_PER_USE";
    if (value == 6) return "IpConstCastspell.NUMUSES_1_CHARGE_PER_USE";
    if (value == 8) return "IpConstCastspell.NUMUSES_1_USE_PER_DAY";
    if (value == 5) return "IpConstCastspell.NUMUSES_2_CHARGES_PER_USE";
    if (value == 9) return "IpConstCastspell.NUMUSES_2_USES_PER_DAY";
    if (value == 4) return "IpConstCastspell.NUMUSES_3_CHARGES_PER_USE";
    if (value == 10) return "IpConstCastspell.NUMUSES_3_USES_PER_DAY";
    if (value == 3) return "IpConstCastspell.NUMUSES_4_CHARGES_PER_USE";
    if (value == 11) return "IpConstCastspell.NUMUSES_4_USES_PER_DAY";
    if (value == 2) return "IpConstCastspell.NUMUSES_5_CHARGES_PER_USE";
    if (value == 12) return "IpConstCastspell.NUMUSES_5_USES_PER_DAY";
    if (value == 1) return "IpConstCastspell.NUMUSES_SINGLE_USE";
    if (value == 13) return "IpConstCastspell.NUMUSES_UNLIMITED_USE";
    if (value == 351) return "IpConstCastspell.ONE_WITH_THE_LAND_7";
    if (value == 369) return "IpConstCastspell.OWLS_INSIGHT_15";
    if (value == 292) return "IpConstCastspell.OWLS_WISDOM_10";
    if (value == 293) return "IpConstCastspell.OWLS_WISDOM_15";
    if (value == 291) return "IpConstCastspell.OWLS_WISDOM_3";
    if (value == 205) return "IpConstCastspell.PHANTASMAL_KILLER_7";
    if (value == 382) return "IpConstCastspell.PLANAR_ALLY_15";
    if (value == 206) return "IpConstCastspell.PLANAR_BINDING_11";
    if (value == 207) return "IpConstCastspell.POISON_5";
    if (value == 208) return "IpConstCastspell.POLYMORPH_SELF_7";
    if (value == 209) return "IpConstCastspell.POWER_WORD_KILL_17";
    if (value == 210) return "IpConstCastspell.POWER_WORD_STUN_13";
    if (value == 211) return "IpConstCastspell.PRAYER_5";
    if (value == 212) return "IpConstCastspell.PREMONITION_15";
    if (value == 213) return "IpConstCastspell.PRISMATIC_SPRAY_13";
    if (value == 284) return "IpConstCastspell.PROTECTION_FROM_ALIGNMENT_2";
    if (value == 285) return "IpConstCastspell.PROTECTION_FROM_ALIGNMENT_5";
    if (value == 217) return "IpConstCastspell.PROTECTION_FROM_ELEMENTS_10";
    if (value == 216) return "IpConstCastspell.PROTECTION_FROM_ELEMENTS_3";
    if (value == 224) return "IpConstCastspell.PROTECTION_FROM_SPELLS_13";
    if (value == 225) return "IpConstCastspell.PROTECTION_FROM_SPELLS_20";
    if (value == 356) return "IpConstCastspell.QUILLFIRE_8";
    if (value == 226) return "IpConstCastspell.RAISE_DEAD_9";
    if (value == 227) return "IpConstCastspell.RAY_OF_ENFEEBLEMENT_2";
    if (value == 228) return "IpConstCastspell.RAY_OF_FROST_1";
    if (value == 323) return "IpConstCastspell.REGENERATE_13";
    if (value == 229) return "IpConstCastspell.REMOVE_BLINDNESS_DEAFNESS_5";
    if (value == 230) return "IpConstCastspell.REMOVE_CURSE_5";
    if (value == 231) return "IpConstCastspell.REMOVE_DISEASE_5";
    if (value == 232) return "IpConstCastspell.REMOVE_FEAR_2";
    if (value == 233) return "IpConstCastspell.REMOVE_PARALYSIS_3";
    if (value == 236) return "IpConstCastspell.RESISTANCE_2";
    if (value == 237) return "IpConstCastspell.RESISTANCE_5";
    if (value == 235) return "IpConstCastspell.RESIST_ELEMENTS_10";
    if (value == 234) return "IpConstCastspell.RESIST_ELEMENTS_3";
    if (value == 238) return "IpConstCastspell.RESTORATION_7";
    if (value == 239) return "IpConstCastspell.RESURRECTION_13";
    if (value == 328) return "IpConstCastspell.ROGUES_CUNNING_3";
    if (value == 240) return "IpConstCastspell.SANCTUARY_2";
    if (value == 241) return "IpConstCastspell.SCARE_2";
    if (value == 242) return "IpConstCastspell.SEARING_LIGHT_5";
    if (value == 243) return "IpConstCastspell.SEE_INVISIBILITY_3";
    if (value == 244) return "IpConstCastspell.SHADES_11";
    if (value == 245) return "IpConstCastspell.SHADOW_CONJURATION_7";
    if (value == 246) return "IpConstCastspell.SHADOW_SHIELD_13";
    if (value == 247) return "IpConstCastspell.SHAPECHANGE_17";
    if (value == 348) return "IpConstCastspell.SHIELD_5";
    if (value == 381) return "IpConstCastspell.SHIELD_OF_FAITH_5";
    if (value == 249) return "IpConstCastspell.SILENCE_3";
    if (value == 250) return "IpConstCastspell.SLAY_LIVING_9";
    if (value == 251) return "IpConstCastspell.SLEEP_2";
    if (value == 252) return "IpConstCastspell.SLEEP_5";
    if (value == 253) return "IpConstCastspell.SLOW_5";
    if (value == 254) return "IpConstCastspell.SOUND_BURST_3";
    if (value == 330) return "IpConstCastspell.SPECIAL_ALCOHOL_BEER";
    if (value == 332) return "IpConstCastspell.SPECIAL_ALCOHOL_SPIRITS";
    if (value == 331) return "IpConstCastspell.SPECIAL_ALCOHOL_WINE";
    if (value == 333) return "IpConstCastspell.SPECIAL_HERB_BELLADONNA";
    if (value == 334) return "IpConstCastspell.SPECIAL_HERB_GARLIC";
    if (value == 257) return "IpConstCastspell.SPELL_MANTLE_13";
    if (value == 256) return "IpConstCastspell.SPELL_RESISTANCE_15";
    if (value == 255) return "IpConstCastspell.SPELL_RESISTANCE_9";
    if (value == 385) return "IpConstCastspell.SPIKE_GROWTH_9";
    if (value == 259) return "IpConstCastspell.STINKING_CLOUD_5";
    if (value == 260) return "IpConstCastspell.STONESKIN_7";
    if (value == 399) return "IpConstCastspell.STONE_TO_FLESH_5";
    if (value == 261) return "IpConstCastspell.STORM_OF_VENGEANCE_17";
    if (value == 265) return "IpConstCastspell.SUMMON_CREATURE_III_5";
    if (value == 264) return "IpConstCastspell.SUMMON_CREATURE_II_3";
    if (value == 266) return "IpConstCastspell.SUMMON_CREATURE_IV_7";
    if (value == 267) return "IpConstCastspell.SUMMON_CREATURE_IX_17";
    if (value == 262) return "IpConstCastspell.SUMMON_CREATURE_I_2";
    if (value == 263) return "IpConstCastspell.SUMMON_CREATURE_I_5";
    if (value == 271) return "IpConstCastspell.SUMMON_CREATURE_VIII_15";
    if (value == 270) return "IpConstCastspell.SUMMON_CREATURE_VII_13";
    if (value == 269) return "IpConstCastspell.SUMMON_CREATURE_VI_11";
    if (value == 268) return "IpConstCastspell.SUMMON_CREATURE_V_9";
    if (value == 272) return "IpConstCastspell.SUNBEAM_13";
    if (value == 358) return "IpConstCastspell.SUNBURST_20";
    if (value == 388) return "IpConstCastspell.TASHAS_HIDEOUS_LAUGHTER_7";
    if (value == 273) return "IpConstCastspell.TENSERS_TRANSFORMATION_11";
    if (value == 274) return "IpConstCastspell.TIME_STOP_17";
    if (value == 275) return "IpConstCastspell.TRUE_SEEING_9";
    if (value == 346) return "IpConstCastspell.TRUE_STRIKE_5";
    if (value == 375) return "IpConstCastspell.UNDEATHS_ETERNAL_FOE_20";
    if (value == 329) return "IpConstCastspell.UNIQUE_POWER";
    if (value == 335) return "IpConstCastspell.UNIQUE_POWER_SELF_ONLY";
    if (value == 277) return "IpConstCastspell.VAMPIRIC_TOUCH_5";
    if (value == 278) return "IpConstCastspell.VIRTUE_1";
    if (value == 279) return "IpConstCastspell.WAIL_OF_THE_BANSHEE_17";
    if (value == 280) return "IpConstCastspell.WALL_OF_FIRE_9";
    if (value == 322) return "IpConstCastspell.WAR_CRY_7";
    if (value == 281) return "IpConstCastspell.WEB_3";
    if (value == 282) return "IpConstCastspell.WEIRD_17";
    if (value == 283) return "IpConstCastspell.WORD_OF_FAITH_13";
    if (value == 372) return "IpConstCastspell.WOUNDING_WHISPERS_9";
    return "IpConstCastspell.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "IpConstCastspell.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "IpConstCastspell.(not found: " + value + ")";
  }
}
