package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "PACKAGE".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class Package {
  private Package() {}

  public final static int ABERRATION = 73;
  public final static int ANIMAL = 74;
  public final static int ARCANE_ARCHER = 65;
  public final static int ASSASSIN = 66;
  public final static int BARBARIAN = 0;
  public final static int BARBARIAN_BLACKGUARD = 90;
  public final static int BARBARIAN_BLACKGUARD_2NDCLASS = 118;
  public final static int BARBARIAN_BRUTE = 15;
  public final static int BARBARIAN_ORCBLOOD = 18;
  public final static int BARBARIAN_SAVAGE = 17;
  public final static int BARBARIAN_SLAYER = 16;
  public final static int BARD = 1;
  public final static int BARD_BLADE = 43;
  public final static int BARD_GALLANT = 44;
  public final static int BARD_HARPER = 91;
  public final static int BARD_HARPER_2NDCLASS = 119;
  public final static int BARD_JESTER = 45;
  public final static int BARD_LOREMASTER = 46;
  public final static int BEAST = 83;
  public final static int BLACKGUARD = 67;
  public final static int CLERIC = 2;
  public final static int CLERIC_BATTLE_PRIEST = 22;
  public final static int CLERIC_DEADWALKER = 20;
  public final static int CLERIC_DIVINE = 92;
  public final static int CLERIC_DIVINE_2NDCLASS = 120;
  public final static int CLERIC_ELEMENTALIST = 21;
  public final static int CLERIC_SHAMAN = 19;
  public final static int COMMONER = 82;
  public final static int CONSTRUCT = 75;
  public final static int DIVINE_CHAMPION = 109;
  public final static int DRAGON = 80;
  public final static int DRAGON_DISCIPLE = 111;
  public final static int DRUID = 3;
  public final static int DRUID_DEATH = 13;
  public final static int DRUID_GRAY = 12;
  public final static int DRUID_HAWKMASTER = 14;
  public final static int DRUID_INTERLOPER = 11;
  public final static int DRUID_SHIFTER = 93;
  public final static int DRUID_SHIFTER_2NDCLASS = 121;
  public final static int DWARVEN_DEFENDER = 89;
  public final static int ELEMENTAL = 78;
  public final static int FEY = 79;
  public final static int FIGHTER = 4;
  public final static int FIGHTER_COMMANDER = 26;
  public final static int FIGHTER_FINESSE = 23;
  public final static int FIGHTER_GLADIATOR = 25;
  public final static int FIGHTER_PIRATE = 24;
  public final static int FIGHTER_WEAPONMASTER = 94;
  public final static int FIGHTER_WEAPONMASTER_2NDCLASS = 122;
  public final static int GIANT = 84;
  public final static int HARPER = 64;
  public final static int HUMANOID = 76;
  public final static int INVALID = 255;
  public final static int MAGICBEAST = 85;
  public final static int MONK = 5;
  public final static int MONK_ASSASSIN = 95;
  public final static int MONK_ASSASSIN_2NDCLASS = 123;
  public final static int MONK_DEVOUT = 49;
  public final static int MONK_GIFTED = 48;
  public final static int MONK_PEASANT = 50;
  public final static int MONK_SPIRIT = 47;
  public final static int MONSTROUS = 77;
  public final static int NPC_ARIBETH_BLACKGUARD = 130;
  public final static int NPC_ARIBETH_PALADIN = 129;
  public final static int NPC_BARBARIAN_DAELAN = 105;
  public final static int NPC_BARD = 72;
  public final static int NPC_BARD_DEEKIN_2 = 117;
  public final static int NPC_BARD_FIGHTER = 106;
  public final static int NPC_BARD_FIGHTER_SHARWYN2 = 114;
  public final static int NPC_CLERIC_LINU = 104;
  public final static int NPC_FT_WEAPONMASTER = 102;
  public final static int NPC_FT_WEAPONMASTER_VALEN_2 = 113;
  public final static int NPC_PALADIN_FALLING = 107;
  public final static int NPC_RG_SHADOWDANCER = 103;
  public final static int NPC_RG_TOMI_2 = 116;
  public final static int NPC_ROGUE = 71;
  public final static int NPC_SORCERER = 70;
  public final static int NPC_WIZASSASSIN = 101;
  public final static int NPC_WIZASSASSIN_NATHYRRA = 115;
  public final static int OUTSIDER = 86;
  public final static int PALADIN = 6;
  public final static int PALADIN_CHAMPION = 54;
  public final static int PALADIN_DIVINE = 96;
  public final static int PALADIN_DIVINE_2NDCLASS = 124;
  public final static int PALADIN_ERRANT = 51;
  public final static int PALADIN_INQUISITOR = 53;
  public final static int PALADIN_UNDEAD = 52;
  public final static int PALE_MASTER = 110;
  public final static int RANGER = 7;
  public final static int RANGER_ARCANEARCHER = 97;
  public final static int RANGER_ARCANEARCHER_2NDCLASS = 125;
  public final static int RANGER_GIANTKILLER = 58;
  public final static int RANGER_MARKSMAN = 55;
  public final static int RANGER_STALKER = 57;
  public final static int RANGER_WARDEN = 56;
  public final static int ROGUE = 8;
  public final static int ROGUE_BANDIT = 60;
  public final static int ROGUE_GYPSY = 59;
  public final static int ROGUE_SCOUT = 61;
  public final static int ROGUE_SHADOWDANCER = 98;
  public final static int ROGUE_SHADOWDANCER_2NDCLASS = 126;
  public final static int ROGUE_SWASHBUCKLER = 62;
  public final static int SHADOWDANCER = 63;
  public final static int SHAPECHANGER = 87;
  public final static int SHIFTER = 108;
  public final static int SORCERER = 9;
  public final static int SORCERER_ABJURATION = 35;
  public final static int SORCERER_CONJURATION = 36;
  public final static int SORCERER_DIVINATION = 37;
  public final static int SORCERER_DRAGONDISCIPLE = 99;
  public final static int SORCERER_DRAGONDISCIPLE_2NDCLASS = 127;
  public final static int SORCERER_ENCHANTMENT = 38;
  public final static int SORCERER_EVOCATION = 39;
  public final static int SORCERER_ILLUSION = 40;
  public final static int SORCERER_NECROMANCY = 41;
  public final static int SORCERER_TRANSMUTATION = 42;
  public final static int UNDEAD = 81;
  public final static int VERMIN = 88;
  public final static int WEAPONMASTER = 112;
  public final static int WIZARDGENERALIST = 10;
  public final static int WIZARD_ABJURATION = 27;
  public final static int WIZARD_CONJURATION = 28;
  public final static int WIZARD_DIVINATION = 29;
  public final static int WIZARD_ENCHANTMENT = 30;
  public final static int WIZARD_EVOCATION = 31;
  public final static int WIZARD_ILLUSION = 32;
  public final static int WIZARD_NECROMANCY = 33;
  public final static int WIZARD_PALEMASTER = 100;
  public final static int WIZARD_PALEMASTER_2NDCLASS = 128;
  public final static int WIZARD_TRANSMUTATION = 34;

  public static String nameOf(int value) {
    if (value == 73) return "Package.ABERRATION";
    if (value == 74) return "Package.ANIMAL";
    if (value == 65) return "Package.ARCANE_ARCHER";
    if (value == 66) return "Package.ASSASSIN";
    if (value == 0) return "Package.BARBARIAN";
    if (value == 90) return "Package.BARBARIAN_BLACKGUARD";
    if (value == 118) return "Package.BARBARIAN_BLACKGUARD_2NDCLASS";
    if (value == 15) return "Package.BARBARIAN_BRUTE";
    if (value == 18) return "Package.BARBARIAN_ORCBLOOD";
    if (value == 17) return "Package.BARBARIAN_SAVAGE";
    if (value == 16) return "Package.BARBARIAN_SLAYER";
    if (value == 1) return "Package.BARD";
    if (value == 43) return "Package.BARD_BLADE";
    if (value == 44) return "Package.BARD_GALLANT";
    if (value == 91) return "Package.BARD_HARPER";
    if (value == 119) return "Package.BARD_HARPER_2NDCLASS";
    if (value == 45) return "Package.BARD_JESTER";
    if (value == 46) return "Package.BARD_LOREMASTER";
    if (value == 83) return "Package.BEAST";
    if (value == 67) return "Package.BLACKGUARD";
    if (value == 2) return "Package.CLERIC";
    if (value == 22) return "Package.CLERIC_BATTLE_PRIEST";
    if (value == 20) return "Package.CLERIC_DEADWALKER";
    if (value == 92) return "Package.CLERIC_DIVINE";
    if (value == 120) return "Package.CLERIC_DIVINE_2NDCLASS";
    if (value == 21) return "Package.CLERIC_ELEMENTALIST";
    if (value == 19) return "Package.CLERIC_SHAMAN";
    if (value == 82) return "Package.COMMONER";
    if (value == 75) return "Package.CONSTRUCT";
    if (value == 109) return "Package.DIVINE_CHAMPION";
    if (value == 80) return "Package.DRAGON";
    if (value == 111) return "Package.DRAGON_DISCIPLE";
    if (value == 3) return "Package.DRUID";
    if (value == 13) return "Package.DRUID_DEATH";
    if (value == 12) return "Package.DRUID_GRAY";
    if (value == 14) return "Package.DRUID_HAWKMASTER";
    if (value == 11) return "Package.DRUID_INTERLOPER";
    if (value == 93) return "Package.DRUID_SHIFTER";
    if (value == 121) return "Package.DRUID_SHIFTER_2NDCLASS";
    if (value == 89) return "Package.DWARVEN_DEFENDER";
    if (value == 78) return "Package.ELEMENTAL";
    if (value == 79) return "Package.FEY";
    if (value == 4) return "Package.FIGHTER";
    if (value == 26) return "Package.FIGHTER_COMMANDER";
    if (value == 23) return "Package.FIGHTER_FINESSE";
    if (value == 25) return "Package.FIGHTER_GLADIATOR";
    if (value == 24) return "Package.FIGHTER_PIRATE";
    if (value == 94) return "Package.FIGHTER_WEAPONMASTER";
    if (value == 122) return "Package.FIGHTER_WEAPONMASTER_2NDCLASS";
    if (value == 84) return "Package.GIANT";
    if (value == 64) return "Package.HARPER";
    if (value == 76) return "Package.HUMANOID";
    if (value == 255) return "Package.INVALID";
    if (value == 85) return "Package.MAGICBEAST";
    if (value == 5) return "Package.MONK";
    if (value == 95) return "Package.MONK_ASSASSIN";
    if (value == 123) return "Package.MONK_ASSASSIN_2NDCLASS";
    if (value == 49) return "Package.MONK_DEVOUT";
    if (value == 48) return "Package.MONK_GIFTED";
    if (value == 50) return "Package.MONK_PEASANT";
    if (value == 47) return "Package.MONK_SPIRIT";
    if (value == 77) return "Package.MONSTROUS";
    if (value == 130) return "Package.NPC_ARIBETH_BLACKGUARD";
    if (value == 129) return "Package.NPC_ARIBETH_PALADIN";
    if (value == 105) return "Package.NPC_BARBARIAN_DAELAN";
    if (value == 72) return "Package.NPC_BARD";
    if (value == 117) return "Package.NPC_BARD_DEEKIN_2";
    if (value == 106) return "Package.NPC_BARD_FIGHTER";
    if (value == 114) return "Package.NPC_BARD_FIGHTER_SHARWYN2";
    if (value == 104) return "Package.NPC_CLERIC_LINU";
    if (value == 102) return "Package.NPC_FT_WEAPONMASTER";
    if (value == 113) return "Package.NPC_FT_WEAPONMASTER_VALEN_2";
    if (value == 107) return "Package.NPC_PALADIN_FALLING";
    if (value == 103) return "Package.NPC_RG_SHADOWDANCER";
    if (value == 116) return "Package.NPC_RG_TOMI_2";
    if (value == 71) return "Package.NPC_ROGUE";
    if (value == 70) return "Package.NPC_SORCERER";
    if (value == 101) return "Package.NPC_WIZASSASSIN";
    if (value == 115) return "Package.NPC_WIZASSASSIN_NATHYRRA";
    if (value == 86) return "Package.OUTSIDER";
    if (value == 6) return "Package.PALADIN";
    if (value == 54) return "Package.PALADIN_CHAMPION";
    if (value == 96) return "Package.PALADIN_DIVINE";
    if (value == 124) return "Package.PALADIN_DIVINE_2NDCLASS";
    if (value == 51) return "Package.PALADIN_ERRANT";
    if (value == 53) return "Package.PALADIN_INQUISITOR";
    if (value == 52) return "Package.PALADIN_UNDEAD";
    if (value == 110) return "Package.PALE_MASTER";
    if (value == 7) return "Package.RANGER";
    if (value == 97) return "Package.RANGER_ARCANEARCHER";
    if (value == 125) return "Package.RANGER_ARCANEARCHER_2NDCLASS";
    if (value == 58) return "Package.RANGER_GIANTKILLER";
    if (value == 55) return "Package.RANGER_MARKSMAN";
    if (value == 57) return "Package.RANGER_STALKER";
    if (value == 56) return "Package.RANGER_WARDEN";
    if (value == 8) return "Package.ROGUE";
    if (value == 60) return "Package.ROGUE_BANDIT";
    if (value == 59) return "Package.ROGUE_GYPSY";
    if (value == 61) return "Package.ROGUE_SCOUT";
    if (value == 98) return "Package.ROGUE_SHADOWDANCER";
    if (value == 126) return "Package.ROGUE_SHADOWDANCER_2NDCLASS";
    if (value == 62) return "Package.ROGUE_SWASHBUCKLER";
    if (value == 63) return "Package.SHADOWDANCER";
    if (value == 87) return "Package.SHAPECHANGER";
    if (value == 108) return "Package.SHIFTER";
    if (value == 9) return "Package.SORCERER";
    if (value == 35) return "Package.SORCERER_ABJURATION";
    if (value == 36) return "Package.SORCERER_CONJURATION";
    if (value == 37) return "Package.SORCERER_DIVINATION";
    if (value == 99) return "Package.SORCERER_DRAGONDISCIPLE";
    if (value == 127) return "Package.SORCERER_DRAGONDISCIPLE_2NDCLASS";
    if (value == 38) return "Package.SORCERER_ENCHANTMENT";
    if (value == 39) return "Package.SORCERER_EVOCATION";
    if (value == 40) return "Package.SORCERER_ILLUSION";
    if (value == 41) return "Package.SORCERER_NECROMANCY";
    if (value == 42) return "Package.SORCERER_TRANSMUTATION";
    if (value == 81) return "Package.UNDEAD";
    if (value == 88) return "Package.VERMIN";
    if (value == 112) return "Package.WEAPONMASTER";
    if (value == 10) return "Package.WIZARDGENERALIST";
    if (value == 27) return "Package.WIZARD_ABJURATION";
    if (value == 28) return "Package.WIZARD_CONJURATION";
    if (value == 29) return "Package.WIZARD_DIVINATION";
    if (value == 30) return "Package.WIZARD_ENCHANTMENT";
    if (value == 31) return "Package.WIZARD_EVOCATION";
    if (value == 32) return "Package.WIZARD_ILLUSION";
    if (value == 33) return "Package.WIZARD_NECROMANCY";
    if (value == 100) return "Package.WIZARD_PALEMASTER";
    if (value == 128) return "Package.WIZARD_PALEMASTER_2NDCLASS";
    if (value == 34) return "Package.WIZARD_TRANSMUTATION";
    return "Package.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "Package.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "Package.(not found: " + value + ")";
  }
}
