package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "SPELL".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class Spell {
  private Spell() {}

  public final static int ACID_FOG = 0;
  public final static int ACID_SPLASH = 424;
  public final static int ACTIVATE_ITEM_PORTAL = 472;
  public final static int ACTIVATE_ITEM_SELF2 = 428;
  public final static int AID = 1;
  public final static int ALL_SPELLS = -1;
  public final static int AMPLIFY = 442;
  public final static int ANIMATE_DEAD = 2;
  public final static int AURAOFGLORY = 429;
  public final static int AURA_OF_VITALITY = 372;
  public final static int AWAKEN = 363;
  public final static int BALAGARNSIRONHORN = 436;
  public final static int BALL_LIGHTNING = 516;
  public final static int BANE = 449;
  public final static int BANISHMENT = 430;
  public final static int BARKSKIN = 3;
  public final static int BATTLETIDE = 517;
  public final static int BESTOW_CURSE = 4;
  public final static int BIGBYS_CLENCHED_FIST = 462;
  public final static int BIGBYS_CRUSHING_HAND = 463;
  public final static int BIGBYS_FORCEFUL_HAND = 460;
  public final static int BIGBYS_GRASPING_HAND = 461;
  public final static int BIGBYS_INTERPOSING_HAND = 459;
  public final static int BLACKSTAFF = 541;
  public final static int BLACK_BLADE_OF_DISASTER = 533;
  public final static int BLADE_BARRIER = 5;
  public final static int BLADE_THIRST = 535;
  public final static int BLESS = 6;
  public final static int BLESS_WEAPON = 537;
  public final static int BLINDNESS_AND_DEAFNESS = 8;
  public final static int BLOOD_FRENZY = 422;
  public final static int BOMBARDMENT = 423;
  public final static int BULLS_STRENGTH = 9;
  public final static int BURNING_HANDS = 10;
  public final static int CALL_LIGHTNING = 11;
  public final static int CAMOFLAGE = 421;
  public final static int CATS_GRACE = 13;
  public final static int CHAIN_LIGHTNING = 14;
  public final static int CHARGER = 500;
  public final static int CHARM_MONSTER = 15;
  public final static int CHARM_PERSON = 16;
  public final static int CHARM_PERSON_OR_ANIMAL = 17;
  public final static int CIRCLE_OF_DEATH = 18;
  public final static int CIRCLE_OF_DOOM = 19;
  public final static int CLAIRAUDIENCE_AND_CLAIRVOYANCE = 20;
  public final static int CLARITY = 21;
  public final static int CLOAK_OF_CHAOS = 22;
  public final static int CLOUDKILL = 23;
  public final static int CLOUD_OF_BEWILDERMENT = 569;
  public final static int COLOR_SPRAY = 24;
  public final static int COMBUST = 518;
  public final static int CONE_OF_COLD = 25;
  public final static int CONFUSION = 26;
  public final static int CONTAGION = 27;
  public final static int CONTINUAL_FLAME = 419;
  public final static int CONTROL_UNDEAD = 28;
  public final static int CRAFT_ADD_ITEM_PROPERTY = 654;
  public final static int CRAFT_CRAFT_ARMOR_SKILL = 657;
  public final static int CRAFT_CRAFT_WEAPON_SKILL = 656;
  public final static int CRAFT_DYE_CLOTHCOLOR_1 = 648;
  public final static int CRAFT_DYE_CLOTHCOLOR_2 = 649;
  public final static int CRAFT_DYE_LEATHERCOLOR_1 = 650;
  public final static int CRAFT_DYE_LEATHERCOLOR_2 = 651;
  public final static int CRAFT_DYE_METALCOLOR_1 = 652;
  public final static int CRAFT_DYE_METALCOLOR_2 = 653;
  public final static int CRAFT_HARPER_ITEM = 479;
  public final static int CRAFT_POISON_WEAPON_OR_AMMO = 655;
  public final static int CREATE_GREATER_UNDEAD = 29;
  public final static int CREATE_UNDEAD = 30;
  public final static int CREEPING_DOOM = 364;
  public final static int CRUMBLE = 512;
  public final static int CURE_CRITICAL_WOUNDS = 31;
  public final static int CURE_LIGHT_WOUNDS = 32;
  public final static int CURE_MINOR_WOUNDS = 33;
  public final static int CURE_MODERATE_WOUNDS = 34;
  public final static int CURE_SERIOUS_WOUNDS = 35;
  public final static int DARKFIRE = 548;
  public final static int DARKNESS = 36;
  public final static int DARKVISION = 365;
  public final static int DAZE = 37;
  public final static int DEAFENING_CLANG = 536;
  public final static int DEATH_ARMOR = 519;
  public final static int DEATH_WARD = 38;
  public final static int DECHARGER = 510;
  public final static int DECK_AVATAR = 503;
  public final static int DECK_BUTTERFLYSPRAY = 505;
  public final static int DECK_GEMSPRAY = 504;
  public final static int DECK_OF_MANY_THINGS = 500;
  public final static int DELAYED_BLAST_FIREBALL = 39;
  public final static int DESTRUCTION = 366;
  public final static int DIRGE = 445;
  public final static int DISMISSAL = 40;
  public final static int DISPEL_MAGIC = 41;
  public final static int DISPLACEMENT = 458;
  public final static int DIVINE_FAVOR = 414;
  public final static int DIVINE_MIGHT = 473;
  public final static int DIVINE_POWER = 42;
  public final static int DIVINE_SHIELD = 474;
  public final static int DOMINATE_ANIMAL = 43;
  public final static int DOMINATE_MONSTER = 44;
  public final static int DOMINATE_PERSON = 45;
  public final static int DOOM = 46;
  public final static int DROWN = 437;
  public final static int EAGLE_SPLEDOR = 354;
  public final static int EARTHQUAKE = 426;
  public final static int ELECTRIC_JOLT = 439;
  public final static int ELEMENTAL_SHIELD = 47;
  public final static int ELEMENTAL_SUMMONING_ITEM = 502;
  public final static int ELEMENTAL_SWARM = 48;
  public final static int ENDURANCE = 49;
  public final static int ENDURE_ELEMENTS = 50;
  public final static int ENERGY_BUFFER = 369;
  public final static int ENERGY_DRAIN = 51;
  public final static int ENERVATION = 52;
  public final static int ENTANGLE = 53;
  public final static int ENTROPIC_SHIELD = 418;
  public final static int EPIC_DRAGON_KNIGHT = 638;
  public final static int EPIC_HELLBALL = 636;
  public final static int EPIC_MAGE_ARMOR = 639;
  public final static int EPIC_MUMMY_DUST = 637;
  public final static int EPIC_RUIN = 640;
  public final static int ETHEREALNESS = 443;
  public final static int ETHEREAL_VISAGE = 121;
  public final static int EVARDS_BLACK_TENTACLES = 375;
  public final static int EXPEDITIOUS_RETREAT = 456;
  public final static int FEAR = 54;
  public final static int FEEBLEMIND = 55;
  public final static int FIND_TRAPS = 377;
  public final static int FINGER_OF_DEATH = 56;
  public final static int FIREBALL = 58;
  public final static int FIREBRAND = 440;
  public final static int FIRE_STORM = 57;
  public final static int FLAME_ARROW = 59;
  public final static int FLAME_LASH = 60;
  public final static int FLAME_STRIKE = 61;
  public final static int FLAME_WEAPON = 542;
  public final static int FLARE = 416;
  public final static int FLESH_TO_STONE = 485;
  public final static int FLYING_DEBRIS = 620;
  public final static int FOXS_CUNNING = 356;
  public final static int FREEDOM_OF_MOVEMENT = 62;
  public final static int GATE = 63;
  public final static int GEDLEES_ELECTRIC_LOOP = 520;
  public final static int GHOSTLY_VISAGE = 120;
  public final static int GHOUL_TOUCH = 64;
  public final static int GLOBE_OF_INVULNERABILITY = 65;
  public final static int GLYPH_OF_WARDING = 549;
  public final static int GREASE = 66;
  public final static int GREATER_BREACH = 72;
  public final static int GREATER_BULLS_STRENGTH = 360;
  public final static int GREATER_CATS_GRACE = 361;
  public final static int GREATER_DISPELLING = 67;
  public final static int GREATER_EAGLE_SPLENDOR = 357;
  public final static int GREATER_ENDURANCE = 362;
  public final static int GREATER_FOXS_CUNNING = 359;
  public final static int GREATER_MAGIC_FANG = 453;
  public final static int GREATER_MAGIC_WEAPON = 545;
  public final static int GREATER_MANTLE = 73;
  public final static int GREATER_OWLS_WISDOM = 358;
  public final static int GREATER_PLANAR_BINDING = 69;
  public final static int GREATER_RESTORATION = 70;
  public final static int GREATER_SHADOW_CONJURATION_ACID_ARROW = 350;
  public final static int GREATER_SHADOW_CONJURATION_MINOR_GLOBE = 353;
  public final static int GREATER_SHADOW_CONJURATION_MIRROR_IMAGE = 351;
  public final static int GREATER_SHADOW_CONJURATION_SUMMON_SHADOW = 349;
  public final static int GREATER_SHADOW_CONJURATION_WEB = 352;
  public final static int GREATER_STONESKIN = 74;
  public final static int GREAT_THUNDERCLAP = 515;
  public final static int GRENADE_ACID = 469;
  public final static int GRENADE_CALTROPS = 471;
  public final static int GRENADE_CHICKEN = 470;
  public final static int GRENADE_CHOKING = 467;
  public final static int GRENADE_FIRE = 464;
  public final static int GRENADE_HOLY = 466;
  public final static int GRENADE_TANGLE = 465;
  public final static int GRENADE_THUNDERSTONE = 468;
  public final static int GUST_OF_WIND = 75;
  public final static int HAMMER_OF_THE_GODS = 76;
  public final static int HARM = 77;
  public final static int HASTE = 78;
  public final static int HEAL = 79;
  public final static int HEALINGKIT = 506;
  public final static int HEALING_CIRCLE = 80;
  public final static int HEALING_STING = 514;
  public final static int HOLD_ANIMAL = 81;
  public final static int HOLD_MONSTER = 82;
  public final static int HOLD_PERSON = 83;
  public final static int HOLY_AURA = 84;
  public final static int HOLY_SWORD = 538;
  public final static int HORIZIKAULS_BOOM = 521;
  public final static int HORRID_WILTING = 367;
  public final static int HORSE_ASSIGN_MOUNT = 817;
  public final static int HORSE_DISMOUNT = 814;
  public final static int HORSE_MENU = 812;
  public final static int HORSE_MOUNT = 813;
  public final static int HORSE_PARTY_DISMOUNT = 816;
  public final static int HORSE_PARTY_MOUNT = 815;
  public final static int ICE_DAGGER = 543;
  public final static int ICE_STORM = 368;
  public final static int IDENTIFY = 86;
  public final static int IMPLOSION = 87;
  public final static int IMPROVED_INVISIBILITY = 88;
  public final static int INCENDIARY_CLOUD = 89;
  public final static int INFERNO = 446;
  public final static int INFESTATION_OF_MAGGOTS = 513;
  public final static int INFLICT_CRITICAL_WOUNDS = 435;
  public final static int INFLICT_LIGHT_WOUNDS = 432;
  public final static int INFLICT_MINOR_WOUNDS = 431;
  public final static int INFLICT_MODERATE_WOUNDS = 433;
  public final static int INFLICT_SERIOUS_WOUNDS = 434;
  public final static int INVISIBILITY = 90;
  public final static int INVISIBILITY_PURGE = 91;
  public final static int INVISIBILITY_SPHERE = 92;
  public final static int IOUN_STONE_BLUE = 557;
  public final static int IOUN_STONE_DEEP_RED = 558;
  public final static int IOUN_STONE_DUSTY_ROSE = 554;
  public final static int IOUN_STONE_PALE_BLUE = 555;
  public final static int IOUN_STONE_PINK = 559;
  public final static int IOUN_STONE_PINK_GREEN = 560;
  public final static int IOUN_STONE_SCARLET_BLUE = 556;
  public final static int IRONGUTS = 522;
  public final static int ISAACS_GREATER_MISSILE_STORM = 448;
  public final static int ISAACS_LESSER_MISSILE_STORM = 447;
  public final static int KEEN_EDGE = 539;
  public final static int KNOCK = 93;
  public final static int KOBOLD_JUMP = 511;
  public final static int LEGEND_LORE = 376;
  public final static int LESSER_BREACH = 98;
  public final static int LESSER_DISPEL = 94;
  public final static int LESSER_MANTLE = 99;
  public final static int LESSER_MIND_BLANK = 95;
  public final static int LESSER_PLANAR_BINDING = 96;
  public final static int LESSER_RESTORATION = 97;
  public final static int LIGHT = 100;
  public final static int LIGHTNING_BOLT = 101;
  public final static int MAGE_ARMOR = 102;
  public final static int MAGIC_CIRCLE_AGAINST_CHAOS = 103;
  public final static int MAGIC_CIRCLE_AGAINST_EVIL = 104;
  public final static int MAGIC_CIRCLE_AGAINST_GOOD = 105;
  public final static int MAGIC_CIRCLE_AGAINST_LAW = 106;
  public final static int MAGIC_FANG = 452;
  public final static int MAGIC_MISSILE = 107;
  public final static int MAGIC_VESTMENT = 546;
  public final static int MAGIC_WEAPON = 544;
  public final static int MANTLE = 169;
  public final static int MASS_BLINDNESS_AND_DEAFNESS = 110;
  public final static int MASS_CAMOFLAGE = 455;
  public final static int MASS_CHARM = 111;
  public final static int MASS_HASTE = 113;
  public final static int MASS_HEAL = 114;
  public final static int MELFS_ACID_ARROW = 115;
  public final static int MESTILS_ACID_BREATH = 523;
  public final static int MESTILS_ACID_SHEATH = 524;
  public final static int METEOR_SWARM = 116;
  public final static int MIND_BLANK = 117;
  public final static int MIND_FOG = 118;
  public final static int MINOR_GLOBE_OF_INVULNERABILITY = 119;
  public final static int MONSTROUS_REGENERATION = 525;
  public final static int MORDENKAINENS_DISJUNCTION = 122;
  public final static int MORDENKAINENS_SWORD = 123;
  public final static int NATURES_BALANCE = 124;
  public final static int NEGATIVE_ENERGY_BURST = 370;
  public final static int NEGATIVE_ENERGY_PROTECTION = 125;
  public final static int NEGATIVE_ENERGY_RAY = 371;
  public final static int NEUTRALIZE_POISON = 126;
  public final static int ONE_WITH_THE_LAND = 420;
  public final static int OWLS_INSIGHT = 438;
  public final static int OWLS_WISDOM = 355;
  public final static int PALADIN_SUMMON_MOUNT = 818;
  public final static int PHANTASMAL_KILLER = 127;
  public final static int PLANAR_ALLY = 451;
  public final static int PLANAR_BINDING = 128;
  public final static int POISON = 129;
  public final static int POLYMORPH_SELF = 130;
  public final static int POWERSTONE = 507;
  public final static int POWER_WORD_KILL = 131;
  public final static int POWER_WORD_STUN = 132;
  public final static int PRAYER = 133;
  public final static int PREMONITION = 134;
  public final static int PRISMATIC_SPRAY = 135;
  public final static int PROTECTION_FROM_ELEMENTS = 137;
  public final static int PROTECTION_FROM_EVIL = 138;
  public final static int PROTECTION_FROM_GOOD = 139;
  public final static int PROTECTION_FROM_LAW = 140;
  public final static int PROTECTION_FROM_SPELLS = 141;
  public final static int PROTECTION__FROM_CHAOS = 136;
  public final static int QUILLFIRE = 425;
  public final static int RAISE_DEAD = 142;
  public final static int RAY_OF_ENFEEBLEMENT = 143;
  public final static int RAY_OF_FROST = 144;
  public final static int REGENERATE = 374;
  public final static int REMOVE_BLINDNESS_AND_DEAFNESS = 145;
  public final static int REMOVE_CURSE = 146;
  public final static int REMOVE_DISEASE = 147;
  public final static int REMOVE_FEAR = 148;
  public final static int REMOVE_PARALYSIS = 149;
  public final static int RESISTANCE = 168;
  public final static int RESIST_ELEMENTS = 150;
  public final static int RESTORATION = 152;
  public final static int RESURRECTION = 153;
  public final static int ROD_OF_WONDER = 499;
  public final static int SANCTUARY = 154;
  public final static int SCARE = 155;
  public final static int SCHOOL_ABJURATION = 1;
  public final static int SCHOOL_CONJURATION = 2;
  public final static int SCHOOL_DIVINATION = 3;
  public final static int SCHOOL_ENCHANTMENT = 4;
  public final static int SCHOOL_EVOCATION = 5;
  public final static int SCHOOL_GENERAL = 0;
  public final static int SCHOOL_ILLUSION = 6;
  public final static int SCHOOL_NECROMANCY = 7;
  public final static int SCHOOL_TRANSMUTATION = 8;
  public final static int SCINTILLATING_SPHERE = 526;
  public final static int SEARING_LIGHT = 156;
  public final static int SEE_INVISIBILITY = 157;
  public final static int SHADES_CONE_OF_COLD = 340;
  public final static int SHADES_FIREBALL = 341;
  public final static int SHADES_STONESKIN = 342;
  public final static int SHADES_SUMMON_SHADOW = 324;
  public final static int SHADES_WALL_OF_FIRE = 343;
  public final static int SHADOW_CONJURATION_DARKNESS = 345;
  public final static int SHADOW_CONJURATION_INIVSIBILITY = 346;
  public final static int SHADOW_CONJURATION_MAGE_ARMOR = 347;
  public final static int SHADOW_CONJURATION_MAGIC_MISSILE = 348;
  public final static int SHADOW_CONJURATION_SUMMON_SHADOW = 344;
  public final static int SHADOW_DAZE = 475;
  public final static int SHADOW_EVADE = 477;
  public final static int SHADOW_SHIELD = 160;
  public final static int SHAPECHANGE = 161;
  public final static int SHELGARNS_PERSISTENT_BLADE = 534;
  public final static int SHIELD = 417;
  public final static int SHIELD_OF_FAITH = 450;
  public final static int SHIELD_OF_LAW = 162;
  public final static int SILENCE = 163;
  public final static int SLAY_LIVING = 164;
  public final static int SLEEP = 165;
  public final static int SLOW = 166;
  public final static int SOUND_BURST = 167;
  public final static int SPELLSTAFF = 508;
  public final static int SPHERE_OF_CHAOS = 170;
  public final static int SPIKE_GROWTH = 454;
  public final static int STINKING_CLOUD = 171;
  public final static int STONEHOLD = 547;
  public final static int STONESKIN = 172;
  public final static int STONE_BONES = 527;
  public final static int STONE_TO_FLESH = 486;
  public final static int STORM_OF_VENGEANCE = 173;
  public final static int SUMMON_CREATURE_I = 174;
  public final static int SUMMON_CREATURE_II = 175;
  public final static int SUMMON_CREATURE_III = 176;
  public final static int SUMMON_CREATURE_IV = 177;
  public final static int SUMMON_CREATURE_IX = 178;
  public final static int SUMMON_CREATURE_V = 179;
  public final static int SUMMON_CREATURE_VI = 180;
  public final static int SUMMON_CREATURE_VII = 181;
  public final static int SUMMON_CREATURE_VIII = 182;
  public final static int SUMMON_SHADOW = 476;
  public final static int SUNBEAM = 183;
  public final static int SUNBURST = 427;
  public final static int TASHAS_HIDEOUS_LAUGHTER = 457;
  public final static int TENSERS_TRANSFORMATION = 184;
  public final static int TIME_STOP = 185;
  public final static int TRAP_ARROW = 487;
  public final static int TRAP_BOLT = 488;
  public final static int TRAP_DART = 493;
  public final static int TRAP_SHURIKEN = 494;
  public final static int TRUE_SEEING = 186;
  public final static int TRUE_STRIKE = 415;
  public final static int TYMORAS_SMILE = 478;
  public final static int UNDEATHS_ETERNAL_FOE = 444;
  public final static int UNDEATH_TO_DEATH = 528;
  public final static int UNHOLY_AURA = 187;
  public final static int VAMPIRIC_TOUCH = 188;
  public final static int VINE_MINE = 529;
  public final static int VINE_MINE_CAMOUFLAGE = 532;
  public final static int VINE_MINE_ENTANGLE = 530;
  public final static int VINE_MINE_HAMPER_MOVEMENT = 531;
  public final static int VIRTUE = 189;
  public final static int WAIL_OF_THE_BANSHEE = 190;
  public final static int WALL_OF_FIRE = 191;
  public final static int WAR_CRY = 373;
  public final static int WEB = 192;
  public final static int WEIRD = 193;
  public final static int WORD_OF_FAITH = 194;
  public final static int WOUNDING_WHISPERS = 441;

  public static String nameOf(int value) {
    if (value == 0) return "Spell.ACID_FOG";
    if (value == 424) return "Spell.ACID_SPLASH";
    if (value == 472) return "Spell.ACTIVATE_ITEM_PORTAL";
    if (value == 428) return "Spell.ACTIVATE_ITEM_SELF2";
    if (value == 1) return "Spell.AID";
    if (value == -1) return "Spell.ALL_SPELLS";
    if (value == 442) return "Spell.AMPLIFY";
    if (value == 2) return "Spell.ANIMATE_DEAD";
    if (value == 429) return "Spell.AURAOFGLORY";
    if (value == 372) return "Spell.AURA_OF_VITALITY";
    if (value == 363) return "Spell.AWAKEN";
    if (value == 436) return "Spell.BALAGARNSIRONHORN";
    if (value == 516) return "Spell.BALL_LIGHTNING";
    if (value == 449) return "Spell.BANE";
    if (value == 430) return "Spell.BANISHMENT";
    if (value == 3) return "Spell.BARKSKIN";
    if (value == 517) return "Spell.BATTLETIDE";
    if (value == 4) return "Spell.BESTOW_CURSE";
    if (value == 462) return "Spell.BIGBYS_CLENCHED_FIST";
    if (value == 463) return "Spell.BIGBYS_CRUSHING_HAND";
    if (value == 460) return "Spell.BIGBYS_FORCEFUL_HAND";
    if (value == 461) return "Spell.BIGBYS_GRASPING_HAND";
    if (value == 459) return "Spell.BIGBYS_INTERPOSING_HAND";
    if (value == 541) return "Spell.BLACKSTAFF";
    if (value == 533) return "Spell.BLACK_BLADE_OF_DISASTER";
    if (value == 5) return "Spell.BLADE_BARRIER";
    if (value == 535) return "Spell.BLADE_THIRST";
    if (value == 6) return "Spell.BLESS";
    if (value == 537) return "Spell.BLESS_WEAPON";
    if (value == 8) return "Spell.BLINDNESS_AND_DEAFNESS";
    if (value == 422) return "Spell.BLOOD_FRENZY";
    if (value == 423) return "Spell.BOMBARDMENT";
    if (value == 9) return "Spell.BULLS_STRENGTH";
    if (value == 10) return "Spell.BURNING_HANDS";
    if (value == 11) return "Spell.CALL_LIGHTNING";
    if (value == 421) return "Spell.CAMOFLAGE";
    if (value == 13) return "Spell.CATS_GRACE";
    if (value == 14) return "Spell.CHAIN_LIGHTNING";
    if (value == 500) return "Spell.CHARGER";
    if (value == 15) return "Spell.CHARM_MONSTER";
    if (value == 16) return "Spell.CHARM_PERSON";
    if (value == 17) return "Spell.CHARM_PERSON_OR_ANIMAL";
    if (value == 18) return "Spell.CIRCLE_OF_DEATH";
    if (value == 19) return "Spell.CIRCLE_OF_DOOM";
    if (value == 20) return "Spell.CLAIRAUDIENCE_AND_CLAIRVOYANCE";
    if (value == 21) return "Spell.CLARITY";
    if (value == 22) return "Spell.CLOAK_OF_CHAOS";
    if (value == 23) return "Spell.CLOUDKILL";
    if (value == 569) return "Spell.CLOUD_OF_BEWILDERMENT";
    if (value == 24) return "Spell.COLOR_SPRAY";
    if (value == 518) return "Spell.COMBUST";
    if (value == 25) return "Spell.CONE_OF_COLD";
    if (value == 26) return "Spell.CONFUSION";
    if (value == 27) return "Spell.CONTAGION";
    if (value == 419) return "Spell.CONTINUAL_FLAME";
    if (value == 28) return "Spell.CONTROL_UNDEAD";
    if (value == 654) return "Spell.CRAFT_ADD_ITEM_PROPERTY";
    if (value == 657) return "Spell.CRAFT_CRAFT_ARMOR_SKILL";
    if (value == 656) return "Spell.CRAFT_CRAFT_WEAPON_SKILL";
    if (value == 648) return "Spell.CRAFT_DYE_CLOTHCOLOR_1";
    if (value == 649) return "Spell.CRAFT_DYE_CLOTHCOLOR_2";
    if (value == 650) return "Spell.CRAFT_DYE_LEATHERCOLOR_1";
    if (value == 651) return "Spell.CRAFT_DYE_LEATHERCOLOR_2";
    if (value == 652) return "Spell.CRAFT_DYE_METALCOLOR_1";
    if (value == 653) return "Spell.CRAFT_DYE_METALCOLOR_2";
    if (value == 479) return "Spell.CRAFT_HARPER_ITEM";
    if (value == 655) return "Spell.CRAFT_POISON_WEAPON_OR_AMMO";
    if (value == 29) return "Spell.CREATE_GREATER_UNDEAD";
    if (value == 30) return "Spell.CREATE_UNDEAD";
    if (value == 364) return "Spell.CREEPING_DOOM";
    if (value == 512) return "Spell.CRUMBLE";
    if (value == 31) return "Spell.CURE_CRITICAL_WOUNDS";
    if (value == 32) return "Spell.CURE_LIGHT_WOUNDS";
    if (value == 33) return "Spell.CURE_MINOR_WOUNDS";
    if (value == 34) return "Spell.CURE_MODERATE_WOUNDS";
    if (value == 35) return "Spell.CURE_SERIOUS_WOUNDS";
    if (value == 548) return "Spell.DARKFIRE";
    if (value == 36) return "Spell.DARKNESS";
    if (value == 365) return "Spell.DARKVISION";
    if (value == 37) return "Spell.DAZE";
    if (value == 536) return "Spell.DEAFENING_CLANG";
    if (value == 519) return "Spell.DEATH_ARMOR";
    if (value == 38) return "Spell.DEATH_WARD";
    if (value == 510) return "Spell.DECHARGER";
    if (value == 503) return "Spell.DECK_AVATAR";
    if (value == 505) return "Spell.DECK_BUTTERFLYSPRAY";
    if (value == 504) return "Spell.DECK_GEMSPRAY";
    if (value == 500) return "Spell.DECK_OF_MANY_THINGS";
    if (value == 39) return "Spell.DELAYED_BLAST_FIREBALL";
    if (value == 366) return "Spell.DESTRUCTION";
    if (value == 445) return "Spell.DIRGE";
    if (value == 40) return "Spell.DISMISSAL";
    if (value == 41) return "Spell.DISPEL_MAGIC";
    if (value == 458) return "Spell.DISPLACEMENT";
    if (value == 414) return "Spell.DIVINE_FAVOR";
    if (value == 473) return "Spell.DIVINE_MIGHT";
    if (value == 42) return "Spell.DIVINE_POWER";
    if (value == 474) return "Spell.DIVINE_SHIELD";
    if (value == 43) return "Spell.DOMINATE_ANIMAL";
    if (value == 44) return "Spell.DOMINATE_MONSTER";
    if (value == 45) return "Spell.DOMINATE_PERSON";
    if (value == 46) return "Spell.DOOM";
    if (value == 437) return "Spell.DROWN";
    if (value == 354) return "Spell.EAGLE_SPLEDOR";
    if (value == 426) return "Spell.EARTHQUAKE";
    if (value == 439) return "Spell.ELECTRIC_JOLT";
    if (value == 47) return "Spell.ELEMENTAL_SHIELD";
    if (value == 502) return "Spell.ELEMENTAL_SUMMONING_ITEM";
    if (value == 48) return "Spell.ELEMENTAL_SWARM";
    if (value == 49) return "Spell.ENDURANCE";
    if (value == 50) return "Spell.ENDURE_ELEMENTS";
    if (value == 369) return "Spell.ENERGY_BUFFER";
    if (value == 51) return "Spell.ENERGY_DRAIN";
    if (value == 52) return "Spell.ENERVATION";
    if (value == 53) return "Spell.ENTANGLE";
    if (value == 418) return "Spell.ENTROPIC_SHIELD";
    if (value == 638) return "Spell.EPIC_DRAGON_KNIGHT";
    if (value == 636) return "Spell.EPIC_HELLBALL";
    if (value == 639) return "Spell.EPIC_MAGE_ARMOR";
    if (value == 637) return "Spell.EPIC_MUMMY_DUST";
    if (value == 640) return "Spell.EPIC_RUIN";
    if (value == 443) return "Spell.ETHEREALNESS";
    if (value == 121) return "Spell.ETHEREAL_VISAGE";
    if (value == 375) return "Spell.EVARDS_BLACK_TENTACLES";
    if (value == 456) return "Spell.EXPEDITIOUS_RETREAT";
    if (value == 54) return "Spell.FEAR";
    if (value == 55) return "Spell.FEEBLEMIND";
    if (value == 377) return "Spell.FIND_TRAPS";
    if (value == 56) return "Spell.FINGER_OF_DEATH";
    if (value == 58) return "Spell.FIREBALL";
    if (value == 440) return "Spell.FIREBRAND";
    if (value == 57) return "Spell.FIRE_STORM";
    if (value == 59) return "Spell.FLAME_ARROW";
    if (value == 60) return "Spell.FLAME_LASH";
    if (value == 61) return "Spell.FLAME_STRIKE";
    if (value == 542) return "Spell.FLAME_WEAPON";
    if (value == 416) return "Spell.FLARE";
    if (value == 485) return "Spell.FLESH_TO_STONE";
    if (value == 620) return "Spell.FLYING_DEBRIS";
    if (value == 356) return "Spell.FOXS_CUNNING";
    if (value == 62) return "Spell.FREEDOM_OF_MOVEMENT";
    if (value == 63) return "Spell.GATE";
    if (value == 520) return "Spell.GEDLEES_ELECTRIC_LOOP";
    if (value == 120) return "Spell.GHOSTLY_VISAGE";
    if (value == 64) return "Spell.GHOUL_TOUCH";
    if (value == 65) return "Spell.GLOBE_OF_INVULNERABILITY";
    if (value == 549) return "Spell.GLYPH_OF_WARDING";
    if (value == 66) return "Spell.GREASE";
    if (value == 72) return "Spell.GREATER_BREACH";
    if (value == 360) return "Spell.GREATER_BULLS_STRENGTH";
    if (value == 361) return "Spell.GREATER_CATS_GRACE";
    if (value == 67) return "Spell.GREATER_DISPELLING";
    if (value == 357) return "Spell.GREATER_EAGLE_SPLENDOR";
    if (value == 362) return "Spell.GREATER_ENDURANCE";
    if (value == 359) return "Spell.GREATER_FOXS_CUNNING";
    if (value == 453) return "Spell.GREATER_MAGIC_FANG";
    if (value == 545) return "Spell.GREATER_MAGIC_WEAPON";
    if (value == 73) return "Spell.GREATER_MANTLE";
    if (value == 358) return "Spell.GREATER_OWLS_WISDOM";
    if (value == 69) return "Spell.GREATER_PLANAR_BINDING";
    if (value == 70) return "Spell.GREATER_RESTORATION";
    if (value == 350) return "Spell.GREATER_SHADOW_CONJURATION_ACID_ARROW";
    if (value == 353) return "Spell.GREATER_SHADOW_CONJURATION_MINOR_GLOBE";
    if (value == 351) return "Spell.GREATER_SHADOW_CONJURATION_MIRROR_IMAGE";
    if (value == 349) return "Spell.GREATER_SHADOW_CONJURATION_SUMMON_SHADOW";
    if (value == 352) return "Spell.GREATER_SHADOW_CONJURATION_WEB";
    if (value == 74) return "Spell.GREATER_STONESKIN";
    if (value == 515) return "Spell.GREAT_THUNDERCLAP";
    if (value == 469) return "Spell.GRENADE_ACID";
    if (value == 471) return "Spell.GRENADE_CALTROPS";
    if (value == 470) return "Spell.GRENADE_CHICKEN";
    if (value == 467) return "Spell.GRENADE_CHOKING";
    if (value == 464) return "Spell.GRENADE_FIRE";
    if (value == 466) return "Spell.GRENADE_HOLY";
    if (value == 465) return "Spell.GRENADE_TANGLE";
    if (value == 468) return "Spell.GRENADE_THUNDERSTONE";
    if (value == 75) return "Spell.GUST_OF_WIND";
    if (value == 76) return "Spell.HAMMER_OF_THE_GODS";
    if (value == 77) return "Spell.HARM";
    if (value == 78) return "Spell.HASTE";
    if (value == 79) return "Spell.HEAL";
    if (value == 506) return "Spell.HEALINGKIT";
    if (value == 80) return "Spell.HEALING_CIRCLE";
    if (value == 514) return "Spell.HEALING_STING";
    if (value == 81) return "Spell.HOLD_ANIMAL";
    if (value == 82) return "Spell.HOLD_MONSTER";
    if (value == 83) return "Spell.HOLD_PERSON";
    if (value == 84) return "Spell.HOLY_AURA";
    if (value == 538) return "Spell.HOLY_SWORD";
    if (value == 521) return "Spell.HORIZIKAULS_BOOM";
    if (value == 367) return "Spell.HORRID_WILTING";
    if (value == 817) return "Spell.HORSE_ASSIGN_MOUNT";
    if (value == 814) return "Spell.HORSE_DISMOUNT";
    if (value == 812) return "Spell.HORSE_MENU";
    if (value == 813) return "Spell.HORSE_MOUNT";
    if (value == 816) return "Spell.HORSE_PARTY_DISMOUNT";
    if (value == 815) return "Spell.HORSE_PARTY_MOUNT";
    if (value == 543) return "Spell.ICE_DAGGER";
    if (value == 368) return "Spell.ICE_STORM";
    if (value == 86) return "Spell.IDENTIFY";
    if (value == 87) return "Spell.IMPLOSION";
    if (value == 88) return "Spell.IMPROVED_INVISIBILITY";
    if (value == 89) return "Spell.INCENDIARY_CLOUD";
    if (value == 446) return "Spell.INFERNO";
    if (value == 513) return "Spell.INFESTATION_OF_MAGGOTS";
    if (value == 435) return "Spell.INFLICT_CRITICAL_WOUNDS";
    if (value == 432) return "Spell.INFLICT_LIGHT_WOUNDS";
    if (value == 431) return "Spell.INFLICT_MINOR_WOUNDS";
    if (value == 433) return "Spell.INFLICT_MODERATE_WOUNDS";
    if (value == 434) return "Spell.INFLICT_SERIOUS_WOUNDS";
    if (value == 90) return "Spell.INVISIBILITY";
    if (value == 91) return "Spell.INVISIBILITY_PURGE";
    if (value == 92) return "Spell.INVISIBILITY_SPHERE";
    if (value == 557) return "Spell.IOUN_STONE_BLUE";
    if (value == 558) return "Spell.IOUN_STONE_DEEP_RED";
    if (value == 554) return "Spell.IOUN_STONE_DUSTY_ROSE";
    if (value == 555) return "Spell.IOUN_STONE_PALE_BLUE";
    if (value == 559) return "Spell.IOUN_STONE_PINK";
    if (value == 560) return "Spell.IOUN_STONE_PINK_GREEN";
    if (value == 556) return "Spell.IOUN_STONE_SCARLET_BLUE";
    if (value == 522) return "Spell.IRONGUTS";
    if (value == 448) return "Spell.ISAACS_GREATER_MISSILE_STORM";
    if (value == 447) return "Spell.ISAACS_LESSER_MISSILE_STORM";
    if (value == 539) return "Spell.KEEN_EDGE";
    if (value == 93) return "Spell.KNOCK";
    if (value == 511) return "Spell.KOBOLD_JUMP";
    if (value == 376) return "Spell.LEGEND_LORE";
    if (value == 98) return "Spell.LESSER_BREACH";
    if (value == 94) return "Spell.LESSER_DISPEL";
    if (value == 99) return "Spell.LESSER_MANTLE";
    if (value == 95) return "Spell.LESSER_MIND_BLANK";
    if (value == 96) return "Spell.LESSER_PLANAR_BINDING";
    if (value == 97) return "Spell.LESSER_RESTORATION";
    if (value == 100) return "Spell.LIGHT";
    if (value == 101) return "Spell.LIGHTNING_BOLT";
    if (value == 102) return "Spell.MAGE_ARMOR";
    if (value == 103) return "Spell.MAGIC_CIRCLE_AGAINST_CHAOS";
    if (value == 104) return "Spell.MAGIC_CIRCLE_AGAINST_EVIL";
    if (value == 105) return "Spell.MAGIC_CIRCLE_AGAINST_GOOD";
    if (value == 106) return "Spell.MAGIC_CIRCLE_AGAINST_LAW";
    if (value == 452) return "Spell.MAGIC_FANG";
    if (value == 107) return "Spell.MAGIC_MISSILE";
    if (value == 546) return "Spell.MAGIC_VESTMENT";
    if (value == 544) return "Spell.MAGIC_WEAPON";
    if (value == 169) return "Spell.MANTLE";
    if (value == 110) return "Spell.MASS_BLINDNESS_AND_DEAFNESS";
    if (value == 455) return "Spell.MASS_CAMOFLAGE";
    if (value == 111) return "Spell.MASS_CHARM";
    if (value == 113) return "Spell.MASS_HASTE";
    if (value == 114) return "Spell.MASS_HEAL";
    if (value == 115) return "Spell.MELFS_ACID_ARROW";
    if (value == 523) return "Spell.MESTILS_ACID_BREATH";
    if (value == 524) return "Spell.MESTILS_ACID_SHEATH";
    if (value == 116) return "Spell.METEOR_SWARM";
    if (value == 117) return "Spell.MIND_BLANK";
    if (value == 118) return "Spell.MIND_FOG";
    if (value == 119) return "Spell.MINOR_GLOBE_OF_INVULNERABILITY";
    if (value == 525) return "Spell.MONSTROUS_REGENERATION";
    if (value == 122) return "Spell.MORDENKAINENS_DISJUNCTION";
    if (value == 123) return "Spell.MORDENKAINENS_SWORD";
    if (value == 124) return "Spell.NATURES_BALANCE";
    if (value == 370) return "Spell.NEGATIVE_ENERGY_BURST";
    if (value == 125) return "Spell.NEGATIVE_ENERGY_PROTECTION";
    if (value == 371) return "Spell.NEGATIVE_ENERGY_RAY";
    if (value == 126) return "Spell.NEUTRALIZE_POISON";
    if (value == 420) return "Spell.ONE_WITH_THE_LAND";
    if (value == 438) return "Spell.OWLS_INSIGHT";
    if (value == 355) return "Spell.OWLS_WISDOM";
    if (value == 818) return "Spell.PALADIN_SUMMON_MOUNT";
    if (value == 127) return "Spell.PHANTASMAL_KILLER";
    if (value == 451) return "Spell.PLANAR_ALLY";
    if (value == 128) return "Spell.PLANAR_BINDING";
    if (value == 129) return "Spell.POISON";
    if (value == 130) return "Spell.POLYMORPH_SELF";
    if (value == 507) return "Spell.POWERSTONE";
    if (value == 131) return "Spell.POWER_WORD_KILL";
    if (value == 132) return "Spell.POWER_WORD_STUN";
    if (value == 133) return "Spell.PRAYER";
    if (value == 134) return "Spell.PREMONITION";
    if (value == 135) return "Spell.PRISMATIC_SPRAY";
    if (value == 137) return "Spell.PROTECTION_FROM_ELEMENTS";
    if (value == 138) return "Spell.PROTECTION_FROM_EVIL";
    if (value == 139) return "Spell.PROTECTION_FROM_GOOD";
    if (value == 140) return "Spell.PROTECTION_FROM_LAW";
    if (value == 141) return "Spell.PROTECTION_FROM_SPELLS";
    if (value == 136) return "Spell.PROTECTION__FROM_CHAOS";
    if (value == 425) return "Spell.QUILLFIRE";
    if (value == 142) return "Spell.RAISE_DEAD";
    if (value == 143) return "Spell.RAY_OF_ENFEEBLEMENT";
    if (value == 144) return "Spell.RAY_OF_FROST";
    if (value == 374) return "Spell.REGENERATE";
    if (value == 145) return "Spell.REMOVE_BLINDNESS_AND_DEAFNESS";
    if (value == 146) return "Spell.REMOVE_CURSE";
    if (value == 147) return "Spell.REMOVE_DISEASE";
    if (value == 148) return "Spell.REMOVE_FEAR";
    if (value == 149) return "Spell.REMOVE_PARALYSIS";
    if (value == 168) return "Spell.RESISTANCE";
    if (value == 150) return "Spell.RESIST_ELEMENTS";
    if (value == 152) return "Spell.RESTORATION";
    if (value == 153) return "Spell.RESURRECTION";
    if (value == 499) return "Spell.ROD_OF_WONDER";
    if (value == 154) return "Spell.SANCTUARY";
    if (value == 155) return "Spell.SCARE";
    if (value == 1) return "Spell.SCHOOL_ABJURATION";
    if (value == 2) return "Spell.SCHOOL_CONJURATION";
    if (value == 3) return "Spell.SCHOOL_DIVINATION";
    if (value == 4) return "Spell.SCHOOL_ENCHANTMENT";
    if (value == 5) return "Spell.SCHOOL_EVOCATION";
    if (value == 0) return "Spell.SCHOOL_GENERAL";
    if (value == 6) return "Spell.SCHOOL_ILLUSION";
    if (value == 7) return "Spell.SCHOOL_NECROMANCY";
    if (value == 8) return "Spell.SCHOOL_TRANSMUTATION";
    if (value == 526) return "Spell.SCINTILLATING_SPHERE";
    if (value == 156) return "Spell.SEARING_LIGHT";
    if (value == 157) return "Spell.SEE_INVISIBILITY";
    if (value == 340) return "Spell.SHADES_CONE_OF_COLD";
    if (value == 341) return "Spell.SHADES_FIREBALL";
    if (value == 342) return "Spell.SHADES_STONESKIN";
    if (value == 324) return "Spell.SHADES_SUMMON_SHADOW";
    if (value == 343) return "Spell.SHADES_WALL_OF_FIRE";
    if (value == 345) return "Spell.SHADOW_CONJURATION_DARKNESS";
    if (value == 346) return "Spell.SHADOW_CONJURATION_INIVSIBILITY";
    if (value == 347) return "Spell.SHADOW_CONJURATION_MAGE_ARMOR";
    if (value == 348) return "Spell.SHADOW_CONJURATION_MAGIC_MISSILE";
    if (value == 344) return "Spell.SHADOW_CONJURATION_SUMMON_SHADOW";
    if (value == 475) return "Spell.SHADOW_DAZE";
    if (value == 477) return "Spell.SHADOW_EVADE";
    if (value == 160) return "Spell.SHADOW_SHIELD";
    if (value == 161) return "Spell.SHAPECHANGE";
    if (value == 534) return "Spell.SHELGARNS_PERSISTENT_BLADE";
    if (value == 417) return "Spell.SHIELD";
    if (value == 450) return "Spell.SHIELD_OF_FAITH";
    if (value == 162) return "Spell.SHIELD_OF_LAW";
    if (value == 163) return "Spell.SILENCE";
    if (value == 164) return "Spell.SLAY_LIVING";
    if (value == 165) return "Spell.SLEEP";
    if (value == 166) return "Spell.SLOW";
    if (value == 167) return "Spell.SOUND_BURST";
    if (value == 508) return "Spell.SPELLSTAFF";
    if (value == 170) return "Spell.SPHERE_OF_CHAOS";
    if (value == 454) return "Spell.SPIKE_GROWTH";
    if (value == 171) return "Spell.STINKING_CLOUD";
    if (value == 547) return "Spell.STONEHOLD";
    if (value == 172) return "Spell.STONESKIN";
    if (value == 527) return "Spell.STONE_BONES";
    if (value == 486) return "Spell.STONE_TO_FLESH";
    if (value == 173) return "Spell.STORM_OF_VENGEANCE";
    if (value == 174) return "Spell.SUMMON_CREATURE_I";
    if (value == 175) return "Spell.SUMMON_CREATURE_II";
    if (value == 176) return "Spell.SUMMON_CREATURE_III";
    if (value == 177) return "Spell.SUMMON_CREATURE_IV";
    if (value == 178) return "Spell.SUMMON_CREATURE_IX";
    if (value == 179) return "Spell.SUMMON_CREATURE_V";
    if (value == 180) return "Spell.SUMMON_CREATURE_VI";
    if (value == 181) return "Spell.SUMMON_CREATURE_VII";
    if (value == 182) return "Spell.SUMMON_CREATURE_VIII";
    if (value == 476) return "Spell.SUMMON_SHADOW";
    if (value == 183) return "Spell.SUNBEAM";
    if (value == 427) return "Spell.SUNBURST";
    if (value == 457) return "Spell.TASHAS_HIDEOUS_LAUGHTER";
    if (value == 184) return "Spell.TENSERS_TRANSFORMATION";
    if (value == 185) return "Spell.TIME_STOP";
    if (value == 487) return "Spell.TRAP_ARROW";
    if (value == 488) return "Spell.TRAP_BOLT";
    if (value == 493) return "Spell.TRAP_DART";
    if (value == 494) return "Spell.TRAP_SHURIKEN";
    if (value == 186) return "Spell.TRUE_SEEING";
    if (value == 415) return "Spell.TRUE_STRIKE";
    if (value == 478) return "Spell.TYMORAS_SMILE";
    if (value == 444) return "Spell.UNDEATHS_ETERNAL_FOE";
    if (value == 528) return "Spell.UNDEATH_TO_DEATH";
    if (value == 187) return "Spell.UNHOLY_AURA";
    if (value == 188) return "Spell.VAMPIRIC_TOUCH";
    if (value == 529) return "Spell.VINE_MINE";
    if (value == 532) return "Spell.VINE_MINE_CAMOUFLAGE";
    if (value == 530) return "Spell.VINE_MINE_ENTANGLE";
    if (value == 531) return "Spell.VINE_MINE_HAMPER_MOVEMENT";
    if (value == 189) return "Spell.VIRTUE";
    if (value == 190) return "Spell.WAIL_OF_THE_BANSHEE";
    if (value == 191) return "Spell.WALL_OF_FIRE";
    if (value == 373) return "Spell.WAR_CRY";
    if (value == 192) return "Spell.WEB";
    if (value == 193) return "Spell.WEIRD";
    if (value == 194) return "Spell.WORD_OF_FAITH";
    if (value == 441) return "Spell.WOUNDING_WHISPERS";
    return "Spell.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "Spell.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "Spell.(not found: " + value + ")";
  }
}
