package org.nwnx.nwnx2.jvm.constants;

/**
 * This class contains all unique constants beginning with "VFX_EYES".
 * Non-distinct keys are filtered; only the LAST appearing was
 * kept.
*/
public final class VfxEyes {
  private VfxEyes() {}

  public final static int CYN_DWARF_FEMALE = 596;
  public final static int CYN_DWARF_MALE = 595;
  public final static int CYN_ELF_FEMALE = 598;
  public final static int CYN_ELF_MALE = 597;
  public final static int CYN_GNOME_FEMALE = 600;
  public final static int CYN_GNOME_MALE = 599;
  public final static int CYN_HALFLING_FEMALE = 602;
  public final static int CYN_HALFLING_MALE = 601;
  public final static int CYN_HALFORC_FEMALE = 604;
  public final static int CYN_HALFORC_MALE = 603;
  public final static int CYN_HUMAN_FEMALE = 594;
  public final static int CYN_HUMAN_MALE = 593;
  public final static int CYN_TROGLODYTE = 605;
  public final static int GREEN_DWARF_FEMALE = 570;
  public final static int GREEN_DWARF_MALE = 569;
  public final static int GREEN_ELF_FEMALE = 572;
  public final static int GREEN_ELF_MALE = 571;
  public final static int GREEN_GNOME_FEMALE = 574;
  public final static int GREEN_GNOME_MALE = 573;
  public final static int GREEN_HALFELF_FEMALE = 568;
  public final static int GREEN_HALFELF_MALE = 567;
  public final static int GREEN_HALFLING_FEMALE = 576;
  public final static int GREEN_HALFLING_MALE = 575;
  public final static int GREEN_HALFORC_FEMALE = 578;
  public final static int GREEN_HALFORC_MALE = 577;
  public final static int GREEN_HUMAN_FEMALE = 568;
  public final static int GREEN_HUMAN_MALE = 567;
  public final static int GREEN_TROGLODYTE = 579;
  public final static int ORG_DWARF_FEMALE = 389;
  public final static int ORG_DWARF_MALE = 388;
  public final static int ORG_ELF_FEMALE = 391;
  public final static int ORG_ELF_MALE = 390;
  public final static int ORG_GNOME_FEMALE = 393;
  public final static int ORG_GNOME_MALE = 392;
  public final static int ORG_HALFLING_FEMALE = 395;
  public final static int ORG_HALFLING_MALE = 394;
  public final static int ORG_HALFORC_FEMALE = 397;
  public final static int ORG_HALFORC_MALE = 396;
  public final static int ORG_HUMAN_FEMALE = 387;
  public final static int ORG_HUMAN_MALE = 386;
  public final static int ORG_TROGLODYTE = 398;
  public final static int PUR_DWARF_FEMALE = 583;
  public final static int PUR_DWARF_MALE = 582;
  public final static int PUR_ELF_FEMALE = 585;
  public final static int PUR_ELF_MALE = 584;
  public final static int PUR_GNOME_FEMALE = 587;
  public final static int PUR_GNOME_MALE = 586;
  public final static int PUR_HALFLING_FEMALE = 589;
  public final static int PUR_HALFLING_MALE = 588;
  public final static int PUR_HALFORC_FEMALE = 591;
  public final static int PUR_HALFORC_MALE = 590;
  public final static int PUR_HUMAN_FEMALE = 581;
  public final static int PUR_HUMAN_MALE = 580;
  public final static int PUR_TROGLODYTE = 592;
  public final static int RED_FLAME_DWARF_FEMALE = 363;
  public final static int RED_FLAME_DWARF_MALE = 362;
  public final static int RED_FLAME_ELF_FEMALE = 365;
  public final static int RED_FLAME_ELF_MALE = 364;
  public final static int RED_FLAME_GNOME_FEMALE = 367;
  public final static int RED_FLAME_GNOME_MALE = 366;
  public final static int RED_FLAME_HALFELF_FEMALE = 361;
  public final static int RED_FLAME_HALFELF_MALE = 360;
  public final static int RED_FLAME_HALFLING_FEMALE = 369;
  public final static int RED_FLAME_HALFLING_MALE = 368;
  public final static int RED_FLAME_HALFORC_FEMALE = 371;
  public final static int RED_FLAME_HALFORC_MALE = 370;
  public final static int RED_FLAME_HUMAN_FEMALE = 361;
  public final static int RED_FLAME_HUMAN_MALE = 360;
  public final static int RED_FLAME_TROGLODYTE = 372;
  public final static int WHT_DWARF_FEMALE = 609;
  public final static int WHT_DWARF_MALE = 608;
  public final static int WHT_ELF_FEMALE = 611;
  public final static int WHT_ELF_MALE = 610;
  public final static int WHT_GNOME_FEMALE = 613;
  public final static int WHT_GNOME_MALE = 612;
  public final static int WHT_HALFLING_FEMALE = 615;
  public final static int WHT_HALFLING_MALE = 614;
  public final static int WHT_HALFORC_FEMALE = 617;
  public final static int WHT_HALFORC_MALE = 616;
  public final static int WHT_HUMAN_FEMALE = 607;
  public final static int WHT_HUMAN_MALE = 606;
  public final static int WHT_TROGLODYTE = 618;
  public final static int YEL_DWARF_FEMALE = 376;
  public final static int YEL_DWARF_MALE = 375;
  public final static int YEL_ELF_FEMALE = 378;
  public final static int YEL_ELF_MALE = 377;
  public final static int YEL_GNOME_FEMALE = 380;
  public final static int YEL_GNOME_MALE = 379;
  public final static int YEL_HALFLING_FEMALE = 382;
  public final static int YEL_HALFLING_MALE = 381;
  public final static int YEL_HALFORC_FEMALE = 384;
  public final static int YEL_HALFORC_MALE = 383;
  public final static int YEL_HUMAN_FEMALE = 374;
  public final static int YEL_HUMAN_MALE = 373;
  public final static int YEL_TROGLODYTE = 385;

  public static String nameOf(int value) {
    if (value == 596) return "VfxEyes.CYN_DWARF_FEMALE";
    if (value == 595) return "VfxEyes.CYN_DWARF_MALE";
    if (value == 598) return "VfxEyes.CYN_ELF_FEMALE";
    if (value == 597) return "VfxEyes.CYN_ELF_MALE";
    if (value == 600) return "VfxEyes.CYN_GNOME_FEMALE";
    if (value == 599) return "VfxEyes.CYN_GNOME_MALE";
    if (value == 602) return "VfxEyes.CYN_HALFLING_FEMALE";
    if (value == 601) return "VfxEyes.CYN_HALFLING_MALE";
    if (value == 604) return "VfxEyes.CYN_HALFORC_FEMALE";
    if (value == 603) return "VfxEyes.CYN_HALFORC_MALE";
    if (value == 594) return "VfxEyes.CYN_HUMAN_FEMALE";
    if (value == 593) return "VfxEyes.CYN_HUMAN_MALE";
    if (value == 605) return "VfxEyes.CYN_TROGLODYTE";
    if (value == 570) return "VfxEyes.GREEN_DWARF_FEMALE";
    if (value == 569) return "VfxEyes.GREEN_DWARF_MALE";
    if (value == 572) return "VfxEyes.GREEN_ELF_FEMALE";
    if (value == 571) return "VfxEyes.GREEN_ELF_MALE";
    if (value == 574) return "VfxEyes.GREEN_GNOME_FEMALE";
    if (value == 573) return "VfxEyes.GREEN_GNOME_MALE";
    if (value == 568) return "VfxEyes.GREEN_HALFELF_FEMALE";
    if (value == 567) return "VfxEyes.GREEN_HALFELF_MALE";
    if (value == 576) return "VfxEyes.GREEN_HALFLING_FEMALE";
    if (value == 575) return "VfxEyes.GREEN_HALFLING_MALE";
    if (value == 578) return "VfxEyes.GREEN_HALFORC_FEMALE";
    if (value == 577) return "VfxEyes.GREEN_HALFORC_MALE";
    if (value == 568) return "VfxEyes.GREEN_HUMAN_FEMALE";
    if (value == 567) return "VfxEyes.GREEN_HUMAN_MALE";
    if (value == 579) return "VfxEyes.GREEN_TROGLODYTE";
    if (value == 389) return "VfxEyes.ORG_DWARF_FEMALE";
    if (value == 388) return "VfxEyes.ORG_DWARF_MALE";
    if (value == 391) return "VfxEyes.ORG_ELF_FEMALE";
    if (value == 390) return "VfxEyes.ORG_ELF_MALE";
    if (value == 393) return "VfxEyes.ORG_GNOME_FEMALE";
    if (value == 392) return "VfxEyes.ORG_GNOME_MALE";
    if (value == 395) return "VfxEyes.ORG_HALFLING_FEMALE";
    if (value == 394) return "VfxEyes.ORG_HALFLING_MALE";
    if (value == 397) return "VfxEyes.ORG_HALFORC_FEMALE";
    if (value == 396) return "VfxEyes.ORG_HALFORC_MALE";
    if (value == 387) return "VfxEyes.ORG_HUMAN_FEMALE";
    if (value == 386) return "VfxEyes.ORG_HUMAN_MALE";
    if (value == 398) return "VfxEyes.ORG_TROGLODYTE";
    if (value == 583) return "VfxEyes.PUR_DWARF_FEMALE";
    if (value == 582) return "VfxEyes.PUR_DWARF_MALE";
    if (value == 585) return "VfxEyes.PUR_ELF_FEMALE";
    if (value == 584) return "VfxEyes.PUR_ELF_MALE";
    if (value == 587) return "VfxEyes.PUR_GNOME_FEMALE";
    if (value == 586) return "VfxEyes.PUR_GNOME_MALE";
    if (value == 589) return "VfxEyes.PUR_HALFLING_FEMALE";
    if (value == 588) return "VfxEyes.PUR_HALFLING_MALE";
    if (value == 591) return "VfxEyes.PUR_HALFORC_FEMALE";
    if (value == 590) return "VfxEyes.PUR_HALFORC_MALE";
    if (value == 581) return "VfxEyes.PUR_HUMAN_FEMALE";
    if (value == 580) return "VfxEyes.PUR_HUMAN_MALE";
    if (value == 592) return "VfxEyes.PUR_TROGLODYTE";
    if (value == 363) return "VfxEyes.RED_FLAME_DWARF_FEMALE";
    if (value == 362) return "VfxEyes.RED_FLAME_DWARF_MALE";
    if (value == 365) return "VfxEyes.RED_FLAME_ELF_FEMALE";
    if (value == 364) return "VfxEyes.RED_FLAME_ELF_MALE";
    if (value == 367) return "VfxEyes.RED_FLAME_GNOME_FEMALE";
    if (value == 366) return "VfxEyes.RED_FLAME_GNOME_MALE";
    if (value == 361) return "VfxEyes.RED_FLAME_HALFELF_FEMALE";
    if (value == 360) return "VfxEyes.RED_FLAME_HALFELF_MALE";
    if (value == 369) return "VfxEyes.RED_FLAME_HALFLING_FEMALE";
    if (value == 368) return "VfxEyes.RED_FLAME_HALFLING_MALE";
    if (value == 371) return "VfxEyes.RED_FLAME_HALFORC_FEMALE";
    if (value == 370) return "VfxEyes.RED_FLAME_HALFORC_MALE";
    if (value == 361) return "VfxEyes.RED_FLAME_HUMAN_FEMALE";
    if (value == 360) return "VfxEyes.RED_FLAME_HUMAN_MALE";
    if (value == 372) return "VfxEyes.RED_FLAME_TROGLODYTE";
    if (value == 609) return "VfxEyes.WHT_DWARF_FEMALE";
    if (value == 608) return "VfxEyes.WHT_DWARF_MALE";
    if (value == 611) return "VfxEyes.WHT_ELF_FEMALE";
    if (value == 610) return "VfxEyes.WHT_ELF_MALE";
    if (value == 613) return "VfxEyes.WHT_GNOME_FEMALE";
    if (value == 612) return "VfxEyes.WHT_GNOME_MALE";
    if (value == 615) return "VfxEyes.WHT_HALFLING_FEMALE";
    if (value == 614) return "VfxEyes.WHT_HALFLING_MALE";
    if (value == 617) return "VfxEyes.WHT_HALFORC_FEMALE";
    if (value == 616) return "VfxEyes.WHT_HALFORC_MALE";
    if (value == 607) return "VfxEyes.WHT_HUMAN_FEMALE";
    if (value == 606) return "VfxEyes.WHT_HUMAN_MALE";
    if (value == 618) return "VfxEyes.WHT_TROGLODYTE";
    if (value == 376) return "VfxEyes.YEL_DWARF_FEMALE";
    if (value == 375) return "VfxEyes.YEL_DWARF_MALE";
    if (value == 378) return "VfxEyes.YEL_ELF_FEMALE";
    if (value == 377) return "VfxEyes.YEL_ELF_MALE";
    if (value == 380) return "VfxEyes.YEL_GNOME_FEMALE";
    if (value == 379) return "VfxEyes.YEL_GNOME_MALE";
    if (value == 382) return "VfxEyes.YEL_HALFLING_FEMALE";
    if (value == 381) return "VfxEyes.YEL_HALFLING_MALE";
    if (value == 384) return "VfxEyes.YEL_HALFORC_FEMALE";
    if (value == 383) return "VfxEyes.YEL_HALFORC_MALE";
    if (value == 374) return "VfxEyes.YEL_HUMAN_FEMALE";
    if (value == 373) return "VfxEyes.YEL_HUMAN_MALE";
    if (value == 385) return "VfxEyes.YEL_TROGLODYTE";
    return "VfxEyes.(not found: " + value + ")";
  }

  public static String nameOf(float value) {
    return "VfxEyes.(not found: " + value + ")";
  }

  public static String nameOf(String value) {
    return "VfxEyes.(not found: " + value + ")";
  }
}
