var annotated =
[
    [ "NWNX_Area_TileInfo", "structNWNX__Area__TileInfo.html", "structNWNX__Area__TileInfo" ],
    [ "NWNX_Creature_MemorisedSpell", "structNWNX__Creature__MemorisedSpell.html", "structNWNX__Creature__MemorisedSpell" ],
    [ "NWNX_Creature_SpecialAbility", "structNWNX__Creature__SpecialAbility.html", "structNWNX__Creature__SpecialAbility" ],
    [ "NWNX_Damage_AttackEventData", "structNWNX__Damage__AttackEventData.html", "structNWNX__Damage__AttackEventData" ],
    [ "NWNX_Damage_DamageData", "structNWNX__Damage__DamageData.html", "structNWNX__Damage__DamageData" ],
    [ "NWNX_Damage_DamageEventData", "structNWNX__Damage__DamageEventData.html", "structNWNX__Damage__DamageEventData" ],
    [ "NWNX_EffectUnpacked", "structNWNX__EffectUnpacked.html", "structNWNX__EffectUnpacked" ],
    [ "NWNX_Encounter_CreatureListEntry", "structNWNX__Encounter__CreatureListEntry.html", "structNWNX__Encounter__CreatureListEntry" ],
    [ "NWNX_IPUnpacked", "structNWNX__IPUnpacked.html", "structNWNX__IPUnpacked" ],
    [ "NWNX_Object_LocalVariable", "structNWNX__Object__LocalVariable.html", "structNWNX__Object__LocalVariable" ],
    [ "NWNX_Player_JournalEntry", "structNWNX__Player__JournalEntry.html", "structNWNX__Player__JournalEntry" ],
    [ "NWNX_Player_QuickBarSlot", "structNWNX__Player__QuickBarSlot.html", "structNWNX__Player__QuickBarSlot" ],
    [ "NWNX_Redis_PubSubMessageData", "structNWNX__Redis__PubSubMessageData.html", "structNWNX__Redis__PubSubMessageData" ],
    [ "NWNX_SkillRanks_SkillFeat", "structNWNX__SkillRanks__SkillFeat.html", "structNWNX__SkillRanks__SkillFeat" ],
    [ "NWNX_Tileset_CustomTileData", "structNWNX__Tileset__CustomTileData.html", "structNWNX__Tileset__CustomTileData" ],
    [ "NWNX_Tileset_TileDoorData", "structNWNX__Tileset__TileDoorData.html", "structNWNX__Tileset__TileDoorData" ],
    [ "NWNX_Tileset_TileEdgesAndCorners", "structNWNX__Tileset__TileEdgesAndCorners.html", "structNWNX__Tileset__TileEdgesAndCorners" ],
    [ "NWNX_Tileset_TilesetData", "structNWNX__Tileset__TilesetData.html", "structNWNX__Tileset__TilesetData" ],
    [ "NWNX_Tileset_TilesetGroupData", "structNWNX__Tileset__TilesetGroupData.html", "structNWNX__Tileset__TilesetGroupData" ],
    [ "NWNX_Time_HighResTimestamp", "structNWNX__Time__HighResTimestamp.html", "structNWNX__Time__HighResTimestamp" ],
    [ "NWNX_Util_HighResTimestamp", "structNWNX__Util__HighResTimestamp.html", "structNWNX__Util__HighResTimestamp" ],
    [ "NWNX_Util_WorldTime", "structNWNX__Util__WorldTime.html", "structNWNX__Util__WorldTime" ],
    [ "NWNX_Weapon_DevastatingCriticalEvent_Data", "structNWNX__Weapon__DevastatingCriticalEvent__Data.html", "structNWNX__Weapon__DevastatingCriticalEvent__Data" ],
    [ "NWNX_WebHook_Message", "structNWNX__WebHook__Message.html", "structNWNX__WebHook__Message" ],
    [ "SQLite_MillisecondTimeStamp", "structSQLite__MillisecondTimeStamp.html", "structSQLite__MillisecondTimeStamp" ]
];