var array__example_8nss =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md147", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md148", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md149", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md150", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md151", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md152", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md153", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md154", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md165", null ],
    [ "Example", "group__damage.html#autotoc_md167", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md168", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md169", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md170", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md171", [
      [ "Dependencies", "group__dotnet.html#autotoc_md172", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md173", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md174", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md175", [
        [ "Sample", "group__nwnx.html#autotoc_md155", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md176", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md177", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md178", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md179", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md180", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md181", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md182", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md183", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md184", [
      [ "NWN types", "group__dotnet.html#autotoc_md185", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md186", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md187", null ],
      [ "Closures", "group__dotnet.html#autotoc_md188", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md189", null ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md190", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md191", null ],
    [ "Events", "group__elc.html#autotoc_md192", null ],
    [ "Example Script", "group__elc.html#autotoc_md193", null ],
    [ "Notes", "group__experimental.html#autotoc_md288", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md289", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md290", null ],
    [ "Setup", "group__feat.html#autotoc_md291", null ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md292", [
      [ "AB", "group__feat.html#autotoc_md293", null ],
      [ "ABILITY", "group__feat.html#autotoc_md295", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md297", null ],
      [ "AC", "group__feat.html#autotoc_md299", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md301", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md303", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md305", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md307", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md309", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md311", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md313", null ],
      [ "HASTE", "group__feat.html#autotoc_md315", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md317", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md319", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md321", null ],
      [ "SAVE", "group__feat.html#autotoc_md323", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md325", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md327", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md329", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md331", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md333", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md335", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md337", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md339", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md341", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md343", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md345", null ],
    [ "Quick start", "group__lua.html#autotoc_md346", [
      [ "Docker", "group__lua.html#autotoc_md347", null ],
      [ "Native", "group__lua.html#autotoc_md348", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md349", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md350", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md351", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md352", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md353", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md354", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md355", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md356", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md357", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md358", null ],
    [ "Environment Variables", "group__nostack.html#autotoc_md359", [
      [ "NWNX_NOSTACK_*", "group__nostack.html#autotoc_md360", null ],
      [ "NWNX_NOSTACK_*_DEFAULT_TYPE", "group__nostack.html#autotoc_md361", null ],
      [ "NWNX_NOSTACK_SEPARATE_INVALID_OID_EFFECTS", "group__nostack.html#autotoc_md362", null ]
    ] ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md363", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md364", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md366", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md367", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md368", null ],
    [ "Setup", "group__race.html#autotoc_md369", [
      [ "The 2da Method", "group__race.html#autotoc_md370", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md371", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md372", [
      [ "AB", "group__race.html#autotoc_md373", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md376", null ],
      [ "AC", "group__race.html#autotoc_md379", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md382", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md385", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md388", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md391", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md394", null ],
      [ "FEAT", "group__race.html#autotoc_md397", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md400", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md403", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md406", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md409", null ],
      [ "RACE", "group__race.html#autotoc_md412", null ],
      [ "REGENERATION", "group__race.html#autotoc_md415", null ],
      [ "SAVE", "group__race.html#autotoc_md418", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md421", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md424", null ],
      [ "SKILL", "group__race.html#autotoc_md427", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md430", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md433", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md436", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md439", null ],
    [ "Setup", "group__redis.html#autotoc_md440", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md441", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md442", [
      [ "Moving on", "group__redis.html#autotoc_md443", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md444", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md445", null ],
    [ "Sample Include", "group__rename.html#autotoc_md446", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md447", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md448", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md449", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md456", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md457", null ],
    [ "Migration", "group__sql.html#autotoc_md461", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md462", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md463", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md464", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md465", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md466", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md467", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md468", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md469", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md470", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md471", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md472", null ],
    [ "Notes", "group__tileset.html#autotoc_md473", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md474", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md475", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md476", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md477", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md478", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md479", null ],
      [ "NWNX_TWEAKS_LANGUAGE_OVERRIDE", "group__tweaks.html#autotoc_md480", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md481", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md482", null ],
    [ "Available functions", "group__weapon.html#autotoc_md483", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md484", null ],
    [ "Limitations", "group__webhook.html#autotoc_md485", null ],
    [ "Example usage", "group__webhook.html#autotoc_md486", null ],
    [ "Log", "array__example_8nss.html#a71f6011f9c84f74acca8b63d03303cb6", null ],
    [ "TestArrayOnModule", "array__example_8nss.html#a15e56d0f9f40208818b8b5ac4bbfb3d0", null ],
    [ "TestArrayOnChicken", "array__example_8nss.html#a493a8ce1f39e3d96e3f2e7faf28f6fb7", null ],
    [ "TestNWNXArray", "array__example_8nss.html#a79f746b87354fb91846482213ec74929", null ],
    [ "main", "array__example_8nss.html#acdef7a1fd863a6d3770c1268cb06add3", null ]
];