var array__example_8nss =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md181", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md182", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md183", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md184", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md185", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md186", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md187", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md188", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md250", null ],
    [ "Environment Variables", "group__compiler.html#autotoc_md251", null ],
    [ "Example", "group__damage.html#autotoc_md252", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md253", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md254", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md255", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md256", [
      [ "Dependencies", "group__dotnet.html#autotoc_md257", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md258", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md259", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md260", [
        [ "Sample", "group__nwnx.html#autotoc_md189", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md261", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md262", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md263", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md264", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md265", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md266", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md267", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md268", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md269", [
      [ "NWN types", "group__dotnet.html#autotoc_md270", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md271", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md272", null ],
      [ "Closures", "group__dotnet.html#autotoc_md273", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md274", null ]
    ] ],
    [ "Environment Variables", "group__effect.html#autotoc_md275", [
      [ "NWNX_EFFECT_EXTEND_DURATION_TYPE = true/false", "group__effect.html#autotoc_md276", [
        [ "const int DURATION_TYPE_EQUIPPED = 3;", "group__effect.html#autotoc_md277", null ],
        [ "const int DURATION_TYPE_INNATE = 4;", "group__effect.html#autotoc_md278", null ]
      ] ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md279", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md280", null ],
    [ "Events", "group__elc.html#autotoc_md281", null ],
    [ "Example Script", "group__elc.html#autotoc_md282", null ],
    [ "Notes", "group__experimental.html#autotoc_md397", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md398", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md399", null ],
    [ "Setup", "group__feat.html#autotoc_md400", [
      [ "The 2da Method", "group__feat.html#autotoc_md401", null ]
    ] ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md402", [
      [ "AB", "group__feat.html#autotoc_md403", null ],
      [ "ABILITY", "group__feat.html#autotoc_md405", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md407", null ],
      [ "AC", "group__feat.html#autotoc_md409", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md411", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md413", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md415", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md417", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md419", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md421", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md423", null ],
      [ "HASTE", "group__feat.html#autotoc_md425", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md427", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md429", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md431", null ],
      [ "SAVE", "group__feat.html#autotoc_md433", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md435", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md437", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md439", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md441", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md443", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md445", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md447", null ],
      [ "SPELLSAVEDC", "group__feat.html#autotoc_md449", null ],
      [ "SPELLSAVEDCFORSCHOOL", "group__feat.html#autotoc_md451", null ],
      [ "SPELLSAVEDCFORSPELL", "group__feat.html#autotoc_md453", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md455", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md457", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md459", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md461", null ],
    [ "Quick start", "group__lua.html#autotoc_md462", [
      [ "Docker", "group__lua.html#autotoc_md463", null ],
      [ "Native", "group__lua.html#autotoc_md464", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md465", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md466", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md467", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md468", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md469", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md470", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md471", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md472", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md473", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md474", null ],
    [ "Environment Variables", "group__nostack.html#autotoc_md475", [
      [ "NWNX_NOSTACK_*", "group__nostack.html#autotoc_md476", null ],
      [ "NWNX_NOSTACK_*_DEFAULT_TYPE", "group__nostack.html#autotoc_md477", null ],
      [ "NWNX_NOSTACK_SEPARATE_INVALID_OID_EFFECTS", "group__nostack.html#autotoc_md478", null ]
    ] ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md479", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md480", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md482", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md483", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md484", null ],
    [ "Setup", "group__race.html#autotoc_md485", [
      [ "The 2da Method", "group__race.html#autotoc_md486", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md487", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md488", [
      [ "AB", "group__race.html#autotoc_md489", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md492", null ],
      [ "AC", "group__race.html#autotoc_md495", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md498", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md501", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md504", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md507", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md510", null ],
      [ "FEAT", "group__race.html#autotoc_md513", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md516", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md519", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md522", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md525", null ],
      [ "RACE", "group__race.html#autotoc_md528", null ],
      [ "REGENERATION", "group__race.html#autotoc_md531", null ],
      [ "SAVE", "group__race.html#autotoc_md534", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md537", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md540", null ],
      [ "SKILL", "group__race.html#autotoc_md543", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md546", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md549", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md552", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md555", null ],
    [ "Setup", "group__redis.html#autotoc_md556", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md557", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md558", [
      [ "Moving on", "group__redis.html#autotoc_md559", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md560", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md561", null ],
    [ "Sample Include", "group__rename.html#autotoc_md562", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md567", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md568", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md569", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md576", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md577", null ],
    [ "Migration", "group__sql.html#autotoc_md581", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md582", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md583", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md584", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md585", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md586", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md587", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md588", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md589", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md590", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md591", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md592", null ],
    [ "Notes", "group__tileset.html#autotoc_md593", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md594", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md595", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md596", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md597", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md598", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md599", null ],
      [ "NWNX_TWEAKS_LANGUAGE_OVERRIDE", "group__tweaks.html#autotoc_md600", null ],
      [ "NWNX_TWEAKS_HIDE_HARDCODED_ITEM_VFX", "group__tweaks.html#autotoc_md601", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md602", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md603", null ],
    [ "Available functions", "group__weapon.html#autotoc_md604", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md605", null ],
    [ "Limitations", "group__webhook.html#autotoc_md606", null ],
    [ "Example usage", "group__webhook.html#autotoc_md607", null ],
    [ "Log", "array__example_8nss.html#a71f6011f9c84f74acca8b63d03303cb6", null ],
    [ "TestArrayOnModule", "array__example_8nss.html#a15e56d0f9f40208818b8b5ac4bbfb3d0", null ],
    [ "TestArrayOnChicken", "array__example_8nss.html#a493a8ce1f39e3d96e3f2e7faf28f6fb7", null ],
    [ "TestNWNXArray", "array__example_8nss.html#a79f746b87354fb91846482213ec74929", null ],
    [ "main", "array__example_8nss.html#acdef7a1fd863a6d3770c1268cb06add3", null ]
];