var array__example_8nss =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md181", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md182", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md183", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md184", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md185", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md186", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md187", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md188", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md250", null ],
    [ "Environment Variables", "group__compiler.html#autotoc_md251", null ],
    [ "Example", "group__damage.html#autotoc_md252", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md253", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md254", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md255", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md256", [
      [ "Dependencies", "group__dotnet.html#autotoc_md257", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md258", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md259", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md260", [
        [ "Sample", "group__nwnx.html#autotoc_md189", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md261", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md262", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md263", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md264", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md265", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md266", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md267", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md268", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md269", [
      [ "NWN types", "group__dotnet.html#autotoc_md270", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md271", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md272", null ],
      [ "Closures", "group__dotnet.html#autotoc_md273", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md274", null ]
    ] ],
    [ "Environment Variables", "group__effect.html#autotoc_md275", [
      [ "NWNX_EFFECT_EXTEND_DURATION_TYPE = true/false", "group__effect.html#autotoc_md276", [
        [ "const int DURATION_TYPE_EQUIPPED = 3;", "group__effect.html#autotoc_md277", null ],
        [ "const int DURATION_TYPE_INNATE = 4;", "group__effect.html#autotoc_md278", null ]
      ] ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md279", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md280", null ],
    [ "Events", "group__elc.html#autotoc_md281", null ],
    [ "Example Script", "group__elc.html#autotoc_md282", null ],
    [ "Notes", "group__experimental.html#autotoc_md392", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md393", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md394", null ],
    [ "Setup", "group__feat.html#autotoc_md395", [
      [ "The 2da Method", "group__feat.html#autotoc_md396", null ]
    ] ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md397", [
      [ "AB", "group__feat.html#autotoc_md398", null ],
      [ "ABILITY", "group__feat.html#autotoc_md400", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md402", null ],
      [ "AC", "group__feat.html#autotoc_md404", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md406", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md408", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md410", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md412", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md414", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md416", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md418", null ],
      [ "HASTE", "group__feat.html#autotoc_md420", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md422", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md424", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md426", null ],
      [ "SAVE", "group__feat.html#autotoc_md428", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md430", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md432", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md434", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md436", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md438", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md440", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md442", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md444", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md446", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md448", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md450", null ],
    [ "Quick start", "group__lua.html#autotoc_md451", [
      [ "Docker", "group__lua.html#autotoc_md452", null ],
      [ "Native", "group__lua.html#autotoc_md453", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md454", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md455", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md456", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md457", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md458", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md459", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md460", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md461", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md462", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md463", null ],
    [ "Environment Variables", "group__nostack.html#autotoc_md464", [
      [ "NWNX_NOSTACK_*", "group__nostack.html#autotoc_md465", null ],
      [ "NWNX_NOSTACK_*_DEFAULT_TYPE", "group__nostack.html#autotoc_md466", null ],
      [ "NWNX_NOSTACK_SEPARATE_INVALID_OID_EFFECTS", "group__nostack.html#autotoc_md467", null ]
    ] ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md468", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md469", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md471", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md472", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md473", null ],
    [ "Setup", "group__race.html#autotoc_md474", [
      [ "The 2da Method", "group__race.html#autotoc_md475", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md476", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md477", [
      [ "AB", "group__race.html#autotoc_md478", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md481", null ],
      [ "AC", "group__race.html#autotoc_md484", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md487", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md490", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md493", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md496", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md499", null ],
      [ "FEAT", "group__race.html#autotoc_md502", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md505", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md508", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md511", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md514", null ],
      [ "RACE", "group__race.html#autotoc_md517", null ],
      [ "REGENERATION", "group__race.html#autotoc_md520", null ],
      [ "SAVE", "group__race.html#autotoc_md523", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md526", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md529", null ],
      [ "SKILL", "group__race.html#autotoc_md532", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md535", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md538", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md541", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md544", null ],
    [ "Setup", "group__redis.html#autotoc_md545", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md546", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md547", [
      [ "Moving on", "group__redis.html#autotoc_md548", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md549", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md550", null ],
    [ "Sample Include", "group__rename.html#autotoc_md551", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md552", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md553", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md554", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md561", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md562", null ],
    [ "Migration", "group__sql.html#autotoc_md566", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md567", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md568", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md569", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md570", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md571", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md572", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md573", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md574", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md575", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md576", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md577", null ],
    [ "Notes", "group__tileset.html#autotoc_md578", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md579", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md580", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md581", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md582", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md583", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md584", null ],
      [ "NWNX_TWEAKS_LANGUAGE_OVERRIDE", "group__tweaks.html#autotoc_md585", null ],
      [ "NWNX_TWEAKS_HIDE_HARDCODED_ITEM_VFX", "group__tweaks.html#autotoc_md586", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md587", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md588", null ],
    [ "Available functions", "group__weapon.html#autotoc_md589", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md590", null ],
    [ "Limitations", "group__webhook.html#autotoc_md591", null ],
    [ "Example usage", "group__webhook.html#autotoc_md592", null ],
    [ "Log", "array__example_8nss.html#a71f6011f9c84f74acca8b63d03303cb6", null ],
    [ "TestArrayOnModule", "array__example_8nss.html#a15e56d0f9f40208818b8b5ac4bbfb3d0", null ],
    [ "TestArrayOnChicken", "array__example_8nss.html#a493a8ce1f39e3d96e3f2e7faf28f6fb7", null ],
    [ "TestNWNXArray", "array__example_8nss.html#a79f746b87354fb91846482213ec74929", null ],
    [ "main", "array__example_8nss.html#acdef7a1fd863a6d3770c1268cb06add3", null ]
];