var dir_ce92b3ebeae221968cfbe8aae0d60ffe =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md17", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md18", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md19", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md20", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md21", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md22", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md23", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md34", null ],
    [ "Example", "group__damage.html#autotoc_md35", null ],
    [ "Notes", "group__elc.html#autotoc_md36", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md37", null ],
    [ "Example Script", "group__elc.html#autotoc_md38", null ],
    [ "Notes", "group__experimental.html#autotoc_md39", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md40", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md41", null ],
    [ "Quick start", "group__lua.html#autotoc_md42", [
      [ "Docker", "group__lua.html#autotoc_md43", null ],
      [ "Native", "group__lua.html#autotoc_md44", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md45", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md46", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md47", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md48", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md49", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md50", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md51", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md52", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md53", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md54", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md55", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md57", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md58", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md59", null ],
    [ "Setup", "group__race.html#autotoc_md60", [
      [ "The 2da Method", "group__race.html#autotoc_md61", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md62", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md63", [
      [ "AB", "group__race.html#autotoc_md64", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md67", null ],
      [ "AC", "group__race.html#autotoc_md70", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md73", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md76", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md79", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md82", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md85", null ],
      [ "FEAT", "group__race.html#autotoc_md88", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md91", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md94", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md97", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md100", null ],
      [ "RACE", "group__race.html#autotoc_md103", null ],
      [ "REGENERATION", "group__race.html#autotoc_md106", null ],
      [ "SAVE", "group__race.html#autotoc_md109", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md112", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md115", null ],
      [ "SKILL", "group__race.html#autotoc_md118", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md121", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md124", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md127", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md130", null ],
    [ "Setup", "group__redis.html#autotoc_md131", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md132", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md133", [
      [ "Moving on", "group__redis.html#autotoc_md134", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md135", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md136", null ],
    [ "Sample Include", "group__rename.html#autotoc_md137", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md138", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md139", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md146", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md147", null ],
    [ "Migration", "group__sql.html#autotoc_md151", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md152", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md153", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md154", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md155", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md156", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md157", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md158", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md159", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md160", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md164", null ],
    [ "Limitations", "group__webhook.html#autotoc_md170", null ],
    [ "Example usage", "group__webhook.html#autotoc_md171", null ],
    [ "nwnx.nss", "nwnx_8nss.html", "nwnx_8nss" ],
    [ "nwnx_consts.nss", "nwnx__consts_8nss.html", "nwnx__consts_8nss" ],
    [ "nwnx_tests.nss", "nwnx__tests_8nss.html", "nwnx__tests_8nss" ]
];