var dir_b4615358f6508fb1b951d958d300a95c =
[
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md25", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md36", null ],
    [ "Example", "group__damage.html#autotoc_md37", null ],
    [ "Notes", "group__elc.html#autotoc_md38", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md39", null ],
    [ "Example Script", "group__elc.html#autotoc_md40", null ],
    [ "Notes", "group__experimental.html#autotoc_md41", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md42", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md43", null ],
    [ "Quick start", "group__lua.html#autotoc_md44", [
      [ "Docker", "group__lua.html#autotoc_md45", null ],
      [ "Native", "group__lua.html#autotoc_md46", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md47", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md48", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md49", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md50", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md51", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md52", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md53", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md54", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md55", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md56", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md57", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md59", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md60", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md61", null ],
    [ "Setup", "group__race.html#autotoc_md62", [
      [ "The 2da Method", "group__race.html#autotoc_md63", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md64", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md65", [
      [ "AB", "group__race.html#autotoc_md66", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md69", null ],
      [ "AC", "group__race.html#autotoc_md72", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md75", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md78", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md81", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md84", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md87", null ],
      [ "FEAT", "group__race.html#autotoc_md90", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md93", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md96", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md99", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md102", null ],
      [ "RACE", "group__race.html#autotoc_md105", null ],
      [ "REGENERATION", "group__race.html#autotoc_md108", null ],
      [ "SAVE", "group__race.html#autotoc_md111", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md114", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md117", null ],
      [ "SKILL", "group__race.html#autotoc_md120", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md123", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md126", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md129", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md132", null ],
    [ "Setup", "group__redis.html#autotoc_md133", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md134", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md135", [
      [ "Moving on", "group__redis.html#autotoc_md136", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md137", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md138", null ],
    [ "Sample Include", "group__rename.html#autotoc_md139", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md140", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md141", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md148", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md149", null ],
    [ "Migration", "group__sql.html#autotoc_md153", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md154", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md155", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md156", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md157", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md158", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md159", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md160", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md161", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md162", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md166", null ],
    [ "Limitations", "group__webhook.html#autotoc_md172", null ],
    [ "Example usage", "group__webhook.html#autotoc_md173", null ]
];