var dir_ce92b3ebeae221968cfbe8aae0d60ffe =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md37", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md38", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md39", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md40", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md41", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md42", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md43", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md54", null ],
    [ "Example", "group__damage.html#autotoc_md55", null ],
    [ "Notes", "group__elc.html#autotoc_md76", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md77", null ],
    [ "Example Script", "group__elc.html#autotoc_md78", null ],
    [ "Notes", "group__experimental.html#autotoc_md135", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md136", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md137", null ],
    [ "Quick start", "group__lua.html#autotoc_md138", [
      [ "Docker", "group__lua.html#autotoc_md139", null ],
      [ "Native", "group__lua.html#autotoc_md140", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md141", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md142", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md143", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md144", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md145", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md146", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md147", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md148", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md149", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md150", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md151", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md153", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md154", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md155", null ],
    [ "Setup", "group__race.html#autotoc_md156", [
      [ "The 2da Method", "group__race.html#autotoc_md157", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md158", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md159", [
      [ "AB", "group__race.html#autotoc_md160", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md163", null ],
      [ "AC", "group__race.html#autotoc_md166", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md169", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md172", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md175", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md178", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md181", null ],
      [ "FEAT", "group__race.html#autotoc_md184", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md187", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md190", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md193", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md196", null ],
      [ "RACE", "group__race.html#autotoc_md199", null ],
      [ "REGENERATION", "group__race.html#autotoc_md202", null ],
      [ "SAVE", "group__race.html#autotoc_md205", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md208", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md211", null ],
      [ "SKILL", "group__race.html#autotoc_md214", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md217", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md220", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md223", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md226", null ],
    [ "Setup", "group__redis.html#autotoc_md227", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md228", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md229", [
      [ "Moving on", "group__redis.html#autotoc_md230", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md231", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md232", null ],
    [ "Sample Include", "group__rename.html#autotoc_md233", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md234", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md235", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md242", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md243", null ],
    [ "Migration", "group__sql.html#autotoc_md247", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md248", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md249", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md250", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md251", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md252", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md253", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md254", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md255", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md256", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md260", null ],
    [ "Limitations", "group__webhook.html#autotoc_md266", null ],
    [ "Example usage", "group__webhook.html#autotoc_md267", null ],
    [ "nwnx.nss", "nwnx_8nss.html", "nwnx_8nss" ],
    [ "nwnx_consts.nss", "nwnx__consts_8nss.html", "nwnx__consts_8nss" ],
    [ "nwnx_tests.nss", "nwnx__tests_8nss.html", "nwnx__tests_8nss" ]
];