var modules =
[
    [ "NWNX", "group__nwnx.html", "group__nwnx" ],
    [ "Administration", "group__admin.html", "group__admin" ],
    [ "Appearance", "group__appearance.html", "group__appearance" ],
    [ "Area", "group__area.html", "group__area" ],
    [ "Chat", "group__chat.html", "group__chat" ],
    [ "Combat Modes", "group__combatmodes.html", "group__combatmodes" ],
    [ "Creature", "group__creature.html", "group__creature" ],
    [ "Damage", "group__damage.html", "group__damage" ],
    [ "Data", "group__data.html", "group__data" ],
    [ "Diagnostics", "group__diagnostics.html", "group__diagnostics" ],
    [ "Dialog", "group__dialog.html", "group__dialog" ],
    [ "DotNET", "group__dotnet.html", "group__dotnet" ],
    [ "Effect", "group__effect.html", "group__effect" ],
    [ "ELC", "group__elc.html", "group__elc" ],
    [ "Encounter", "group__encounter.html", "group__encounter" ],
    [ "Events", "group__events.html", "group__events" ],
    [ "Experimental", "group__experimental.html", "group__experimental" ],
    [ "Feat", "group__feat.html", "group__feat" ],
    [ "Feedback", "group__feedback.html", "group__feedback" ],
    [ "Item", "group__item.html", "group__item" ],
    [ "ItemProperty", "group__itemproperty.html", "group__itemproperty" ],
    [ "LUA", "group__lua.html", "group__lua" ],
    [ "MaxLevel", "group__maxlevel.html", "group__maxlevel" ],
    [ "Metrics InfluxDB", "group__metrics__influxdb.html", "group__metrics__influxdb" ],
    [ "Object", "group__object.html", "group__object" ],
    [ "Optimizations", "group__optimizations.html", "group__optimizations" ],
    [ "Player", "group__player.html", "group__player" ],
    [ "Profiler", "group__profiler.html", "group__profiler" ],
    [ "Race", "group__race.html", "group__race" ],
    [ "Redis", "group__redis.html", "group__redis" ],
    [ "Regex", "group__regex.html", "group__regex" ],
    [ "Rename", "group__rename.html", "group__rename" ],
    [ "Reveal", "group__reveal.html", "group__reveal" ],
    [ "Ruby", "group__ruby.html", "group__ruby" ],
    [ "ServerLogRedirector", "group__serverlogredirector.html", "group__serverlogredirector" ],
    [ "SkillRanks", "group__skillranks.html", "group__skillranks" ],
    [ "SpellChecker", "group__spellchecker.html", "group__spellchecker" ],
    [ "SQL", "group__sql.html", "group__sql" ],
    [ "ThreadWatchdog", "group__threadwatchdog.html", "group__threadwatchdog" ],
    [ "Tileset", "group__tileset.html", "group__tileset" ],
    [ "Time", "group__time.html", "group__time" ],
    [ "Tracking", "group__tracking.html", "group__tracking" ],
    [ "Tweaks", "group__tweaks.html", "group__tweaks" ],
    [ "Util", "group__util.html", "group__util" ],
    [ "Visibility", "group__visibility.html", "group__visibility" ],
    [ "Weapon", "group__weapon.html", "group__weapon" ],
    [ "Webhook", "group__webhook.html", "group__webhook" ]
];