#include "C2DA.cpp"
#include "CAppManager.cpp"
#include "CCallbackImplTemplated12.cpp"
#include "CCallbackImplTemplated16.cpp"
#include "CCallbackImplTemplated20.cpp"
#include "CCallbackImplTemplated264.cpp"
#include "CCallbackImplTemplated28.cpp"
#include "CCallbackImplTemplated4.cpp"
#include "CCallbackImplTemplated8.cpp"
#include "CCodeBase.cpp"
#include "CCodeBaseInternal.cpp"
#include "CCombatInformation.cpp"
#include "CCombatInformationNode.cpp"
#include "CERFFile.cpp"
#include "CERFKey.cpp"
#include "CERFRes.cpp"
#include "CERFString.cpp"
#include "CExoAliasList.cpp"
#include "CExoAliasListInternal.cpp"
#include "CExoArrayListTemplatedCCombatInformationNodePtr.cpp"
#include "CExoArrayListTemplatedCExoString.cpp"
#include "CExoArrayListTemplatedCExoStringPtr.cpp"
#include "CExoArrayListTemplatedCFeatUseListEntryPtr.cpp"
#include "CExoArrayListTemplatedCFileInfo.cpp"
#include "CExoArrayListTemplatedCGameEffectPtr.cpp"
#include "CExoArrayListTemplatedCGameObjectPtr.cpp"
#include "CExoArrayListTemplatedchar.cpp"
#include "CExoArrayListTemplatedCNetLayerPlayerCDKeyInfo.cpp"
#include "CExoArrayListTemplatedCNWCCMessageDataPtr.cpp"
#include "CExoArrayListTemplatedCNWItemProperty.cpp"
#include "CExoArrayListTemplatedCNWLevelStatsPtr.cpp"
#include "CExoArrayListTemplatedCNWSExpressionListPtr.cpp"
#include "CExoArrayListTemplatedCNWSExpressionNodePtr.cpp"
#include "CExoArrayListTemplatedCNWSFactionPtr.cpp"
#include "CExoArrayListTemplatedCNWSInvitationDetails.cpp"
#include "CExoArrayListTemplatedCNWSItemPtr.cpp"
#include "CExoArrayListTemplatedCNWSPersonalReputation.cpp"
#include "CExoArrayListTemplatedCNWSPlayerJournalQuestUpdates.cpp"
#include "CExoArrayListTemplatedCNWSScriptVar.cpp"
#include "CExoArrayListTemplatedCNWSSpellScriptDataPtr.cpp"
#include "CExoArrayListTemplatedCNWSStats_SpellLikeAbility.cpp"
#include "CExoArrayListTemplatedCNWTileSurfaceMeshAABBNodePtr.cpp"
#include "CExoArrayListTemplatedCNWVisibilityNodePtr.cpp"
#include "CExoArrayListTemplatedCResRef.cpp"
#include "CExoArrayListTemplatedCSpell_AddPtr.cpp"
#include "CExoArrayListTemplatedCWorldJournalEntry.cpp"
#include "CExoArrayListTemplatedfloat.cpp"
#include "CExoArrayListTemplatedint.cpp"
#include "CExoArrayListTemplatedMaterialShaderParam.cpp"
#include "CExoArrayListTemplatedNWPlayerCharacterList_stPtr.cpp"
#include "CExoArrayListTemplatedNWPlayerCharacterListClass_st.cpp"
#include "CExoArrayListTemplatedSJournalEntry.cpp"
#include "CExoArrayListTemplatedSMstBuddyEntryPtr.cpp"
#include "CExoArrayListTemplatedSMstDigiDistInfoPtr.cpp"
#include "CExoArrayListTemplatedunsignedchar.cpp"
#include "CExoArrayListTemplatedunsignedlong.cpp"
#include "CExoArrayListTemplatedunsignedlonglong.cpp"
#include "CExoArrayListTemplatedunsignedshort.cpp"
#include "CExoBase.cpp"
#include "CExoBaseInternal.cpp"
#include "CExoCriticalSection.cpp"
#include "CExoCriticalSectionInternal.cpp"
#include "CExoDebug.cpp"
#include "CExoDebugInternal.cpp"
#include "CExoEncapsulatedFile.cpp"
#include "CExoEncrypt.cpp"
#include "CExoFile.cpp"
#include "CExoFileInternal.cpp"
#include "CExoFileThread.cpp"
#include "CExoIni.cpp"
#include "CExoIniInternal.cpp"
#include "CExoKeyTable.cpp"
#include "CExoLinkedListInternal.cpp"
#include "CExoLinkedListTemplatedC2DA.cpp"
#include "CExoLinkedListTemplatedCERFKey.cpp"
#include "CExoLinkedListTemplatedCERFString.cpp"
#include "CExoLinkedListTemplatedCExoKeyTable.cpp"
#include "CExoLinkedListTemplatedCExoString.cpp"
#include "CExoLinkedListTemplatedCKeyTableInfo.cpp"
#include "CExoLinkedListTemplatedCLinuxFileKey.cpp"
#include "CExoLinkedListTemplatedCLinuxFileSection.cpp"
#include "CExoLinkedListTemplatedCNWSClient.cpp"
#include "CExoLinkedListTemplatedCNWSDialogPlayer.cpp"
#include "CExoLinkedListTemplatedCNWSObjectActionNode.cpp"
#include "CExoLinkedListTemplatedCNWSPlayerLUOInventoryItem.cpp"
#include "CExoLinkedListTemplatedCNWSPlayerTURD.cpp"
#include "CExoLinkedListTemplatedCRes.cpp"
#include "CExoLinkedListTemplatedCResRef.cpp"
#include "CExoLinkedListTemplatedCServerAIEventNode.cpp"
#include "CExoLinkedListTemplatedNWAreaExpansion_st.cpp"
#include "CExoLinkedListTemplatedNWModuleCutScene_st.cpp"
#include "CExoLinkedListTemplatedNWModuleExpansion_st.cpp"
#include "CExoLinkedListTemplatedNWPlayerListItem_st.cpp"
#include "CExoLinkedListTemplatedunsignedlong.cpp"
#include "CExoLinkedListTemplatedunsignedshort.cpp"
#include "CExoLocString.cpp"
#include "CExoLocStringInternal.cpp"
#include "CExoMemman.cpp"
#include "CExoPackedFile.cpp"
#include "CExoRand.cpp"
#include "CExoRandInternal.cpp"
#include "CExoResFile.cpp"
#include "CExoResMan.cpp"
#include "CExoResourceImageFile.cpp"
#include "CExoString.cpp"
#include "CExoStringList.cpp"
#include "CExoTimers.cpp"
#include "CExoTimersInternal.cpp"
#include "CExtendedServerInfo.cpp"
#include "CFactionManager.cpp"
#include "CFriendInfo.cpp"
#include "CFriendPresenceInfo.cpp"
#include "CGameEffect.cpp"
#include "CGameObject.cpp"
#include "CGameObjectArray.cpp"
#include "CGOG.cpp"
#include "CGOGInternal.cpp"
#include "CItemRepository.cpp"
#include "CLastUpdateObject.cpp"
#include "CLoopingVisualEffect.cpp"
#include "CMemRecord.cpp"
#include "CNetLayer.cpp"
#include "CNetLayerInternal.cpp"
#include "CNetLayerPlayerInfo.cpp"
#include "CNetLayerSessionInfo.cpp"
#include "CNetLayerWindow.cpp"
#include "CNWArea.cpp"
#include "CNWBaseItem.cpp"
#include "CNWBaseItemArray.cpp"
#include "CNWCCMessageData.cpp"
#include "CNWClass.cpp"
#include "CNWCreatureStatsUpdate.cpp"
#include "CNWDomain.cpp"
#include "CNWDoorSurfaceMesh.cpp"
#include "CNWFeat.cpp"
#include "CNWItem.cpp"
#include "CNWLevelStats.cpp"
#include "CNWMessage.cpp"
#include "CNWNameGen.cpp"
#include "CNWPlaceableSurfaceMesh.cpp"
#include "CNWPlaceMeshManager.cpp"
#include "CNWRace.cpp"
#include "CNWRules.cpp"
#include "CNWSAmbientSound.cpp"
#include "CNWSArea.cpp"
#include "CNWSAreaOfEffectObject.cpp"
#include "CNWSBarter.cpp"
#include "CNWSClient.cpp"
#include "CNWSCombatAttackData.cpp"
#include "CNWSCombatRound.cpp"
#include "CNWSCombatRoundAction.cpp"
#include "CNWSCreature.cpp"
#include "CNWSCreatureStats.cpp"
#include "CNWSCreatureStats_ClassInfo.cpp"
#include "CNWSDialog.cpp"
#include "CNWSDoor.cpp"
#include "CNWSDungeonMaster.cpp"
#include "CNWSEffectListHandler.cpp"
#include "CNWSEncounter.cpp"
#include "CNWSExpression.cpp"
#include "CNWSExpressionList.cpp"
#include "CNWSExpressionNode.cpp"
#include "CNWSFaction.cpp"
#include "CNWSForcedAction.cpp"
#include "CNWSInventory.cpp"
#include "CNWSItem.cpp"
#include "CNWSItemPropertyHandler.cpp"
#include "CNWSJournal.cpp"
#include "CNWSkill.cpp"
#include "CNWSMessage.cpp"
#include "CNWSModule.cpp"
#include "CNWSObject.cpp"
#include "CNWSObjectActionNode.cpp"
#include "CNWSpell.cpp"
#include "CNWSpellArray.cpp"
#include "CNWSPlaceable.cpp"
#include "CNWSPlayer.cpp"
#include "CNWSPlayerCharSheetGUI.cpp"
#include "CNWSPlayerContainerGUI.cpp"
#include "CNWSPlayerInventoryGUI.cpp"
#include "CNWSPlayerLastUpdateObject.cpp"
#include "CNWSPlayerLUOInventory.cpp"
#include "CNWSPlayerStoreGUI.cpp"
#include "CNWSPlayerTURD.cpp"
#include "CNWSRules.cpp"
#include "CNWSScriptVarTable.cpp"
#include "CNWSSoundObject.cpp"
#include "CNWSSpellScriptData.cpp"
#include "CNWSStats_Spell.cpp"
#include "CNWSStats_SpellLikeAbility.cpp"
#include "CNWSStore.cpp"
#include "CNWSSysAdmin.cpp"
#include "CNWSTile.cpp"
#include "CNWSTransition.cpp"
#include "CNWSTrigger.cpp"
#include "CNWSWaypoint.cpp"
#include "CNWTile.cpp"
#include "CNWTileData.cpp"
#include "CNWTileSet.cpp"
#include "CNWTileSetManager.cpp"
#include "CNWTileSurfaceMesh.cpp"
#include "CNWTileSurfaceMeshAABBNode.cpp"
#include "CNWTileSurfaceMeshHashTableEntry.cpp"
#include "CNWVirtualMachineCommands.cpp"
#include "CObjectLookupTable.cpp"
#include "CObjectTableManager.cpp"
#include "CPathfindInfoIntraTileSuccessors.cpp"
#include "CPathfindInformation.cpp"
#include "CrashReporter_Linux.cpp"
#include "CRes.cpp"
#include "CRes2DA.cpp"
#include "CResARE.cpp"
#include "CResDWK.cpp"
#include "CResGFF.cpp"
#include "CResGFFFieldIDHash.cpp"
#include "CResHelperTemplatedCRes2DA2017.cpp"
#include "CResHelperTemplatedCResARE2012.cpp"
#include "CResHelperTemplatedCResDWK2052.cpp"
#include "CResHelperTemplatedCResIFO2014.cpp"
#include "CResHelperTemplatedCResLTR2036.cpp"
#include "CResHelperTemplatedCResNCS2010.cpp"
#include "CResHelperTemplatedCResNDB2064.cpp"
#include "CResHelperTemplatedCResNSS2009.cpp"
#include "CResHelperTemplatedCResPWK2053.cpp"
#include "CResHelperTemplatedCResSET2013.cpp"
#include "CResHelperTemplatedCResTLK2018.cpp"
#include "CResHelperTemplatedCResWOK2016.cpp"
#include "CResIFO.cpp"
#include "CResLTR.cpp"
#include "CResNCS.cpp"
#include "CResNDB.cpp"
#include "CResNSS.cpp"
#include "CResPWK.cpp"
#include "CResRef.cpp"
#include "CResSET.cpp"
#include "CResTGA.cpp"
#include "CResTLK.cpp"
#include "CResWOK.cpp"
#include "CScriptCompiler.cpp"
#include "CScriptCompilerIdListEntry.cpp"
#include "CScriptEvent.cpp"
#include "CScriptLocation.cpp"
#include "CScriptSourceFile.cpp"
#include "CScriptTalent.cpp"
#include "CServerAIBodyBagInfo.cpp"
#include "CServerAIEventNode.cpp"
#include "CServerAIList.cpp"
#include "CServerAIMaster.cpp"
#include "CServerExoApp.cpp"
#include "CServerExoAppInternal.cpp"
#include "CServerInfo.cpp"
#include "CStoreCustomer.cpp"
#include "CTlkFile.cpp"
#include "CTlkResFile.cpp"
#include "CTlkTable.cpp"
#include "CTwoDimArrays.cpp"
#include "CVirtualMachine.cpp"
#include "CVirtualMachineCache.cpp"
#include "CVirtualMachineDebuggerInstance.cpp"
#include "CVirtualMachineDebugLoader.cpp"
#include "CVirtualMachineFile.cpp"
#include "CVirtualMachineScript.cpp"
#include "CVirtualMachineStack.cpp"
#include "CWorldTimer.cpp"
#include "HttpBuffer.cpp"
#include "HttpConnection.cpp"
#include "ICrashReporter.cpp"
#include "ListTemplatedCExoString.cpp"
#include "Matrix.cpp"
#include "Plane.cpp"
#include "Quaternion.cpp"
#include "ScopeGuard.cpp"
#include "SJournalEntry.cpp"
#include "STR_RES.cpp"
#include "Vector.cpp"
#include "Vector4.cpp"
#include "addrinfo.cpp"
#include "AggInfo.cpp"
#include "AggInfo_col.cpp"
#include "AggInfo_func.cpp"
#include "algo_time_t.cpp"
#include "analysisInfo.cpp"
#include "asprintf.cpp"
#include "audio_buf_info.cpp"
#include "AudioBootStrap.cpp"
#include "auth.cpp"
#include "AuthContext.cpp"
#include "AutoincInfo.cpp"
#include "AuxData.cpp"
#include "axis_correct.cpp"
#include "B4BLOCK.cpp"
#include "B4KEY_DATA.cpp"
#include "B4NODE_HEADER.cpp"
#include "B4STD_HEADER.cpp"
#include "back.cpp"
#include "balldelta.cpp"
#include "BenignMallocHooks.cpp"
#include "BiffFileHeader_st.cpp"
#include "BiffFileVarResEntry_st.cpp"
#include "BIT_CStream_t.cpp"
#include "BIT_DStream_t.cpp"
#include "Bitvec.cpp"
#include "blacklist_node.cpp"
#include "blit_table.cpp"
#include "blockProperties_t.cpp"
#include "BtCursor.cpp"
#include "BtLock.cpp"
#include "Btree.cpp"
#include "BtreePayload.cpp"
#include "BtShared.cpp"
#include "buffer.cpp"
#include "buffer_data_t.cpp"
#include "buffer_s.cpp"
#include "BusyHandler.cpp"
#include "callback_data_t.cpp"
#include "CallCount.cpp"
#include "CAutoSave.cpp"
#include "CBaseExoApp.cpp"
#include "CBWCBase.cpp"
#include "CBWCBlowFish.cpp"
#include "CBWCBlowFishBlock.cpp"
#include "CBWCBlowFishState.cpp"
#include "CBWCMD5.cpp"
#include "CCallbackBase.cpp"
#include "CCallbackHandlerBase.cpp"
#include "CCallbackManualTemplatedCSteamInternalGameLobbyJoinRequested_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalGameRichPresenceJoinRequested_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalLobbyChatUpdate_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalLobbyCreated_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalLobbyDataUpdate_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalLobbyEnter_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalLobbyMatchList_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalP2PSessionRequest_tfalse.cpp"
#include "CCallbackManualTemplatedCSteamInternalUserStatsReceived_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalGameLobbyJoinRequested_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalGameRichPresenceJoinRequested_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalLobbyChatUpdate_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalLobbyCreated_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalLobbyDataUpdate_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalLobbyEnter_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalLobbyMatchList_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalP2PSessionRequest_tfalse.cpp"
#include "CCallbackTemplatedCSteamInternalUserStatsReceived_tfalse.cpp"
#include "CCallResultTemplatedCSteamInternalCreateItemResult_t.cpp"
#include "CCallResultTemplatedCSteamInternalEncryptedAppTicketResponse_t.cpp"
#include "CCallResultTemplatedCSteamInternalLobbyEnter_t.cpp"
#include "CCallResultTemplatedCSteamInternalSteamUGCQueryCompleted_t.cpp"
#include "CCallResultTemplatedCSteamInternalSteamUGCRequestUGCDetailsResult_t.cpp"
#include "CCallResultTemplatedCSteamInternalSubmitItemUpdateResult_t.cpp"
#include "CClientExoApp.cpp"
#include "CConnectionLib.cpp"
#include "CConnectionLib__RoomListEntry.cpp"
#include "CCurHint.cpp"
#include "CEffectIconObject.cpp"
#include "CellArray.cpp"
#include "CellInfo.cpp"
#include "CEncounterListEntry.cpp"
#include "CEncounterSpawnPoint.cpp"
#include "CExoAliasListInternal__CExoAlias.cpp"
#include "CExoArrayListTemplatedCConnectionLib__RoomListEntry.cpp"
#include "CExoArrayListTemplatedCEffectIconObjectPtr.cpp"
#include "CExoArrayListTemplatedCExoNetInternal__PendingAddressTranslationPtr.cpp"
#include "CExoArrayListTemplatedCGOGFriendRichPresencePtr.cpp"
#include "CExoArrayListTemplatedCLoopingVisualEffectPtr.cpp"
#include "CExoArrayListTemplatedCNWSExpressionPtr.cpp"
#include "CExoArrayListTemplatedCNWSPVPEntry.cpp"
#include "CExoArrayListTemplatedCNWSStats_SpellPtr.cpp"
#include "CExoArrayListTemplatedCNWSTagNode.cpp"
#include "CExoArrayListTemplatedconstCGameEffectPtr.cpp"
#include "CExoArrayListTemplatedCScriptLogPtr.cpp"
#include "CExoArrayListTemplatedCSpell_DeletePtr.cpp"
#include "CExoArrayListTemplatedCStoreCustomerPtr.cpp"
#include "CExoArrayListTemplatedCVirtualMachineFilePtr.cpp"
#include "CExoArrayListTemplatedlonglongunsignedint.cpp"
#include "CExoArrayListTemplatedlongunsignedint.cpp"
#include "CExoArrayListTemplatedNWSync__CNWSync__ManifestEntry.cpp"
#include "CExoArrayListTemplatedNWSync__CNWSync__MappingBatchInsertEntry.cpp"
#include "CExoArrayListTemplatedNWSync__CNWSync__ResRefBatchInsertEntry.cpp"
#include "CExoArrayListTemplatedNWSync__StorageProviderPtr.cpp"
#include "CExoArrayListTemplatedSCodeBaseDataPtr.cpp"
#include "CExoArrayListTemplatedshortunsignedint.cpp"
#include "CExoArrayListTemplatedSMstKeyEntryPtr.cpp"
#include "CExoArrayListTemplatedSMstNameEntryPtr.cpp"
#include "CExoArrayListTemplatedSSubNetProfilePtr.cpp"
#include "CExoLinkedListNode.cpp"
#include "CExoLinkedListTemplatedCERFRes.cpp"
#include "CExoLinkedListTemplatedCLastUpdateObject.cpp"
#include "CExoLinkedListTemplatedCLastUpdatePartyObject.cpp"
#include "CExoLinkedListTemplatedCNWSCombatRoundAction.cpp"
#include "CExoLinkedListTemplatedCNWSPlayer.cpp"
#include "CExoLinkedListTemplatedCNWSPlayerPtr.cpp"
#include "CExoLinkedListTemplatedExoLocString_st.cpp"
#include "CExoLinkedListTemplatedlongunsignedint.cpp"
#include "CExoLinkedListTemplatedshortunsignedint.cpp"
#include "CExoMemHeap.cpp"
#include "CExoMemHeapStats.cpp"
#include "CExoMemHeapWalkInfo.cpp"
#include "CExoNet.cpp"
#include "CExoNetExtendableBuffer.cpp"
#include "CExoNetFrameBuffer.cpp"
#include "CExoNetInternal.cpp"
#include "CExoNetInternal__PendingAddressTranslation.cpp"
#include "CFeatUseListEntry.cpp"
#include "CFileInfo.cpp"
#include "CGameEffectApplierRemover.cpp"
#include "CGameID.cpp"
#include "CGameID__GameID_t.cpp"
#include "CGameObjectArrayNode.cpp"
#include "CGOGFriendRichPresence.cpp"
#include "Chunk.cpp"
#include "CItemPropertyApplierRemover.cpp"
#include "CJoiningRestrictions.cpp"
#include "CKeyTableEntry.cpp"
#include "CKeyTableInfo.cpp"
#include "CLastUpdatePartyObject.cpp"
#include "CLinuxFileKey.cpp"
#include "CLinuxFileSection.cpp"
#include "CMessageProfile.cpp"
#include "CMstNetLayer.cpp"
#include "CNetLayerPlayerCDKeyInfo.cpp"
#include "CNetworkProfiler.cpp"
#include "CNWActionNode.cpp"
#include "CNWAmbientSound.cpp"
#include "CNWCArea.cpp"
#include "CNWCAreaOfEffectObject.cpp"
#include "CNWCCreature.cpp"
#include "CNWCDoor.cpp"
#include "CNWCItem.cpp"
#include "CNWClass__CNWClass_Skill.cpp"
#include "CNWClass_Feat.cpp"
#include "CNWCModule.cpp"
#include "CNWCObject.cpp"
#include "CNWCPlaceable.cpp"
#include "CNWCProjectile.cpp"
#include "CNWCSoundObject.cpp"
#include "CNWCStore.cpp"
#include "CNWCTrigger.cpp"
#include "CNWItemProperty.cpp"
#include "CNWReentrantServerStats.cpp"
#include "CNWSAnimBase.cpp"
#include "CNWSAreaGridSuccessors.cpp"
#include "CNWSAreaGridTransTableEntry.cpp"
#include "CNWSAreaInterTileSuccessors.cpp"
#include "CNWSCreatureAppearanceInfo.cpp"
#include "CNWSCreRestorePolymorphData.cpp"
#include "CNWSDialogEntry.cpp"
#include "CNWSDialogLinkEntry.cpp"
#include "CNWSDialogLinkReply.cpp"
#include "CNWSDialogPlayer.cpp"
#include "CNWSDialogReply.cpp"
#include "CNWSDialogSpeaker.cpp"
#include "CNWSInvitationDetails.cpp"
#include "CNWSPersonalReputation.cpp"
#include "CNWSPlayerJournalQuest.cpp"
#include "CNWSPlayerJournalQuestUpdates.cpp"
#include "CNWSPlayerLUOAppearanceInfo.cpp"
#include "CNWSPlayerLUOInventoryItem.cpp"
#include "CNWSPlayerLUOQuickbarItemButton.cpp"
#include "CNWSPlayerLUOSortedObjectList.cpp"
#include "CNWSPVPEntry.cpp"
#include "CNWSQuickbarButton.cpp"
#include "CNWSScriptVar.cpp"
#include "CNWSTagNode.cpp"
#include "CNWTilePathNode.cpp"
#include "CNWTileSurfaceMeshLocalInfo.cpp"
#include "CNWTileSurfaceMeshNodeFace.cpp"
#include "CNWTileSurfaceMeshNodeVertex.cpp"
#include "CNWTileSurfaceMeshSortSuccessors.cpp"
#include "CNWVisibilityNode.cpp"
#include "code.cpp"
#include "CODE4St.cpp"
#include "CODE4TRANSSt.cpp"
#include "COLLATE4.cpp"
#include "CollSeq.cpp"
#include "Column.cpp"
#include "compareInfo.cpp"
#include "config_s.cpp"
#include "conncache.cpp"
#include "ConnectBits.cpp"
#include "connectbundle.cpp"
#include "connectdata.cpp"
#include "connfind.cpp"
#include "contenc_writer_s.cpp"
#include "content_encoding_s.cpp"
#include "Cookie.cpp"
#include "CookieInfo.cpp"
#include "CountCtx.cpp"
#include "CPersistantWorldOptions.cpp"
#include "CPlayOptions.cpp"
#include "CrashReporterData.cpp"
#include "CreateItemResult_t.cpp"
#include "CResetOption.cpp"
#include "CResGFFField.cpp"
#include "CResGFFFileHeader.cpp"
#include "CResGFFLabel.cpp"
#include "CResGFFStruct.cpp"
#include "CResHelperTemplatedCRes2DA2017u.cpp"
#include "CResHelperTemplatedCResARE2012u.cpp"
#include "CResHelperTemplatedCResDWK2052u.cpp"
#include "CResHelperTemplatedCResIFO2014u.cpp"
#include "CResHelperTemplatedCResLTR2036u.cpp"
#include "CResHelperTemplatedCResNCS2010u.cpp"
#include "CResHelperTemplatedCResNDB2064u.cpp"
#include "CResHelperTemplatedCResNSS2009u.cpp"
#include "CResHelperTemplatedCResPWK2053u.cpp"
#include "CResHelperTemplatedCResSET2013u.cpp"
#include "CResHelperTemplatedCResTLK2018u.cpp"
#include "CResHelperTemplatedCResWOK2016u.cpp"
#include "CResList.cpp"
#include "CResStruct.cpp"
#include "CScriptCompilerIdentifierHashTableEntry.cpp"
#include "CScriptCompilerIncludeFileStackEntry.cpp"
#include "CScriptCompilerInternal.cpp"
#include "CScriptCompilerKeyWordEntry.cpp"
#include "CScriptCompilerStackEntry.cpp"
#include "CScriptCompilerStructureEntry.cpp"
#include "CScriptCompilerStructureFieldEntry.cpp"
#include "CScriptCompilerSymbolTableEntry.cpp"
#include "CScriptCompilerVarStackEntry.cpp"
#include "CScriptLog.cpp"
#include "CScriptParseTreeNode.cpp"
#include "CScriptParseTreeNodeBlock.cpp"
#include "CServerNetOptions.cpp"
#include "CServerOptionLookup.cpp"
#include "CSpell_Add.cpp"
#include "CSpell_Delete.cpp"
#include "CSteam.cpp"
#include "CSteamID.cpp"
#include "CSteamID__SteamID_t__SteamIDComponent_t.cpp"
#include "CSteamInternal.cpp"
#include "CSteamInternal__SubscribedItems.cpp"
#include "ct_data_s.cpp"
#include "Cte.cpp"
#include "CTlkTableToken.cpp"
#include "CTlkTableTokenCustom.cpp"
#include "curl_actual_call.cpp"
#include "Curl_addrinfo.cpp"
#include "Curl_async.cpp"
#include "curl_certinfo.cpp"
#include "Curl_chunker.cpp"
#include "Curl_dns_entry.cpp"
#include "Curl_easy.cpp"
#include "curl_fileinfo.cpp"
#include "curl_forms.cpp"
#include "Curl_handler.cpp"
#include "curl_hash.cpp"
#include "curl_hash_element.cpp"
#include "curl_hash_iterator.cpp"
#include "Curl_http2_dep.cpp"
#include "curl_httppost.cpp"
#include "curl_khkey.cpp"
#include "curl_llist.cpp"
#include "curl_llist_element.cpp"
#include "Curl_message.cpp"
#include "Curl_mime_contenttype__ContentType.cpp"
#include "curl_mime_s.cpp"
#include "curl_mimepart_s.cpp"
#include "Curl_multi.cpp"
#include "curl_pushheaders.cpp"
#include "Curl_send_buffer.cpp"
#include "Curl_sh_entry.cpp"
#include "Curl_share.cpp"
#include "curl_slist.cpp"
#include "curl_sockaddr.cpp"
#include "Curl_sockaddr_ex.cpp"
#include "Curl_sockaddr_storage.cpp"
#include "curl_ssl_backend.cpp"
#include "curl_ssl_session.cpp"
#include "curl_tlssessioninfo.cpp"
#include "Curl_tree.cpp"
#include "curl_version_info_data.cpp"
#include "curl_waitfd.cpp"
#include "CURLMsg.cpp"
#include "curltime.cpp"
#include "CURRENCY4.cpp"
#include "CVirtualMachineCmdImplementer.cpp"
#include "CVirtualMachineDebuggingContext.cpp"
#include "CVirtualMachineInternal.cpp"
#include "CWorldJournalEntry.cpp"
#include "DATA4FILESt.cpp"
#include "DATA4HEADER_FULL.cpp"
#include "DATA4LISTSt.cpp"
#include "DATA4St.cpp"
#include "DataBlock.cpp"
#include "DateTime.cpp"
#include "Db.cpp"
#include "DbFixer.cpp"
#include "Depth.cpp"
#include "DetailedTiming.cpp"
#include "digestdata.cpp"
#include "dirent.cpp"
#include "DistinctCtx.cpp"
#include "div_t.cpp"
#include "DOW.cpp"
#include "DTableDesc.cpp"
#include "dynamically_allocated_data.cpp"
#include "DynamicStatic.cpp"
#include "e4exprSt.cpp"
#include "E4FUNCTIONS.cpp"
#include "E4INFO_REPORT.cpp"
#include "E4INFOSt.cpp"
#include "E4PARSE.cpp"
#include "EncapsulatedHeader_st.cpp"
#include "EncapsulatedKeyListEntry_st.cpp"
#include "EncapsulatedResListEntry_st.cpp"
#include "EncryptedAppTicketResponse_t.cpp"
#include "ERROR4DATASt.cpp"
#include "ERROR4INFO_ARRAY.cpp"
#include "errorLogCallback__TemplatedlambdaOpenParenCloseParen.cpp"
#include "et_info.cpp"
#include "Exo2DAHeader_st.cpp"
#include "ExoLocString_st.cpp"
#include "ExoLTRHeader_st.cpp"
#include "ExoTGAHeader_st.cpp"
#include "Expansion4compressionArray.cpp"
#include "Expr.cpp"
#include "EXPR4CALCSt.cpp"
#include "ExprList.cpp"
#include "ExprList_item.cpp"
#include "F4FLAG.cpp"
#include "F4MEMOSt.cpp"
#include "fd_set.cpp"
#include "ff_condition_effect.cpp"
#include "ff_constant_effect.cpp"
#include "ff_effect.cpp"
#include "ff_envelope.cpp"
#include "ff_periodic_effect.cpp"
#include "ff_ramp_effect.cpp"
#include "ff_replay.cpp"
#include "ff_rumble_effect.cpp"
#include "ff_trigger.cpp"
#include "FIELD4IMAGE.cpp"
#include "FIELD4INFO.cpp"
#include "FIELD4St.cpp"
#include "FILE4LONG_EXTENDSt.cpp"
#include "FILE4SEQ_READ.cpp"
#include "FILE4SEQ_WRITE.cpp"
#include "FILE4St.cpp"
#include "FileChunk.cpp"
#include "fileinfo.cpp"
#include "FilePoint.cpp"
#include "FKey.cpp"
#include "flex_unit.cpp"
#include "flock.cpp"
#include "FormInfo.cpp"
#include "FrameBound.cpp"
#include "FriendGameInfo_t.cpp"
#include "FSE_CState_t.cpp"
#include "FSE_decode_t.cpp"
#include "FSE_DState_t.cpp"
#include "FSE_DTableHeader.cpp"
#include "FSE_symbolCompressionTransform.cpp"
#include "fseWkspMax_t.cpp"
#include "ftp_conn.cpp"
#include "func_t.cpp"
#include "FuncDef.cpp"
#include "FuncDefHash.cpp"
#include "FuncDeor.cpp"
#include "funcs.cpp"
#include "GameLobbyJoinRequested_t.cpp"
#include "GameRichPresenceJoinRequested_t.cpp"
#include "GL_FBOList.cpp"
#include "GL_RenderData.cpp"
#include "GL_ShaderContext.cpp"
#include "GL_ShaderData.cpp"
#include "GL_TextureData.cpp"
#include "GLES2_DriverContext.cpp"
#include "GLES2_FBOList.cpp"
#include "GLES2_ProgramCache.cpp"
#include "GLES2_ProgramCacheEntry.cpp"
#include "GLES2_Shader.cpp"
#include "GLES2_ShaderCache.cpp"
#include "GLES2_ShaderCacheEntry.cpp"
#include "GLES2_ShaderInstance.cpp"
#include "GLES2_TextureData.cpp"
#include "haptic_effect.cpp"
#include "haptic_hwdata.cpp"
#include "haptic_hweffect.cpp"
#include "Hash.cpp"
#include "HashElem.cpp"
#include "hashtable.cpp"
#include "hashtable_bucket.cpp"
#include "hashtable_list.cpp"
#include "hashtable_pair.cpp"
#include "Header.cpp"
#include "HiddenIndexInfo.cpp"
#include "HMAC_params.cpp"
#include "hostcache_prune_data.cpp"
#include "hostent.cpp"
#include "hostname.cpp"
#include "HTTP.cpp"
#include "http_conn.cpp"
#include "http_connect_state.cpp"
#include "HttpBufferReceiver.cpp"
#include "HttpConnection__HeaderTuple.cpp"
#include "HttpConnection__PrivateData.cpp"
#include "HttpConnection__QueuedURL.cpp"
#include "HUF_CElt_s.cpp"
#include "HUF_compress_tables_t.cpp"
#include "HUF_DEltX1.cpp"
#include "HUF_DEltX2.cpp"
#include "hwdata_ball.cpp"
#include "hwdata_hat.cpp"
#include "ICrashReporter__ChecksumFile__TemplatedlambdaOpenParenCloseParen.cpp"
#include "IdList.cpp"
#include "IdList_item.cpp"
#include "IdxCover.cpp"
#include "IdxExprTrans.cpp"
#include "ifmap.cpp"
#include "ifreq.cpp"
#include "IMA_ADPCM_decoder.cpp"
#include "IMA_ADPCM_decodestate.cpp"
#include "imap_conn.cpp"
#include "in_addr.cpp"
#include "in6_addr.cpp"
#include "inBuff_t.cpp"
#include "Incrblob.cpp"
#include "IncrMerger.cpp"
#include "Index.cpp"
#include "INDEX4FILESt.cpp"
#include "INDEX4St.cpp"
#include "inflate_state.cpp"
#include "InitData.cpp"
#include "InLoop.cpp"
#include "input_absinfo.cpp"
#include "input_event.cpp"
#include "input_id.cpp"
#include "IntegrityCk.cpp"
#include "isAuxiliaryVtabOperator__Op2.cpp"
#include "ISteamApps.cpp"
#include "ISteamClient.cpp"
#include "ISteamFriends.cpp"
#include "ISteamMatchmaking.cpp"
#include "ISteamNetworking.cpp"
#include "ISteamUGC.cpp"
#include "ISteamUser.cpp"
#include "ISteamUserStats.cpp"
#include "joystick_hwdata.cpp"
#include "json_array_t.cpp"
#include "json_error_t.cpp"
#include "json_integer_t.cpp"
#include "json_object_t.cpp"
#include "json_real_t.cpp"
#include "json_string_t.cpp"
#include "json_t.cpp"
#include "KeyFileHeader_st.cpp"
#include "KeyFileKeyEntry_st.cpp"
#include "KeyFileResFileName_st.cpp"
#include "KeyInfo.cpp"
#include "KeyRepeatCheckData.cpp"
#include "l4linkSt.cpp"
#include "L4LOGICAL.cpp"
#include "LastValueCtx.cpp"
#include "lconv.cpp"
#include "ldiv_t.cpp"
#include "ldmEntry_t.cpp"
#include "ldmParams_t.cpp"
#include "ldmState_t.cpp"
#include "lex_t.cpp"
#include "LIST4.cpp"
#include "ListTemplatedVector.cpp"
#include "lldiv_t.cpp"
#include "LobbyChatUpdate_t.cpp"
#include "LobbyCreated_t.cpp"
#include "LobbyDataUpdate_t.cpp"
#include "LobbyEnter_t.cpp"
#include "LobbyMatchList_t.cpp"
#include "Lock4.cpp"
#include "LOCK4GROUP.cpp"
#include "LOCK4ID.cpp"
#include "LOG4HEADER.cpp"
#include "LONG_DOUBLE_12.cpp"
#include "Lookaside.cpp"
#include "LookasideSlot.cpp"
#include "MaterialShaderParam.cpp"
#include "Matrix4x4.cpp"
#include "max_align_t.cpp"
#include "MD5_context.cpp"
#include "MD5_CTX.cpp"
#include "MD5_params.cpp"
#include "Mem0Global.cpp"
#include "MEM4st.cpp"
#include "MemJournal.cpp"
#include "MEMO4BLOCK.cpp"
#include "MEMO4FILE.cpp"
#include "MEMO4HEADER.cpp"
#include "MEMORY4GROUP.cpp"
#include "MemPage.cpp"
#include "MergeEngine.cpp"
#include "mime_encoder.cpp"
#include "mime_encoder_state.cpp"
#include "mime_state.cpp"
#include "Module.cpp"
#include "MonitorInfo.cpp"
#include "MONTH.cpp"
#include "monty.cpp"
#include "moodycamel__ConcurrentQueueDefaultTraits.cpp"
#include "moodycamel__ConsumerToken.cpp"
#include "moodycamel__details___hash_32_or_64Templatedfalse.cpp"
#include "moodycamel__details__ConcurrentQueueProducerTypelessBase.cpp"
#include "moodycamel__details__thread_id_converterTemplatedunsignedint.cpp"
#include "moodycamel__ProducerToken.cpp"
#include "MS_ADPCM_decoder.cpp"
#include "MS_ADPCM_decodestate.cpp"
#include "MS_RSAPrivateKey.cpp"
#include "MS_RSAPublicKey.cpp"
#include "MS_RSAVLong.cpp"
#include "MS_RSAVLong_value.cpp"
#include "my_tm.cpp"
#include "namebuff.cpp"
#include "NameContext.cpp"
#include "Names.cpp"
#include "nodeElt_s.cpp"
#include "nsprintf.cpp"
#include "NtileCtx.cpp"
#include "NWAreaExpansion_st.cpp"
#include "NWAreaHeader_st.cpp"
#include "NWERFHeader_st.cpp"
#include "NWModuleCutScene_st.cpp"
#include "NWModuleEntryInfo_st.cpp"
#include "NWModuleExpansion_st.cpp"
#include "NWModuleHeader_st.cpp"
#include "NWPlayerCharacterList_st.cpp"
#include "NWPlayerCharacterListClass_st.cpp"
#include "NWPlayerListItem_st.cpp"
#include "NWSync__CNWSync.cpp"
#include "NWSync__CNWSync__Config.cpp"
#include "NWSync__CNWSync__ManifestEntry.cpp"
#include "NWSync__CNWSync__ManifestMetaData.cpp"
#include "NWSync__CNWSync__MappingBatchInsertEntry.cpp"
#include "NWSync__CNWSync__ReconciliationStatus.cpp"
#include "NWSync__CNWSync__ResRefBatchInsertEntry.cpp"
#include "NWSync__CNWSyncInternal.cpp"
#include "NWSync__CNWSyncInternal__ApplyMigration__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__ApplyMigration__TemplatedlambdaOpenParenCloseParen__operatorOpenParenCloseParen__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__BatchSetMappingData__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__BatchSetMappingData__TemplatedlambdaOpenParenCloseParen__operatorOpenParenCloseParen__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__CreateManifest__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__GetCachedManifest__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__GetManifestContents__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__GetManifestMetaData__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__GetResrefData__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__HasManifest__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__Housekeeping__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__MarkManifestUsedBy__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__Migrate__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__Migrate__TemplatedlambdaOpenParenvoidPtrintcharPtrPtrcharPtrPtrCloseParen.cpp"
#include "NWSync__CNWSyncInternal__ReconfigureSqlite__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__RunMigration__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__SetCachedManifest__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__SetStorageRoot__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__UpdateManifestMetaData__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CNWSyncInternal__WithTransaction__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__CompressedBufferHandler.cpp"
#include "NWSync__CompressionProvider.cpp"
#include "NWSync__HashTreeStorageProvider.cpp"
#include "NWSync__NullCompressionProvider.cpp"
#include "NWSync__SQLiteStorageProvider.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__CompactPages__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__Delete__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__Fetch__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__GetPageInfo__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__PageInfo.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__ReindexEntries__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__Store__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__StorageShard__StoreSingleNotTransactional__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__Store__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__SQLiteStorageProvider__WithTransaction__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__StorageProvider.cpp"
#include "NWSync__StorageProvider__CompressIntoFile__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__StorageProvider__DecompressFromFile__TemplatedlambdaOpenParenCloseParen.cpp"
#include "NWSync__ZlibCompressionProvider.cpp"
#include "NWSync__ZstdCompressionProvider.cpp"
#include "ObjectVisualTransformData.cpp"
#include "OPT4.cpp"
#include "OPT4BLOCK.cpp"
#include "OPT4CMP.cpp"
#include "OPT4LIST.cpp"
#include "optState_t.cpp"
#include "P2PSessionRequest_t.cpp"
#include "Pager.cpp"
#include "PagerSavepoint.cpp"
#include "Parse.cpp"
#include "passwd.cpp"
#include "PCache.cpp"
#include "PCache1.cpp"
#include "PCacheGlobal.cpp"
#include "pfAECommands.cpp"
#include "pfAIPCommands.cpp"
#include "pfCVMCommands.cpp"
#include "pfRECommands.cpp"
#include "pfRIPCommands.cpp"
#include "PgFreeslot.cpp"
#include "PgHdr.cpp"
#include "PgHdr1.cpp"
#include "PGroup.cpp"
#include "pingpong.cpp"
#include "PmaReader.cpp"
#include "PmaWriter.cpp"
#include "pollfd.cpp"
#include "POOL_ctx_s.cpp"
#include "POOL_job_s.cpp"
#include "pop3_conn.cpp"
#include "PragmaName.cpp"
#include "PragmaVtab.cpp"
#include "PragmaVtabCursor.cpp"
#include "prime_factory.cpp"
#include "PrintfArguments.cpp"
#include "Progress.cpp"
#include "proxy_info.cpp"
#include "prunedead.cpp"
#include "pthread_mutex_t____pthread_mutex_s.cpp"
#include "PureInfo.cpp"
#include "R4BLOCK_DATA.cpp"
#include "R4REINDEX.cpp"
#include "range_t.cpp"
#include "rankPos.cpp"
#include "rawSeq.cpp"
#include "rawSeqStore_t.cpp"
#include "RELATE4St.cpp"
#include "RELATION4St.cpp"
#include "RenameCtx.cpp"
#include "RenameToken.cpp"
#include "repcodes_s.cpp"
#include "resdata.cpp"
#include "RESID.cpp"
#include "ReusableSpace.cpp"
#include "RGB2YUVFactors.cpp"
#include "RGB2YUVParam.cpp"
#include "RLEDestFormat.cpp"
#include "roundBuff_t.cpp"
#include "RowLoadInfo.cpp"
#include "RowSet.cpp"
#include "RowSetChunk.cpp"
#include "RowSetEntry.cpp"
#include "rtsp_conn.cpp"
#include "S4SCAN.cpp"
#include "s4singleDistantSt.cpp"
#include "s4singleSt.cpp"
#include "S4SPOOL.cpp"
#include "S4STACK.cpp"
#include "SASL.cpp"
#include "SASLproto.cpp"
#include "Savepoint.cpp"
#include "Schema.cpp"
#include "SCodeBaseData.cpp"
#include "sColMap.cpp"
#include "Screen.cpp"
#include "ScreenFormat.cpp"
#include "Select.cpp"
#include "SelectDest.cpp"
#include "seq_t.cpp"
#include "seqDef_s.cpp"
#include "seqState_t.cpp"
#include "seqStore_t.cpp"
#include "serialState_t.cpp"
#include "SETEntry.cpp"
#include "SETSection.cpp"
#include "sha256_state.cpp"
#include "sigaction.cpp"
#include "siginfo_t.cpp"
#include "SimplyCopyingHttpBufferReceiver.cpp"
#include "Single4.cpp"
#include "Single4distant.cpp"
#include "Single4lock.cpp"
#include "SingleRequest.cpp"
#include "site_blacklist_entry.cpp"
#include "smb_conn.cpp"
#include "SMstBuddyEntry.cpp"
#include "SMstDigiDistInfo.cpp"
#include "SMstKeyEntry.cpp"
#include "SMstNameEntry.cpp"
#include "smtp_conn.cpp"
#include "sockaddr.cpp"
#include "sockaddr_in.cpp"
#include "sockaddr_in6.cpp"
#include "sockaddr_storage.cpp"
#include "sockaddr_un.cpp"
#include "SORT4.cpp"
#include "SortCtx.cpp"
#include "sortedSymbol_t.cpp"
#include "SorterFile.cpp"
#include "SorterList.cpp"
#include "SorterRecord.cpp"
#include "SortSubtask.cpp"
#include "sqlite3.cpp"
#include "sqlite3_api_routines.cpp"
#include "sqlite3_backup.cpp"
#include "sqlite3_blob.cpp"
#include "sqlite3_context.cpp"
#include "sqlite3_file.cpp"
#include "sqlite3_index_constraint.cpp"
#include "sqlite3_index_constraint_usage.cpp"
#include "sqlite3_index_info.cpp"
#include "sqlite3_index_orderby.cpp"
#include "sqlite3_io_methods.cpp"
#include "sqlite3_mem_methods.cpp"
#include "sqlite3_module.cpp"
#include "sqlite3_mutex.cpp"
#include "sqlite3_mutex_methods.cpp"
#include "sqlite3_pcache.cpp"
#include "sqlite3_pcache_methods2.cpp"
#include "sqlite3_pcache_page.cpp"
#include "sqlite3_stmt.cpp"
#include "sqlite3_str.cpp"
#include "sqlite3_value.cpp"
#include "sqlite3_vfs.cpp"
#include "sqlite3_vtab.cpp"
#include "sqlite3_vtab_cursor.cpp"
#include "sqlite3AutoExtList.cpp"
#include "Sqlite3Config.cpp"
#include "sqlite3InitInfo.cpp"
#include "sqlite3ParseUri__OpenMode.cpp"
#include "sqlite3Pragma__EncName.cpp"
#include "sqlite3PrngType.cpp"
#include "sqlite3StatType.cpp"
#include "SQLiteThread.cpp"
#include "SrcCount.cpp"
#include "SrcList.cpp"
#include "SrcList_item.cpp"
#include "SRecord.cpp"
#include "ssh_conn.cpp"
#include "ssl_config_data.cpp"
#include "ssl_connect_data.cpp"
#include "ssl_general_config.cpp"
#include "ssl_primary_config.cpp"
#include "SSubNetProfile.cpp"
#include "stat.cpp"
#include "Stat4Accum.cpp"
#include "Stat4Sample.cpp"
#include "statfs.cpp"
#include "static_tree_desc_s.cpp"
#include "SteamParamStringArray_t.cpp"
#include "SteamUGCDetails_t.cpp"
#include "SteamUGCQueryCompleted_t.cpp"
#include "SteamUGCRequestUGCDetailsResult_t.cpp"
#include "STR_RES_HEADER.cpp"
#include "STR_RES_HEADER_OLD.cpp"
#include "strbuffer_t.cpp"
#include "stream_t.cpp"
#include "string_data_t.cpp"
#include "STRUCT_B4NODE.cpp"
#include "SubmitItemUpdateResult_t.cpp"
#include "SubProgram.cpp"
#include "SubstContext.cpp"
#include "SumCtx.cpp"
#include "SW_RenderData.cpp"
#include "sysinfo.cpp"
#include "T4HEADER.cpp"
#include "Table.cpp"
#include "TableLock.cpp"
#include "TabResult.cpp"
#include "TAG4FILESt.cpp"
#include "TAG4INFO.cpp"
#include "TAG4KEY_REMOVED.cpp"
#include "TAG4St.cpp"
#include "tagDBDATE.cpp"
#include "tagDBTIME.cpp"
#include "tagDBTIMESTAMP.cpp"
#include "Task__CExoBaseTask.cpp"
#include "Task__CExoTaskGroup.cpp"
#include "Task__CExoTaskManager.cpp"
#include "Task__CExoTaskManager_impl.cpp"
#include "Task__CExoTaskResultTemplatedbool.cpp"
#include "Task__CExoTaskTemplatedbool.cpp"
#include "Task__CExoTaskThread.cpp"
#include "Task__CExoTaskThread__BlockForWork__TemplatedlambdaOpenParenCloseParen.cpp"
#include "Task__CExoTaskThread__LinkGroup__TemplatedlambdaOpenParenTask__CExoTaskGroupPtrTask__CExoTaskGroupPtrCloseParen.cpp"
#include "Task__CExoTaskThread__ThreadFunc__TemplatedlambdaOpenParenconstTask__CExoTaskGroupPtrCloseParen.cpp"
#include "tColorRGBA.cpp"
#include "tColorY.cpp"
#include "tempbuf.cpp"
#include "TextLineData.cpp"
#include "tftp_state_data.cpp"
#include "thread_args.cpp"
#include "thread_data.cpp"
#include "thread_sync_data.cpp"
#include "time_node.cpp"
#include "timeb.cpp"
#include "timespec.cpp"
#include "timeval.cpp"
#include "timezone.cpp"
#include "Timing.cpp"
#include "TLK_FILE_HEADER.cpp"
#include "tm.cpp"
#include "Token.cpp"
#include "TOTAL4st.cpp"
#include "TRAN4FILESt.cpp"
#include "TRAN4St.cpp"
#include "Translate4arrayChar.cpp"
#include "Translate4arrayUnicode.cpp"
#include "tree_desc_s.cpp"
#include "TrigEvent.cpp"
#include "Trigger.cpp"
#include "TriggerPrg.cpp"
#include "TriggerStep.cpp"
#include "tzinfo.cpp"
#include "unalign16.cpp"
#include "unalign32.cpp"
#include "unalign64.cpp"
#include "unalignArch.cpp"
#include "unix_syscall.cpp"
#include "unixFile.cpp"
#include "unixFileId.cpp"
#include "unixInodeInfo.cpp"
#include "unixShm.cpp"
#include "unixShmNode.cpp"
#include "UnixUnusedFd.cpp"
#include "UnpackedRecord.cpp"
#include "Upsert.cpp"
#include "UrlState.cpp"
#include "UserDefined.cpp"
#include "UserStatsReceived_t.cpp"
#include "va_stack_t.cpp"
#include "ValueNewStat4Ctx.cpp"
#include "Vdbe.cpp"
#include "VdbeCursor.cpp"
#include "VdbeFrame.cpp"
#include "VdbeOp.cpp"
#include "VdbeOpList.cpp"
#include "VdbeSorter.cpp"
#include "VideoBootStrap.cpp"
#include "Visual.cpp"
#include "VkAllocationCallbacks.cpp"
#include "VkExtensionProperties.cpp"
#include "VkInstance_T.cpp"
#include "VkXcbSurfaceCreateInfoKHR.cpp"
#include "VkXlibSurfaceCreateInfoKHR.cpp"
#include "VtabCtx.cpp"
#include "VTable.cpp"
#include "Wal.cpp"
#include "WalCkptInfo.cpp"
#include "WalHashLoc.cpp"
#include "WalIndexHdr.cpp"
#include "WalIterator.cpp"
#include "Walker.cpp"
#include "walMergesort__Sublist.cpp"
#include "WalSegment.cpp"
#include "WalWriter.cpp"
#include "WaveExtensibleFMT.cpp"
#include "WaveFMT.cpp"
#include "WhereAndInfo.cpp"
#include "WhereClause.cpp"
#include "WhereConst.cpp"
#include "WhereInfo.cpp"
#include "WhereLevel.cpp"
#include "WhereLoop.cpp"
#include "WhereLoopBuilder.cpp"
#include "WhereMaskSet.cpp"
#include "WhereOrCost.cpp"
#include "WhereOrInfo.cpp"
#include "WhereOrSet.cpp"
#include "WherePath.cpp"
#include "WhereScan.cpp"
#include "WhereTerm.cpp"
#include "WildcardData.cpp"
#include "Window_0.cpp"
#include "WindowRewrite.cpp"
#include "With.cpp"
#include "x11dynlib.cpp"
#include "xAllocColorCellsReply.cpp"
#include "xAllocColorPlanesReply.cpp"
#include "xAllocColorReply.cpp"
#include "xAllocNamedColorReply.cpp"
#include "XAnyEvent.cpp"
#include "XButtonEvent.cpp"
#include "xcb_connection_t.cpp"
#include "XCharStruct.cpp"
#include "XCirculateEvent.cpp"
#include "XCirculateRequestEvent.cpp"
#include "XClassHint.cpp"
#include "XClientMessageEvent.cpp"
#include "XColor.cpp"
#include "XColormapEvent.cpp"
#include "XConfigureEvent.cpp"
#include "XConfigureRequestEvent.cpp"
#include "XCreateWindowEvent.cpp"
#include "XCrossingEvent.cpp"
#include "XDestroyWindowEvent.cpp"
#include "xError.cpp"
#include "XErrorEvent.cpp"
#include "XExposeEvent.cpp"
#include "XExtCodes.cpp"
#include "XF86VidModeModeInfo.cpp"
#include "XF86VidModeModeLine.cpp"
#include "XFocusChangeEvent.cpp"
#include "XFontProp.cpp"
#include "XFontStruct.cpp"
#include "XGCValues.cpp"
#include "XGenericEvent.cpp"
#include "XGenericEventCookie.cpp"
#include "xGenericReply.cpp"
#include "xGetAtomNameReply.cpp"
#include "xGetFontPathReply.cpp"
#include "xGetGeometryReply.cpp"
#include "xGetImageReply.cpp"
#include "xGetInputFocusReply.cpp"
#include "xGetKeyboardMappingReply.cpp"
#include "xGetModifierMappingReply.cpp"
#include "xGetMotionEventsReply.cpp"
#include "xGetPointerControlReply.cpp"
#include "xGetPointerMappingReply.cpp"
#include "xGetPropertyReply.cpp"
#include "xGetScreenSaverReply.cpp"
#include "xGetSelectionOwnerReply.cpp"
#include "xGrabPointerReply.cpp"
#include "XGraphicsExposeEvent.cpp"
#include "XGravityEvent.cpp"
#include "XIAnyClassInfo.cpp"
#include "XIDeviceInfo.cpp"
#include "XIEventMask.cpp"
#include "XineramaScreenInfo.cpp"
#include "xInternAtomReply.cpp"
#include "XIRawEvent.cpp"
#include "XIValuatorState.cpp"
#include "xListExtensionsReply.cpp"
#include "xListFontsReply.cpp"
#include "xListHostsReply.cpp"
#include "xListInstalledColormapsReply.cpp"
#include "xListPropertiesReply.cpp"
#include "xLookupColorReply.cpp"
#include "XMapEvent.cpp"
#include "XMappingEvent.cpp"
#include "XMapRequestEvent.cpp"
#include "XModifierKeymap.cpp"
#include "XMotionEvent.cpp"
#include "XNoExposeEvent.cpp"
#include "XPixmapFormatValues.cpp"
#include "XPropertyEvent.cpp"
#include "xQueryBestSizeReply.cpp"
#include "xQueryColorsReply.cpp"
#include "xQueryExtensionReply.cpp"
#include "xQueryPointerReply.cpp"
#include "xQueryTextExtentsReply.cpp"
#include "xQueryTreeReply.cpp"
#include "XRectangle.cpp"
#include "XReparentEvent.cpp"
#include "XResizeRequestEvent.cpp"
#include "XRRPropertyInfo.cpp"
#include "XRRScreenSize.cpp"
#include "XSelectionClearEvent.cpp"
#include "XSelectionEvent.cpp"
#include "XSelectionRequestEvent.cpp"
#include "xSetMappingReply.cpp"
#include "XSetWindowAttributes.cpp"
#include "XShmSegmentInfo.cpp"
#include "XSizeHints.cpp"
#include "XTextProperty.cpp"
#include "xTranslateCoordsReply.cpp"
#include "XUnmapEvent.cpp"
#include "XVisibilityEvent.cpp"
#include "XVisualInfo.cpp"
#include "XWindowAttributes.cpp"
#include "XWMHints.cpp"
#include "XXH32_canonical_t.cpp"
#include "XXH32_state_s.cpp"
#include "XXH64_canonical_t.cpp"
#include "XXH64_state_s.cpp"
#include "Y4CHUNK.cpp"
#include "YUV2RGBParam.cpp"
#include "yyParser.cpp"
#include "yyStackEntry.cpp"
#include "z_gz_header_s.cpp"
#include "z_internal_state.cpp"
#include "z_stream.cpp"
#include "z_stream_s.cpp"
#include "zlib_params.cpp"
#include "ZlibHeader.cpp"
#include "ZSTD_blockState_t.cpp"
#include "ZSTD_CCtx_params_s.cpp"
#include "ZSTD_CCtx_s.cpp"
#include "ZSTD_CDict_s.cpp"
#include "ZSTD_compressedBlockState_t.cpp"
#include "ZSTD_compressionParameters.cpp"
#include "ZSTD_cpuid_t.cpp"
#include "ZSTD_customMem.cpp"
#include "ZSTD_DCtx_s.cpp"
#include "ZSTD_DDict_s.cpp"
#include "ZSTD_entropyCTables_t.cpp"
#include "ZSTD_entropyDTables_t.cpp"
#include "ZSTD_frameHeader.cpp"
#include "ZSTD_frameParameters.cpp"
#include "ZSTD_frameProgression.cpp"
#include "ZSTD_fseCTables_t.cpp"
#include "ZSTD_fseState.cpp"
#include "ZSTD_hufCTables_t.cpp"
#include "ZSTD_inBuffer_s.cpp"
#include "ZSTD_match_t.cpp"
#include "ZSTD_matchState_t.cpp"
#include "ZSTD_optimal_t.cpp"
#include "ZSTD_outBuffer_s.cpp"
#include "ZSTD_parameters.cpp"
#include "ZSTD_prefixDict_s.cpp"
#include "ZSTD_seqSymbol.cpp"
#include "ZSTD_seqSymbol_header.cpp"
#include "ZSTD_window_t.cpp"
#include "ZstdHeader.cpp"
#include "ZSTDMT_bufferPool_s.cpp"
#include "ZSTDMT_CCtx_s.cpp"
#include "ZSTDMT_CCtxPool.cpp"
#include "ZSTDMT_jobDescription.cpp"
#include "pthread_cond_t.cpp"
#include "pthread_mutex_t.cpp"

namespace
{
    template <int size, int desiredSize>
    struct CheckSize { static_assert(size == desiredSize, "Struct size mismatch!"); };

    CheckSize<sizeof(NWNXLib::API::C2DA), 76> __attribute__((unused)) SIZE_CHECK_C2DA;
    CheckSize<sizeof(NWNXLib::API::CAppManager), 60> __attribute__((unused)) SIZE_CHECK_CAPPMANAGER;
    CheckSize<sizeof(NWNXLib::API::CCodeBase), 4> __attribute__((unused)) SIZE_CHECK_CCODEBASE;
    CheckSize<sizeof(NWNXLib::API::CCodeBaseInternal), 16> __attribute__((unused)) SIZE_CHECK_CCODEBASEINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CCombatInformation), 84> __attribute__((unused)) SIZE_CHECK_CCOMBATINFORMATION;
    CheckSize<sizeof(NWNXLib::API::CCombatInformationNode), 6> __attribute__((unused)) SIZE_CHECK_CCOMBATINFORMATIONNODE;
    CheckSize<sizeof(NWNXLib::API::CERFFile), 196> __attribute__((unused)) SIZE_CHECK_CERFFILE;
    CheckSize<sizeof(NWNXLib::API::CERFKey), 24> __attribute__((unused)) SIZE_CHECK_CERFKEY;
    CheckSize<sizeof(NWNXLib::API::CERFRes), 12> __attribute__((unused)) SIZE_CHECK_CERFRES;
    CheckSize<sizeof(NWNXLib::API::CERFString), 12> __attribute__((unused)) SIZE_CHECK_CERFSTRING;
    CheckSize<sizeof(NWNXLib::API::CExoAliasList), 4> __attribute__((unused)) SIZE_CHECK_CEXOALIASLIST;
    CheckSize<sizeof(NWNXLib::API::CExoAliasListInternal), 12> __attribute__((unused)) SIZE_CHECK_CEXOALIASLISTINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoBase), 36> __attribute__((unused)) SIZE_CHECK_CEXOBASE;
    CheckSize<sizeof(NWNXLib::API::CExoBaseInternal), 12> __attribute__((unused)) SIZE_CHECK_CEXOBASEINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoCriticalSection), 4> __attribute__((unused)) SIZE_CHECK_CEXOCRITICALSECTION;
    CheckSize<sizeof(NWNXLib::API::CExoCriticalSectionInternal), 24> __attribute__((unused)) SIZE_CHECK_CEXOCRITICALSECTIONINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoDebug), 12> __attribute__((unused)) SIZE_CHECK_CEXODEBUG;
    CheckSize<sizeof(NWNXLib::API::CExoDebugInternal), 44> __attribute__((unused)) SIZE_CHECK_CEXODEBUGINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoEncapsulatedFile), 68> __attribute__((unused)) SIZE_CHECK_CEXOENCAPSULATEDFILE;
    CheckSize<sizeof(NWNXLib::API::CExoEncrypt), 168> __attribute__((unused)) SIZE_CHECK_CEXOENCRYPT;
    CheckSize<sizeof(NWNXLib::API::CExoFile), 8> __attribute__((unused)) SIZE_CHECK_CEXOFILE;
    CheckSize<sizeof(NWNXLib::API::CExoFileInternal), 36> __attribute__((unused)) SIZE_CHECK_CEXOFILEINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoFileThread), 112> __attribute__((unused)) SIZE_CHECK_CEXOFILETHREAD;
    CheckSize<sizeof(NWNXLib::API::CExoIni), 4> __attribute__((unused)) SIZE_CHECK_CEXOINI;
    CheckSize<sizeof(NWNXLib::API::CExoIniInternal), 4> __attribute__((unused)) SIZE_CHECK_CEXOINIINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoKeyTable), 56> __attribute__((unused)) SIZE_CHECK_CEXOKEYTABLE;
    CheckSize<sizeof(NWNXLib::API::CExoLinkedListInternal), 12> __attribute__((unused)) SIZE_CHECK_CEXOLINKEDLISTINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoLocString), 8> __attribute__((unused)) SIZE_CHECK_CEXOLOCSTRING;
    CheckSize<sizeof(NWNXLib::API::CExoLocStringInternal), 8> __attribute__((unused)) SIZE_CHECK_CEXOLOCSTRINGINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoMemman), 92802080> __attribute__((unused)) SIZE_CHECK_CEXOMEMMAN;
    CheckSize<sizeof(NWNXLib::API::CExoPackedFile), 48> __attribute__((unused)) SIZE_CHECK_CEXOPACKEDFILE;
    CheckSize<sizeof(NWNXLib::API::CExoRand), 4> __attribute__((unused)) SIZE_CHECK_CEXORAND;
    CheckSize<sizeof(NWNXLib::API::CExoRandInternal), 144> __attribute__((unused)) SIZE_CHECK_CEXORANDINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExoResFile), 56> __attribute__((unused)) SIZE_CHECK_CEXORESFILE;
    CheckSize<sizeof(NWNXLib::API::CExoResMan), 80> __attribute__((unused)) SIZE_CHECK_CEXORESMAN;
    CheckSize<sizeof(NWNXLib::API::CExoResourceImageFile), 52> __attribute__((unused)) SIZE_CHECK_CEXORESOURCEIMAGEFILE;
    CheckSize<sizeof(NWNXLib::API::CExoString), 8> __attribute__((unused)) SIZE_CHECK_CEXOSTRING;
    CheckSize<sizeof(NWNXLib::API::CExoStringList), 20> __attribute__((unused)) SIZE_CHECK_CEXOSTRINGLIST;
    CheckSize<sizeof(NWNXLib::API::CExoTimers), 4> __attribute__((unused)) SIZE_CHECK_CEXOTIMERS;
    CheckSize<sizeof(NWNXLib::API::CExoTimersInternal), 32> __attribute__((unused)) SIZE_CHECK_CEXOTIMERSINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CExtendedServerInfo), 80> __attribute__((unused)) SIZE_CHECK_CEXTENDEDSERVERINFO;
    CheckSize<sizeof(NWNXLib::API::CFactionManager), 32> __attribute__((unused)) SIZE_CHECK_CFACTIONMANAGER;
    CheckSize<sizeof(NWNXLib::API::CFriendInfo), 24> __attribute__((unused)) SIZE_CHECK_CFRIENDINFO;
    CheckSize<sizeof(NWNXLib::API::CFriendPresenceInfo), 104> __attribute__((unused)) SIZE_CHECK_CFRIENDPRESENCEINFO;
    CheckSize<sizeof(NWNXLib::API::CGameEffect), 160> __attribute__((unused)) SIZE_CHECK_CGAMEEFFECT;
    CheckSize<sizeof(NWNXLib::API::CGameObject), 16> __attribute__((unused)) SIZE_CHECK_CGAMEOBJECT;
    CheckSize<sizeof(NWNXLib::API::CGameObjectArray), 36> __attribute__((unused)) SIZE_CHECK_CGAMEOBJECTARRAY;
    CheckSize<sizeof(NWNXLib::API::CGOG), 4> __attribute__((unused)) SIZE_CHECK_CGOG;
    CheckSize<sizeof(NWNXLib::API::CGOGInternal), 16> __attribute__((unused)) SIZE_CHECK_CGOGINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CItemRepository), 20> __attribute__((unused)) SIZE_CHECK_CITEMREPOSITORY;
    CheckSize<sizeof(NWNXLib::API::CLastUpdateObject), 520> __attribute__((unused)) SIZE_CHECK_CLASTUPDATEOBJECT;
    CheckSize<sizeof(NWNXLib::API::CLoopingVisualEffect), 12> __attribute__((unused)) SIZE_CHECK_CLOOPINGVISUALEFFECT;
    CheckSize<sizeof(NWNXLib::API::CMemRecord), 224> __attribute__((unused)) SIZE_CHECK_CMEMRECORD;
    CheckSize<sizeof(NWNXLib::API::CNetLayer), 4> __attribute__((unused)) SIZE_CHECK_CNETLAYER;
    CheckSize<sizeof(NWNXLib::API::CNetLayerInternal), 889744> __attribute__((unused)) SIZE_CHECK_CNETLAYERINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CNetLayerPlayerInfo), 120> __attribute__((unused)) SIZE_CHECK_CNETLAYERPLAYERINFO;
    CheckSize<sizeof(NWNXLib::API::CNetLayerSessionInfo), 116> __attribute__((unused)) SIZE_CHECK_CNETLAYERSESSIONINFO;
    CheckSize<sizeof(NWNXLib::API::CNetLayerWindow), 2332> __attribute__((unused)) SIZE_CHECK_CNETLAYERWINDOW;
    CheckSize<sizeof(NWNXLib::API::CNWArea), 168> __attribute__((unused)) SIZE_CHECK_CNWAREA;
    CheckSize<sizeof(NWNXLib::API::CNWBaseItem), 196> __attribute__((unused)) SIZE_CHECK_CNWBASEITEM;
    CheckSize<sizeof(NWNXLib::API::CNWBaseItemArray), 8> __attribute__((unused)) SIZE_CHECK_CNWBASEITEMARRAY;
    CheckSize<sizeof(NWNXLib::API::CNWCCMessageData), 52> __attribute__((unused)) SIZE_CHECK_CNWCCMESSAGEDATA;
    CheckSize<sizeof(NWNXLib::API::CNWClass), 636> __attribute__((unused)) SIZE_CHECK_CNWCLASS;
    CheckSize<sizeof(NWNXLib::API::CNWCreatureStatsUpdate), 100> __attribute__((unused)) SIZE_CHECK_CNWCREATURESTATSUPDATE;
    CheckSize<sizeof(NWNXLib::API::CNWDomain), 92> __attribute__((unused)) SIZE_CHECK_CNWDOMAIN;
    CheckSize<sizeof(NWNXLib::API::CNWDoorSurfaceMesh), 176> __attribute__((unused)) SIZE_CHECK_CNWDOORSURFACEMESH;
    CheckSize<sizeof(NWNXLib::API::CNWFeat), 128> __attribute__((unused)) SIZE_CHECK_CNWFEAT;
    CheckSize<sizeof(NWNXLib::API::CNWItem), 40> __attribute__((unused)) SIZE_CHECK_CNWITEM;
    CheckSize<sizeof(NWNXLib::API::CNWLevelStats), 268> __attribute__((unused)) SIZE_CHECK_CNWLEVELSTATS;
    CheckSize<sizeof(NWNXLib::API::CNWMessage), 80> __attribute__((unused)) SIZE_CHECK_CNWMESSAGE;
    CheckSize<sizeof(NWNXLib::API::CNWNameGen), 52> __attribute__((unused)) SIZE_CHECK_CNWNAMEGEN;
    CheckSize<sizeof(NWNXLib::API::CNWPlaceableSurfaceMesh), 88> __attribute__((unused)) SIZE_CHECK_CNWPLACEABLESURFACEMESH;
    CheckSize<sizeof(NWNXLib::API::CNWPlaceMeshManager), 8> __attribute__((unused)) SIZE_CHECK_CNWPLACEMESHMANAGER;
    CheckSize<sizeof(NWNXLib::API::CNWRace), 60> __attribute__((unused)) SIZE_CHECK_CNWRACE;
    CheckSize<sizeof(NWNXLib::API::CNWRules), 284> __attribute__((unused)) SIZE_CHECK_CNWRULES;
    CheckSize<sizeof(NWNXLib::API::CNWSAmbientSound), 48> __attribute__((unused)) SIZE_CHECK_CNWSAMBIENTSOUND;
    CheckSize<sizeof(NWNXLib::API::CNWSArea), 568> __attribute__((unused)) SIZE_CHECK_CNWSAREA;
    CheckSize<sizeof(NWNXLib::API::CNWSAreaOfEffectObject), 636> __attribute__((unused)) SIZE_CHECK_CNWSAREAOFEFFECTOBJECT;
    CheckSize<sizeof(NWNXLib::API::CNWSBarter), 40> __attribute__((unused)) SIZE_CHECK_CNWSBARTER;
    CheckSize<sizeof(NWNXLib::API::CNWSClient), 12> __attribute__((unused)) SIZE_CHECK_CNWSCLIENT;
    CheckSize<sizeof(NWNXLib::API::CNWSCombatAttackData), 168> __attribute__((unused)) SIZE_CHECK_CNWSCOMBATATTACKDATA;
    CheckSize<sizeof(NWNXLib::API::CNWSCombatRound), 8544> __attribute__((unused)) SIZE_CHECK_CNWSCOMBATROUND;
    CheckSize<sizeof(NWNXLib::API::CNWSCombatRoundAction), 40> __attribute__((unused)) SIZE_CHECK_CNWSCOMBATROUNDACTION;
    CheckSize<sizeof(NWNXLib::API::CNWSCreature), 2168> __attribute__((unused)) SIZE_CHECK_CNWSCREATURE;
    CheckSize<sizeof(NWNXLib::API::CNWSCreatureStats), 1384> __attribute__((unused)) SIZE_CHECK_CNWSCREATURESTATS;
    CheckSize<sizeof(NWNXLib::API::CNWSCreatureStats_ClassInfo), 312> __attribute__((unused)) SIZE_CHECK_CNWSCREATURESTATS_CLASSINFO;
    CheckSize<sizeof(NWNXLib::API::CNWSDialog), 152> __attribute__((unused)) SIZE_CHECK_CNWSDIALOG;
    CheckSize<sizeof(NWNXLib::API::CNWSDoor), 904> __attribute__((unused)) SIZE_CHECK_CNWSDOOR;
    CheckSize<sizeof(NWNXLib::API::CNWSDungeonMaster), 176> __attribute__((unused)) SIZE_CHECK_CNWSDUNGEONMASTER;
    CheckSize<sizeof(NWNXLib::API::CNWSEffectListHandler), 12> __attribute__((unused)) SIZE_CHECK_CNWSEFFECTLISTHANDLER;
    CheckSize<sizeof(NWNXLib::API::CNWSEncounter), 764> __attribute__((unused)) SIZE_CHECK_CNWSENCOUNTER;
    CheckSize<sizeof(NWNXLib::API::CNWSExpression), 32> __attribute__((unused)) SIZE_CHECK_CNWSEXPRESSION;
    CheckSize<sizeof(NWNXLib::API::CNWSExpressionList), 12> __attribute__((unused)) SIZE_CHECK_CNWSEXPRESSIONLIST;
    CheckSize<sizeof(NWNXLib::API::CNWSExpressionNode), 28> __attribute__((unused)) SIZE_CHECK_CNWSEXPRESSIONNODE;
    CheckSize<sizeof(NWNXLib::API::CNWSFaction), 36> __attribute__((unused)) SIZE_CHECK_CNWSFACTION;
    CheckSize<sizeof(NWNXLib::API::CNWSForcedAction), 28> __attribute__((unused)) SIZE_CHECK_CNWSFORCEDACTION;
    CheckSize<sizeof(NWNXLib::API::CNWSInventory), 76> __attribute__((unused)) SIZE_CHECK_CNWSINVENTORY;
    CheckSize<sizeof(NWNXLib::API::CNWSItem), 792> __attribute__((unused)) SIZE_CHECK_CNWSITEM;
    CheckSize<sizeof(NWNXLib::API::CNWSItemPropertyHandler), 12> __attribute__((unused)) SIZE_CHECK_CNWSITEMPROPERTYHANDLER;
    CheckSize<sizeof(NWNXLib::API::CNWSJournal), 16> __attribute__((unused)) SIZE_CHECK_CNWSJOURNAL;
    CheckSize<sizeof(NWNXLib::API::CNWSkill), 44> __attribute__((unused)) SIZE_CHECK_CNWSKILL;
    CheckSize<sizeof(NWNXLib::API::CNWSMessage), 80> __attribute__((unused)) SIZE_CHECK_CNWSMESSAGE;
    CheckSize<sizeof(NWNXLib::API::CNWSModule), 656> __attribute__((unused)) SIZE_CHECK_CNWSMODULE;
    CheckSize<sizeof(NWNXLib::API::CNWSObject), 532> __attribute__((unused)) SIZE_CHECK_CNWSOBJECT;
    CheckSize<sizeof(NWNXLib::API::CNWSObjectActionNode), 108> __attribute__((unused)) SIZE_CHECK_CNWSOBJECTACTIONNODE;
    CheckSize<sizeof(NWNXLib::API::CNWSpell), 560> __attribute__((unused)) SIZE_CHECK_CNWSPELL;
    CheckSize<sizeof(NWNXLib::API::CNWSpellArray), 8> __attribute__((unused)) SIZE_CHECK_CNWSPELLARRAY;
    CheckSize<sizeof(NWNXLib::API::CNWSPlaceable), 1028> __attribute__((unused)) SIZE_CHECK_CNWSPLACEABLE;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayer), 168> __attribute__((unused)) SIZE_CHECK_CNWSPLAYER;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerCharSheetGUI), 16> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERCHARSHEETGUI;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerContainerGUI), 12> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERCONTAINERGUI;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerInventoryGUI), 20> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERINVENTORYGUI;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerLastUpdateObject), 1288> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERLASTUPDATEOBJECT;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerLUOInventory), 172> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERLUOINVENTORY;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerStoreGUI), 20> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERSTOREGUI;
    CheckSize<sizeof(NWNXLib::API::CNWSPlayerTURD), 588> __attribute__((unused)) SIZE_CHECK_CNWSPLAYERTURD;
    CheckSize<sizeof(NWNXLib::API::CNWSRules), 284> __attribute__((unused)) SIZE_CHECK_CNWSRULES;
    CheckSize<sizeof(NWNXLib::API::CNWSScriptVarTable), 16> __attribute__((unused)) SIZE_CHECK_CNWSSCRIPTVARTABLE;
    CheckSize<sizeof(NWNXLib::API::CNWSSoundObject), 616> __attribute__((unused)) SIZE_CHECK_CNWSSOUNDOBJECT;
    CheckSize<sizeof(NWNXLib::API::CNWSSpellScriptData), 48> __attribute__((unused)) SIZE_CHECK_CNWSSPELLSCRIPTDATA;
    CheckSize<sizeof(NWNXLib::API::CNWSStats_Spell), 16> __attribute__((unused)) SIZE_CHECK_CNWSSTATS_SPELL;
    CheckSize<sizeof(NWNXLib::API::CNWSStats_SpellLikeAbility), 12> __attribute__((unused)) SIZE_CHECK_CNWSSTATS_SPELLLIKEABILITY;
    CheckSize<sizeof(NWNXLib::API::CNWSStore), 652> __attribute__((unused)) SIZE_CHECK_CNWSSTORE;
    CheckSize<sizeof(NWNXLib::API::CNWSSysAdmin), 12> __attribute__((unused)) SIZE_CHECK_CNWSSYSADMIN;
    CheckSize<sizeof(NWNXLib::API::CNWSTile), 88> __attribute__((unused)) SIZE_CHECK_CNWSTILE;
    CheckSize<sizeof(NWNXLib::API::CNWSTransition), 12> __attribute__((unused)) SIZE_CHECK_CNWSTRANSITION;
    CheckSize<sizeof(NWNXLib::API::CNWSTrigger), 756> __attribute__((unused)) SIZE_CHECK_CNWSTRIGGER;
    CheckSize<sizeof(NWNXLib::API::CNWSWaypoint), 556> __attribute__((unused)) SIZE_CHECK_CNWSWAYPOINT;
    CheckSize<sizeof(NWNXLib::API::CNWTile), 44> __attribute__((unused)) SIZE_CHECK_CNWTILE;
    CheckSize<sizeof(NWNXLib::API::CNWTileData), 144> __attribute__((unused)) SIZE_CHECK_CNWTILEDATA;
    CheckSize<sizeof(NWNXLib::API::CNWTileSet), 172> __attribute__((unused)) SIZE_CHECK_CNWTILESET;
    CheckSize<sizeof(NWNXLib::API::CNWTileSetManager), 1600> __attribute__((unused)) SIZE_CHECK_CNWTILESETMANAGER;
    CheckSize<sizeof(NWNXLib::API::CNWTileSurfaceMesh), 400> __attribute__((unused)) SIZE_CHECK_CNWTILESURFACEMESH;
    CheckSize<sizeof(NWNXLib::API::CNWTileSurfaceMeshAABBNode), 44> __attribute__((unused)) SIZE_CHECK_CNWTILESURFACEMESHAABBNODE;
    CheckSize<sizeof(NWNXLib::API::CNWTileSurfaceMeshHashTableEntry), 16> __attribute__((unused)) SIZE_CHECK_CNWTILESURFACEMESHHASHTABLEENTRY;
    CheckSize<sizeof(NWNXLib::API::CNWVirtualMachineCommands), 16> __attribute__((unused)) SIZE_CHECK_CNWVIRTUALMACHINECOMMANDS;
    CheckSize<sizeof(NWNXLib::API::CObjectLookupTable), 16> __attribute__((unused)) SIZE_CHECK_COBJECTLOOKUPTABLE;
    CheckSize<sizeof(NWNXLib::API::CObjectTableManager), 1024> __attribute__((unused)) SIZE_CHECK_COBJECTTABLEMANAGER;
    CheckSize<sizeof(NWNXLib::API::CPathfindInfoIntraTileSuccessors), 24> __attribute__((unused)) SIZE_CHECK_CPATHFINDINFOINTRATILESUCCESSORS;
    CheckSize<sizeof(NWNXLib::API::CPathfindInformation), 404> __attribute__((unused)) SIZE_CHECK_CPATHFINDINFORMATION;
    CheckSize<sizeof(NWNXLib::API::CrashReporter_Linux), 12> __attribute__((unused)) SIZE_CHECK_CRASHREPORTER_LINUX;
    CheckSize<sizeof(NWNXLib::API::CRes), 56> __attribute__((unused)) SIZE_CHECK_CRES;
    CheckSize<sizeof(NWNXLib::API::CRes2DA), 72> __attribute__((unused)) SIZE_CHECK_CRES2DA;
    CheckSize<sizeof(NWNXLib::API::CResARE), 196> __attribute__((unused)) SIZE_CHECK_CRESARE;
    CheckSize<sizeof(NWNXLib::API::CResDWK), 68> __attribute__((unused)) SIZE_CHECK_CRESDWK;
    CheckSize<sizeof(NWNXLib::API::CResGFF), 196> __attribute__((unused)) SIZE_CHECK_CRESGFF;
    CheckSize<sizeof(NWNXLib::API::CResGFFFieldIDHash), 1> __attribute__((unused)) SIZE_CHECK_CRESGFFFIELDIDHASH;
    CheckSize<sizeof(NWNXLib::API::CResIFO), 196> __attribute__((unused)) SIZE_CHECK_CRESIFO;
    CheckSize<sizeof(NWNXLib::API::CResLTR), 108> __attribute__((unused)) SIZE_CHECK_CRESLTR;
    CheckSize<sizeof(NWNXLib::API::CResNCS), 68> __attribute__((unused)) SIZE_CHECK_CRESNCS;
    CheckSize<sizeof(NWNXLib::API::CResNDB), 68> __attribute__((unused)) SIZE_CHECK_CRESNDB;
    CheckSize<sizeof(NWNXLib::API::CResNSS), 68> __attribute__((unused)) SIZE_CHECK_CRESNSS;
    CheckSize<sizeof(NWNXLib::API::CResPWK), 68> __attribute__((unused)) SIZE_CHECK_CRESPWK;
    CheckSize<sizeof(NWNXLib::API::CResRef), 32> __attribute__((unused)) SIZE_CHECK_CRESREF;
    CheckSize<sizeof(NWNXLib::API::CResSET), 76> __attribute__((unused)) SIZE_CHECK_CRESSET;
    CheckSize<sizeof(NWNXLib::API::CResTGA), 92> __attribute__((unused)) SIZE_CHECK_CRESTGA;
    CheckSize<sizeof(NWNXLib::API::CResTLK), 56> __attribute__((unused)) SIZE_CHECK_CRESTLK;
    CheckSize<sizeof(NWNXLib::API::CResWOK), 68> __attribute__((unused)) SIZE_CHECK_CRESWOK;
    CheckSize<sizeof(NWNXLib::API::CScriptCompiler), 13788> __attribute__((unused)) SIZE_CHECK_CSCRIPTCOMPILER;
    CheckSize<sizeof(NWNXLib::API::CScriptCompilerIdListEntry), 128> __attribute__((unused)) SIZE_CHECK_CSCRIPTCOMPILERIDLISTENTRY;
    CheckSize<sizeof(NWNXLib::API::CScriptEvent), 52> __attribute__((unused)) SIZE_CHECK_CSCRIPTEVENT;
    CheckSize<sizeof(NWNXLib::API::CScriptLocation), 28> __attribute__((unused)) SIZE_CHECK_CSCRIPTLOCATION;
    CheckSize<sizeof(NWNXLib::API::CScriptSourceFile), 44> __attribute__((unused)) SIZE_CHECK_CSCRIPTSOURCEFILE;
    CheckSize<sizeof(NWNXLib::API::CScriptTalent), 24> __attribute__((unused)) SIZE_CHECK_CSCRIPTTALENT;
    CheckSize<sizeof(NWNXLib::API::CServerAIBodyBagInfo), 16> __attribute__((unused)) SIZE_CHECK_CSERVERAIBODYBAGINFO;
    CheckSize<sizeof(NWNXLib::API::CServerAIEventNode), 24> __attribute__((unused)) SIZE_CHECK_CSERVERAIEVENTNODE;
    CheckSize<sizeof(NWNXLib::API::CServerAIList), 16> __attribute__((unused)) SIZE_CHECK_CSERVERAILIST;
    CheckSize<sizeof(NWNXLib::API::CServerAIMaster), 148> __attribute__((unused)) SIZE_CHECK_CSERVERAIMASTER;
    CheckSize<sizeof(NWNXLib::API::CServerExoApp), 8> __attribute__((unused)) SIZE_CHECK_CSERVEREXOAPP;
    CheckSize<sizeof(NWNXLib::API::CServerExoAppInternal), 65928> __attribute__((unused)) SIZE_CHECK_CSERVEREXOAPPINTERNAL;
    CheckSize<sizeof(NWNXLib::API::CServerInfo), 1204> __attribute__((unused)) SIZE_CHECK_CSERVERINFO;
    CheckSize<sizeof(NWNXLib::API::CStoreCustomer), 24> __attribute__((unused)) SIZE_CHECK_CSTORECUSTOMER;
    CheckSize<sizeof(NWNXLib::API::CTlkFile), 28> __attribute__((unused)) SIZE_CHECK_CTLKFILE;
    CheckSize<sizeof(NWNXLib::API::CTlkResFile), 72> __attribute__((unused)) SIZE_CHECK_CTLKRESFILE;
    CheckSize<sizeof(NWNXLib::API::CTlkTable), 44> __attribute__((unused)) SIZE_CHECK_CTLKTABLE;
    CheckSize<sizeof(NWNXLib::API::CTwoDimArrays), 620> __attribute__((unused)) SIZE_CHECK_CTWODIMARRAYS;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachine), 1016> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINE;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachineCache), 12> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINECACHE;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachineDebuggerInstance), 264> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINEDEBUGGERINSTANCE;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachineDebugLoader), 48> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINEDEBUGLOADER;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachineFile), 44> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINEFILE;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachineScript), 36> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINESCRIPT;
    CheckSize<sizeof(NWNXLib::API::CVirtualMachineStack), 24> __attribute__((unused)) SIZE_CHECK_CVIRTUALMACHINESTACK;
    CheckSize<sizeof(NWNXLib::API::CWorldTimer), 56> __attribute__((unused)) SIZE_CHECK_CWORLDTIMER;
    //CheckSize<sizeof(NWNXLib::API::HttpBuffer), 312> __attribute__((unused)) SIZE_CHECK_HTTPBUFFER;
    //CheckSize<sizeof(NWNXLib::API::HttpConnection), 36> __attribute__((unused)) SIZE_CHECK_HTTPCONNECTION;
    CheckSize<sizeof(NWNXLib::API::ICrashReporter), 12> __attribute__((unused)) SIZE_CHECK_ICRASHREPORTER;
    CheckSize<sizeof(NWNXLib::API::Matrix), 36> __attribute__((unused)) SIZE_CHECK_MATRIX;
    CheckSize<sizeof(NWNXLib::API::Plane), 16> __attribute__((unused)) SIZE_CHECK_PLANE;
    CheckSize<sizeof(NWNXLib::API::Quaternion), 16> __attribute__((unused)) SIZE_CHECK_QUATERNION;
    //CheckSize<sizeof(NWNXLib::API::ScopeGuard), 16> __attribute__((unused)) SIZE_CHECK_SCOPEGUARD;
    CheckSize<sizeof(NWNXLib::API::SJournalEntry), 56> __attribute__((unused)) SIZE_CHECK_SJOURNALENTRY;
    CheckSize<sizeof(NWNXLib::API::STR_RES), 44> __attribute__((unused)) SIZE_CHECK_STR_RES;
    CheckSize<sizeof(NWNXLib::API::TLK_FILE_HEADER), 20> __attribute__((unused)) SIZE_CHECK_TLK_FILE_HEADER;
    CheckSize<sizeof(NWNXLib::API::Vector), 12> __attribute__((unused)) SIZE_CHECK_VECTOR;
    CheckSize<sizeof(NWNXLib::API::Vector4), 16> __attribute__((unused)) SIZE_CHECK_VECTOR4;
}
