#pragma once

#include <cstdint>

#include "Constants/Base.hpp"
#include "Constants/VirtualMachine.hpp"
#include "Constants/ClassType.hpp"
#include "Constants/RacialType.hpp"
#include "Constants/Skill.hpp"
#include "Constants/Feat.hpp"
#include "Constants/MiscRules.hpp"
//#include "Constants/Item.hpp"
//#include "Constants/Effect.hpp"
//#include "Constants/Events.hpp"
//#include "Constants/AI.hpp"
//#include "Constants/Combat.hpp"
//#include "Constants/Misc.hpp"

namespace NWNXLib {

namespace API {

namespace Constants {




constexpr uint8_t AI_PRIORITY_VERY_LOW =                               0;
constexpr uint8_t AI_PRIORITY_LOW =                                    1;
constexpr uint8_t AI_PRIORITY_MEDIUM =                                 2;
constexpr uint8_t AI_PRIORITY_HIGH =                                   3;
constexpr uint8_t AI_PRIORITY_VERY_HIGH =                              4;

constexpr const char* AIPriorityToString(const uint8_t priority)
{
    constexpr const char* PRIORITY_STRINGS[] =
    {
        "VERY_LOW",
        "LOW",
        "MEDIUM",
        "HIGH",
        "VERY_HIGH"
    };

    return (priority > AI_PRIORITY_VERY_HIGH) ? "(invalid)" : PRIORITY_STRINGS[priority];
}

constexpr uint32_t QUICKBAR_TYPE_INVALID =                              0;
constexpr uint32_t QUICKBAR_TYPE_ITEM =                                 1;
constexpr uint32_t QUICKBAR_TYPE_SPELL =                                2;
constexpr uint32_t QUICKBAR_TYPE_PARRY =                                3;
constexpr uint32_t QUICKBAR_TYPE_FEAT =                                 4;
constexpr uint32_t QUICKBAR_TYPE_TALKTO =                               6;
constexpr uint32_t QUICKBAR_TYPE_ATTACK =                               7;
constexpr uint32_t QUICKBAR_TYPE_EMOTE =                                8;
constexpr uint32_t QUICKBAR_TYPE_MODE =                                10;
constexpr uint32_t QUICKBAR_TYPE_MACRO =                               18;

constexpr uint32_t CREATURE_EVENT_HEARTBEAT =                           0;
constexpr uint32_t CREATURE_EVENT_PERCEPTION =                          1;
constexpr uint32_t CREATURE_EVENT_SPELLCAST =                           2;
constexpr uint32_t CREATURE_EVENT_ATTACKED =                            3;
constexpr uint32_t CREATURE_EVENT_DAMAGED =                             4;
constexpr uint32_t CREATURE_EVENT_DISTURBED =                           5;
constexpr uint32_t CREATURE_EVENT_ENDCOMBAT =                           6;
constexpr uint32_t CREATURE_EVENT_CONVERSATION =                        7;
constexpr uint32_t CREATURE_EVENT_SPAWN =                               8;
constexpr uint32_t CREATURE_EVENT_RESTED =                              9;
constexpr uint32_t CREATURE_EVENT_DEATH =                              10;
constexpr uint32_t CREATURE_EVENT_USERDEF =                            11;
constexpr uint32_t CREATURE_EVENT_BLOCKED =                            12;

constexpr uint32_t EQUIPMENT_SLOT_HEAD =                        (1 <<  0);    /* ESLOT_0001 */
constexpr uint32_t EQUIPMENT_SLOT_CHEST =                       (1 <<  1);    /* ESLOT_0002 */
constexpr uint32_t EQUIPMENT_SLOT_BOOTS =                       (1 <<  2);    /* ESLOT_0004 */
constexpr uint32_t EQUIPMENT_SLOT_ARMS =                        (1 <<  3);    /* ESLOT_0008 */
constexpr uint32_t EQUIPMENT_SLOT_RIGHTHAND =                   (1 <<  4);    /* ESLOT_0010 */
constexpr uint32_t EQUIPMENT_SLOT_LEFTHAND =                    (1 <<  5);    /* ESLOT_0020 */
constexpr uint32_t EQUIPMENT_SLOT_CLOAK =                       (1 <<  6);    /* ESLOT_0040 */
constexpr uint32_t EQUIPMENT_SLOT_LEFTRING =                    (1 <<  7);    /* ESLOT_0080 */
constexpr uint32_t EQUIPMENT_SLOT_RIGHTRING =                   (1 <<  8);    /* ESLOT_0100 */
constexpr uint32_t EQUIPMENT_SLOT_NECK =                        (1 <<  9);    /* ESLOT_0200 */
constexpr uint32_t EQUIPMENT_SLOT_BELT =                        (1 << 10);    /* ESLOT_0400 */
constexpr uint32_t EQUIPMENT_SLOT_ARROWS =                      (1 << 11);    /* ESLOT_0800 */
constexpr uint32_t EQUIPMENT_SLOT_BULLETS =                     (1 << 12);    /* ESLOT_1000 */
constexpr uint32_t EQUIPMENT_SLOT_BOLTS =                       (1 << 13);    /* ESLOT_2000 */
constexpr uint32_t EQUIPMENT_SLOT_CWEAPON_L =                   (1 << 14);    /* ESLOT_4000 */
constexpr uint32_t EQUIPMENT_SLOT_CWEAPON_R =                   (1 << 15);    /* ESLOT_8000 */
constexpr uint32_t EQUIPMENT_SLOT_CWEAPON_B =                   (1 << 16);    /* ESLOT_10000 */
constexpr uint32_t EQUIPMENT_SLOT_CARMOUR =                     (1 << 17);    /* ESLOT_20000 */

constexpr uint32_t INVENTORY_SLOT_HEAD =                                0;
constexpr uint32_t INVENTORY_SLOT_CHEST =                               1;
constexpr uint32_t INVENTORY_SLOT_BOOTS =                               2;
constexpr uint32_t INVENTORY_SLOT_ARMS =                                3;
constexpr uint32_t INVENTORY_SLOT_RIGHTHAND =                           4;
constexpr uint32_t INVENTORY_SLOT_LEFTHAND =                            5;
constexpr uint32_t INVENTORY_SLOT_CLOAK =                               6;
constexpr uint32_t INVENTORY_SLOT_LEFTRING =                            7;
constexpr uint32_t INVENTORY_SLOT_RIGHTRING =                           8;
constexpr uint32_t INVENTORY_SLOT_NECK =                                9;
constexpr uint32_t INVENTORY_SLOT_BELT =                               10;
constexpr uint32_t INVENTORY_SLOT_ARROWS =                             11;
constexpr uint32_t INVENTORY_SLOT_BULLETS =                            12;
constexpr uint32_t INVENTORY_SLOT_BOLTS =                              13;
constexpr uint32_t INVENTORY_SLOT_CWEAPON_L =                          14;
constexpr uint32_t INVENTORY_SLOT_CWEAPON_R =                          15;
constexpr uint32_t INVENTORY_SLOT_CWEAPON_B =                          16;
constexpr uint32_t INVENTORY_SLOT_CARMOUR =                            17;

constexpr uint32_t BASE_ITEM_SHORTSWORD =                               0;    /* BASE_000 */
constexpr uint32_t BASE_ITEM_LONGSWORD =                                1;    /* BASE_001 */
constexpr uint32_t BASE_ITEM_BATTLEAXE =                                2;    /* BASE_002 */
constexpr uint32_t BASE_ITEM_BASTARDSWORD =                             3;    /* BASE_003 */
constexpr uint32_t BASE_ITEM_LIGHTFLAIL =                               4;    /* BASE_004 */
constexpr uint32_t BASE_ITEM_WARHAMMER =                                5;    /* BASE_005 */
constexpr uint32_t BASE_ITEM_HEAVYCROSSBOW =                            6;    /* BASE_006 */
constexpr uint32_t BASE_ITEM_LIGHTCROSSBOW =                            7;    /* BASE_007 */
constexpr uint32_t BASE_ITEM_LONGBOW =                                  8;    /* BASE_008 */
constexpr uint32_t BASE_ITEM_LIGHTMACE =                                9;    /* BASE_009 */
constexpr uint32_t BASE_ITEM_HALBERD =                                 10;    /* BASE_00A */
constexpr uint32_t BASE_ITEM_SHORTBOW =                                11;    /* BASE_00B */
constexpr uint32_t BASE_ITEM_TWOBLADEDSWORD =                          12;    /* BASE_00C */
constexpr uint32_t BASE_ITEM_GREATSWORD =                              13;    /* BASE_00D */
constexpr uint32_t BASE_ITEM_SMALLSHIELD =                             14;    /* BASE_00E */
constexpr uint32_t BASE_ITEM_TORCH =                                   15;    /* BASE_00F */
constexpr uint32_t BASE_ITEM_ARMOR =                                   16;    /* BASE_010 */
constexpr uint32_t BASE_ITEM_HELMET =                                  17;    /* BASE_011 */
constexpr uint32_t BASE_ITEM_GREATAXE =                                18;    /* BASE_012 */
constexpr uint32_t BASE_ITEM_AMULET =                                  19;    /* BASE_013 */
constexpr uint32_t BASE_ITEM_ARROW =                                   20;    /* BASE_014 */
constexpr uint32_t BASE_ITEM_BELT =                                    21;    /* BASE_015 */
constexpr uint32_t BASE_ITEM_DAGGER =                                  22;    /* BASE_016 */
constexpr uint32_t BASE_ITEM_MISCSMALL =                               24;    /* BASE_018 */
constexpr uint32_t BASE_ITEM_BOLT =                                    25;    /* BASE_019 */
constexpr uint32_t BASE_ITEM_BOOTS =                                   26;    /* BASE_01A */
constexpr uint32_t BASE_ITEM_BULLET =                                  27;    /* BASE_01B */
constexpr uint32_t BASE_ITEM_CLUB =                                    28;    /* BASE_01C */
constexpr uint32_t BASE_ITEM_MISCMEDIUM =                              29;    /* BASE_01D */
constexpr uint32_t BASE_ITEM_DART =                                    31;    /* BASE_01F */
constexpr uint32_t BASE_ITEM_DIREMACE =                                32;    /* BASE_020 */
constexpr uint32_t BASE_ITEM_DOUBLEAXE =                               33;    /* BASE_021 */
constexpr uint32_t BASE_ITEM_MISCLARGE =                               34;    /* BASE_022 */
constexpr uint32_t BASE_ITEM_HEAVYFLAIL =                              35;    /* BASE_023 */
constexpr uint32_t BASE_ITEM_GLOVES =                                  36;    /* BASE_024 */
constexpr uint32_t BASE_ITEM_LIGHTHAMMER =                             37;    /* BASE_025 */
constexpr uint32_t BASE_ITEM_HANDAXE =                                 38;    /* BASE_026 */
constexpr uint32_t BASE_ITEM_HEALERSKIT =                              39;    /* BASE_027 */
constexpr uint32_t BASE_ITEM_KAMA =                                    40;    /* BASE_028 */
constexpr uint32_t BASE_ITEM_KATANA =                                  41;    /* BASE_029 */
constexpr uint32_t BASE_ITEM_KUKRI =                                   42;    /* BASE_02A */
constexpr uint32_t BASE_ITEM_MISCTALL =                                43;    /* BASE_02B */
constexpr uint32_t BASE_ITEM_MAGICROD =                                44;    /* BASE_02C */
constexpr uint32_t BASE_ITEM_MAGICSTAFF =                              45;    /* BASE_02D */
constexpr uint32_t BASE_ITEM_MAGICWAND =                               46;    /* BASE_02E */
constexpr uint32_t BASE_ITEM_MORNINGSTAR =                             47;    /* BASE_02F */
constexpr uint32_t BASE_ITEM_POTIONS =                                 49;    /* BASE_031 */
constexpr uint32_t BASE_ITEM_QUARTERSTAFF =                            50;    /* BASE_032 */
constexpr uint32_t BASE_ITEM_RAPIER =                                  51;    /* BASE_033 */
constexpr uint32_t BASE_ITEM_RING =                                    52;    /* BASE_034 */
constexpr uint32_t BASE_ITEM_SCIMITAR =                                53;    /* BASE_035 */
constexpr uint32_t BASE_ITEM_SCROLL =                                  54;    /* BASE_036 */
constexpr uint32_t BASE_ITEM_SCYTHE =                                  55;    /* BASE_037 */
constexpr uint32_t BASE_ITEM_LARGESHIELD =                             56;    /* BASE_038 */
constexpr uint32_t BASE_ITEM_TOWERSHIELD =                             57;    /* BASE_039 */
constexpr uint32_t BASE_ITEM_SHORTSPEAR =                              58;    /* BASE_03A */
constexpr uint32_t BASE_ITEM_SHURIKEN =                                59;    /* BASE_03B */
constexpr uint32_t BASE_ITEM_SICKLE =                                  60;    /* BASE_03C */
constexpr uint32_t BASE_ITEM_SLING =                                   61;    /* BASE_03D */
constexpr uint32_t BASE_ITEM_THIEVESTOOLS =                            62;    /* BASE_03E */
constexpr uint32_t BASE_ITEM_THROWINGAXE =                             63;    /* BASE_03F */
constexpr uint32_t BASE_ITEM_TRAPKIT =                                 64;    /* BASE_040 */
constexpr uint32_t BASE_ITEM_KEY =                                     65;    /* BASE_041 */
constexpr uint32_t BASE_ITEM_LARGEBOX =                                66;    /* BASE_042 */
constexpr uint32_t BASE_ITEM_MISCWIDE =                                68;    /* BASE_044 */
constexpr uint32_t BASE_ITEM_CSLASHWEAPON =                            69;    /* BASE_045 */
constexpr uint32_t BASE_ITEM_CPIERCWEAPON =                            70;    /* BASE_046 */
constexpr uint32_t BASE_ITEM_CBLUDGWEAPON =                            71;    /* BASE_047 */
constexpr uint32_t BASE_ITEM_CSLSHPRCWEAP =                            72;    /* BASE_048 */
constexpr uint32_t BASE_ITEM_CREATUREITEM =                            73;    /* BASE_049 */
constexpr uint32_t BASE_ITEM_BOOK =                                    74;    /* BASE_04A */
constexpr uint32_t BASE_ITEM_SPELLSCROLL =                             75;    /* BASE_04B */
constexpr uint32_t BASE_ITEM_GOLD =                                    76;    /* BASE_04C */
constexpr uint32_t BASE_ITEM_GEM =                                     77;    /* BASE_04D */
constexpr uint32_t BASE_ITEM_BRACER =                                  78;    /* BASE_04E */
constexpr uint32_t BASE_ITEM_MISCTHIN =                                79;    /* BASE_04F */
constexpr uint32_t BASE_ITEM_CLOAK =                                   80;    /* BASE_050 */
constexpr uint32_t BASE_ITEM_GRENADE =                                 81;    /* BASE_051 */
constexpr uint32_t BASE_ITEM_ENCAMPMENT =                              82;    /* BASE_052 */
constexpr uint32_t BASE_ITEM_LANCE =                                   92;    /* BASE_05C */
constexpr uint32_t BASE_ITEM_TRUMPET =                                 92;    /* BASE_05D */
constexpr uint32_t BASE_ITEM_MOONONASTICK =                            92;    /* BASE_05E */
constexpr uint32_t BASE_ITEM_TRIDENT =                                 95;    /* BASE_05F */
constexpr uint32_t BASE_ITEM_BLANK_POTION =                           101;    /* BASE_065 */
constexpr uint32_t BASE_ITEM_BLANK_SCROLL =                           102;    /* BASE_066 */
constexpr uint32_t BASE_ITEM_BLANK_WAND =                             103;    /* BASE_067 */
constexpr uint32_t BASE_ITEM_ENCHANTED_POTION =                       104;    /* BASE_068 */
constexpr uint32_t BASE_ITEM_ENCHANTED_SCROLL =                       105;    /* BASE_069 */
constexpr uint32_t BASE_ITEM_ENCHANTED_WAND =                         106;    /* BASE_06A */
constexpr uint32_t BASE_ITEM_DWARVENWARAXE =                          108;    /* BASE_06C */
constexpr uint32_t BASE_ITEM_CRAFTMATERIALMED =                       109;    /* BASE_06D */
constexpr uint32_t BASE_ITEM_CRAFTMATERIALSML =                       110;    /* BASE_06E */
constexpr uint32_t BASE_ITEM_WHIP =                                   111;    /* BASE_06F */
constexpr uint32_t BASE_ITEM_CRAFTBASE =                              112;    /* BASE_070 */
constexpr uint32_t BASE_ITEM_INVALID =                                255;    /* BASE_0FF */

constexpr uint32_t BASE_ITEM_CEP_TRIDENT =                            300;    /* BASE_12C */
constexpr uint32_t BASE_ITEM_CEP_HEAVYPICK =                          301;    /* BASE_12D */
constexpr uint32_t BASE_ITEM_CEP_LIGHTPICK =                          302;    /* BASE_12E */
constexpr uint32_t BASE_ITEM_CEP_SAI =                                303;    /* BASE_12F */
constexpr uint32_t BASE_ITEM_CEP_NUNCHAKU =                           304;    /* BASE_130 */
constexpr uint32_t BASE_ITEM_CEP_FALCHION =                           305;    /* BASE_131 */
constexpr uint32_t BASE_ITEM_CEP_SMALLBOX =                           306;    /* BASE_132 */
constexpr uint32_t BASE_ITEM_CEP_MISCMEDIUM2 =                        307;    /* BASE_133 */
constexpr uint32_t BASE_ITEM_CEP_SAP =                                308;    /* BASE_134 */
constexpr uint32_t BASE_ITEM_CEP_ASSASSINDAGGER =                     309;    /* BASE_135 */
constexpr uint32_t BASE_ITEM_CEP_KATAR =                              310;    /* BASE_136 */
constexpr uint32_t BASE_ITEM_CEP_MISCSMALL2 =                         311;    /* BASE_137 */
constexpr uint32_t BASE_ITEM_CEP_HEAVYMACE =                          317;    /* BASE_13D */
constexpr uint32_t BASE_ITEM_CEP_MAUL =                               318;    /* BASE_13E */
constexpr uint32_t BASE_ITEM_CEP_MERCURIALLONGSWORD =                 319;    /* BASE_13F */
constexpr uint32_t BASE_ITEM_CEP_MERCURIALGREATSWORD =                320;    /* BASE_140 */
constexpr uint32_t BASE_ITEM_CEP_DOUBLESCIMITAR =                     321;    /* BASE_141 */
constexpr uint32_t BASE_ITEM_CEP_GOAD =                               322;    /* BASE_142 */
constexpr uint32_t BASE_ITEM_CEP_WINDFIREWHEEL =                      323;    /* BASE_143 */
constexpr uint32_t BASE_ITEM_CEP_DOUBLEPICK =                         324;    /* BASE_144 */
constexpr uint32_t BASE_ITEM_CEP_FLOWERS =                            325;    /* BASE_145 */
constexpr uint32_t BASE_ITEM_CEP_CLOAK =                              349;    /* BASE_15D */


constexpr uint32_t SUBTYPE_MASK =                                      24;
constexpr uint32_t SUBTYPE_MAGICAL =                                    8;
constexpr uint32_t SUBTYPE_SUPERNATURAL =                              16;
constexpr uint32_t SUBTYPE_EXTRAORDINARY =                             24;

constexpr uint32_t DURATION_TYPE_MASK =                                 7;
constexpr uint32_t DURATION_TYPE_INSTANT =                              0;
constexpr uint32_t DURATION_TYPE_TEMPORARY =                            1;
constexpr uint32_t DURATION_TYPE_PERMANENT =                            2;
constexpr uint32_t DURATION_TYPE_EQUIPPED =                             3;
constexpr uint32_t DURATION_TYPE_INNATE =                               4;

constexpr uint32_t EFFECT_TRUETYPE_INVALIDEFFECT =                      0;
constexpr uint32_t EFFECT_TRUETYPE_HASTE =                              1;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_RESISTANCE =                  2;
constexpr uint32_t EFFECT_TRUETYPE_SLOW =                               3;
constexpr uint32_t EFFECT_TRUETYPE_RESURRECTION =                       4;
constexpr uint32_t EFFECT_TRUETYPE_DISEASE =                            5;
constexpr uint32_t EFFECT_TRUETYPE_SUMMON_CREATURE =                    6;
constexpr uint32_t EFFECT_TRUETYPE_REGENERATE =                         7;
constexpr uint32_t EFFECT_TRUETYPE_SETSTATE =                           8;
constexpr uint32_t EFFECT_TRUETYPE_SETSTATE_INTERNAL =                  9;
constexpr uint32_t EFFECT_TRUETYPE_ATTACK_INCREASE =                   10;
constexpr uint32_t EFFECT_TRUETYPE_ATTACK_DECREASE =                   11;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_REDUCTION =                  12;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_INCREASE =                   13;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_DECREASE =                   14;
constexpr uint32_t EFFECT_TRUETYPE_TEMPORARY_HITPOINTS =               15;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_IMMUNITY_INCREASE =          16;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_IMMUNITY_DECREASE =          17;
constexpr uint32_t EFFECT_TRUETYPE_ENTANGLE =                          18;
constexpr uint32_t EFFECT_TRUETYPE_DEATH =                             19;
constexpr uint32_t EFFECT_TRUETYPE_KNOCKDOWN =                         20;
constexpr uint32_t EFFECT_TRUETYPE_DEAF =                              21;
constexpr uint32_t EFFECT_TRUETYPE_IMMUNITY =                          22;
constexpr uint32_t EFFECT_TRUETYPE_SET_AI_STATE =                      23;
constexpr uint32_t EFFECT_TRUETYPE_ENEMY_ATTACK_BONUS =                24;
constexpr uint32_t EFFECT_TRUETYPE_ARCANE_SPELL_FAILURE =              25;
constexpr uint32_t EFFECT_TRUETYPE_SAVING_THROW_INCREASE =             26;
constexpr uint32_t EFFECT_TRUETYPE_SAVING_THROW_DECREASE =             27;
constexpr uint32_t EFFECT_TRUETYPE_MOVEMENT_SPEED_INCREASE =           28;
constexpr uint32_t EFFECT_TRUETYPE_MOVEMENT_SPEED_DECREASE =           29;
constexpr uint32_t EFFECT_TRUETYPE_VISUALEFFECT =                      30;
constexpr uint32_t EFFECT_TRUETYPE_AREA_OF_EFFECT =                    31;
constexpr uint32_t EFFECT_TRUETYPE_BEAM =                              32;
constexpr uint32_t EFFECT_TRUETYPE_SPELL_RESISTANCE_INCREASE =         33;
constexpr uint32_t EFFECT_TRUETYPE_SPELL_RESISTANCE_DECREASE =         34;
constexpr uint32_t EFFECT_TRUETYPE_POISON =                            35;
constexpr uint32_t EFFECT_TRUETYPE_ABILITY_INCREASE =                  36;
constexpr uint32_t EFFECT_TRUETYPE_ABILITY_DECREASE =                  37;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE =                            38;
constexpr uint32_t EFFECT_TRUETYPE_HEAL =                              39;
constexpr uint32_t EFFECT_TRUETYPE_LINK =                              40;
constexpr uint32_t EFFECT_TRUETYPE_HASTE_INTERNAL =                    41;
constexpr uint32_t EFFECT_TRUETYPE_SLOW_INTERNAL =                     42;
constexpr uint32_t EFFECT_TRUETYPE_MODIFYNUMATTACKS =                  44;
constexpr uint32_t EFFECT_TRUETYPE_CURSE =                             45;
constexpr uint32_t EFFECT_TRUETYPE_SILENCE =                           46;
constexpr uint32_t EFFECT_TRUETYPE_INVISIBILITY =                      47;
constexpr uint32_t EFFECT_TRUETYPE_AC_INCREASE =                       48;
constexpr uint32_t EFFECT_TRUETYPE_AC_DECREASE =                       49;
constexpr uint32_t EFFECT_TRUETYPE_SPELL_IMMUNITY =                    50;
constexpr uint32_t EFFECT_TRUETYPE_DISPEL_ALL_MAGIC =                  51;
constexpr uint32_t EFFECT_TRUETYPE_DISPEL_BEST_MAGIC =                 52;
constexpr uint32_t EFFECT_TRUETYPE_TAUNT =                             53;
constexpr uint32_t EFFECT_TRUETYPE_LIGHT =                             54;
constexpr uint32_t EFFECT_TRUETYPE_SKILL_INCREASE =                    55;
constexpr uint32_t EFFECT_TRUETYPE_SKILL_DECREASE =                    56;
constexpr uint32_t EFFECT_TRUETYPE_HITPOINTCHANGEWHENDYING =           57;
constexpr uint32_t EFFECT_TRUETYPE_SETWALKANIMATION =                  58;
constexpr uint32_t EFFECT_TRUETYPE_LIMIT_MOVEMENT_SPEED =              59;
constexpr uint32_t EFFECT_TRUETYPE_DAMAGE_SHIELD =                     61;
constexpr uint32_t EFFECT_TRUETYPE_POLYMORPH =                         62;
constexpr uint32_t EFFECT_TRUETYPE_SANCTUARY =                         63;
constexpr uint32_t EFFECT_TRUETYPE_TIMESTOP =                          64;
constexpr uint32_t EFFECT_TRUETYPE_SPELL_LEVEL_ABSORPTION =            65;
constexpr uint32_t EFFECT_TRUETYPE_ICON =                              67;
constexpr uint32_t EFFECT_TRUETYPE_RACIAL_TYPE =                       68;
constexpr uint32_t EFFECT_TRUETYPE_VISION =                            69;
constexpr uint32_t EFFECT_TRUETYPE_SEEINVISIBLE =                      70;
constexpr uint32_t EFFECT_TRUETYPE_ULTRAVISION =                       71;
constexpr uint32_t EFFECT_TRUETYPE_TRUESEEING =                        72;
constexpr uint32_t EFFECT_TRUETYPE_BLINDNESS =                         73;
constexpr uint32_t EFFECT_TRUETYPE_DARKNESS =                          74;
constexpr uint32_t EFFECT_TRUETYPE_MISS_CHANCE =                       75;
constexpr uint32_t EFFECT_TRUETYPE_CONCEALMENT =                       76;
constexpr uint32_t EFFECT_TRUETYPE_TURN_RESISTANCE_INCREASE =          77;
constexpr uint32_t EFFECT_TRUETYPE_BONUS_SPELL_OF_LEVEL =              78;
constexpr uint32_t EFFECT_TRUETYPE_DISAPPEARAPPEAR =                   79;
constexpr uint32_t EFFECT_TRUETYPE_DISAPPEAR =                         80;
constexpr uint32_t EFFECT_TRUETYPE_APPEAR =                            81;
constexpr uint32_t EFFECT_TRUETYPE_NEGATIVE_LEVEL =                    82;
constexpr uint32_t EFFECT_TRUETYPE_BONUS_FEAT =                        83;
constexpr uint32_t EFFECT_TRUETYPE_WOUNDING =                          84;
constexpr uint32_t EFFECT_TRUETYPE_SWARM =                             85;
constexpr uint32_t EFFECT_TRUETYPE_VAMPIRIC_REGENERATION =             86;
constexpr uint32_t EFFECT_TRUETYPE_DISARM =                            87;
constexpr uint32_t EFFECT_TRUETYPE_TURN_RESISTANCE_DECREASE =          88;
constexpr uint32_t EFFECT_TRUETYPE_BLINDNESS_INACTIVE =                89;
constexpr uint32_t EFFECT_TRUETYPE_PETRIFY =                           90;
constexpr uint32_t EFFECT_TRUETYPE_ITEMPROPERTY =                      91;
constexpr uint32_t EFFECT_TRUETYPE_SPELL_FAILURE =                     92;
constexpr uint32_t EFFECT_TRUETYPE_CUTSCENEGHOST =                     93;
constexpr uint32_t EFFECT_TRUETYPE_CUTSCENEIMMOBILE =                  94;
constexpr uint32_t EFFECT_TRUETYPE_DEFENSIVESTANCE =                   95;


constexpr uint32_t ITEM_RULE_WEAPON_SIZE =                             25;


constexpr int32_t ITEM_APPR_COLOR_LEATHER_1 =                          -9;
constexpr int32_t ITEM_APPR_COLOR_LEATHER_2 =                          -8;
constexpr int32_t ITEM_APPR_COLOR_CLOTH_1 =                            -7;
constexpr int32_t ITEM_APPR_COLOR_CLOTH_2 =                            -6;
constexpr int32_t ITEM_APPR_COLOR_METAL_1 =                            -5;
constexpr int32_t ITEM_APPR_COLOR_METAL_2 =                            -4;
constexpr int32_t ITEM_APPR_MODEL_PART_1 =                             -3;
constexpr int32_t ITEM_APPR_MODEL_PART_2 =                             -2;
constexpr int32_t ITEM_APPR_MODEL_PART_3 =                             -1;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RFOOT =                         0;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LFOOT =                         1;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RSHIN =                         2;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LSHIN =                         3;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LTHIGH =                        4;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RTHIGH =                        5;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_PELVIS =                        6;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_TORSO =                         7;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_BELT =                          8;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_NECK =                          9;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RFOREARM  =                    10;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LFOREARM  =                    11;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RBICEP =                       12;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LBICEP =                       13;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RSHOULDER  =                   14;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LSHOULDER  =                   15;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_RHAND =                        16;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_LHAND =                        17;
constexpr int32_t ITEM_APPR_ARMOR_MODEL_ROBE =                         18;


constexpr int32_t ITEM_APPR_TYPE_SIMPLE_MODEL =                         0;
constexpr int32_t ITEM_APPR_TYPE_WEAPON_COLOR =                         1;
constexpr int32_t ITEM_APPR_TYPE_WEAPON_MODEL =                         2;
constexpr int32_t ITEM_APPR_TYPE_ARMOR_MODEL =                          3;
constexpr int32_t ITEM_APPR_TYPE_ARMOR_COLOR =                          4;
constexpr int32_t ITEM_APPR_NUM_TYPES =                                 5;


constexpr uint32_t VFX_DUR_BLUR =                       0;
constexpr uint32_t VFX_DUR_DARKNESS =                   1;
constexpr uint32_t VFX_DUR_ENTANGLE =                   2;
constexpr uint32_t VFX_DUR_FREEDOM_OF_MOVEMENT =        3;
constexpr uint32_t VFX_DUR_GLOBE_INVULNERABILITY =      4;
constexpr uint32_t VFX_DUR_BLACKOUT =                   5;
constexpr uint32_t VFX_DUR_INVISIBILITY =               6;
constexpr uint32_t VFX_DUR_MIND_AFFECTING_NEGATIVE =    7;
constexpr uint32_t VFX_DUR_MIND_AFFECTING_POSITIVE =    8;
constexpr uint32_t VFX_DUR_GHOSTLY_VISAGE =             9;
constexpr uint32_t VFX_DUR_ETHEREAL_VISAGE =            10;
constexpr uint32_t VFX_DUR_PROT_BARKSKIN =              11;
constexpr uint32_t VFX_DUR_PROT_GREATER_STONESKIN =     12;
constexpr uint32_t VFX_DUR_PROT_PREMONITION =           13;
constexpr uint32_t VFX_DUR_PROT_SHADOW_ARMOR =          14;
constexpr uint32_t VFX_DUR_PROT_STONESKIN =             15;
constexpr uint32_t VFX_DUR_SANCTUARY =                  16;
constexpr uint32_t VFX_DUR_WEB =                        17;
constexpr uint32_t VFX_FNF_BLINDDEAF =                  18;
constexpr uint32_t VFX_FNF_DISPEL =                     19;
constexpr uint32_t VFX_FNF_DISPEL_DISJUNCTION =         20;
constexpr uint32_t VFX_FNF_DISPEL_GREATER =             21;
constexpr uint32_t VFX_FNF_FIREBALL =                   22;
constexpr uint32_t VFX_FNF_FIRESTORM =                  23;
constexpr uint32_t VFX_FNF_IMPLOSION =                  24;
constexpr uint32_t VFX_FNF_MASS_HEAL =                  26;
constexpr uint32_t VFX_FNF_MASS_MIND_AFFECTING =        27;
constexpr uint32_t VFX_FNF_METEOR_SWARM =               28;
constexpr uint32_t VFX_FNF_NATURES_BALANCE =            29;
constexpr uint32_t VFX_FNF_PWKILL =                     30;
constexpr uint32_t VFX_FNF_PWSTUN =                     31;
constexpr uint32_t VFX_FNF_SUMMON_GATE =                32;
constexpr uint32_t VFX_FNF_SUMMON_MONSTER_1 =           33;
constexpr uint32_t VFX_FNF_SUMMON_MONSTER_2 =           34;
constexpr uint32_t VFX_FNF_SUMMON_MONSTER_3 =           35;
constexpr uint32_t VFX_FNF_SUMMON_UNDEAD =              36;
constexpr uint32_t VFX_FNF_SUNBEAM =                    37;
constexpr uint32_t VFX_FNF_TIME_STOP =                  38;
constexpr uint32_t VFX_FNF_WAIL_O_BANSHEES =            39;
constexpr uint32_t VFX_FNF_WEIRD =                      40;
constexpr uint32_t VFX_FNF_WORD =                       41;
constexpr uint32_t VFX_IMP_AC_BONUS =                   42;
constexpr uint32_t VFX_IMP_ACID_L =                     43;
constexpr uint32_t VFX_IMP_ACID_S =                     44;
constexpr uint32_t VFX_IMP_BLIND_DEAF_M =               46;
constexpr uint32_t VFX_IMP_BREACH =                     47;
constexpr uint32_t VFX_IMP_CONFUSION_S =                48;
constexpr uint32_t VFX_IMP_DAZED_S =                    49;
constexpr uint32_t VFX_IMP_DEATH =                      50;
constexpr uint32_t VFX_IMP_DISEASE_S =                  51;
constexpr uint32_t VFX_IMP_DISPEL =                     52;
constexpr uint32_t VFX_IMP_DISPEL_DISJUNCTION =         53;
constexpr uint32_t VFX_IMP_DIVINE_STRIKE_FIRE =         54;
constexpr uint32_t VFX_IMP_DIVINE_STRIKE_HOLY =         55;
constexpr uint32_t VFX_IMP_DOMINATE_S =                 56;
constexpr uint32_t VFX_IMP_DOOM =                       57;
constexpr uint32_t VFX_IMP_FEAR_S =                     58;
constexpr uint32_t VFX_IMP_FLAME_M =                    60;
constexpr uint32_t VFX_IMP_FLAME_S =                    61;
constexpr uint32_t VFX_IMP_FROST_L =                    62;
constexpr uint32_t VFX_IMP_FROST_S =                    63;
constexpr uint32_t VFX_IMP_GREASE =                     64;
constexpr uint32_t VFX_IMP_HASTE =                      65;
constexpr uint32_t VFX_IMP_HEALING_G =                  66;
constexpr uint32_t VFX_IMP_HEALING_L =                  67;
constexpr uint32_t VFX_IMP_HEALING_M =                  68;
constexpr uint32_t VFX_IMP_HEALING_S =                  69;
constexpr uint32_t VFX_IMP_HEALING_X =                  70;
constexpr uint32_t VFX_IMP_HOLY_AID =                   71;
constexpr uint32_t VFX_IMP_KNOCK =                      72;
constexpr uint32_t VFX_BEAM_LIGHTNING =                 73;
constexpr uint32_t VFX_IMP_LIGHTNING_M =                74;
constexpr uint32_t VFX_IMP_LIGHTNING_S =                75;
constexpr uint32_t VFX_IMP_MAGBLUE =                    76;
constexpr uint32_t VFX_IMP_NEGATIVE_ENERGY =            81;
constexpr uint32_t VFX_DUR_PARALYZE_HOLD =              82;
constexpr uint32_t VFX_IMP_POISON_L =                   83;
constexpr uint32_t VFX_IMP_POISON_S =                   84;
constexpr uint32_t VFX_IMP_POLYMORPH =                  85;
constexpr uint32_t VFX_IMP_PULSE_COLD =                 86;
constexpr uint32_t VFX_IMP_PULSE_FIRE =                 87;
constexpr uint32_t VFX_IMP_PULSE_HOLY =                 88;
constexpr uint32_t VFX_IMP_PULSE_NEGATIVE =             89;
constexpr uint32_t VFX_IMP_RAISE_DEAD =                 90;
constexpr uint32_t VFX_IMP_REDUCE_ABILITY_SCORE =       91;
constexpr uint32_t VFX_IMP_REMOVE_CONDITION =           92;
constexpr uint32_t VFX_IMP_SILENCE =                    93;
constexpr uint32_t VFX_IMP_SLEEP =                      94;
constexpr uint32_t VFX_IMP_SLOW =                       95;
constexpr uint32_t VFX_IMP_SONIC =                      96;
constexpr uint32_t VFX_IMP_STUN =                       97;
constexpr uint32_t VFX_IMP_SUNSTRIKE =                  98;
constexpr uint32_t VFX_IMP_UNSUMMON =                   99;
constexpr uint32_t VFX_COM_SPECIAL_BLUE_RED =           100;
constexpr uint32_t VFX_COM_SPECIAL_PINK_ORANGE =        101;
constexpr uint32_t VFX_COM_SPECIAL_RED_WHITE =          102;
constexpr uint32_t VFX_COM_SPECIAL_RED_ORANGE =         103;
constexpr uint32_t VFX_COM_SPECIAL_WHITE_BLUE =         104;
constexpr uint32_t VFX_COM_SPECIAL_WHITE_ORANGE =       105;
constexpr uint32_t VFX_COM_BLOOD_REG_WIMP =             106;
constexpr uint32_t VFX_COM_BLOOD_LRG_WIMP =             107;
constexpr uint32_t VFX_COM_BLOOD_CRT_WIMP =             108;
constexpr uint32_t VFX_COM_BLOOD_REG_RED =              109;
constexpr uint32_t VFX_COM_BLOOD_REG_GREEN =            110;
constexpr uint32_t VFX_COM_BLOOD_REG_YELLOW =           111;
constexpr uint32_t VFX_COM_BLOOD_LRG_RED =              112;
constexpr uint32_t VFX_COM_BLOOD_LRG_GREEN =            113;
constexpr uint32_t VFX_COM_BLOOD_LRG_YELLOW =           114;
constexpr uint32_t VFX_COM_BLOOD_CRT_RED =              115;
constexpr uint32_t VFX_COM_BLOOD_CRT_GREEN =            116;
constexpr uint32_t VFX_COM_BLOOD_CRT_YELLOW =           117;
constexpr uint32_t VFX_COM_SPARKS_PARRY =               118;
constexpr uint32_t VFX_COM_UNLOAD_MODEL =               120;
constexpr uint32_t VFX_COM_CHUNK_RED_SMALL =            121;
constexpr uint32_t VFX_COM_CHUNK_RED_MEDIUM =           122;
constexpr uint32_t VFX_COM_CHUNK_GREEN_SMALL =          123;
constexpr uint32_t VFX_COM_CHUNK_GREEN_MEDIUM =         124;
constexpr uint32_t VFX_COM_CHUNK_YELLOW_SMALL =         125;
constexpr uint32_t VFX_COM_CHUNK_YELLOW_MEDIUM =        126;
constexpr uint32_t VFX_IMP_LEAF =                       132;
constexpr uint32_t VFX_IMP_CLOUD =                      133;
constexpr uint32_t VFX_IMP_WIND =                       134;
constexpr uint32_t VFX_IMP_ROCKEXPLODE =                135;
constexpr uint32_t VFX_IMP_ROCKEXPLODE2 =               136;
constexpr uint32_t VFX_IMP_SMOKING =                    137;
constexpr uint32_t VFX_DUR_SPELLTURNING =               138;
constexpr uint32_t VFX_IMP_IMPROVE_ABILITY_SCORE =      139;
constexpr uint32_t VFX_IMP_CHARM =                      140;
constexpr uint32_t VFX_IMP_MAGICAL_VISION =             141;
constexpr uint32_t VFX_IMP_EVIL_HELP =                  144;
constexpr uint32_t VFX_IMP_GOOD_HELP =                  145;
constexpr uint32_t VFX_IMP_DEATH_WARD =                 146;
constexpr uint32_t VFX_DUR_ELEMENTAL_SHIELD =           147;
constexpr uint32_t VFX_DUR_LIGHT =                      148;
constexpr uint32_t VFX_IMP_MAGIC_PROTECTION =           149;
constexpr uint32_t VFX_IMP_SUPER_HEROISM =              150;
constexpr uint32_t VFX_FNF_STORM =                      151;
constexpr uint32_t VFX_IMP_ELEMENTAL_PROTECTION =       152;
constexpr uint32_t VFX_DUR_LIGHT_BLUE_5 =               153;
constexpr uint32_t VFX_DUR_LIGHT_BLUE_10 =              154;
constexpr uint32_t VFX_DUR_LIGHT_BLUE_15 =              155;
constexpr uint32_t VFX_DUR_LIGHT_BLUE_20 =              156;
constexpr uint32_t VFX_DUR_LIGHT_YELLOW_5 =             157;
constexpr uint32_t VFX_DUR_LIGHT_YELLOW_10 =            158;
constexpr uint32_t VFX_DUR_LIGHT_YELLOW_15 =            159;
constexpr uint32_t VFX_DUR_LIGHT_YELLOW_20 =            160;
constexpr uint32_t VFX_DUR_LIGHT_PURPLE_5 =             161;
constexpr uint32_t VFX_DUR_LIGHT_PURPLE_10 =            162;
constexpr uint32_t VFX_DUR_LIGHT_PURPLE_15 =            163;
constexpr uint32_t VFX_DUR_LIGHT_PURPLE_20 =            164;
constexpr uint32_t VFX_DUR_LIGHT_RED_5 =                165;
constexpr uint32_t VFX_DUR_LIGHT_RED_10 =               166;
constexpr uint32_t VFX_DUR_LIGHT_RED_15 =               167;
constexpr uint32_t VFX_DUR_LIGHT_RED_20 =               168;
constexpr uint32_t VFX_DUR_LIGHT_ORANGE_5 =             169;
constexpr uint32_t VFX_DUR_LIGHT_ORANGE_10 =            170;
constexpr uint32_t VFX_DUR_LIGHT_ORANGE_15 =            171;
constexpr uint32_t VFX_DUR_LIGHT_ORANGE_20 =            172;
constexpr uint32_t VFX_DUR_LIGHT_WHITE_5 =              173;
constexpr uint32_t VFX_DUR_LIGHT_WHITE_10 =             174;
constexpr uint32_t VFX_DUR_LIGHT_WHITE_15 =             175;
constexpr uint32_t VFX_DUR_LIGHT_WHITE_20 =             176;
constexpr uint32_t VFX_DUR_LIGHT_GREY_5 =               177;
constexpr uint32_t VFX_DUR_LIGHT_GREY_10 =              178;
constexpr uint32_t VFX_DUR_LIGHT_GREY_15 =              179;
constexpr uint32_t VFX_DUR_LIGHT_GREY_20 =              180;
constexpr uint32_t VFX_IMP_MIRV =                       181;
constexpr uint32_t VFX_DUR_DARKVISION =                 182;
constexpr uint32_t VFX_FNF_SOUND_BURST =                183;
constexpr uint32_t VFX_FNF_STRIKE_HOLY =                184;
constexpr uint32_t VFX_FNF_LOS_EVIL_10 =                185;
constexpr uint32_t VFX_FNF_LOS_EVIL_20 =                186;
constexpr uint32_t VFX_FNF_LOS_EVIL_30 =                187;
constexpr uint32_t VFX_FNF_LOS_HOLY_10 =                188;
constexpr uint32_t VFX_FNF_LOS_HOLY_20 =                189;
constexpr uint32_t VFX_FNF_LOS_HOLY_30 =                190;
constexpr uint32_t VFX_FNF_LOS_NORMAL_10 =              191;
constexpr uint32_t VFX_FNF_LOS_NORMAL_20 =              192;
constexpr uint32_t VFX_FNF_LOS_NORMAL_30 =              193;
constexpr uint32_t VFX_IMP_HEAD_ACID =                  194;
constexpr uint32_t VFX_IMP_HEAD_FIRE =                  195;
constexpr uint32_t VFX_IMP_HEAD_SONIC =                 196;
constexpr uint32_t VFX_IMP_HEAD_ELECTRICITY =           197;
constexpr uint32_t VFX_IMP_HEAD_COLD =                  198;
constexpr uint32_t VFX_IMP_HEAD_HOLY =                  199;
constexpr uint32_t VFX_IMP_HEAD_NATURE =                200;
constexpr uint32_t VFX_IMP_HEAD_HEAL =                  201;
constexpr uint32_t VFX_IMP_HEAD_MIND =                  202;
constexpr uint32_t VFX_IMP_HEAD_EVIL =                  203;
constexpr uint32_t VFX_IMP_HEAD_ODD =                   204;
constexpr uint32_t VFX_DUR_CESSATE_NEUTRAL =            205;
constexpr uint32_t VFX_DUR_CESSATE_POSITIVE =           206;
constexpr uint32_t VFX_DUR_CESSATE_NEGATIVE =           207;
constexpr uint32_t VFX_DUR_MIND_AFFECTING_DISABLED =    208;
constexpr uint32_t VFX_DUR_MIND_AFFECTING_DOMINATED =   209;
constexpr uint32_t VFX_BEAM_FIRE =                      210;
constexpr uint32_t VFX_BEAM_COLD =                      211;
constexpr uint32_t VFX_BEAM_HOLY =                      212;
constexpr uint32_t VFX_BEAM_MIND =                      213;
constexpr uint32_t VFX_BEAM_EVIL =                      214;
constexpr uint32_t VFX_BEAM_ODD =                       215;
constexpr uint32_t VFX_BEAM_FIRE_LASH =                 216;
constexpr uint32_t VFX_IMP_DEATH_L =                    217;
constexpr uint32_t VFX_DUR_MIND_AFFECTING_FEAR =        218;
constexpr uint32_t VFX_FNF_SUMMON_CELESTIAL =           219;
constexpr uint32_t VFX_DUR_GLOBE_MINOR =                220;
constexpr uint32_t VFX_IMP_RESTORATION_LESSER =         221;
constexpr uint32_t VFX_IMP_RESTORATION =                222;
constexpr uint32_t VFX_IMP_RESTORATION_GREATER =        223;
constexpr uint32_t VFX_DUR_PROTECTION_ELEMENTS =        224;
constexpr uint32_t VFX_DUR_PROTECTION_GOOD_MINOR =      225;
constexpr uint32_t VFX_DUR_PROTECTION_GOOD_MAJOR =      226;
constexpr uint32_t VFX_DUR_PROTECTION_EVIL_MINOR =      227;
constexpr uint32_t VFX_DUR_PROTECTION_EVIL_MAJOR =      228;
constexpr uint32_t VFX_DUR_MAGICAL_SIGHT =              229;
constexpr uint32_t VFX_DUR_WEB_MASS =                   230;
constexpr uint32_t VFX_FNF_ICESTORM =                   231;
constexpr uint32_t VFX_DUR_PARALYZED =                  232;
constexpr uint32_t VFX_IMP_MIRV_FLAME =                 233;
constexpr uint32_t VFX_IMP_DESTRUCTION =                234;
constexpr uint32_t VFX_COM_CHUNK_RED_LARGE =            235;
constexpr uint32_t VFX_COM_CHUNK_BONE_MEDIUM =          236;
constexpr uint32_t VFX_COM_BLOOD_SPARK_SMALL =          237;
constexpr uint32_t VFX_COM_BLOOD_SPARK_MEDIUM =         238;
constexpr uint32_t VFX_COM_BLOOD_SPARK_LARGE =          239;
constexpr uint32_t VFX_DUR_GHOSTLY_PULSE =              240;
constexpr uint32_t VFX_FNF_HORRID_WILTING =             241;
constexpr uint32_t VFX_DUR_BLINDVISION =                242;
constexpr uint32_t VFX_DUR_LOWLIGHTVISION =             243;
constexpr uint32_t VFX_DUR_ULTRAVISION =                244;
constexpr uint32_t VFX_DUR_MIRV_ACID =                  245;
constexpr uint32_t VFX_IMP_HARM =                       246;
constexpr uint32_t VFX_DUR_BLIND =                      247;
constexpr uint32_t VFX_DUR_ANTI_LIGHT_10 =              248;
constexpr uint32_t VFX_DUR_MAGIC_RESISTANCE =           249;
constexpr uint32_t VFX_IMP_MAGIC_RESISTANCE_USE =       250;
constexpr uint32_t VFX_IMP_GLOBE_USE =                  251;
constexpr uint32_t VFX_IMP_WILL_SAVING_THROW_USE =      252;
constexpr uint32_t VFX_IMP_SPIKE_TRAP =                 253;
constexpr uint32_t VFX_IMP_SPELL_MANTLE_USE =           254;
constexpr uint32_t VFX_IMP_FORTITUDE_SAVING_THROW_USE = 255;
constexpr uint32_t VFX_IMP_REFLEX_SAVE_THROW_USE =      256;
constexpr uint32_t VFX_FNF_GAS_EXPLOSION_ACID =         257;
constexpr uint32_t VFX_FNF_GAS_EXPLOSION_EVIL =         258;
constexpr uint32_t VFX_FNF_GAS_EXPLOSION_NATURE =       259;
constexpr uint32_t VFX_FNF_GAS_EXPLOSION_FIRE =         260;
constexpr uint32_t VFX_FNF_GAS_EXPLOSION_GREASE =       261;
constexpr uint32_t VFX_FNF_GAS_EXPLOSION_MIND =         262;
constexpr uint32_t VFX_FNF_SMOKE_PUFF =                 263;
constexpr uint32_t VFX_IMP_PULSE_WATER =                264;
constexpr uint32_t VFX_IMP_PULSE_WIND =                 265;
constexpr uint32_t VFX_IMP_PULSE_NATURE =               266;
constexpr uint32_t VFX_DUR_AURA_COLD =                  267;
constexpr uint32_t VFX_DUR_AURA_FIRE =                  268;
constexpr uint32_t VFX_DUR_AURA_POISON =                269;
constexpr uint32_t VFX_DUR_AURA_DISEASE =               270;
constexpr uint32_t VFX_DUR_AURA_ODD =                   271;
constexpr uint32_t VFX_DUR_AURA_SILENCE =               272;
constexpr uint32_t VFX_DUR_AURA_HOLY =                  273;
constexpr uint32_t VFX_IMP_AURA_HOLY =                  273;
constexpr uint32_t VFX_DUR_AURA_UNEARTHLY =             274;
constexpr uint32_t VFX_IMP_AURA_UNEARTHLY =             274;
constexpr uint32_t VFX_DUR_AURA_FEAR =                  275;
constexpr uint32_t VFX_IMP_AURA_FEAR =                  275;
constexpr uint32_t VFX_DUR_AURA_NEGATIVE_ENERGY =       276;
constexpr uint32_t VFX_IMP_AURA_NEGATIVE_ENERGY =       276;
constexpr uint32_t VFX_DUR_BARD_SONG =                  277;
constexpr uint32_t VFX_FNF_HOWL_MIND =                  278;
constexpr uint32_t VFX_FNF_HOWL_ODD =                   279;
constexpr uint32_t VFX_COM_HIT_FIRE =                   280;
constexpr uint32_t VFX_COM_HIT_FROST =                  281;
constexpr uint32_t VFX_COM_HIT_ELECTRICAL =             282;
constexpr uint32_t VFX_COM_HIT_ACID =                   283;
constexpr uint32_t VFX_COM_HIT_SONIC =                  284;
constexpr uint32_t VFX_FNF_HOWL_WAR_CRY =               285;
constexpr uint32_t VFX_FNF_SCREEN_SHAKE =               286;
constexpr uint32_t VFX_FNF_SCREEN_BUMP =                287;
constexpr uint32_t VFX_COM_HIT_NEGATIVE =               288;
constexpr uint32_t VFX_COM_HIT_DIVINE =                 289;
constexpr uint32_t VFX_FNF_HOWL_WAR_CRY_FEMALE =        290;
constexpr uint32_t VFX_DUR_AURA_DRAGON_FEAR =           291;
constexpr uint32_t VFX_FNF_SPELL_FAIL_HEAD =            292;
constexpr uint32_t VFX_FNF_SPELL_FAIL_HAND =            293;
constexpr uint32_t VFX_IMP_DESTRUCTION_LOW =            302;
constexpr uint32_t VFX_DUR_FLAG_RED =                   303;
constexpr uint32_t VFX_DUR_FLAG_BLUE =                  304;
constexpr uint32_t VFX_DUR_FLAG_GOLD =                  305;
constexpr uint32_t VFX_DUR_FLAG_PURPLE =                306;
constexpr uint32_t VFX_BEAM_SILENT_LIGHTNING =          307;
constexpr uint32_t VFX_BEAM_SILENT_FIRE =               308;
constexpr uint32_t VFX_BEAM_SILENT_COLD =               309;
constexpr uint32_t VFX_BEAM_SILENT_HOLY =               310;
constexpr uint32_t VFX_BEAM_SILENT_MIND =               311;
constexpr uint32_t VFX_BEAM_SILENT_EVIL =               312;
constexpr uint32_t VFX_BEAM_SILENT_ODD =                313;
constexpr uint32_t VFX_DUR_BIGBYS_INTERPOSING_HAND =    314;
constexpr uint32_t VFX_IMP_BIGBYS_FORCEFUL_HAND =       315;
constexpr uint32_t VFX_DUR_BIGBYS_CLENCHED_FIST =       316;
constexpr uint32_t VFX_DUR_BIGBYS_CRUSHING_HAND =       317;
constexpr uint32_t VFX_DUR_BIGBYS_GRASPING_HAND =       318;
constexpr uint32_t VFX_DUR_CALTROPS =                   319;
constexpr uint32_t VFX_DUR_SMOKE =                      320;
constexpr uint32_t VFX_DUR_PIXIEDUST =                  321;
constexpr uint32_t VFX_FNF_DECK =                       322;
constexpr uint32_t VFX_DUR_TENTACLE =                   346;
constexpr uint32_t VFX_DUR_PETRIFY =                    351;
constexpr uint32_t VFX_DUR_FREEZE_ANIMATION =           352;
constexpr uint32_t VFX_COM_CHUNK_STONE_SMALL =          353;
constexpr uint32_t VFX_COM_CHUNK_STONE_MEDIUM =         354;
constexpr uint32_t VFX_DUR_CUTSCENE_INVISIBILITY =      355;
constexpr uint32_t VFX_FNF_SCREEN_SHAKE2 =              356;
constexpr uint32_t VFX_IMP_MIRV_ARROW =                 357;
constexpr uint32_t VFX_IMP_MIRV_DART =                  359;
constexpr uint32_t VFX_DUR_IOUNSTONE =                  403;
constexpr uint32_t VFX_IMP_TORNADO =                    407;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_BLUE =            408;
constexpr uint32_t VFX_DUR_GLOW_PURPLE =                409;
constexpr uint32_t VFX_DUR_GLOW_BLUE =                  410;
constexpr uint32_t VFX_DUR_GLOW_RED =                   411;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_RED =             412;
constexpr uint32_t VFX_DUR_GLOW_YELLOW =                413;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_YELLOW =          414;
constexpr uint32_t VFX_DUR_GLOW_GREEN =                 415;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_GREEN =           416;
constexpr uint32_t VFX_DUR_GLOW_ORANGE =                417;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_ORANGE =          418;
constexpr uint32_t VFX_DUR_GLOW_BROWN =                 419;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_BROWN =           420;
constexpr uint32_t VFX_DUR_GLOW_GREY =                  421;
constexpr uint32_t VFX_DUR_GLOW_WHITE =                 422;
constexpr uint32_t VFX_DUR_GLOW_LIGHT_PURPLE =          423;
constexpr uint32_t VFX_DUR_GHOST_TRANSPARENT =          424;
constexpr uint32_t VFX_DUR_GHOST_SMOKE =                425;
constexpr uint32_t VFX_BEAM_FLAME =                     444;
constexpr uint32_t VFX_DUR_GLYPH_OF_WARDING =           445;
constexpr uint32_t VFX_FNF_SOUND_BURST_SILENT =         446;
constexpr uint32_t VFX_BEAM_DISINTEGRATE =              447;
constexpr uint32_t VFX_DUR_ACID_SHEATH =                448;
constexpr uint32_t VFX_FNF_ELECTRIC_EXPLOSION =         459;
constexpr uint32_t VFX_IMP_DUST_EXPLOSION =             460;
constexpr uint32_t VFX_IMP_PULSE_HOLY_SILENT =          461;
constexpr uint32_t VFX_DUR_DEATH_ARMOR =                463;
constexpr uint32_t VFX_FNF_HELLBALL =                   464;
constexpr uint32_t VFX_DUR_ICESKIN =                    465;
constexpr uint32_t VFX_CONJ_MIND =                      466;
constexpr uint32_t VFX_CONJ_FIRE =                      467;
constexpr uint32_t VFX_DUR_BARD_SONG_SILENT =           468;
constexpr uint32_t VFX_IMP_PULSE_BOMB =                 469;
constexpr uint32_t VFX_FNF_SWINGING_BLADE =             473;
constexpr uint32_t VFX_DUR_INFERNO =                    474;
constexpr uint32_t VFX_FNF_DEMON_HAND =                 475;
constexpr uint32_t VFX_DUR_STONEHOLD =                  476;
constexpr uint32_t VFX_FNF_MYSTICAL_EXPLOSION =         477;
constexpr uint32_t VFX_DUR_GHOSTLY_VISAGE_NO_SOUND =    478;
constexpr uint32_t VFX_DUR_GHOST_SMOKE_2 =              479;
constexpr uint32_t VFX_DUR_FLIES =                      480;
constexpr uint32_t VFX_FNF_SUMMONDRAGON =               481;
constexpr uint32_t VFX_BEAM_FIRE_W =                    482;
constexpr uint32_t VFX_BEAM_FIRE_W_SILENT =             483;
constexpr uint32_t VFX_BEAM_CHAIN =                     484;
constexpr uint32_t VFX_BEAM_BLACK =                     485;
constexpr uint32_t VFX_IMP_WALLSPIKE =                  486;
constexpr uint32_t VFX_FNF_GREATER_RUIN =               487;
constexpr uint32_t VFX_FNF_UNDEAD_DRAGON =              488;
constexpr uint32_t VFX_DUR_CONECOLD_HEAD =              490;
constexpr uint32_t VFX_COM_BLOOD_CRT_RED_HEAD =         491;
constexpr uint32_t VFX_COM_BLOOD_CRT_GREEN_HEAD =       492;
constexpr uint32_t VFX_COM_BLOOD_CRT_YELLOW_HEAD =      493;
constexpr uint32_t VFX_FNF_DRAGBREATHGROUND =           494;
constexpr uint32_t VFX_DUR_PROT_EPIC_ARMOR =            495;
constexpr uint32_t VFX_FNF_SUMMON_EPIC_UNDEAD =         496;
constexpr uint32_t VFX_DUR_PROT_EPIC_ARMOR_2 =          497;
constexpr uint32_t VFX_DUR_INFERNO_CHEST =              498;
constexpr uint32_t VFX_DUR_IOUNSTONE_RED =              499;
constexpr uint32_t VFX_DUR_IOUNSTONE_BLUE =             500;
constexpr uint32_t VFX_DUR_IOUNSTONE_YELLOW =           501;
constexpr uint32_t VFX_DUR_IOUNSTONE_GREEN =            502;
constexpr uint32_t VFX_IMP_MIRV_ELECTRIC =              503;
constexpr uint32_t VFX_COM_CHUNK_RED_BALLISTA =         504;
constexpr uint32_t VFX_DUR_INFERNO_NO_SOUND =           505;
constexpr uint32_t VFX_DUR_BARD_SONG_EVIL =             507;
constexpr uint32_t VFX_DUR_AURA_PULSE_RED_WHITE =       512;
constexpr uint32_t VFX_DUR_AURA_PULSE_BLUE_WHITE =      513;
constexpr uint32_t VFX_DUR_AURA_PULSE_GREEN_WHITE =     514;
constexpr uint32_t VFX_DUR_AURA_PULSE_YELLOW_WHITE =    515;
constexpr uint32_t VFX_DUR_AURA_PULSE_MAGENTA_WHITE =   516;
constexpr uint32_t VFX_DUR_AURA_PULSE_CYAN_WHITE =      517;
constexpr uint32_t VFX_DUR_AURA_PULSE_ORANGE_WHITE =    518;
constexpr uint32_t VFX_DUR_AURA_PULSE_BROWN_WHITE =     519;
constexpr uint32_t VFX_DUR_AURA_PULSE_PURPLE_WHITE =    520;
constexpr uint32_t VFX_DUR_AURA_PULSE_GREY_WHITE =      521;
constexpr uint32_t VFX_DUR_AURA_PULSE_GREY_BLACK =      522;
constexpr uint32_t VFX_DUR_AURA_PULSE_BLUE_GREEN =      523;
constexpr uint32_t VFX_DUR_AURA_PULSE_RED_BLUE =        524;
constexpr uint32_t VFX_DUR_AURA_PULSE_RED_YELLOW =      525;
constexpr uint32_t VFX_DUR_AURA_PULSE_GREEN_YELLOW =    526;
constexpr uint32_t VFX_DUR_AURA_PULSE_RED_GREEN =       527;
constexpr uint32_t VFX_DUR_AURA_PULSE_BLUE_YELLOW =     528;
constexpr uint32_t VFX_DUR_AURA_PULSE_BLUE_BLACK =      529;
constexpr uint32_t VFX_DUR_AURA_PULSE_RED_BLACK =       530;
constexpr uint32_t VFX_DUR_AURA_PULSE_GREEN_BLACK =     531;
constexpr uint32_t VFX_DUR_AURA_PULSE_YELLOW_BLACK =    532;
constexpr uint32_t VFX_DUR_AURA_PULSE_MAGENTA_BLACK =   533;
constexpr uint32_t VFX_DUR_AURA_PULSE_CYAN_BLACK =      534;
constexpr uint32_t VFX_DUR_AURA_PULSE_ORANGE_BLACK =    535;
constexpr uint32_t VFX_DUR_AURA_PULSE_BROWN_BLACK =     536;
constexpr uint32_t VFX_DUR_AURA_PULSE_PURPLE_BLACK =    537;
constexpr uint32_t VFX_DUR_AURA_PULSE_CYAN_GREEN =      538;
constexpr uint32_t VFX_DUR_AURA_PULSE_CYAN_BLUE =       539;
constexpr uint32_t VFX_DUR_AURA_PULSE_CYAN_RED =        540;
constexpr uint32_t VFX_DUR_AURA_PULSE_CYAN_YELLOW =     541;
constexpr uint32_t VFX_DUR_AURA_PULSE_MAGENTA_BLUE =    542;
constexpr uint32_t VFX_DUR_AURA_PULSE_MAGENTA_RED =     543;
constexpr uint32_t VFX_DUR_AURA_PULSE_MAGENTA_GREEN =   544;
constexpr uint32_t VFX_DUR_AURA_PULSE_MAGENTA_YELLOW =  545;
constexpr uint32_t VFX_DUR_AURA_PULSE_RED_ORANGE =      546;
constexpr uint32_t VFX_DUR_AURA_PULSE_YELLOW_ORANGE =   547;
constexpr uint32_t VFX_DUR_AURA_RED =                   548;
constexpr uint32_t VFX_DUR_AURA_GREEN =                 549;
constexpr uint32_t VFX_DUR_AURA_BLUE =                  550;
constexpr uint32_t VFX_DUR_AURA_MAGENTA =               551;
constexpr uint32_t VFX_DUR_AURA_YELLOW =                552;
constexpr uint32_t VFX_DUR_AURA_WHITE =                 553;
constexpr uint32_t VFX_DUR_AURA_ORANGE =                554;
constexpr uint32_t VFX_DUR_AURA_BROWN =                 555;
constexpr uint32_t VFX_DUR_AURA_PURPLE =                556;
constexpr uint32_t VFX_DUR_AURA_CYAN =                  557;
constexpr uint32_t VFX_DUR_AURA_GREEN_DARK =            558;
constexpr uint32_t VFX_DUR_AURA_GREEN_LIGHT =           559;
constexpr uint32_t VFX_DUR_AURA_RED_DARK =              560;
constexpr uint32_t VFX_DUR_AURA_RED_LIGHT =             561;
constexpr uint32_t VFX_DUR_AURA_BLUE_DARK =             562;
constexpr uint32_t VFX_DUR_AURA_BLUE_LIGHT =            563;
constexpr uint32_t VFX_DUR_AURA_YELLOW_DARK =           564;
constexpr uint32_t VFX_DUR_AURA_YELLOW_LIGHT =          565;
constexpr uint32_t VFX_DUR_BUBBLES =                    566;
constexpr uint32_t VFX_EYES_GREEN_HUMAN_MALE =          567;
constexpr uint32_t VFX_EYES_GREEN_HUMAN_FEMALE =        568;
constexpr uint32_t VFX_EYES_GREEN_DWARF_MALE =          569;
constexpr uint32_t VFX_EYES_GREEN_DWARF_FEMALE =        570;
constexpr uint32_t VFX_EYES_GREEN_ELF_MALE =            571;
constexpr uint32_t VFX_EYES_GREEN_ELF_FEMALE =          572;
constexpr uint32_t VFX_EYES_GREEN_GNOME_MALE =          573;
constexpr uint32_t VFX_EYES_GREEN_GNOME_FEMALE =        574;
constexpr uint32_t VFX_EYES_GREEN_HALFLING_MALE =       575;
constexpr uint32_t VFX_EYES_GREEN_HALFLING_FEMALE =     576;
constexpr uint32_t VFX_EYES_GREEN_HALFORC_MALE =        577;
constexpr uint32_t VFX_EYES_GREEN_HALFORC_FEMALE =      578;
constexpr uint32_t VFX_EYES_GREEN_TROGLODYTE =          579;

}

}

}
