#include "nwnx"

// Gets if feedback message nMessage is hidden.
// Notes:
// If oPC == OBJECT_INVALID it will return the global state:
//    TRUE      nMessage is globally hidden
//    FALSE     nMEssage is not globally hidden
// If oPC is a valid player it will return the personal state:
//    TRUE      nMessage is hidden for oPC
//    FALSE     nMessage is not hidden for oPC
//    -1        Personal state is not set
int NWNX_Feedback_GetMessageHidden(int nMessage, object oPC = OBJECT_INVALID);
// Sets if feedback message nMessage is hidden.
// Notes:
// If oPC == OBJECT_INVALID it will set the global state:
//    TRUE      nMessage is globally hidden
//    FALSE     nMEssage is not globally hidden
// If oPC is a valid player it will set the personal state:
//    TRUE      nMessage is hidden for oPC
//    FALSE     nMessage is not hidden for oPC
//    -1        Remove the personal state
//
// Personal state overrides the global state which means if a global state is set
// to TRUE but the personal state is set to FALSE, the message will be shown to oPC
void NWNX_Feedback_SetMessageHidden(int nMessage, int bHidden, object oPC = OBJECT_INVALID);

// ***
// For a list of the various feedback messages see below.
// ***

const string NWNX_Feedback = "NWNX_Feedback";


int NWNX_Feedback_GetMessageHidden(int nMessage, object oPC = OBJECT_INVALID)
{
    string sFunc = "GetMessageHidden";

    NWNX_PushArgumentInt(NWNX_Feedback, sFunc, nMessage);
    NWNX_PushArgumentObject(NWNX_Feedback, sFunc, oPC);
    NWNX_CallFunction(NWNX_Feedback, sFunc);

    return NWNX_GetReturnValueInt(NWNX_Feedback, sFunc);
}

void NWNX_Feedback_SetMessageHidden(int nMessage, int nHide, object oPC = OBJECT_INVALID)
{
    string sFunc = "SetMessageHidden";

    NWNX_PushArgumentInt(NWNX_Feedback, sFunc, nHide);
    NWNX_PushArgumentInt(NWNX_Feedback, sFunc, nMessage);
    NWNX_PushArgumentObject(NWNX_Feedback, sFunc, oPC);
    NWNX_CallFunction(NWNX_Feedback, sFunc);
}

/* Feedback Messages
// Skill Feedback Messages
FEEDBACK_SKILL_CANT_USE                         0
FEEDBACK_SKILL_CANT_USE_TIMER                   1
FEEDBACK_SKILL_ANIMALEMPATHY_VALID_TARGETS      2
FEEDBACK_SKILL_TAUNT_VALID_TARGETS              3
FEEDBACK_SKILL_TAUNT_TARGET_IMMUNE              223
FEEDBACK_SKILL_PICKPOCKET_STOLE_ITEM            4
FEEDBACK_SKILL_PICKPOCKET_STOLE_GOLD            5
FEEDBACK_SKILL_PICKPOCKET_ATTEMPTING_TO_STEAL   46
FEEDBACK_SKILL_PICKPOCKET_ATTEMPT_DETECTED      150
FEEDBACK_SKILL_PICKPOCKET_STOLE_ITEM_TARGET     47
FEEDBACK_SKILL_PICKPOCKET_STOLE_GOLD_TARGET     48
FEEDBACK_SKILL_PICKPOCKET_TARGET_BROKE          57
FEEDBACK_SKILL_HEAL_TARGET_NOT_DISPSND          55
FEEDBACK_SKILL_HEAL_VALID_TARGETS               56
FEEDBACK_SKILL_STEALTH_IN_COMBAT                60

// Miscellaneous Targetting Messages
FEEDBACK_TARGET_UNAWARE                     6
FEEDBACK_ACTION_NOT_POSSIBLE_STATUS         7
FEEDBACK_ACTION_NOT_POSSIBLE_PVP            187
FEEDBACK_ACTION_CANT_REACH_TARGET           218
FEEDBACK_ACTION_NO_LOOT                     247

// Miscellaneous Feedback Messages
FEEDBACK_WEIGHT_TOO_ENCUMBERED_TO_RUN       8
FEEDBACK_WEIGHT_TOO_ENCUMBERED_WALK_SLOW    9
FEEDBACK_WEIGHT_TOO_ENCUMBERED_CANT_PICKUP  10
FEEDBACK_STATS_LEVELUP                      11
FEEDBACK_INVENTORY_FULL                     12
FEEDBACK_CONTAINER_FULL                     212
FEEDBACK_TRAP_TRIGGERED                     82
FEEDBACK_DAMAGE_HEALED                      151
FEEDBACK_EXPERIENCE_GAINNED                 182
FEEDBACK_EXPERIENCE_LOST                    183
FEEDBACK_JOURNALUPDATED                     184
FEEDBACK_BARTER_CANCELLED                   185

// Mode activation/deactivation Messages
FEEDBACK_DETECT_MODE_ACTIVATED              83
FEEDBACK_DETECT_MODE_DEACTIVATED            84
FEEDBACK_STEALTH_MODE_ACTIVATED             85
FEEDBACK_STEALTH_MODE_DEACTIVATED           86
FEEDBACK_PARRY_MODE_ACTIVATED               87
FEEDBACK_PARRY_MODE_DEACTIVATED             88
FEEDBACK_POWER_ATTACK_MODE_ACTIVATED        89
FEEDBACK_POWER_ATTACK_MODE_DEACTIVATED      90
FEEDBACK_IMPROVED_POWER_ATTACK_MODE_ACTIVATED 91
FEEDBACK_IMPROVED_POWER_ATTACK_MODE_DEACTIVATED 92
FEEDBACK_RAPID_SHOT_MODE_ACTIVATED          166
FEEDBACK_RAPID_SHOT_MODE_DEACTIVATED        167
FEEDBACK_FLURRY_OF_BLOWS_MODE_ACTIVATED     168
FEEDBACK_FLURRY_OF_BLOWS_MODE_DEACTIVATED   169
FEEDBACK_EXPERTISE_MODE_ACTIVATED           227
FEEDBACK_EXPERTISE_MODE_DEACTIVATED         228
FEEDBACK_IMPROVED_EXPERTISE_MODE_ACTIVATED  229
FEEDBACK_IMPROVED_EXPERTISE_MODE_DEACTIVATED 230
FEEDBACK_DEFENSIVE_CAST_MODE_ACTIVATED      231
FEEDBACK_DEFENSIVE_CAST_MODE_DEACTIVATED    232
FEEDBACK_MODE_CANNOT_USE_WEAPONS            188
FEEDBACK_DIRTY_FIGHTING_MODE_ACTIVATED      237
FEEDBACK_DIRTY_FIGHTING_MODE_DEACTIVATED    238

FEEDBACK_DEFENSIVE_STANCE_MODE_ACTIVATED      252
FEEDBACK_DEFENSIVE_STANCE_MODE_DEACTIVATED    253

// Equipping Feedback Messages
FEEDBACK_EQUIP_SKILL_SPELL_MODIFIERS        71
FEEDBACK_EQUIP_UNIDENTIFIED                 76
FEEDBACK_EQUIP_MONK_ABILITIES               77
FEEDBACK_EQUIP_INSUFFICIENT_LEVEL           98
FEEDBACK_EQUIP_PROFICIENCIES                119
FEEDBACK_EQUIP_WEAPON_TOO_LARGE             120
FEEDBACK_EQUIP_WEAPON_TOO_SMALL             260
FEEDBACK_EQUIP_ONE_HANDED_WEAPON            121
FEEDBACK_EQUIP_TWO_HANDED_WEAPON            122
FEEDBACK_EQUIP_WEAPON_SWAPPED_OUT           123
FEEDBACK_EQUIP_ONE_CHAIN_WEAPON             124
FEEDBACK_EQUIP_NATURAL_AC_NO_STACK          189
FEEDBACK_EQUIP_ARMOUR_AC_NO_STACK           190
FEEDBACK_EQUIP_SHIELD_AC_NO_STACK           191
FEEDBACK_EQUIP_DEFLECTION_AC_NO_STACK       192
FEEDBACK_EQUIP_NO_ARMOR_COMBAT              193
FEEDBACK_EQUIP_RANGER_ABILITIES             200
FEEDBACK_EQUIP_ALIGNMENT                    207
FEEDBACK_EQUIP_CLASS                        208
FEEDBACK_EQUIP_RACE                         209
FEEDBACK_UNEQUIP_NO_ARMOR_COMBAT            194

// Action Feedback Messages
FEEDBACK_OBJECT_LOCKED                      13
FEEDBACK_OBJECT_NOT_LOCKED                  14
FEEDBACK_OBJECT_SPECIAL_KEY                 15
FEEDBACK_OBJECT_USED_KEY                    16
FEEDBACK_REST_EXCITED_CANT_REST             17
FEEDBACK_REST_BEGINNING_REST                18
FEEDBACK_REST_FINISHED_REST                 19
FEEDBACK_REST_CANCEL_REST                   20
FEEDBACK_REST_NOT_ALLOWED_IN_AREA           54
FEEDBACK_REST_NOT_ALLOWED_BY_POSSESSED_FAMILIAR 153
FEEDBACK_REST_NOT_ALLOWED_ENEMIES           186
FEEDBACK_REST_CANT_UNDER_THIS_EFFECT        213
FEEDBACK_CAST_LOST_TARGET                   21
FEEDBACK_CAST_CANT_CAST                     22
FEEDBACK_CAST_CNTRSPELL_TARGET_LOST_TARGET  52
FEEDBACK_CAST_ARCANE_SPELL_FAILURE          61
FEEDBACK_CAST_CNTRSPELL_TARGET_ARCANE_SPELL_FAILURE 118
FEEDBACK_CAST_ENTANGLE_CONCENTRATION_FAILURE 65
FEEDBACK_CAST_CNTRSPELL_TARGET_ENTANGLE_CONCENTRATION_FAILURE 147
FEEDBACK_CAST_SPELL_INTERRUPTED             72
FEEDBACK_CAST_EFFECT_SPELL_FAILURE          236
FEEDBACK_CAST_CANT_CAST_WHILE_POLYMORPHED   107
FEEDBACK_CAST_USE_HANDS                     210
FEEDBACK_CAST_USE_MOUTH                     211
FEEDBACK_CAST_DEFCAST_CONCENTRATION_FAILURE 233
FEEDBACK_CAST_DEFCAST_CONCENTRATION_SUCCESS 240
FEEDBACK_USEITEM_CANT_USE                   23
FEEDBACK_CONVERSATION_TOOFAR                58
FEEDBACK_CONVERSATION_BUSY                  59
FEEDBACK_CONVERSATION_IN_COMBAT             152
FEEDBACK_CHARACTER_INTRANSIT                74
FEEDBACK_CHARACTER_OUTTRANSIT               75
FEEDBACK_USEITEM_NOT_EQUIPPED               244
FEEDBACK_DROPITEM_CANT_DROP                 245
FEEDBACK_DROPITEM_CANT_GIVE                 246
FEEDBACK_CLIENT_SERVER_SPELL_MISMATCH       259

// Combat feedback messages
FEEDBACK_COMBAT_RUNNING_OUT_OF_AMMO         24
FEEDBACK_COMBAT_OUT_OF_AMMO                 25
FEEDBACK_COMBAT_HENCHMAN_OUT_OF_AMMO        241
FEEDBACK_COMBAT_DAMAGE_IMMUNITY             62
FEEDBACK_COMBAT_SPELL_IMMUNITY              68
FEEDBACK_COMBAT_DAMAGE_RESISTANCE           63
FEEDBACK_COMBAT_DAMAGE_RESISTANCE_REMAINING 66
FEEDBACK_COMBAT_DAMAGE_REDUCTION            64
FEEDBACK_COMBAT_DAMAGE_REDUCTION_REMAINING  67
FEEDBACK_COMBAT_SPELL_LEVEL_ABSORPTION      69
FEEDBACK_COMBAT_SPELL_LEVEL_ABSORPTION_REMAINING 70
FEEDBACK_COMBAT_WEAPON_NOT_EFFECTIVE        117
FEEDBACK_COMBAT_EPIC_DODGE_ATTACK_EVADED    234
FEEDBACK_COMBAT_MASSIVE_DAMAGE              235
FEEDBACK_COMBAT_SAVED_VS_MASSIVE_DAMAGE     254
FEEDBACK_COMBAT_SAVED_VS_DEVASTATING_CRITICAL 257

// Feat Feedback Messages
FEEDBACK_FEAT_SAP_VALID_TARGETS             26
FEEDBACK_FEAT_KNOCKDOWN_VALID_TARGETS       27
FEEDBACK_FEAT_IMPKNOCKDOWN_VALID_TARGETS    28
FEEDBACK_FEAT_CALLED_SHOT_NO_LEGS           29
FEEDBACK_FEAT_CALLED_SHOT_NO_ARMS           30
FEEDBACK_FEAT_SMITE_GOOD_TARGET_NOT_GOOD    239
FEEDBACK_FEAT_SMITE_EVIL_TARGET_NOT_EVIL    53
FEEDBACK_FEAT_QUIVERING_PALM_HIGHER_LEVEL   73
FEEDBACK_FEAT_KEEN_SENSE_DETECT             195
FEEDBACK_FEAT_USE_UNARMED                   198
FEEDBACK_FEAT_USES                          199
FEEDBACK_FEAT_USE_WEAPON_OF_CHOICE          243

// Party Feedback Messages
FEEDBACK_PARTY_NEW_LEADER                   31
FEEDBACK_PARTY_MEMBER_KICKED                32
FEEDBACK_PARTY_KICKED_YOU                   33
FEEDBACK_PARTY_ALREADY_CONSIDERING          34
FEEDBACK_PARTY_ALREADY_INVOLVED             35
FEEDBACK_PARTY_SENT_INVITATION              36
FEEDBACK_PARTY_RECEIVED_INVITATION          37
FEEDBACK_PARTY_JOINED                       38
FEEDBACK_PARTY_INVITATION_IGNORED           39
FEEDBACK_PARTY_YOU_IGNORED_INVITATION       40
FEEDBACK_PARTY_INVITATION_REJECTED          41
FEEDBACK_PARTY_YOU_REJECTED_INVITATION      42
FEEDBACK_PARTY_INVITATION_EXPIRED           43
FEEDBACK_PARTY_LEFT_PARTY                   44
FEEDBACK_PARTY_YOU_LEFT                     45
FEEDBACK_PARTY_HENCHMAN_LIMIT               49
FEEDBACK_PARTY_CANNOT_LEAVE_THE_ONE_PARTY   196
FEEDBACK_PARTY_CANNOT_KICK_FROM_THE_ONE_PARTY 197
FEEDBACK_PARTY_YOU_INVITED_NON_SINGLETON    202
FEEDBACK_PVP_REACTION_DISLIKESYOU           203

// Item Feedback Messages
FEEDBACK_ITEM_RECEIVED                      50
FEEDBACK_ITEM_LOST                          51
FEEDBACK_ITEM_EJECTED                       96
FEEDBACK_ITEM_USE_UNIDENTIFIED              97
FEEDBACK_ITEM_GOLD_GAINED                   148
FEEDBACK_ITEM_GOLD_LOST                     149

// Spell Scroll Learning
FEEDBACK_LEARN_SCROLL_NOT_SCROLL            78
FEEDBACK_LEARN_SCROLL_CANT_LEARN_CLASS      79
FEEDBACK_LEARN_SCROLL_CANT_LEARN_LEVEL      80
FEEDBACK_LEARN_SCROLL_CANT_LEARN_ABILITY    81
FEEDBACK_LEARN_SCROLL_CANT_LEARN_OPPOSITION 219
FEEDBACK_LEARN_SCROLL_CANT_LEARN_POSSESS    220
FEEDBACK_LEARN_SCROLL_CANT_LEARN_KNOWN      221
FEEDBACK_LEARN_SCROLL_CANT_LEARN_DIVINE     224
FEEDBACK_LEARN_SCROLL_SUCCESS               222

// Floaty text feedback
FEEDBACK_FLOATY_TEXT_STRREF                 93
FEEDBACK_FLOATY_TEXT_STRING                 94

// store feedback
FEEDBACK_CANNOT_SELL_PLOT_ITEM              99
FEEDBACK_CANNOT_SELL_CONTAINER              100
FEEDBACK_CANNOT_SELL_ITEM                   101
FEEDBACK_NOT_ENOUGH_GOLD                    102
FEEDBACK_TRANSACTION_SUCCEEDED              103
FEEDBACK_PRICE_TOO_HIGH                     248
FEEDBACK_STORE_NOT_ENOUGH_GOLD              249
FEEDBACK_CANNOT_SELL_STOLEN_ITEM            250
FEEDBACK_CANNOT_SELL_RESTRICTED_ITEM        251

// Portal control feedback
FEEDBACK_PORTAL_TIMEDOUT                    104
FEEDBACK_PORTAL_INVALID                     105

// Chat feedback
FEEDBACK_CHAT_TELL_PLAYER_NOT_FOUND         106

// Alignment Feedback
FEEDBACK_ALIGNMENT_SHIFT                    108
FEEDBACK_ALIGNMENT_PARTY_SHIFT              111
FEEDBACK_ALIGNMENT_CHANGE                   109
FEEDBACK_ALIGNMENT_RESTRICTED_BY_CLASS_LOST 110
FEEDBACK_ALIGNMENT_RESTRICTED_BY_CLASS_GAIN 115
FEEDBACK_ALIGNMENT_RESTRICTED_WARNING_LOSS  116
FEEDBACK_ALIGNMENT_RESTRICTED_WARNING_GAIN  112
FEEDBACK_ALIGNMENT_EPITOME_GAINED           113
FEEDBACK_ALIGNMENT_EPITOME_LOST             114

// Immunity Feedback
FEEDBACK_IMMUNITY_DISEASE                   125
FEEDBACK_IMMUNITY_CRITICAL_HIT              126
FEEDBACK_IMMUNITY_DEATH_MAGIC               127
FEEDBACK_IMMUNITY_FEAR                      128
FEEDBACK_IMMUNITY_KNOCKDOWN                 129
FEEDBACK_IMMUNITY_PARALYSIS                 130
FEEDBACK_IMMUNITY_NEGATIVE_LEVEL            131
FEEDBACK_IMMUNITY_MIND_SPELLS               132
FEEDBACK_IMMUNITY_POISON                    133
FEEDBACK_IMMUNITY_SNEAK_ATTACK              134
FEEDBACK_IMMUNITY_SLEEP                     135
FEEDBACK_IMMUNITY_DAZE                      136
FEEDBACK_IMMUNITY_CONFUSION                 137
FEEDBACK_IMMUNITY_STUN                      138
FEEDBACK_IMMUNITY_BLINDNESS                 139
FEEDBACK_IMMUNITY_DEAFNESS                  140
FEEDBACK_IMMUNITY_CURSE                     141
FEEDBACK_IMMUNITY_CHARM                     142
FEEDBACK_IMMUNITY_DOMINATE                  143
FEEDBACK_IMMUNITY_ENTANGLE                  144
FEEDBACK_IMMUNITY_SILENCE                   145
FEEDBACK_IMMUNITY_SLOW                      146

// Associates
FEEDBACK_ASSOCIATE_SUMMONED                 154
FEEDBACK_ASSOCIATE_UNSUMMONING              155
FEEDBACK_ASSOCIATE_UNSUMMONING_BECAUSE_REST 156
FEEDBACK_ASSOCIATE_UNSUMMONING_BECAUSE_DIED 157
FEEDBACK_ASSOCIATE_DOMINATED                158
FEEDBACK_ASSOCIATE_DOMINATION_ENDED         159
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_RECOVER_TRAP 170
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_BARTER  171
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_EQUIP   172
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_REPOSITORY_MOVE 173
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_PICK_UP 174
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_DROP    175
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_UNEQUIP 176
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_REST    177
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_DIALOGUE 178
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_GIVE_ITEM 179
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_TAKE_ITEM 180
FEEDBACK_ASSOCIATE_POSSESSED_CANNOT_USE_CONTAINER 181

FEEDBACK_SCRIPT_ERROR                       160
FEEDBACK_ACTION_LIST_OVERFLOW               161
FEEDBACK_EFFECT_LIST_OVERFLOW               162
FEEDBACK_AI_UPDATE_TIME_OVERFLOW            163
FEEDBACK_ACTION_LIST_WIPE_OVERFLOW          164
FEEDBACK_EFFECT_LIST_WIPE_OVERFLOW          165
FEEDBACK_SEND_MESSAGE_TO_PC                 204
FEEDBACK_SEND_MESSAGE_TO_PC_STRREF          242

// Misc GUI feedback
FEEDBACK_GUI_ONLY_PARTY_LEADER_MAY_CLICK    201
FEEDBACK_PAUSED                             205
FEEDBACK_UNPAUSED                           206
FEEDBACK_REST_YOU_MAY_NOT_AT_THIS_TIME      214
FEEDBACK_GUI_CHAR_EXPORT_REQUEST_SENT       215
FEEDBACK_GUI_CHAR_EXPORTED_SUCCESSFULLY     216
FEEDBACK_GUI_ERROR_CHAR_NOT_EXPORTED        217
FEEDBACK_CAMERA_BG                          255
FEEDBACK_CAMERA_EQ                          256
FEEDBACK_CAMERA_CHASECAM                    258

FEEDBACK_SAVING                             225
FEEDBACK_SAVE_COMPLETE                      226
*/
