#include <iostream>
#include <string>
#include <vector>
#include "NWNXLib/External/json/json.hpp"

extern "C" {
    #include "quickjs.h"
}

// Generated by xxd in test.sh
#include "ajv_bundle_data.h" 

using json = nlohmann::json;
static JSRuntime *rt = nullptr;
static JSContext *ctx = nullptr;

// --- Helper: Convert QuickJS Result to JSON ---
static json JSValueToJSON(JSValue val) {
    JSValue jsonStrVal = JS_JSONStringify(ctx, val, JS_UNDEFINED, JS_UNDEFINED);
    const char* cStr = JS_ToCString(ctx, jsonStrVal);
    json result = json::parse(cStr ? cStr : "{\"error\": \"Engine Error\"}");
    JS_FreeCString(ctx, cStr);
    JS_FreeValue(ctx, jsonStrVal);
    return result;
}

// --- Helper: Run JS snippet and return JSON result ---
json RunJsAction(const std::string& script) {
    JSValue resVal = JS_Eval(ctx, script.c_str(), script.length(), "<test>", JS_EVAL_TYPE_GLOBAL);
    json res = JSValueToJSON(resVal);
    JS_FreeValue(ctx, resVal);
    return res;
}

void PrintHeader(const std::string& title) {
    std::cout << "\n=== " << title << " ===" << std::endl;
}

int main() {
    // 1. LIFECYCLE: Load Plugin
    rt = JS_NewRuntime();
    ctx = JS_NewContext(rt);
    
    // Bootstrap: Shield console and init manual cache
    const char* boot = "globalThis.console = { log:()=>{}, warn:()=>{}, error:()=>{} }; globalThis.compiledSchemas = {};";
    JS_Eval(ctx, boot, strlen(boot), "<init>", JS_EVAL_TYPE_GLOBAL);

    // Load AJV Bundle (Primed with ajv-formats and better-ajv-errors)
    JS_Eval(ctx, (const char*)ajv_runtime_min_js, ajv_runtime_min_js_len, "ajv_runtime.js", JS_EVAL_TYPE_GLOBAL);

    JSValue global = JS_GetGlobalObject(ctx);
    std::cout << "--- NWNX SCHEMA FULL TEST SUITE 2026 ---" << std::endl;

    // 2. TEST: ValidateSchema
    PrintHeader("ValidateSchema");
    json schemaA = { {"type", "object"}, {"properties", {{"id", {{"type", "integer"}}}}} };
    JS_SetPropertyStr(ctx, global, "schema", JS_NewString(ctx, schemaA.dump().c_str()));
    std::cout << "[PASS] Valid Meta-Schema: " << RunJsAction("globalThis.ajv.validateSchema(JSON.parse(globalThis.schema)) ? {valid:true} : {valid:false}").dump() << std::endl;

    json badMeta = { {"type", "invalid_type"} }; // illegal type
    JS_SetPropertyStr(ctx, global, "schema", JS_NewString(ctx, badMeta.dump().c_str()));
    std::cout << "[FAIL] Invalid Meta-Schema: " << RunJsAction(R"(
        (function(){
            const s = JSON.parse(globalThis.schema);
            if (globalThis.ajv.validateSchema(s)) return {valid:true};
            return {valid:false, errors: globalThis.betterAjvErrors({schema:null, data:s, errors:globalThis.ajv.errors})};
        })()
    )").dump(2) << std::endl;

    // 3. TEST: AddFormat (Configuration)
    PrintHeader("AddFormat");
    JS_SetPropertyStr(ctx, global, "formatName", JS_NewString(ctx, "nwn_resref"));
    JS_SetPropertyStr(ctx, global, "formatRegex", JS_NewString(ctx, "^[a-z0-9_]{1,16}$"));
    RunJsAction("globalThis.ajv.addFormat(globalThis.formatName, new RegExp(globalThis.formatRegex));");
    std::cout << "[PASS] Registered custom 'nwn_resref' format." << std::endl;

    // 4. TEST: RegisterSchema (Population)
    PrintHeader("RegisterSchema");
    json mainSchema = { 
        {"$id", "nwn_item"}, 
        {"type", "object"}, 
        {"properties", {
            {"cost", {{"type", "integer"}}},
            {"res", {{"format", "nwn_resref"}}}
        }} 
    };
    JS_SetPropertyStr(ctx, global, "schema", JS_NewString(ctx, mainSchema.dump().c_str()));
    JS_SetPropertyStr(ctx, global, "compileSchema", JS_NewBool(ctx, false)); // Lazy
    std::cout << "[PASS] Lazy Reg: " << RunJsAction(R"(
        (function(){
            const s = JSON.parse(globalThis.schema);
            globalThis.ajv.addSchema(s, s.$id);
            return {success:true, key:s.$id};
        })()
    )").dump() << std::endl;

    // 5. TEST: IsRegistered
    PrintHeader("IsRegistered");
    JS_SetPropertyStr(ctx, global, "schemaID", JS_NewString(ctx, "nwn_item"));
    bool isReg = JS_ToBool(ctx, JS_Eval(ctx, "!!globalThis.ajv.getSchema(globalThis.schemaID)", 43, "<test>", JS_EVAL_TYPE_GLOBAL));
    std::cout << "[PASS] Check 'nwn_item' exists: " << (isReg ? "YES" : "NO") << std::endl;

    // 6. TEST: ValidateInstance (Dynamic)
    PrintHeader("ValidateInstance");
    
    // Declare the missing variable here
    json dynamicSchema = { {"type", "string"}, {"minLength", 5} };
    json dynamicData = "NWNX:EE";

    JS_SetPropertyStr(ctx, global, "schema", JS_NewString(ctx, dynamicSchema.dump().c_str()));
    JS_SetPropertyStr(ctx, global, "instance", JS_NewString(ctx, dynamicData.dump().c_str()));

    std::cout << "[PASS] Dynamic Validation: " << RunJsAction(R"(
        (function(){
            try {
                const s = JSON.parse(globalThis.schema);
                const d = JSON.parse(globalThis.instance);
                const isValid = globalThis.ajv.validate(s, d);
                return { valid: !!isValid };
            } catch(e) { 
                return { valid: false, errors: e.message }; 
            }
        })()
    )").dump(2) << std::endl;

    // Negative test for dynamic validation
    json shortData = "NWN";
    JS_SetPropertyStr(ctx, global, "instance", JS_NewString(ctx, shortData.dump().c_str()));
    std::cout << "[FAIL] Dynamic Invalid Result: " << RunJsAction(R"(
        (function(){
            const s = JSON.parse(globalThis.schema);
            const d = JSON.parse(globalThis.instance);
            if (globalThis.ajv.validate(s, d)) return { valid: true };
            return { 
                valid: false, 
                errors: globalThis.betterAjvErrors({ schema: s, data: d, errors: globalThis.ajv.errors }) 
            };
        })()
    )").dump(2) << std::endl;

    JSContext *ctx_p;
    while (JS_ExecutePendingJob(rt, &ctx_p) > 0);

    // 7. TEST: ValidateInstanceByID
    PrintHeader("ValidateInstanceByID");
    json badData = { {"cost", "too_expensive"}, {"res", "RESREF_FAIL_CAPS"} };
    JS_SetPropertyStr(ctx, global, "instance", JS_NewString(ctx, badData.dump().c_str()));
    JS_SetPropertyStr(ctx, global, "schemaID", JS_NewString(ctx, "nwn_item"));
    std::cout << "[FAIL] Validation by ID:\n" << RunJsAction(R"(
        (function(){
            const d = JSON.parse(globalThis.instance);
            const v = globalThis.ajv.getSchema(globalThis.schemaID);
            if (v(d)) return {valid:true};
            return {valid:false, errors: globalThis.betterAjvErrors({schema:v.schema, data:d, errors:v.errors})};
        })()
    )").dump(2) << std::endl;

    // 8. TEST: RemoveSchema / ClearCache
    PrintHeader("RemoveSchema & ClearCache");
    RunJsAction("globalThis.ajv.removeSchema('nwn_item'); delete globalThis.compiledSchemas['nwn_item'];");
    JS_SetPropertyStr(ctx, global, "schemaID", JS_NewString(ctx, "nwn_item"));
    isReg = JS_ToBool(ctx, JS_Eval(ctx, "!!globalThis.ajv.getSchema(globalThis.schemaID)", 43, "<test>", JS_EVAL_TYPE_GLOBAL));
    std::cout << "[PASS] 'nwn_item' removed: " << (!isReg ? "YES" : "NO") << std::endl;

    // --- CLEANUP ---
    JS_FreeValue(ctx, global);
    //JSContext *ctx_p;
    while (JS_ExecutePendingJob(rt, &ctx_p) > 0);
    JS_FreeContext(ctx);
    ctx = nullptr;
    for (int i = 0; i < 3; i++) JS_RunGC(rt);
    JS_FreeRuntime(rt);

    return 0;
}
