#pragma once
#include "nwn_api.hpp"



#ifdef NWN_API_PROLOGUE
NWN_API_PROLOGUE(ENCAPSULATED_KEYLISTENTRY_E1)
#endif



typedef uint8_t RESREF[16];
typedef uint16_t RESTYPE;


struct ENCAPSULATED_KEYLISTENTRY_E1
{
    RESREF resRef;
    uint32_t nID;
    RESTYPE nType;
    uint16_t unused;
    uint8_t sSha1[20];



#ifdef NWN_CLASS_EXTENSION_ENCAPSULATED_KEYLISTENTRY_E1
    NWN_CLASS_EXTENSION_ENCAPSULATED_KEYLISTENTRY_E1
#endif
};


#ifdef NWN_API_EPILOGUE
NWN_API_EPILOGUE(ENCAPSULATED_KEYLISTENTRY_E1)
#endif

