var array__example_8nss =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md159", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md160", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md161", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md162", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md163", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md164", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md165", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md166", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md224", null ],
    [ "Environment Variables", "group__compiler.html#autotoc_md225", null ],
    [ "Example", "group__damage.html#autotoc_md226", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md227", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md228", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md229", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md230", [
      [ "Dependencies", "group__dotnet.html#autotoc_md231", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md232", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md233", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md234", [
        [ "Sample", "group__nwnx.html#autotoc_md167", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md235", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md236", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md237", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md238", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md239", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md240", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md241", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md242", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md243", [
      [ "NWN types", "group__dotnet.html#autotoc_md244", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md245", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md246", null ],
      [ "Closures", "group__dotnet.html#autotoc_md247", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md248", null ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md249", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md250", null ],
    [ "Events", "group__elc.html#autotoc_md251", null ],
    [ "Example Script", "group__elc.html#autotoc_md252", null ],
    [ "Notes", "group__experimental.html#autotoc_md356", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md357", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md358", null ],
    [ "Setup", "group__feat.html#autotoc_md359", null ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md360", [
      [ "AB", "group__feat.html#autotoc_md361", null ],
      [ "ABILITY", "group__feat.html#autotoc_md363", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md365", null ],
      [ "AC", "group__feat.html#autotoc_md367", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md369", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md371", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md373", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md375", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md377", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md379", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md381", null ],
      [ "HASTE", "group__feat.html#autotoc_md383", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md385", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md387", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md389", null ],
      [ "SAVE", "group__feat.html#autotoc_md391", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md393", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md395", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md397", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md399", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md401", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md403", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md405", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md407", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md409", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md411", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md413", null ],
    [ "Quick start", "group__lua.html#autotoc_md414", [
      [ "Docker", "group__lua.html#autotoc_md415", null ],
      [ "Native", "group__lua.html#autotoc_md416", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md417", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md418", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md419", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md420", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md421", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md422", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md423", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md424", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md425", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md426", null ],
    [ "Environment Variables", "group__nostack.html#autotoc_md427", [
      [ "NWNX_NOSTACK_*", "group__nostack.html#autotoc_md428", null ],
      [ "NWNX_NOSTACK_*_DEFAULT_TYPE", "group__nostack.html#autotoc_md429", null ],
      [ "NWNX_NOSTACK_SEPARATE_INVALID_OID_EFFECTS", "group__nostack.html#autotoc_md430", null ]
    ] ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md431", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md432", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md434", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md435", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md436", null ],
    [ "Setup", "group__race.html#autotoc_md437", [
      [ "The 2da Method", "group__race.html#autotoc_md438", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md439", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md440", [
      [ "AB", "group__race.html#autotoc_md441", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md444", null ],
      [ "AC", "group__race.html#autotoc_md447", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md450", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md453", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md456", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md459", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md462", null ],
      [ "FEAT", "group__race.html#autotoc_md465", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md468", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md471", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md474", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md477", null ],
      [ "RACE", "group__race.html#autotoc_md480", null ],
      [ "REGENERATION", "group__race.html#autotoc_md483", null ],
      [ "SAVE", "group__race.html#autotoc_md486", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md489", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md492", null ],
      [ "SKILL", "group__race.html#autotoc_md495", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md498", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md501", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md504", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md507", null ],
    [ "Setup", "group__redis.html#autotoc_md508", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md509", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md510", [
      [ "Moving on", "group__redis.html#autotoc_md511", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md512", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md513", null ],
    [ "Sample Include", "group__rename.html#autotoc_md514", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md515", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md516", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md517", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md524", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md525", null ],
    [ "Migration", "group__sql.html#autotoc_md529", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md530", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md531", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md532", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md533", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md534", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md535", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md536", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md537", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md538", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md539", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md540", null ],
    [ "Notes", "group__tileset.html#autotoc_md541", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md542", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md543", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md544", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md545", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md546", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md547", null ],
      [ "NWNX_TWEAKS_LANGUAGE_OVERRIDE", "group__tweaks.html#autotoc_md548", null ],
      [ "NWNX_TWEAKS_HIDE_HARDCODED_ITEM_VFX", "group__tweaks.html#autotoc_md549", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md550", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md551", null ],
    [ "Available functions", "group__weapon.html#autotoc_md552", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md553", null ],
    [ "Limitations", "group__webhook.html#autotoc_md554", null ],
    [ "Example usage", "group__webhook.html#autotoc_md555", null ],
    [ "Log", "array__example_8nss.html#a71f6011f9c84f74acca8b63d03303cb6", null ],
    [ "TestArrayOnModule", "array__example_8nss.html#a15e56d0f9f40208818b8b5ac4bbfb3d0", null ],
    [ "TestArrayOnChicken", "array__example_8nss.html#a493a8ce1f39e3d96e3f2e7faf28f6fb7", null ],
    [ "TestNWNXArray", "array__example_8nss.html#a79f746b87354fb91846482213ec74929", null ],
    [ "main", "array__example_8nss.html#acdef7a1fd863a6d3770c1268cb06add3", null ]
];