var array__example_8nss =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md159", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md160", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md161", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md162", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md163", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md164", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md165", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md166", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md224", null ],
    [ "Environment Variables", "group__compiler.html#autotoc_md225", null ],
    [ "Example", "group__damage.html#autotoc_md226", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md227", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md228", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md229", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md230", [
      [ "Dependencies", "group__dotnet.html#autotoc_md231", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md232", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md233", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md234", [
        [ "Sample", "group__nwnx.html#autotoc_md167", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md235", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md236", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md237", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md238", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md239", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md240", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md241", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md242", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md243", [
      [ "NWN types", "group__dotnet.html#autotoc_md244", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md245", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md246", null ],
      [ "Closures", "group__dotnet.html#autotoc_md247", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md248", null ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md249", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md250", null ],
    [ "Events", "group__elc.html#autotoc_md251", null ],
    [ "Example Script", "group__elc.html#autotoc_md252", null ],
    [ "Notes", "group__experimental.html#autotoc_md351", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md352", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md353", null ],
    [ "Setup", "group__feat.html#autotoc_md354", null ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md355", [
      [ "AB", "group__feat.html#autotoc_md356", null ],
      [ "ABILITY", "group__feat.html#autotoc_md358", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md360", null ],
      [ "AC", "group__feat.html#autotoc_md362", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md364", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md366", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md368", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md370", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md372", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md374", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md376", null ],
      [ "HASTE", "group__feat.html#autotoc_md378", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md380", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md382", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md384", null ],
      [ "SAVE", "group__feat.html#autotoc_md386", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md388", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md390", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md392", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md394", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md396", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md398", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md400", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md402", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md404", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md406", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md408", null ],
    [ "Quick start", "group__lua.html#autotoc_md409", [
      [ "Docker", "group__lua.html#autotoc_md410", null ],
      [ "Native", "group__lua.html#autotoc_md411", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md412", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md413", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md414", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md415", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md416", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md417", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md418", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md419", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md420", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md421", null ],
    [ "Environment Variables", "group__nostack.html#autotoc_md422", [
      [ "NWNX_NOSTACK_*", "group__nostack.html#autotoc_md423", null ],
      [ "NWNX_NOSTACK_*_DEFAULT_TYPE", "group__nostack.html#autotoc_md424", null ],
      [ "NWNX_NOSTACK_SEPARATE_INVALID_OID_EFFECTS", "group__nostack.html#autotoc_md425", null ]
    ] ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md426", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md427", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md429", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md430", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md431", null ],
    [ "Setup", "group__race.html#autotoc_md432", [
      [ "The 2da Method", "group__race.html#autotoc_md433", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md434", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md435", [
      [ "AB", "group__race.html#autotoc_md436", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md439", null ],
      [ "AC", "group__race.html#autotoc_md442", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md445", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md448", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md451", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md454", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md457", null ],
      [ "FEAT", "group__race.html#autotoc_md460", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md463", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md466", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md469", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md472", null ],
      [ "RACE", "group__race.html#autotoc_md475", null ],
      [ "REGENERATION", "group__race.html#autotoc_md478", null ],
      [ "SAVE", "group__race.html#autotoc_md481", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md484", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md487", null ],
      [ "SKILL", "group__race.html#autotoc_md490", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md493", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md496", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md499", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md502", null ],
    [ "Setup", "group__redis.html#autotoc_md503", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md504", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md505", [
      [ "Moving on", "group__redis.html#autotoc_md506", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md507", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md508", null ],
    [ "Sample Include", "group__rename.html#autotoc_md509", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md510", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md511", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md512", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md519", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md520", null ],
    [ "Migration", "group__sql.html#autotoc_md524", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md525", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md526", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md527", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md528", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md529", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md530", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md531", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md532", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md533", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md534", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md535", null ],
    [ "Notes", "group__tileset.html#autotoc_md536", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md537", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md538", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md539", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md540", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md541", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md542", null ],
      [ "NWNX_TWEAKS_LANGUAGE_OVERRIDE", "group__tweaks.html#autotoc_md543", null ],
      [ "NWNX_TWEAKS_HIDE_HARDCODED_ITEM_VFX", "group__tweaks.html#autotoc_md544", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md545", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md546", null ],
    [ "Available functions", "group__weapon.html#autotoc_md547", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md548", null ],
    [ "Limitations", "group__webhook.html#autotoc_md549", null ],
    [ "Example usage", "group__webhook.html#autotoc_md550", null ],
    [ "Log", "array__example_8nss.html#a71f6011f9c84f74acca8b63d03303cb6", null ],
    [ "TestArrayOnModule", "array__example_8nss.html#a15e56d0f9f40208818b8b5ac4bbfb3d0", null ],
    [ "TestArrayOnChicken", "array__example_8nss.html#a493a8ce1f39e3d96e3f2e7faf28f6fb7", null ],
    [ "TestNWNXArray", "array__example_8nss.html#a79f746b87354fb91846482213ec74929", null ],
    [ "main", "array__example_8nss.html#acdef7a1fd863a6d3770c1268cb06add3", null ]
];