var dir_b4615358f6508fb1b951d958d300a95c =
[
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md15", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md17", null ],
    [ "Example", "group__damage.html#autotoc_md18", null ],
    [ "Notes", "group__elc.html#autotoc_md19", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md20", null ],
    [ "Example Script", "group__elc.html#autotoc_md21", null ],
    [ "Notes", "group__experimental.html#autotoc_md22", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md23", null ],
    [ "Environment Variables", "group__jvm.html#autotoc_md24", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md25", null ],
    [ "Quick start", "group__lua.html#autotoc_md26", [
      [ "Docker", "group__lua.html#autotoc_md27", null ],
      [ "Native", "group__lua.html#autotoc_md28", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md29", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md30", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md31", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md32", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md33", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md34", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md35", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md36", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md37", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md38", null ],
    [ "How to see sharp?", "group__mono.html#autotoc_md39", null ],
    [ "Remote Debugging", "group__mono.html#autotoc_md40", null ],
    [ "Limitations", "group__mono.html#autotoc_md41", null ],
    [ "Environment Variables", "group__mono.html#autotoc_md42", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md43", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md45", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md46", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md47", null ],
    [ "Setup", "group__race.html#autotoc_md48", [
      [ "The 2da Method", "group__race.html#autotoc_md49", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md50", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md51", [
      [ "AB", "group__race.html#autotoc_md52", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md55", null ],
      [ "AC", "group__race.html#autotoc_md58", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md61", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md64", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md67", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md70", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md73", null ],
      [ "FEAT", "group__race.html#autotoc_md76", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md79", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md82", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md85", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md88", null ],
      [ "RACE", "group__race.html#autotoc_md91", null ],
      [ "REGENERATION", "group__race.html#autotoc_md94", null ],
      [ "SAVE", "group__race.html#autotoc_md97", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md100", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md103", null ],
      [ "SKILL", "group__race.html#autotoc_md106", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md109", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md112", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md115", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md118", null ],
    [ "Setup", "group__redis.html#autotoc_md119", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md120", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md121", [
      [ "Moving on", "group__redis.html#autotoc_md122", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md123", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md124", null ],
    [ "Sample Include", "group__rename.html#autotoc_md125", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md126", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md127", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md134", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md135", null ],
    [ "Migration", "group__sql.html#autotoc_md139", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md140", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md141", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md142", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md143", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md144", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md145", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md146", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md147", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md148", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md152", null ],
    [ "Limitations", "group__webhook.html#autotoc_md158", null ],
    [ "Example usage", "group__webhook.html#autotoc_md159", null ]
];