var dir_ce92b3ebeae221968cfbe8aae0d60ffe =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md99", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md100", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md101", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md102", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md103", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md104", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md105", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md106", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md117", null ],
    [ "Example", "group__damage.html#autotoc_md118", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md119", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md120", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md121", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md122", [
      [ "Dependencies", "group__dotnet.html#autotoc_md123", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md124", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md125", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md126", [
        [ "Sample", "group__nwnx.html#autotoc_md107", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md127", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md128", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md129", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md130", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md131", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md132", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md133", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md134", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md135", [
      [ "NWN types", "group__dotnet.html#autotoc_md136", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md137", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md138", null ],
      [ "Closures", "group__dotnet.html#autotoc_md139", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md140", null ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md141", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md142", null ],
    [ "Events", "group__elc.html#autotoc_md143", null ],
    [ "Example Script", "group__elc.html#autotoc_md144", null ],
    [ "Notes", "group__experimental.html#autotoc_md231", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md232", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md233", null ],
    [ "Setup", "group__feat.html#autotoc_md234", null ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md235", [
      [ "AB", "group__feat.html#autotoc_md236", null ],
      [ "ABILITY", "group__feat.html#autotoc_md238", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md240", null ],
      [ "AC", "group__feat.html#autotoc_md242", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md244", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md246", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md248", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md250", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md252", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md254", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md256", null ],
      [ "HASTE", "group__feat.html#autotoc_md258", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md260", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md262", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md264", null ],
      [ "SAVE", "group__feat.html#autotoc_md266", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md268", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md270", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md272", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md274", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md276", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md278", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md280", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md282", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md284", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md286", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md288", null ],
    [ "Quick start", "group__lua.html#autotoc_md289", [
      [ "Docker", "group__lua.html#autotoc_md290", null ],
      [ "Native", "group__lua.html#autotoc_md291", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md292", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md293", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md294", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md295", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md296", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md297", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md298", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md299", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md300", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md301", null ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md302", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md303", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md305", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md306", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md307", null ],
    [ "Setup", "group__race.html#autotoc_md308", [
      [ "The 2da Method", "group__race.html#autotoc_md309", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md310", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md311", [
      [ "AB", "group__race.html#autotoc_md312", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md315", null ],
      [ "AC", "group__race.html#autotoc_md318", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md321", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md324", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md327", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md330", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md333", null ],
      [ "FEAT", "group__race.html#autotoc_md336", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md339", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md342", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md345", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md348", null ],
      [ "RACE", "group__race.html#autotoc_md351", null ],
      [ "REGENERATION", "group__race.html#autotoc_md354", null ],
      [ "SAVE", "group__race.html#autotoc_md357", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md360", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md363", null ],
      [ "SKILL", "group__race.html#autotoc_md366", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md369", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md372", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md375", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md378", null ],
    [ "Setup", "group__redis.html#autotoc_md379", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md380", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md381", [
      [ "Moving on", "group__redis.html#autotoc_md382", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md383", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md384", null ],
    [ "Sample Include", "group__rename.html#autotoc_md385", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md386", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md387", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md388", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md395", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md396", null ],
    [ "Migration", "group__sql.html#autotoc_md400", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md401", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md402", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md403", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md404", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md405", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md406", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md407", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md408", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md409", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md410", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md411", null ],
    [ "Notes", "group__tileset.html#autotoc_md412", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md413", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md414", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md415", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md416", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md417", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md418", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md419", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md420", null ],
    [ "Available functions", "group__weapon.html#autotoc_md421", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md422", null ],
    [ "Limitations", "group__webhook.html#autotoc_md423", null ],
    [ "Example usage", "group__webhook.html#autotoc_md424", null ],
    [ "nwnx.nss", "nwnx_8nss.html", "nwnx_8nss" ],
    [ "nwnx_consts.nss", "nwnx__consts_8nss.html", "nwnx__consts_8nss" ],
    [ "nwnx_tests.nss", "nwnx__tests_8nss.html", "nwnx__tests_8nss" ]
];