var dir_ce92b3ebeae221968cfbe8aae0d60ffe =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md25", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md26", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md27", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md28", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md29", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md30", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md31", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md42", null ],
    [ "Example", "group__damage.html#autotoc_md43", null ],
    [ "Notes", "group__elc.html#autotoc_md64", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md65", null ],
    [ "Example Script", "group__elc.html#autotoc_md66", null ],
    [ "Notes", "group__experimental.html#autotoc_md123", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md124", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md125", null ],
    [ "Quick start", "group__lua.html#autotoc_md126", [
      [ "Docker", "group__lua.html#autotoc_md127", null ],
      [ "Native", "group__lua.html#autotoc_md128", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md129", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md130", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md131", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md132", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md133", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md134", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md135", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md136", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md137", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md138", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md139", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md141", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md142", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md143", null ],
    [ "Setup", "group__race.html#autotoc_md144", [
      [ "The 2da Method", "group__race.html#autotoc_md145", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md146", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md147", [
      [ "AB", "group__race.html#autotoc_md148", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md151", null ],
      [ "AC", "group__race.html#autotoc_md154", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md157", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md160", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md163", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md166", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md169", null ],
      [ "FEAT", "group__race.html#autotoc_md172", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md175", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md178", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md181", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md184", null ],
      [ "RACE", "group__race.html#autotoc_md187", null ],
      [ "REGENERATION", "group__race.html#autotoc_md190", null ],
      [ "SAVE", "group__race.html#autotoc_md193", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md196", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md199", null ],
      [ "SKILL", "group__race.html#autotoc_md202", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md205", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md208", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md211", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md214", null ],
    [ "Setup", "group__redis.html#autotoc_md215", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md216", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md217", [
      [ "Moving on", "group__redis.html#autotoc_md218", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md219", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md220", null ],
    [ "Sample Include", "group__rename.html#autotoc_md221", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md222", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md223", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md230", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md231", null ],
    [ "Migration", "group__sql.html#autotoc_md235", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md236", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md237", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md238", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md239", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md240", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md241", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md242", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md243", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md244", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md248", null ],
    [ "Limitations", "group__webhook.html#autotoc_md254", null ],
    [ "Example usage", "group__webhook.html#autotoc_md255", null ],
    [ "nwnx.nss", "nwnx_8nss.html", "nwnx_8nss" ],
    [ "nwnx_consts.nss", "nwnx__consts_8nss.html", "nwnx__consts_8nss" ],
    [ "nwnx_tests.nss", "nwnx__tests_8nss.html", "nwnx__tests_8nss" ]
];