var dir_b4615358f6508fb1b951d958d300a95c =
[
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md25", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md36", null ],
    [ "Example", "group__damage.html#autotoc_md37", null ],
    [ "Notes", "group__elc.html#autotoc_md38", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md39", null ],
    [ "Example Script", "group__elc.html#autotoc_md40", null ],
    [ "Notes", "group__experimental.html#autotoc_md41", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md42", null ],
    [ "Environment Variables", "group__jvm.html#autotoc_md43", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md44", null ],
    [ "Quick start", "group__lua.html#autotoc_md45", [
      [ "Docker", "group__lua.html#autotoc_md46", null ],
      [ "Native", "group__lua.html#autotoc_md47", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md48", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md49", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md50", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md51", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md52", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md53", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md54", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md55", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md56", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md57", null ],
    [ "How to see sharp?", "group__mono.html#autotoc_md58", null ],
    [ "Remote Debugging", "group__mono.html#autotoc_md59", null ],
    [ "Limitations", "group__mono.html#autotoc_md60", null ],
    [ "Environment Variables", "group__mono.html#autotoc_md61", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md62", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md64", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md65", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md66", null ],
    [ "Setup", "group__race.html#autotoc_md67", [
      [ "The 2da Method", "group__race.html#autotoc_md68", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md69", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md70", [
      [ "AB", "group__race.html#autotoc_md71", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md74", null ],
      [ "AC", "group__race.html#autotoc_md77", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md80", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md83", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md86", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md89", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md92", null ],
      [ "FEAT", "group__race.html#autotoc_md95", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md98", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md101", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md104", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md107", null ],
      [ "RACE", "group__race.html#autotoc_md110", null ],
      [ "REGENERATION", "group__race.html#autotoc_md113", null ],
      [ "SAVE", "group__race.html#autotoc_md116", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md119", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md122", null ],
      [ "SKILL", "group__race.html#autotoc_md125", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md128", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md131", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md134", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md137", null ],
    [ "Setup", "group__redis.html#autotoc_md138", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md139", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md140", [
      [ "Moving on", "group__redis.html#autotoc_md141", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md142", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md143", null ],
    [ "Sample Include", "group__rename.html#autotoc_md144", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md145", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md146", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md153", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md154", null ],
    [ "Migration", "group__sql.html#autotoc_md158", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md159", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md160", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md161", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md162", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md163", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md164", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md165", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md166", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md167", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md171", null ],
    [ "Limitations", "group__webhook.html#autotoc_md177", null ],
    [ "Example usage", "group__webhook.html#autotoc_md178", null ]
];