var modules =
[
    [ "NWNX", "group__nwnx.html", "group__nwnx" ],
    [ "NWNX Constants", "group__consts.html", "group__consts" ],
    [ "Administration", "group__admin.html", "group__admin" ],
    [ "Appearance", "group__appearance.html", "group__appearance" ],
    [ "Area", "group__area.html", "group__area" ],
    [ "Chat", "group__chat.html", "group__chat" ],
    [ "Creature", "group__creature.html", "group__creature" ],
    [ "Damage", "group__damage.html", "group__damage" ],
    [ "Dialog", "group__dialog.html", "group__dialog" ],
    [ "Effect", "group__effect.html", "group__effect" ],
    [ "ELC", "group__elc.html", "group__elc" ],
    [ "Encounter", "group__encounter.html", "group__encounter" ],
    [ "Events", "group__events.html", "group__events" ],
    [ "Feedback", "group__feedback.html", "group__feedback" ],
    [ "Item", "group__item.html", "group__item" ],
    [ "ItemProperty", "group__itemproperty.html", "group__itemproperty" ],
    [ "LUA", "group__lua.html", "group__lua" ],
    [ "Object", "group__object.html", "group__object" ],
    [ "Player", "group__player.html", "group__player" ],
    [ "Profiler", "group__profiler.html", "group__profiler" ],
    [ "Race", "group__race.html", "group__race" ],
    [ "Redis", "group__redis.html", "group__redis" ],
    [ "Regex", "group__regex.html", "group__regex" ],
    [ "Rename", "group__rename.html", "group__rename" ],
    [ "Reveal", "group__reveal.html", "group__reveal" ],
    [ "Ruby", "group__ruby.html", "group__ruby" ],
    [ "SkillRanks", "group__skillranks.html", "group__skillranks" ],
    [ "SpellChecker", "group__spellcheck.html", "group__spellcheck" ],
    [ "SQL", "group__sql.html", "group__sql" ],
    [ "Time", "group__time.html", "group__time" ],
    [ "Util", "group__util.html", "group__util" ],
    [ "Visibility", "group__visibility.html", "group__visibility" ],
    [ "Weapon", "group__weapon.html", "group__weapon" ],
    [ "Webhook", "group__webhook.html", "group__webhook" ]
];