name: CMake

on: [push]

env:
  BUILD_TYPE: RelWithDebInfo
  CC: gcc-7 -m64
  CXX: g++-7 -m64

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time

    - name: Install Additional packages
      run: sudo apt-get install libhunspell-dev libluajit-5.1-dev doxygen

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -- -j 6

    - name: Generate Documentation
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make docs && make dark-docs

    - name: Move Dark Docs into Proper Location
      working-directory: ${{runner.workspace}}/unified/Documentation
      shell: bash
      run: mv dark light/

    - name: Drop timestamp into Binaries folder
      working-directory: ${{runner.workspace}}/unified/Binaries
      run: echo "${{ steps.current-time.outputs.readableTime }}" > ${{ steps.vars.outputs.sha_short }}.txt

    - name: Pack the Binaries
      working-directory: ${{runner.workspace}}/unified/Binaries
      run: cmake -E tar cfv ../NWNX-EE.zip --format=zip .

    - name: Pack the Scripts
      working-directory: ${{runner.workspace}}/unified
      shell: bash
      run: zip -j ./NWScript.zip `find . -name "*.nss" | grep -Pv '_t+[0-9]{0,1}.nss'`

    - name: Upload Binaries
      uses: actions/upload-artifact@v1
      with:
       path: ./NWNX-EE.zip
       name: NWNX-EE.zip

    - name: Upload Scripts
      uses: actions/upload-artifact@v1
      with:
        path: ./NWScript.zip
        name: NWScript.zip

    - name: Deploy Documents to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       BRANCH: gh-pages
       FOLDER: Documentation/light
       CLEAN: true

    - name: Deploy Latest Development Build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
           ./NWNX-EE.zip
           ./NWScript.zip

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: plenarius/unified:${{ steps.vars.outputs.sha_short }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        build-args: |
          CC=gcc-7
          CXX=g++-7

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  release:
    if: contains(github.ref, 'tags/build')
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Store Release url
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

      - uses: actions/upload-artifact@v1
        with:
          path: ./upload_url
          name: upload_url

  publish:
    if: contains(github.ref, 'tags/build')
    runs-on: ubuntu-20.04
    needs: release

    steps:
    - name: Download Binaries
      uses: actions/download-artifact@v1
      with:
        name: NWNX-EE.zip
        path: ./

    - name: Download Scripts
      uses: actions/download-artifact@v1
      with:
        name: NWScript.zip
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url

    - name: Upload Binaries to Release
      id: upload_binaries_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./NWNX-EE.zip
        asset_name: NWNX-EE.zip
        asset_content_type: application/zip

    - name: Upload Scripts to Release
      id: upload_scripts_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./NWScript.zip
        asset_name: NWScript.zip
        asset_content_type: application/zip