name: CMake

on: [push]

env:
  BUILD_TYPE: RelWithDebInfo
  CC: gcc-7 -m64
  CXX: g++-7 -m64

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu GCC 7", artifact: "NWNX-EE-Binaries.zip",
            os: ubuntu-20.04,
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install Additional packages
      run: sudo apt-get install libhunspell-dev libmagick++-6.q16-dev graphviz libluajit-5.1-dev doxygen

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -- -j 6

    - name: Make Docs
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make docs && make dark-docs

    - name: Move Dark Docs into Light for GH-Pages
      working-directory: ${{runner.workspace}}/unified/Documentation
      shell: bash
      run: mv dark light/

    - name: Pack
      working-directory: ${{runner.workspace}}/unified/Binaries
      run: cmake -E tar cfv ../${{ matrix.config.artifact }} --format=zip .

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
       path: ./${{ matrix.config.artifact }}
       name: ${{ matrix.config.artifact }}

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       BRANCH: gh-pages # The branch the action should deploy to.
       FOLDER: Documentation/light # The folder the action should deploy.
       CLEAN: true # Automatically remove deleted files from the deploy branch

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Store Release url
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

      - uses: actions/upload-artifact@v1
        with:
          path: ./upload_url
          name: upload_url

  publish:
    if: contains(github.ref, 'tags/v')
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu GCC 7", artifact: "NWNX-EE-Binaries.zip",
            os: ubuntu-20.04
          }
    needs: release

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url

    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./${{ matrix.config.artifact }}
        asset_name: ${{ matrix.config.artifact }}
        asset_content_type: application/x-gtar
