name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - '**.nss'
      - '**.md'
      - 'docgen/**'
  pull_request:
    branches:
      - master
    paths:
      - '**.nss'
      - '**.md'
      - 'docgen/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Cache Doxygen
      uses: actions/cache@v2
      id: doxygen-cache
      with:
        path: "~/doxygen"
        key: doxygen-1

    - name: Install Cache Doxygen
      env:
        CACHE_HIT: ${{steps.doxygen-cache.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --force --recursive ~/doxygen/* /
        else
          sudo apt-get install doxygen
          mkdir -p ~/doxygen
          for dep in doxygen; do
              dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/doxygen/
          done
        fi

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE

    - name: Generate Documentation
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make docs && make dark-docs

    - name: Move Dark Docs into Proper Location
      working-directory: ${{runner.workspace}}/unified/Documentation
      shell: bash
      run: mv dark light/

    - name: Deploy Documents to Github Pages
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       BRANCH: gh-pages
       FOLDER: Documentation/light
       CLEAN: true

